Repository darktable-org/darktable, pull requests merged in 2018-10, with the labels that each got.

#1735 masks continuous add
  src/develop/masks.h
  src/develop/masks/brush.c
  src/develop/masks/circle.c
  src/develop/masks/ellipse.c
  src/develop/masks/gradient.c
  src/develop/masks/group.c
  src/develop/masks/masks.c
  src/develop/masks/path.c
  src/iop/retouch.c
  src/views/darkroom.c
Labels: enhancement

#1738 Fix mouse_leave and mask behavior.
  src/develop/masks/masks.c
Labels: bug

#1728 doc(lua_api): fix typo
  doc/usermanual/lua/lua_api.xml
Labels: usermanual

#1731 New copy history
  src/common/history.c
  src/common/history.h
  src/common/styles.c
Labels: enhancement

#1677 Added custom image order by drag and drop in lighttable
  src/common/collection.c
  src/common/collection.h
  src/common/database.c
  src/common/debug.h
  src/common/image.c
  src/gui/gtk.c
  src/libs/tools/filter.c
  src/views/lighttable.c
Labels: enhancement

#1743 fix gui modules order
  src/libs/modulegroups.c
  src/views/darkroom.c
Labels: bug

#1712 Thumb overlay (stars display) improved and expanded
  data/darktableconfig.xml.in
  src/views/view.c
Labels: enhancement

#1719 masks behavior
  src/develop/masks/brush.c
  src/develop/masks/circle.c
  src/develop/masks/ellipse.c
  src/develop/masks/path.c
Labels: enhancement

#1749 Fix: Custom image order only in view Lighttable
  src/common/collection.c
  src/common/image.c
  src/views/lighttable.c
Labels: bug

#1746 Sort aspect ratio
  src/common/collection.c
  src/common/collection.h
  src/common/database.c
  src/control/jobs/control_jobs.c
  src/libs/tools/filter.c
  src/views/lighttable.c
Labels: enhancement

#1753 Denoise profile wavelets: change force by frequency and channel
  src/iop/denoiseprofile.c
Labels: enhancement

#1752 Rawdenoise: change force by frequency and channel
  src/iop/rawdenoise.c
Labels: enhancement

#1755 Introduce a new gamma correction for color profiles based on video so…
  data/kernels/basic.cl
  po/fr.po
  src/iop/profile_gamma.c
Labels: enhancement

#1760 Add collection and sorting based on aspect-ratio.
  src/common/collection.c
  src/common/collection.h
  src/common/database.c
  src/common/image.c
  src/common/image.h
  src/control/jobs/control_jobs.c
  src/libs/collect.c
  src/libs/collect.h
  src/libs/tools/filter.c
  src/views/darkroom.c
Labels: enhancement

#1768 color picker in colorbalance
  src/iop/colorbalance.c
Labels: enhancement

#1771 Enable GCC SSE2 -> AVX2 instructions conversion
  src/CMakeLists.txt
Labels: enhancement

#1782 Colorbalance : add presets
  src/iop/colorbalance.c
Labels: enhancement

#1785 profilegamma : add presets
  src/iop/profile_gamma.c
Labels: enhancement
