Repository darktable-org/darktable, pull requests merged in 2018-12, with the labels that each got.

#1863 build: update list of features
  build.sh
Labels: bug, enhancement

#1865 retouch: reorder tools to be consistent with other module.
  src/iop/retouch.c
Labels: bug, enhancement

#1869 guided filter: add an additional parameter to adjust the effect of th…
  src/common/guided_filter.c
  src/common/guided_filter.h
  src/develop/blend.c
Labels: bug

#1872 update German translation for darktable 2.6 release
  po/de.po
Labels: enhancement

#1870 exif: canon subject distance is in cm.
  src/common/exif.cc
Labels: bug

#1871 Fix masks nb
  src/develop/masks/masks.c
Labels: bug

#1860 Add noise profiles for Panasonic G3 and GX7
  data/noiseprofiles.json
Labels: camera-support

#1862 exiv2: compatibility with 0.27.0.1
  src/common/exif.cc
Labels: bug

#1876 color balance: more meaningful UI
  src/iop/colorbalance.c
Labels: enhancement

#1877 filmic: graph improvements
  src/iop/filmic.c
Labels: enhancement

#1892 Add Fujifilm X-T3 white balance presets
  src/external/wb_presets.c
Labels: camera-support

#1895 fix segfault in denoise(profiled)
  src/iop/denoiseprofile.c
Labels: bug

#1899 Fix crash denoise
  src/develop/imageop.c
  src/iop/denoiseprofile.c
Labels: bug

#1902 equalizer: fix bug #12461 and fix radius in tiling_callback
  src/iop/atrous.c
Labels: bug

#1901 retouch: fix computation of roi_in.
  src/iop/retouch.c
Labels: bug

#1912 Update Polish translation
  po/pl.po
Labels: translation

#1922 Update Hungarian translation
  po/hu.po
Labels: translation

#1911 Update of the French translation of the user manual
  doc/usermanual/po/fr.po
Labels: usermanual

#1923 Update German usermanual for darktable 2.6
  doc/usermanual/po/de.po
Labels: usermanual

#1921 bauhaus: default colors consistent with CSS
  src/bauhaus/bauhaus.c
Labels: bug

#1907 usermanual : add filmic
  doc/usermanual/darkroom/modules/tone/filmic.xml
Labels: usermanual

#1935 amaze demosaic: optimize the loop
  src/iop/amaze_demosaic_RT.cc
Labels: enhancement

#1716 lua get tagged images
  doc/usermanual/lua/lua_api.xml
  src/lua/tags.c
  src/lua/tags.h
Labels: enhancement

#1946 fix hierarchical tags with different upper/lower cases
  src/libs/collect.c
Labels: bug

#1948 channel mixer: add N&B film presets
  src/iop/channelmixer.c
Labels: enhancement

#1679 Manual, watermark plugin, exif field
  doc/usermanual/darkroom/modules/effect/watermark.xml
Labels: usermanual
