Repository darktable-org/darktable, pull requests merged in 2018-09, with the labels that each got.

#1550 Retouch GUI
  src/control/control.c
  src/control/control.h
  src/develop/develop.h
  src/develop/masks/circle.c
  src/develop/masks/ellipse.c
  src/develop/masks/masks.c
  src/develop/masks/path.c
  src/gui/gtk.c
  src/views/darkroom.c
Labels: enhancement

#1680 Added Nikon D850 White Balance Profiles
  src/external/wb_presets.c
Labels: camera-support

#1720 retouch auto levels
  src/iop/retouch.c
Labels: enhancement

#1722 ellipse TODO
  src/develop/masks/ellipse.c
Labels: enhancement

#1699 fix zoom fill
  src/views/darkroom.c
Labels: bug

#1691 Fix map -> find location (Bug #12214)
  data/darktableconfig.xml.in
  src/libs/location.c
Labels: bug

#1721 blend changes lost
  src/develop/imageop.c
Labels: bug

#1726 Descending collection sorting: respect all fields
  src/common/collection.c
Labels: bug, enhancement

#1729 Allow for 400% and 800% zoom.
  src/libs/navigation.c
Labels: enhancement

#1727 Collection: add sorting by title, description
  src/common/collection.c
  src/common/collection.h
  src/libs/tools/filter.c
Labels: enhancement

#1725 rename module
  src/develop/imageop.c
Labels: enhancement

#1708 Improve rendering of image type inside thumbs
  src/views/view.c
Labels: enhancement, incomplete

#1711 Improved display of color labels inside the thumb
  src/dtgtk/paint.c
  src/views/view.c
Labels: enhancement
