Repository darktable-org/darktable, pull requests merged in 2018-11, with the labels that each got.

#1709 [RFC] bilat: don't grab data from preview pipe if hash==0, fixes #11872
  src/iop/bilat.c
Labels: bug

#1781 Add SQL script to migrate albums from Capture One Pro
  tools/migrate_capture_one_pro.sql
Labels: enhancement

#1799 fix undo delete module
  src/common/imageio.c
  src/develop/develop.c
  src/develop/develop.h
  src/libs/history.c
Labels: bug

#1796 Tonecurve presets & GUI improvements
  src/gui/draw.h
  src/iop/tonecurve.c
Labels: enhancement

#1832 filmic: rename "auto tuning security factor" to "security factor"
  src/iop/filmic.c
  src/iop/profile_gamma.c
Labels: enhancement

#1834 Fix opencl of nlmeans (borders were oversmoothed)
  data/kernels/denoiseprofile.cl
  data/kernels/nlmeans.cl
Labels: bug

#1838 Eliminate assertion failures introduced in PR #1816.
  src/libs/tagging.c
Labels: bug

#1839 filmic : use RGB channels average as a black exposure guess instead of RGB min
  src/iop/filmic.c
Labels: bug

#1843 manual: basic documentation for mask feathering
  doc/usermanual/darkroom/concepts/blending.xml
  src/develop/blend_gui.c
Labels: usermanual

#1851 filmic : improvements
  data/kernels/filmic.cl
  src/iop/filmic.c
Labels: enhancement

#1850 filmic: add some borders to area to gain so vertical space.
  src/iop/filmic.c
Labels: bug, enhancement

#1739 Translated darktable user manual to German
  doc/usermanual/po/de.po
Labels: usermanual

#1690 Add white balance presets for Canon EOS M100
  src/external/wb_presets.c
Labels: camera-support

#1697 Added WB presets for Panasonic DMZ-FZ300
  src/external/wb_presets.c
Labels: camera-support

#1668 wb_presets: Add white balance presets of Canon PowerShot SX160 IS
  src/external/wb_presets.c
Labels: camera-support

#1718 Add Panasonic DC-GX9 (V1.1) whitebalance presets
  src/external/wb_presets.c
Labels: camera-support

#1848 Update docs
  doc/usermanual/darkroom/concepts/presets.xml
  doc/usermanual/lighttable/concepts/filtering.xml
  doc/usermanual/print/print.xml
Labels: usermanual
