Repository darktable-org/darktable, pull requests merged in 2019-11, with the labels that each got.

#3250 Polish translation update
  po/pl.po
Labels: translation

#3252 Spanish translation update
  po/es.po
Labels: translation

#3261 update release notes
  RELEASE_NOTES.md
Labels: enhancement

#3262 accel window : default shortcut
  src/gui/gtk.c
Labels: bug

#3268 Spanish translation update
  po/es.po
Labels: translation

#3259 Correct headerbar missing background
  data/themes/darktable.css
Labels: bug

#3260 culling : fix selections changes
  src/views/lighttable.c
Labels: bug

#3264 filmicrgb: improve slightly the default parameters
  src/iop/filmicrgb.c
Labels: enhancement

#3265 bilat (local contrast): improve slightly the default params
  src/iop/bilat.c
Labels: enhancement

#3263 tone equalizer: better default settings
  src/iop/toneequal.c
Labels: enhancement

#3275 First part of translation into German
  po/de.po
Labels: translation

#3282 fix accel window glitch
  data/themes/darktable.css
Labels: bug

#3279 tagging bug fix - flags and synonyms not saved to db in create tag
  src/libs/tagging.c
Labels: bug

#3280 darktable wrapper script disabling gnome nightlight
  tools/darktable-gnome-nightlight-disabled.sh
Labels: enhancement

#3290 Spanish translation update
  po/es.po
Labels: translation

#3287 fix live sample data text for more consistent UI
  data/themes/darktable.css
Labels: bug, enhancement

#3291 Added check for mouse wheel scroll option to profiled denoise
  src/iop/denoiseprofile.c
Labels: bug

#3294 denoiseprofile: update wavelets' tiling
  src/iop/denoiseprofile.c
Labels: bug

#3296 Updated Hebrew translation
  po/he.po
Labels: translation

#3303 Spanish translation update
  po/es.po
Labels: translation

#3310 Polish translation update
  po/pl.po
Labels: translation

#3293 Various UI fixes
  src/libs/export_metadata.c
  src/libs/metadata.c
  src/libs/select.c
  src/views/lighttable.c
Labels: bug

#3315 Disable GTK client side decoration for Windows builds
  src/main.c
Labels: bug

#3317 fix tagging windows resizing (complete #3238)
  src/libs/tagging.c
Labels: bug

#3316 colorspaces.cl: add trc back in the computation.
  data/kernels/colorspaces.cl
Labels: bug

#3068 fix GUI glitches
  data/themes/darktable-elegant-dark.css
  data/themes/darktable-elegant-darker.css
  data/themes/darktable-elegant-grey.css
  data/themes/darktable.css
  src/bauhaus/bauhaus.c
  src/iop/toneequal.c
Labels: bug

#3301 slideshow: rework to lock less to enable multiple thread to render im…
  src/views/slideshow.c
Labels: bug, enhancement

#3143 Making the hue sliders of the colorbalance iop more consistent
  src/iop/colorbalance.c
Labels: enhancement

#3344 Spanish translation update
  po/es.po
Labels: translation

#3332 tools: Fix README.cmake.md
  tools/basecurve/README.cmake.md
Labels: bug

#3334 lighttable : avoid position 'jump' on rating/colorlabels using shortcuts.
  src/views/lighttable.c
Labels: bug

#3337 filmstrip : keep mouseover in sync with mouse position
  src/libs/tools/filmstrip.c
Labels: bug

#3338 Toneequalizer: fix GUI glitches
  src/iop/toneequal.c
Labels: bug

#3320 fix prophoto profile and rework profile creation (simpler)
  src/common/colorspaces.c
Labels: bug

#3350 update default modules presets and workspaces with new modules
  src/iop/CMakeLists.txt
  src/libs/modulelist.c
Labels: bug, enhancement

#3370 fixes parsing when comma in exif
  src/iop/lens.cc
Labels: bug

#3377 (rgb)levels: do not force colors on pickers to let CSS do the job.
  src/iop/levels.c
  src/iop/rgblevels.c
Labels: bug

#3362 Fix UI glitches remaining
  data/themes/darktable-elegant-dark.css
  data/themes/darktable-elegant-grey.css
  data/themes/darktable.css
Labels: bug

#3378 UI: force gtk tabs to be justified for preferences and equalizers
  src/gui/gtk.h
  src/gui/preferences.c
  src/iop/atrous.c
  src/iop/filmicrgb.c
  src/iop/toneequal.c
  src/lua/preferences.c
  tools/generate_prefs.xsl
Labels: bug, enhancement

#3379 filmicrgb: correct the output power in auto tuner too
  src/iop/filmicrgb.c
Labels: bug

#3385 imageop: make the always-on button distinguishable.
  src/develop/imageop.c
  src/dtgtk/paint.c
  src/dtgtk/paint.h
Labels: bug, enhancement

#3390 Fix height histogram scale of 'rgb levels' and 'rgb curve' iops
  src/iop/rgbcurve.c
  src/iop/rgblevels.c
Labels: bug

#3391 Add distinguishable text for always-on entries in history.
  data/themes/darktable.css
  src/libs/history.c
Labels: bug, enhancement

#3392 po/keep default modules
  src/develop/develop.c
Labels: bug

#3396 Hover and focus effect forgotten on always on modules in history
  data/themes/darktable.css
Labels: bug

#3069 doc - added metadata export feature to export selected chapter
  doc/usermanual/lighttable/images/panel_exportselected-metadata-config.png
  doc/usermanual/lighttable/images/panel_exportselected-metadata-selection.png
  doc/usermanual/lighttable/panels/export.xml
Labels: usermanual

#3289 General copy edit of release notes for readability
  RELEASE_NOTES.md
Labels: enhancement

#3399 blend gui: fix a few glitches
  src/develop/blend_gui.c
  src/dtgtk/paint.c
  src/dtgtk/togglebutton.c
Labels: bug

#3400 css: fix history selection buttons.
  data/themes/darktable-elegant-dark.css
  data/themes/darktable-elegant-grey.css
  data/themes/darktable.css
Labels: bug

#3405 Spanish translation update
  po/es.po
Labels: translation

#3407 fix OpenCL inconsistencies on Intel Neo
  src/common/opencl.c
Labels: bug

#3408 filmicrgb bugfix
  src/iop/filmicrgb.c
Labels: bug

#3409 iop-order: don't move colorin/colorout when converting v1 -> v2.
  src/common/iop_order.c
Labels: bug

#3411 Update Release Notes
  RELEASE_NOTES.md
Labels: enhancement

#3422 blend gui: fix several glitches in drawn masks
  src/develop/blend.h
  src/develop/blend_gui.c
  src/develop/masks/masks.c
Labels: bug

#3419 RELEASE_NOTES: propose a few minor language tweaks
  RELEASE_NOTES.md
Labels: enhancement

#3440 tone equalizer: bugfix
  src/iop/toneequal.c
Labels: bug

#3436 tone equalizer interactive cursor : try to improve issue #3428
  src/iop/toneequal.c
Labels: bug, enhancement

#3450 Update naming conflict info as pointed out on list
  doc/usermanual/lighttable/panels/export.xml
Labels: usermanual

#3464 lighttable : don't reset offset if it has just been changed
  src/views/lighttable.c
Labels: bug

#3458 fix tag refresh on darktable tag change
  src/common/tags.c
  src/common/tags.h
Labels: bug

#3468 dt_image_cache_write_release should be locked per image.
  src/common/image_cache.c
Labels: bug

#3470 Change order of image info line
  data/darktableconfig.xml.in
Labels: bug, enhancement

#3471 Capitalize iso at dt_image_print_exif
  src/common/image.c
Labels: enhancement

#3474 bilateral: fix implemetation to correspond to OpenCL version.
  src/common/bilateral.c
Labels: bug

#3476 Add gdbus.exe to the Windows installer
  cmake/windows-macros.cmake
Labels: bug

#3484 Fix frame module crash (#3473)
  src/iop/borders.c
Labels: bug

#3441 Fix OpenCL compile errors on Windows
  src/common/opencl.c
Labels: bug

#3487 Fix colorzones strength upgrade from V3 to V4
  src/iop/colorzones.c
Labels: bug

#3489 Spanish translation update
  po/es.po
Labels: translation

#3480 database: backup db for each new release.
  src/common/database.c
Labels: enhancement

#3512 Spanish translation update
  po/es.po
Labels: translation

#3511 Fix obvious defects and warnings in zh translation
  po/zh_CN.po
Labels: translation

#3523 Button order fixes
  src/gui/preferences.c
  src/gui/presets.c
  src/libs/lib.c
  src/libs/tagging.c
Labels: bug, enhancement

#3509 module list : Ensure we update iop list in all cases
  src/libs/modulegroups.c
Labels: bug

#3530 Fix color lookup table color picker
  src/iop/colorchecker.c
Labels: bug

#3546 Update sk translation
  po/sk.po
Labels: translation

#3544 UI -> rgb_curve
  src/iop/rgbcurve.c
Labels: bug

#3548 colorspaces: stop using hard coded prequantized values.
  src/common/colorspaces.c
Labels: enhancement

#3579 UI - Fix disabled combobox sliders
  data/themes/darktable.css
Labels: bug, enhancement

#3561 Made compression/quality sliders insensitive when uncompressed is selected
  src/imageio/format/tiff.c
  src/imageio/format/webp.c
Labels: enhancement

#3581 Spanish translation update
  po/es.po
Labels: translation

#3566 fix #3516 - make lut size 256 work and add messages to limit input lut size to 256
  src/iop/lut3d.c
Labels: bug

#3565 fix #3555 and #3556. DNG files should keep the color matrix if supplied, non-RAW dng disable some iop
  src/common/exif.cc
  src/iop/cacorrect.c
  src/iop/demosaic.c
  src/iop/highlights.c
  src/iop/hotpixels.c
  src/iop/rawdenoise.c
Labels: bug

#3590 lighttable : ensure to update dnd state after layout change
  src/views/lighttable.c
Labels: bug

#3592 Spanish translation update
  po/es.po
Labels: translation

#3593 Polish translation update
  po/pl.po
Labels: translation

#3596 navigation : verify imgid before drawing
  src/libs/navigation.c
Labels: bug

#3617 Suppress [dt_ioppr_transform_image_colorspace] warning for monochromes
  src/common/iop_order.c
Labels: bug

#3623 Japanese translation update
  po/ja.po
Labels: translation

#3621 colorpicker: use signal mechanism to make it thread safe
  src/control/signal.c
  src/control/signal.h
  src/develop/blend_gui.c
  src/develop/pixelpipe_hb.c
  src/gui/color_picker_proxy.c
  src/gui/color_picker_proxy.h
  src/gui/gtk.c
Labels: bug

#3635 mask refinement: fix opencl codepath for bug in opacity/contrast handling
  data/kernels/blendop.cl
  src/develop/blend.c
Labels: bug

#3639 histogram: prevent flickering when using colorpickers
  src/libs/histogram.c
Labels: bug, enhancement

#3615 Fix selected text issue and improve dialog bar
  data/themes/darktable.css
Labels: bug, enhancement

#3626 crop dimensions string visibility fixes
  src/iop/clipping.c
Labels: enhancement

#3614 fix some casts
  src/common/iop_order.c
Labels: bug, enhancement
