Repository darktable-org/darktable, pull requests merged in 2019-07, with the labels that each got.

#2765 exif: Calculate focus distance for Sony cameras
  src/common/exif.cc
Labels: enhancement

#2771 make denoise profiled scale-invariant
  src/iop/denoiseprofile.c
Labels: enhancement

#2772 optimize render image
  src/control/control.c
  src/control/control.h
  src/control/jobs.h
  src/control/signal.c
  src/control/signal.h
  src/develop/develop.c
  src/develop/pixelpipe_hb.c
  src/develop/pixelpipe_hb.h
  src/libs/duplicate.c
  src/libs/navigation.c
  src/views/darkroom.c
Labels: enhancement

#2773 LEICA Q2 support; white balance presets and denoising profile.
  data/noiseprofiles.json
  src/external/wb_presets.c
Labels: camera-support, noise profile

#2644 color zones: fix periodic boundary conditions when color is selected by hue
  src/CMakeLists.txt
  src/common/curve_tools.c
  src/common/curve_tools.h
  src/common/splines.cpp
  src/common/splines.h
  src/develop/lightroom.c
  src/gui/draw.h
  src/iop/colorzones.c
Labels: bug

#2778 remove auto tags
  src/common/darktable.c
  src/common/darktable.h
  src/common/exif.cc
  src/common/image.c
  src/common/imageio_rawspeed.cc
  src/common/styles.c
  src/common/tags.c
  src/common/tags.h
  src/common/undo.c
  src/control/jobs/control_jobs.c
  src/develop/develop.c
  src/develop/lightroom.c
  src/libs/copy_history.c
  src/libs/duplicate.c
  src/libs/print_settings.c
  src/libs/tagging.c
  src/libs/tools/filmstrip.c
  src/lua/tags.c
Labels: enhancement

#2785 basecurve: use new norms api
  data/kernels/basecurve.cl
  src/iop/basecurve.c
Labels: enhancement

#2783 module order: dither before framing and watermark
  src/common/iop_order.c
Labels: bug, enhancement

#2791 LUT3D fix issue #2779
  src/iop/lut3d.c
Labels: bug

#2789 Polish translation update
  po/pl.po
Labels: translation

#2796 Correctly restore previous state of darktable.gui->reset
  src/develop/blend_gui.c
  src/develop/develop.c
  src/develop/imageop.c
  src/develop/masks/masks.c
  src/gui/color_picker_proxy.c
  src/iop/ashift.c
  src/iop/basecurve.c
  src/iop/basicadj.c
  src/iop/borders.c
  src/iop/colorbalance.c
  src/iop/colorchecker.c
  src/iop/colormapping.c
  src/iop/colorzones.c
  src/iop/denoiseprofile.c
  src/iop/exposure.c
  src/iop/filmic.c
  src/iop/hotpixels.c
  src/iop/invert.c
  src/iop/lens.c
  src/iop/levels.c
  src/iop/profile_gamma.c
  src/iop/relight.c
  src/iop/retouch.c
  src/iop/rgbcurve.c
  src/iop/rgblevels.c
  src/iop/splittoning.c
  src/iop/temperature.c
  src/iop/tonecurve.c
  src/libs/collect.c
  src/libs/colorpicker.c
  src/views/darkroom.c
Labels: bug

#2794 Put import image/folder buttons on same line.
  src/libs/import.c
Labels: enhancement

#2792 Added button to refresh image data
  src/control/jobs/control_jobs.c
  src/control/jobs/control_jobs.h
  src/libs/image.c
Labels: enhancement, wip

#2767 Tags - set tag entry with selected tag in the list
  src/libs/tagging.c
Labels: enhancement, wip

#2740 conf.h minor rework
  src/CMakeLists.txt
  src/bauhaus/bauhaus.c
  src/common/colorspaces.c
  src/common/cups_print.c
  src/common/curl_tools.c
  src/common/darktable.c
  src/common/database.c
  src/common/dbus.c
  src/common/image.c
  src/common/imageio_module.c
  src/common/l10n.c
  src/common/mipmap_cache.c
  src/common/nvidia_gpus.h
  src/common/opencl.c
  src/common/opencl.h
  src/control/conf.c
  src/control/conf.h
  src/gui/gtk.c
  src/gui/preferences.c
  src/imageio/format/pdf.c
  src/imageio/storage/email.c
  src/imageio/storage/facebook.c
  src/imageio/storage/flickr.c
  src/imageio/storage/gallery.c
  src/imageio/storage/googlephoto.c
  src/imageio/storage/latex.c
  src/imageio/storage/piwigo.c
  src/iop/colorin.c
  src/iop/colorout.c
  src/iop/lens.c
  src/libs/export.c
  src/libs/geotagging.c
  src/libs/import.c
  src/libs/modulelist.c
  src/libs/print_settings.c
  src/libs/snapshots.c
  src/libs/tools/darktable.c
  src/views/darkroom.c
  src/views/lighttable.c
Labels: enhancement

#2800 Updates to pt_BR translation
  po/pt_BR.po
Labels: translation

#2801 Add exif data to webp files (fixes #2768)
  src/imageio/format/webp.c
Labels: enhancement

#2793 lens correction: port to C++, add support for lensfun 0.3.95
  src/iop/CMakeLists.txt
  src/iop/lens.cc
Labels: enhancement, wip

#2804 Fix bug in middle button zoom for second preview window
  src/views/darkroom.c
Labels: bug

#2788 For hidden slider move show toast with value
  src/bauhaus/bauhaus.c
  src/iop/exposure.c
Labels: wip

#2805 lensfun: fix library version check, fix db loading
  src/iop/lens.cc
Labels: bug

#2809 Refresh navigation preview after zoom change
  src/views/darkroom.c
Labels: bug

#2815 fix images count in collect.c for tags
  src/libs/collect.c
Labels: bug

#2799 iop/basecurve: Reconcile code path divergence
  data/kernels/basecurve.cl
  src/iop/basecurve.c
Labels: bug, enhancement

#2818 fix combobox behavior to mimic pre-d5053b1 state
  src/bauhaus/bauhaus.c
Labels: bug

#2797 common/opencl_drivers_blacklist: Only blacklist NEO on Windows
  src/common/opencl_drivers_blacklist.h
Labels: enhancement

#2820 Tagging.c - avoid to reinit the tag tree/list on common events
  src/common/tags.c
  src/common/tags.h
  src/libs/tagging.c
Labels: bug, enhancement

#2824 Tagging.c : rename path and selection indicator update
  src/common/tags.c
  src/libs/tagging.c
Labels: enhancement
