Repository darktable-org/darktable, pull requests merged in 2019-06, with the labels that each got.

#2648 Some more css tweaks
  data/themes/darktable-elegant-grey.css
  data/themes/darktable.css
Labels: enhancement

#2645 Fix for #2618 and #2535
  src/develop/imageop.c
Labels: bug

#2650 colorzones: add display selection
  src/develop/blend.c
  src/develop/blend_gui.c
  src/develop/imageop.c
  src/develop/imageop.h
  src/develop/pixelpipe_hb.c
  src/develop/pixelpipe_hb.h
  src/iop/colorzones.c
  src/iop/levels.c
  src/iop/retouch.c
Labels: enhancement

#2569 2nd preview window on Mac
  src/develop/develop.h
  src/views/darkroom.c
Labels: bug, wip

#2663 BUGFIX: colorzones parallel loop for OpenMP 4.0
  src/iop/colorzones.c
Labels: bug

#2662 ashift: Extend maximum lensshift range
  src/iop/ashift.c
Labels: enhancement

#2676 Spanish translation update
  po/es.po
Labels: translation

#2658 gradient slider: rework markers highlight
  src/dtgtk/gradientslider.c
  src/dtgtk/gradientslider.h
Labels: enhancement

#2675 fix compilations errors with clang8 and OpenMP parallel loops shared variables
  src/common/dwt.c
  src/common/focus.h
  src/common/gaussian.c
  src/common/iop_order.c
  src/common/locallaplacian.c
  src/develop/masks/circle.c
  src/develop/masks/ellipse.c
  src/develop/masks/gradient.c
  src/iop/ashift.c
  src/iop/colorreconstruction.c
  src/iop/demosaic.c
  src/iop/filmic.c
  src/iop/globaltonemap.c
  src/iop/grain.c
  src/iop/lowlight.c
  src/iop/profile_gamma.c
Labels: bug

#2672 speedup: enable simd and loop collapsing for bilateral filter lib
  src/common/bilateral.c
  src/common/bilateral.h
  src/common/darktable.h
Labels: enhancement

#2678 add target clones
  src/common/darktable.h
Labels: enhancement

#2605 Panasonic DC-LX100M2: add noise profiles support
  data/noiseprofiles.json
Labels: noise profile

#2691 Accels fixes & enhancements
  src/develop/imageop.c
  src/gui/accelerators.c
  src/gui/accelerators.h
  src/gui/preferences.c
  src/views/darkroom.c
Labels: bug, enhancement

#2686 process histogram waveform when needed
  src/develop/pixelpipe_hb.c
  src/libs/histogram.c
Labels: enhancement

#2630 ILCE-6400-noise-profile
  data/noiseprofiles.json
Labels: noise profile

#2683 Add variable OPENCL_ACTIVATED.
  src/common/variables.c
Labels: enhancement

#2697 Lut3d - make lut filename scrollable
  src/iop/lut3d.c
Labels: enhancement

#2709 Revert store method API on PR #2692
  src/cli/main.c
  src/common/imageio_module.h
  src/control/jobs/control_jobs.c
  src/imageio/storage/disk.c
  src/imageio/storage/email.c
  src/imageio/storage/facebook.c
  src/imageio/storage/flickr.c
  src/imageio/storage/gallery.c
  src/imageio/storage/googlephoto.c
  src/imageio/storage/imageio_storage_api.h
  src/imageio/storage/latex.c
  src/imageio/storage/piwigo.c
  src/lua/luastorage.c
Labels: enhancement

#2710 lut3d: sort contents of the filename combobox
  src/iop/lut3d.c
Labels: enhancement

#2719 base curve: add norms
  data/kernels/basecurve.cl
  src/iop/basecurve.c
Labels: enhancement

#2722 copy history : respect dt selection scheme
  src/common/history.c
  src/common/history.h
  src/libs/copy_history.c
  src/libs/tools/filmstrip.c
Labels: bug, enhancement

#2720 Apply selected IOP preset on mouse button release
  src/gui/presets.c
Labels: bug, enhancement

#2716 denoiseprofile: new scattering formula (better local contrast)
  src/iop/denoiseprofile.c
Labels: enhancement

#2705 accels "remind-me" window
  src/control/control.c
  src/control/control.h
  src/develop/imageop.c
  src/develop/imageop.h
  src/develop/masks.h
  src/develop/masks/masks.c
  src/gui/gtk.c
  src/iop/ashift.c
  src/iop/clipping.c
  src/iop/graduatednd.c
  src/iop/iop_api.h
  src/iop/vignette.c
  src/views/darkroom.c
  src/views/knight.c
  src/views/lighttable.c
  src/views/map.c
  src/views/print.c
  src/views/slideshow.c
  src/views/tethering.c
  src/views/view.c
  src/views/view.h
  src/views/view_api.h
Labels: enhancement

#2643 Tonecurve - added norms to tc RGB
  data/kernels/basic.cl
  data/kernels/basicadj.cl
  data/kernels/rgb_norms.h
  data/kernels/rgbcurve.cl
  src/common/colorspaces.c
  src/common/colorspaces.h
  src/common/rgb_norms.h
  src/iop/basicadj.c
  src/iop/rgbcurve.c
  src/iop/tonecurve.c
Labels: enhancement, wip

#2638 tonecurve - cleanup histogram with log scale
  src/gui/draw.h
  src/iop/tonecurve.c
Labels: bug, enhancement, wip

#2731 Update tonecurve.c
  src/iop/tonecurve.c
Labels: bug

#2728 lighttable : fix group borders drawing
  src/views/lighttable.c
Labels: bug

#2723 fixes compiling with exiv v0.27.2.1
  src/common/exif.cc
Labels: incomplete

#2735 use CAIRO_FILTER_GOOD on navigation instead of CAIRO_FILTER_BEST
  src/libs/navigation.c
Labels: enhancement

#2733 Crop guides: flexible grid
  src/gui/draw.h
  src/gui/guides.c
Labels: enhancement, incomplete

#2737 filmstrip : reuse in-memory sqlite table
  src/libs/tools/filmstrip.c
Labels: enhancement

#2741 accels window enhancements
  data/themes/darktable.css
  src/develop/imageop.c
  src/develop/masks/masks.c
  src/views/map.c
  src/views/slideshow.c
  src/views/view.c
  src/views/view.h
Labels: enhancement

#2746 new module rgb levels
  RELEASE_NOTES.md
  data/kernels/basic.cl
  data/kernels/color_conversion.cl
  data/kernels/programs.conf
  data/kernels/rgblevels.cl
  src/common/iop_order.c
  src/iop/CMakeLists.txt
  src/iop/rgblevels.c
Labels: enhancement

#2745 filemanager : fix reorder of multiple images
  src/views/lighttable.c
Labels: bug

#2744 Css tweaks to improve fields and new accel window
  data/themes/darktable-elegant-grey.css
  data/themes/darktable.css
Labels: bug, enhancement

#2747 tonecurve: properly release the profile in OpenCL implementation.
  src/iop/tonecurve.c
Labels: bug

#2752 Aspect ratio fix
  src/common/history.c
  src/views/darkroom.c
Labels: bug

#2711 Some cleanup for cmake
  CMakeLists.txt
  ConfigureChecks.cmake
  packaging/windows/BUILD.txt
Labels: enhancement

#2757 Misc. typo fixes
  cmake/modules/NSIS.template.in
  data/darktableconfig.xml.in
  doc/usermanual/darkroom/modules/tone/tonecurve.xml
  doc/usermanual/lua/lua_api.xml
  src/views/lighttable.c
  src/views/view.c
  tools/lua_doc/content.lua
Labels: enhancement

#2758 recompute aspect ratio on styles and copy/paste
  src/common/history.c
  src/common/image.c
  src/common/image.h
  src/common/styles.c
Labels: bug

#2754 Adds adobe color matrix coeffs for Fuji XF10
  src/external/adobe_coeff.c
Labels: camera-support
