Repository darktable-org/darktable, pull requests merged in 2019-08, with the labels that each got.

#2831 Tagging.c - bug fixing + allow change path on leaves
  src/libs/tagging.c
Labels: bug, enhancement

#2838 Fixing Exif.GPSInfo.GPSLongitude and Exif.GPSInfo.GPSLatitude
  src/common/exif.cc
Labels: bug

#2841 Panasonic DC-LX100M2: add noise profiles support
  data/noiseprofiles.json
Labels: noise profile

#2830 Added placeholder text in styles dialog, fixes #2825
  src/gui/styles_dialog.c
Labels: enhancement

#2855 Add release metadata
  data/darktable.appdata.xml.in
Labels: enhancement

#2850 Tagging improvements
  data/darktableconfig.xml.in
  src/common/database.c
  src/common/exif.cc
  src/common/tags.c
  src/common/tags.h
  src/dtgtk/paint.c
  src/dtgtk/paint.h
  src/libs/metadata_view.c
  src/libs/tagging.c
Labels: enhancement

#2867 Polish translation: updated and revised
  po/pl.po
Labels: translation

#2872 culling : fix pan if some image are not zoomed
  src/views/lighttable.c
Labels: bug

#2874 Revert direction of shadows/highlights balance slider. Fixes #2610
  src/iop/splittoning.c
Labels: enhancement

#2875 Add metadata support in the camera import dialog.
  src/gui/camera_import_dialog.c
Labels: enhancement

#2878 fix EXR read with channels other than RGB
  src/common/imageio_exr.cc
Labels: bug

#2866 Tagging - bug fixing + presets enabled
  src/common/exif.cc
  src/common/exif.h
  src/common/imageio.c
  src/common/tags.c
  src/common/tags.h
  src/control/jobs/control_jobs.c
  src/dtgtk/paint.c
  src/dtgtk/paint.h
  src/imageio/storage/flickr.c
  src/imageio/storage/piwigo.c
  src/libs/metadata_view.c
  src/libs/tagging.c
Labels: bug, enhancement

#2870 Correcting history compression in lighttable mode.
  src/common/history.c
  src/common/history.h
  src/libs/history.c
Labels: bug, enhancement

#2884 Update french translation GUI
  po/fr.po
Labels: translation

#2885 Tagging - fix issue #2880 related to ctrl-T
  src/libs/tagging.c
Labels: bug

#2892 lens: fix transform routines.
  src/iop/lens.cc
Labels: bug

#2894 filmstrip : surround only current image(s)
  src/views/view.c
Labels: enhancement

#2897 Use O_BINARY flag for g_open() Fixes #2842
  src/common/darktable.h
  src/views/darkroom.c
Labels: bug
