Repository darktable-org/darktable, pull requests merged in 2019-09, with the labels that each got.

#2909 culling : fix toggle mode shortcut
  src/libs/tools/lighttable.c
Labels: bug

#2916 Change open preference button style from toggle button to button
  src/libs/tools/global_toolbox.c
Labels: bug

#2914 Split Tone: Refactor GUI element names and fix updating of the Balance slider colors
  src/iop/splittoning.c
Labels: bug, enhancement

#2925 mark keyboard shortcuts in RELEASE_NOTES.md
  RELEASE_NOTES.md
Labels: enhancement

#2927 Filter exiv2 output in get_image_iso()
  tools/noise/subr.sh
Labels: bug

#2926 Fix instance menu initialization when no module groups are selected
  src/views/darkroom.c
Labels: bug

#2931 Do not try to display db error window when not in gui
  src/common/darktable.c
Labels: bug

#2932 Fix shortcut to hide navigation thumbnail
  src/libs/navigation.c
Labels: bug

#2940 lighttable : always change offset from other views
  src/views/lighttable.c
Labels: bug

#2941 darkroom : small refactor of image change code
  src/views/darkroom.c
Labels: bug

#2759 Fix potentially invalid structure typecast
  src/libs/print_settings.c
  src/views/slideshow.c
Labels: enhancement

#2905 Fix pipe order
  src/common/iop_order.c
Labels: bug

#2918 Add all default modules that can't be disabled but are hidden into hi…
  src/common/history.c
  src/common/history.h
  src/develop/develop.c
Labels: bug

#2949 Fixing history compression and closely related stuff in development.
  src/common/history.c
  src/common/history.h
  src/develop/develop.c
  src/libs/copy_history.c
  src/libs/history.c
Labels: bug, enhancement

#2857 add lut3d doc to darktable manual
  doc/usermanual/darkroom/modules/color/group_color.xml
  doc/usermanual/darkroom/modules/color/lut3d.xml
  doc/usermanual/darkroom/modules/images/lut3d-1.png
Labels: usermanual

#2957 culling : fix if zoom == 1 and image is removed
  src/views/lighttable.c
Labels: bug

#2958 full preview : add keys for sticky preview + update doc
  doc/usermanual/lighttable/lighttable.xml
  doc/usermanual/preferences/keymappings.xml
  src/views/lighttable.c
Labels: bug

#2959 tagging - complete fix #2935 + add detach tag into dictionary popup menu
  src/libs/tagging.c
Labels: bug

#2961 Fixing the regression introduced by pr #2949
  src/develop/develop.c
Labels: bug

#2962 fix #2952 - free_align
  src/common/imageio.c
  src/common/imageio_jpeg.c
  src/common/mipmap_cache.c
  src/views/lighttable.c
Labels: bug

#2974 Back out iop-order changes in v2.
  src/common/iop_order.c
Labels: bug

#2979 Re-introduce the new iop order as v3.
  src/common/iop_order.c
Labels: enhancement

#2976 Fix loading the tone equalizer module
  src/iop/toneequal.c
Labels: bug

#2980 toneequal.c : remove the calls to _init_drawing() in gui_init() and gui_update()
  src/iop/toneequal.c
Labels: bug

#2938 Filmic v3
  src/common/iop_order.c
  src/common/iop_order.h
  src/develop/imageop_math.h
  src/iop/CMakeLists.txt
  src/iop/filmic.c
  src/iop/filmicrgb.c
Labels: enhancement

#2993 fix dt free() crash - dt_free_align in imageio_jpeg.c
  src/common/imageio_jpeg.c
  src/imageio/format/jpeg.c
  src/imageio/format/pdf.c
  src/imageio/format/png.c
Labels: bug

#2989 The advised bugtracker should now be Github
  doc/man/darktable.pod
  doc/usermanual/tethering/troubleshoot.xml
Labels: bug

#2994 correct place of filmicrgb in iop layout
  tools/iop-layout-legacy.sh
  tools/iop-layout.sh
Labels: enhancement

#2970 Again work on history.
  src/common/history.c
  src/common/history.h
  src/develop/develop.c
  src/libs/copy_history.c
  src/libs/history.c
  src/views/darkroom.c
Labels: bug, enhancement

#2987 denoiseprofile: preview more accurate
  src/iop/denoiseprofile.c
Labels: bug, enhancement

#2947 iop: Change the haze removal default values
  src/iop/hazeremoval.c
Labels: enhancement

#3000 filmicrgb : fix glitch in spline in middle zone
  src/iop/filmicrgb.c
Labels: bug

#3001 ensure filmic rgb is inserted right after filmic v2
  src/common/iop_order.c
Labels: bug

#3002 allow searching in deprecated modules that are enabled
  src/libs/modulegroups.c
Labels: enhancement

#3007 Lighttable
  src/dtgtk/paint.c
  src/views/lighttable.c
  src/views/view.c
Labels: enhancement

#3011 lighttable.xml: correct keyboard shortcuts for fully zoom from Z to W
  doc/usermanual/lighttable/lighttable.xml
Labels: bug

#3006 Fix module reorder shortcut in RELEASE_NOTES
  RELEASE_NOTES.md
Labels: bug

#3017 Add safeguard rules in iop_order to protect clipping iop
  src/common/iop_order.c
Labels: enhancement

#3024 Update denoiseprofiled wavelets
  src/iop/denoiseprofile.c
Labels: enhancement

#3033 French translation: Small typo
  po/fr.po
Labels: bug

#3032 Spanish translation update
  po/es.po
Labels: translation

#3038 Better C++ style for reading iop_order from xmp file.
  src/common/exif.cc
Labels: enhancement

#3042 denoiseprofile: faster nlmeans preview
  src/iop/denoiseprofile.c
Labels: bug, enhancement

#3040 Improve readability of preference window
  data/themes/darktable.css
  src/gui/preferences.c
  tools/generate_prefs.xsl
Labels: enhancement

#3048 tone equalizer: more general default params
  src/iop/toneequal.c
Labels: enhancement

#3047 Marking obsolete modules
  src/libs/history.c
Labels: enhancement
