Repository darktable-org/darktable, pull requests merged in 2019-10, with the labels that each got.

#3051 module name sizing moved from code to darktable.css
  data/themes/darktable.css
  src/develop/develop.c
  src/libs/lib.c
Labels: bug, enhancement

#3052 culling : fine tune selection frame
  data/themes/darktable-elegant-darker.css
  data/themes/darktable.css
  src/gui/gtk.c
  src/gui/gtk.h
  src/views/view.c
Labels: bug

#3054 save export metadata parameters to darktablerc
  src/libs/export.c
  src/libs/export_metadata.c
Labels: bug

#3061 Ascii-art for "trash" or "warning" character
  src/libs/history.c
Labels: bug

#3053 po/iop order v4
  src/common/iop_order.c
Labels: bug

#3063 Spanish translation update
  po/es.po
Labels: translation

#3058 split tags and categories in image information
  src/libs/metadata_view.c
Labels: bug, enhancement

#3067 History v3->v4 on-the-fly-conversion
  src/common/iop_order.c
  src/common/iop_order.h
  src/develop/develop.c
Labels: bug

#3072 Spanish translation update
  po/es.po
Labels: translation

#3060 denoiseprofile documentation
  doc/usermanual/darkroom/modules/correction/denoise_profiled.xml
  doc/usermanual/darkroom/modules/images/denoise_profiled.png
  doc/usermanual/darkroom/modules/images/denoise_profiled_ex1.png
Labels: usermanual

#3083 Improve tools menu consistency
  data/themes/darktable.css
Labels: bug, enhancement

#3087 Translation
  po/he.po
Labels: translation

#3096 reload_history_items needs dt_dev_modules_update_multishow(dev)
  src/develop/develop.c
Labels: bug

#3097 Polish translation update
  po/pl.po
Labels: translation

#3099 Hide deprecated modules in favourite modules menu.
  src/libs/modulegroups.c
Labels: bug

#3092 fix exception when no tag on image
  src/libs/metadata_view.c
Labels: bug

#3101 toneeq: add tooltip to warn user about preview slowdown
  src/iop/toneequal.c
Labels: enhancement

#3100 lightroom: fix import of portrait picture.
  src/develop/lightroom.c
Labels: bug

#3102 Do not allow floating window in darkroom to be smaller than 350 pixels.
  src/views/darkroom.c
Labels: bug

#3105 Updated Hebrew translation
  po/he.po
Labels: translation

#3109 Spanish translation update
  po/es.po
Labels: translation

#3110 denoiseprofile: ensure pixel values are >= 0 before backtransform
  data/kernels/denoiseprofile.cl
  src/iop/denoiseprofile.c
Labels: bug

#3113 BUG: toneeq/fast guided filter
  src/common/fast_guided_filter.h
Labels: bug

#3115 debug option ioporder
  src/common/darktable.c
  src/common/darktable.h
  src/common/iop_order.c
  src/develop/develop.c
  src/libs/modulegroups.c
  src/views/darkroom.c
Labels: enhancement

#3127 fix metadata export issues #3119
  src/CMakeLists.txt
  src/cli/main.c
  src/common/metadata_export.c
  src/common/metadata_export.h
  src/libs/export.c
  src/libs/export_metadata.c
  src/lua/luastorage.c
  src/views/darkroom.c
Labels: bug

#3125 threadsafe rowids in history.
  src/common/history.c
  src/develop/develop.c
Labels: bug

#3142 kernel: Fix building of extended.cl
  data/kernels/extended.cl
Labels: bug

#3141 BUG: fix toneequalizer behaviour in overexposed area
  src/common/fast_guided_filter.h
  src/iop/toneequal.c
Labels: bug

#3140 Fixing iop_order when applying a style
  src/common/styles.c
Labels: bug

#3146 Fix orientation in LR import
  src/common/image.h
  src/develop/lightroom.c
  src/iop/flip.c
Labels: bug

#3156 don't compare pointer value to numeric constant
  src/develop/pixelpipe_hb.c
Labels: bug

#3157 remove superfluous argument from function pointer call
  src/develop/imageop.c
  src/develop/imageop.h
  src/iop/ashift.c
  src/iop/clipping.c
  src/iop/graduatednd.c
  src/iop/iop_api.h
  src/iop/vignette.c
  src/libs/lib.c
  src/libs/lib.h
  src/libs/lib_api.h
Labels: bug

#3159 iop: Fix denoise profile backtransform_v2
  src/iop/denoiseprofile.c
Labels: bug

#3160 add missing keyboard shortcut markup in release notes
  RELEASE_NOTES.md
Labels: enhancement

#3131 update German translation
  po/de.po
Labels: translation

#3161 add new tagging features and metadata configuration in release notes
  RELEASE_NOTES.md
Labels: enhancement

#3166 fix format strings
  src/chart/main.c
  src/common/collection.c
  src/common/mipmap_cache.c
  src/common/opencl.c
  src/common/pdf.c
  src/iop/choleski.h
  src/libs/collect.c
  src/views/knight.c
Labels: bug

#3155 Fix crop in LR import
  src/develop/lightroom.c
Labels: bug

#3122 FIx source comment typos
  src/common/cups_print.c
  src/common/exif.cc
  src/common/iop_order.h
  src/common/pdf.c
  src/common/tags.h
Labels: enhancement

#3174 Fixing copy&paste of history (v2)
  src/common/history.c
  src/common/iop_order.c
  src/gui/hist_dialog.c
Labels: bug

#3173 fix tagging display issue when attach without selected image
  src/libs/tagging.c
Labels: bug

#3170 enhance portability
  src/iop/basicadj.c
Labels: bug

#3180 fix PR #3170
  src/iop/basicadj.c
Labels: bug

#3190 denoiseprofile: add missing error check for opencl
  src/iop/denoiseprofile.c
Labels: bug

#3194 tone equalizer: improve tooltips and remove labels
  src/iop/toneequal.c
Labels: enhancement

#3195 filmicrgb: remove presets hints about use
  src/iop/filmicrgb.c
Labels: enhancement

#3199 Spanish translation update
  po/es.po
Labels: translation

#3198 History compression on origin.
  src/common/history.c
Labels: bug

#3200 Polish translation update
  po/pl.po
Labels: translation

#3197 Hope to fix writing hdr dng files.
  src/common/exif.cc
  src/common/imageio_dng.h
Labels: bug

#3208 filmicrgb : improve tooltips
  src/iop/filmicrgb.c
Labels: translation

#3201 lock db at high level **per image**
  src/common/darktable.c
  src/common/darktable.h
  src/common/film.c
  src/common/history.c
  src/common/history_snapshot.c
  src/develop/develop.c
Labels: bug, enhancement

#3214 Fix orientation for non DNG files.
  src/common/exif.cc
Labels: bug

#3219 Po/fix clipping masks
  src/iop/clipping.c
Labels: bug

#3082 usermanual: add open-sans.css to html.stylesheet
  doc/usermanual/xsl/darktable_html_dtorg.xsl
Labels: usermanual

#3225 color_conversion: fix error on macos.
  data/kernels/color_conversion.cl
Labels: bug

#3233 Spanish translation update
  po/es.po
Labels: translation

#3226 LR import: Code simplification + Fix for rotation angle
  src/develop/lightroom.c
Labels: bug, enhancement

#3244 Spanish translation update
  po/es.po
Labels: translation

#3246 crop&rotate: small fix in french translation
  po/fr.po
Labels: translation
