Repository darktable-org/darktable, pull requests merged in 2019-03, with the labels that each got.

#2143 replace free by g_free
  src/lua/database.c
  src/lua/film.c
  src/lua/preferences.c
Labels: enhancement

#2146 fix color picker
  src/develop/imageop.c
  src/develop/imageop.h
  src/develop/pixelpipe_hb.c
  src/gui/color_picker_proxy.c
  src/gui/color_picker_proxy.h
  src/iop/borders.c
  src/iop/colorbalance.c
  src/iop/colorize.c
  src/iop/colorzones.c
  src/iop/exposure.c
  src/iop/filmic.c
  src/iop/graduatednd.c
  src/iop/invert.c
  src/iop/levels.c
  src/iop/monochrome.c
  src/iop/profile_gamma.c
  src/iop/relight.c
  src/iop/retouch.c
  src/iop/splittoning.c
  src/iop/temperature.c
  src/iop/tonecurve.c
  src/iop/watermark.c
Labels: bug

#2150 Update Polish translation
  po/pl.po
Labels: translation

#2144 Update darktable-chart documentation
  doc/usermanual/topics/darktable-chart.xml
Labels: usermanual

#2001 manual: colorbalance
  doc/usermanual/darkroom/modules/color/colorbalance.xml
Labels: usermanual

#2151 upgrade color picker
  src/common/color_picker.c
  src/common/color_picker.h
  src/common/colorspaces_inline_conversions.h
  src/develop/blend.c
  src/develop/blend.h
  src/develop/blend_gui.c
  src/develop/imageop.c
  src/develop/imageop.h
  src/develop/pixelpipe_hb.c
  src/gui/color_picker_proxy.c
  src/gui/color_picker_proxy.h
  src/iop/borders.c
  src/iop/colorbalance.c
  src/iop/colorize.c
  src/iop/colorzones.c
  src/iop/exposure.c
  src/iop/filmic.c
  src/iop/graduatednd.c
  src/iop/invert.c
  src/iop/levels.c
  src/iop/monochrome.c
  src/iop/profile_gamma.c
  src/iop/relight.c
  src/iop/retouch.c
  src/iop/splittoning.c
  src/iop/temperature.c
  src/iop/tonecurve.c
  src/views/darkroom.c
Labels: enhancement

#2152 Polish translation fixes
  po/pl.po
Labels: translation

#2156 colormapping: some code clean-up
  src/iop/colormapping.c
Labels: enhancement

#2157 upgrade colorzones
  src/common/colorspaces_inline_conversions.h
  src/common/histogram.c
  src/common/histogram.h
  src/develop/blend.c
  src/develop/blend_gui.c
  src/develop/imageop.c
  src/develop/imageop.h
  src/develop/pixelpipe_hb.c
  src/gui/color_picker_proxy.c
  src/gui/color_picker_proxy.h
  src/iop/colorzones.c
Labels: enhancement

#2158 update features notes
  RELEASE_NOTES.md
Labels: enhancement

#2163 Update and fix Spanish locale
  po/es.po
Labels: translation

#2160 Fix #2138 by making handling of tag "changed" more effective
  src/common/history.c
  src/develop/develop.c
  src/views/darkroom.c
Labels: bug, enhancement, incomplete

#2165 French update of 2.6 manual
  doc/usermanual/darkroom/modules/color/colorbalance.xml
  doc/usermanual/po/fr.po
Labels: usermanual

#2166 fix crash
  src/common/iop_order.c
Labels: bug

#2181 new "quick" image_infos lib
  data/darktableconfig.xml.in
  src/common/variables.c
  src/libs/CMakeLists.txt
  src/libs/tools/filter.c
  src/libs/tools/image_infos.c
Labels: enhancement

#2127 Denoise profile updates
  data/kernels/denoiseprofile.cl
  src/iop/denoiseprofile.c
Labels: enhancement

#2167 upgrade color zones
  RELEASE_NOTES.md
  data/kernels/basic.cl
  src/develop/blend_gui.c
  src/dtgtk/paint.c
  src/dtgtk/paint.h
  src/iop/colorzones.c
Labels: enhancement

#2191 color transform performance
  data/kernels/colorspaces.cl
  src/common/colorspaces.h
  src/common/iop_order.c
  src/common/iop_order.h
  src/develop/pixelpipe_hb.c
  src/iop/overexposed.c
  src/iop/retouch.c
Labels: enhancement, incomplete

#2193 mask iop release notes
  RELEASE_NOTES.md
Labels: enhancement

#2194 fix overxpose broken
  src/common/iop_order.c
Labels: bug

#2199 Delete konami code and Knight view easter egg.
  src/common/darktable.c
  src/views/CMakeLists.txt
  src/views/knight.c
  src/views/knight_font.h
  src/views/view.c
Labels: bug, enhancement

#2198 Update Spanish translation
  po/es.po
Labels: translation

#2203 fix perspective correction
  src/iop/ashift.c
Labels: bug

#2187 fix blend rgb grey
  data/kernels/blendop.cl
  data/kernels/color_conversion.cl
  src/common/iop_order.c
  src/common/iop_order.h
  src/develop/blend.c
  src/develop/blend_gui.c
  src/develop/imageop.h
  src/iop/colorout.c
Labels: bug

#2206 fix format string issues
  src/common/dtpthread.c
  src/common/resource_limits.c
Labels: bug

#2208 doc: Document hierarchical views for the styles panel
  doc/usermanual/lighttable/panels/styles.xml
Labels: usermanual

#2211 color picker performance
  src/gui/color_picker_proxy.c
  src/views/darkroom.c
Labels: enhancement

#2149 Fix strict aliasing issues
  .gitignore
  data/kernels/basecurve.cl
  data/kernels/basic.cl
  src/CMakeLists.txt
  src/common/darktable.h
  src/common/exif.cc
  src/common/image_cache.c
  src/common/imageio_dng.h
  src/common/interpolation.c
  src/common/points.h
  src/iop/amaze_demosaic_RT.cc
  src/iop/ashift.c
  src/iop/clipping.c
  src/iop/rawprepare.c
  tools/CMakeLists.txt
Labels: enhancement

#2213 Add missing accels for selected images module
  src/libs/image.c
Labels: enhancement

#2197 adds initial raster mask documentation
  doc/usermanual/darkroom/concepts/blending.xml
  doc/usermanual/darkroom/concepts/raster_masks.xml
Labels: usermanual

#2219 Update Spanish translation
  po/es.po
Labels: translation

#2220 liquify distord
  src/iop/liquify.c
Labels: bug

#2217 fix edit by area zoom
  src/gui/draw.h
  src/iop/colorzones.c
Labels: bug

#2168 new module basic adjustments
  RELEASE_NOTES.md
  data/kernels/basicadj.cl
  data/kernels/programs.conf
  src/common/iop_order.c
  src/iop/CMakeLists.txt
  src/iop/basicadj.c
Labels: enhancement

#2239 retouch backward comp
  src/iop/retouch.c
Labels: bug

#2236 Update french manual
  doc/usermanual/po/fr.po
Labels: usermanual

#2195 add a iop search box
  RELEASE_NOTES.md
  data/darktableconfig.xml.in
  src/control/control.c
  src/control/control.h
  src/develop/develop.c
  src/develop/develop.h
  src/gui/gtk.c
  src/libs/modulegroups.c
  src/views/darkroom.c
Labels: enhancement, wip

#2240 Update Polish translation
  po/pl.po
Labels: translation

#2088 remove warnings and special treatment for 32-bit architectures
  data/darktableconfig.xml.in
  src/common/darktable.c
  src/is_supported_platform.h
  src/views/view.c
Labels: enhancement

#2169 new module rgb curve
  RELEASE_NOTES.md
  data/kernels/programs.conf
  data/kernels/rgbcurve.cl
  src/common/histogram.c
  src/common/iop_order.c
  src/gui/draw.h
  src/iop/CMakeLists.txt
  src/iop/rgbcurve.c
Labels: enhancement

#2248 allow rgb modules to be before colorin
  data/kernels/basicadj.cl
  data/kernels/color_conversion.cl
  data/kernels/rgbcurve.cl
  src/common/colorspaces_inline_conversions.h
  src/common/iop_order.c
  src/common/iop_order.h
  src/develop/blend.c
  src/develop/blend_gui.c
  src/iop/basicadj.c
  src/iop/rgbcurve.c
Labels: bug

#2249 Add noise profile for Nikon Z 7
  data/noiseprofiles.json
Labels: noise profile

#2250 color picker updates
  src/develop/blend_gui.c
  src/develop/pixelpipe_hb.c
  src/gui/color_picker_proxy.c
  src/gui/color_picker_proxy.h
  src/iop/basicadj.c
  src/iop/borders.c
  src/iop/colorbalance.c
  src/iop/colorize.c
  src/iop/colorzones.c
  src/iop/exposure.c
  src/iop/filmic.c
  src/iop/graduatednd.c
  src/iop/invert.c
  src/iop/levels.c
  src/iop/monochrome.c
  src/iop/profile_gamma.c
  src/iop/relight.c
  src/iop/retouch.c
  src/iop/rgbcurve.c
  src/iop/splittoning.c
  src/iop/temperature.c
  src/iop/tonecurve.c
  src/iop/watermark.c
Labels: bug, enhancement

#2253 update contextual help url with new doc url
  src/libs/tools/global_toolbox.c
Labels: enhancement

#2254 lib: fix function signature
  src/libs/lib.c
Labels: bug

#2251 Spanish translation update
  po/es.po
Labels: translation

#2255 Nikon Z 7 White Balance Presets
  src/external/wb_presets.c
Labels: camera-support

#2257 color picker updates
  src/common/iop_order.c
  src/common/iop_order.h
  src/develop/pixelpipe_hb.c
  src/gui/color_picker_proxy.c
  src/gui/color_picker_proxy.h
  src/iop/basicadj.c
  src/iop/colorzones.c
  src/iop/rgbcurve.c
  src/libs/colorpicker.c
  src/libs/lib.c
  src/libs/lib.h
Labels: bug, enhancement

#2259 remove meaningless const declarations in return types
  src/common/colorspaces.c
  src/imageio/storage/piwigo.c
  src/iop/demosaic.c
  src/iop/liquify.c
Labels: enhancement

#2261 check for NULL on db start up
  src/common/darktable.c
  src/common/iop_order.c
  src/common/iop_order.h
Labels: enhancement

#2262 rawoverexposed: avoid unnecessary cast
  src/iop/rawoverexposed.c
Labels: enhancement

#2263 fix rgb colorspace transform
  src/common/iop_order.c
Labels: bug

#2273 Lua API: darkroom_display_image
  doc/usermanual/lua/lua_api.xml
  src/views/darkroom.c
Labels: enhancement

#2265 hazeremoval: remove duplicate code
  src/iop/hazeremoval.c
Labels: enhancement

#1496 fix combox and container lua widget behaviour
  src/lua/widget/combobox.c
  src/lua/widget/container.c
Labels: bug

#2270 timeline : update state when changing view
  src/views/lighttable.c
Labels: bug

#2272 fix asan build
  src/common/opencl.c
  src/common/selection.c
  src/libs/modulelist.c
Labels: bug, enhancement

#2276 blend: replace macro by inline function
  src/common/math.h
  src/develop/blend.c
Labels: enhancement

#2277 Lua API: hide, show and query visibility of gui panels
  doc/usermanual/lua/lua_api.xml
  src/lua/gui.c
Labels: enhancement

#2267 lighttabe : full preview & exposé zoom
  data/darktableconfig.xml.in
  src/common/focus.h
  src/common/mipmap_cache.c
  src/common/mipmap_cache.h
  src/control/control.h
  src/gui/gtk.c
  src/libs/duplicate.c
  src/libs/tools/filmstrip.c
  src/views/lighttable.c
  src/views/tethering.c
  src/views/view.c
  src/views/view.h
Labels: enhancement

#2282 Lua API: Add lighttable mode layout and zoom level control
  doc/usermanual/lua/lua_api.xml
  src/libs/tools/lighttable.c
Labels: enhancement

#2284 Lua API: Add view toolbox sort, sort order, rating, and rating comparator control
  doc/usermanual/lua/lua_api.xml
  src/libs/tools/filter.c
Labels: enhancement

#2285 redo rename window fix
  src/develop/imageop.c
Labels: bug

#2278 place hq export in export module
  data/darktableconfig.xml.in
  src/libs/export.c
Labels: enhancement, incomplete

#2293 expose : scroll shouldn't change filemanager zoom
  src/views/lighttable.c
Labels: bug

#2292 duplicate : keep thumb in sync with current preview
  src/libs/duplicate.c
Labels: enhancement

#2287 preview zoom : dynamic memory allocation for full-res image
  src/common/mipmap_cache.c
Labels: bug

#2283 Variance computation mode in denoiseprofile
  data/darktableconfig.xml.in
  src/iop/denoiseprofile.c
Labels: enhancement, incomplete

#2294 fix buffer overflow
  src/common/darktable.c
  src/common/darktable.h
  src/common/imageio.c
  src/develop/develop.c
  src/develop/pixelpipe_hb.c
Labels: bug

#2295 update picker in point mode while dragging
  src/views/darkroom.c
  src/views/view.c
Labels: bug, enhancement

#2298 add skip on conflict export option
  RELEASE_NOTES.md
  src/imageio/storage/disk.c
Labels: enhancement

#2302 dt_history_get_items: order by num as in previous version.
  src/common/history.c
Labels: enhancement

#2299 undo: fix meaningless casts
  src/common/colorlabels.c
  src/common/history.c
  src/common/history_snapshot.c
  src/common/history_snapshot.h
  src/common/metadata.c
  src/common/ratings.c
  src/common/styles.c
  src/common/tags.c
  src/common/undo.c
  src/common/undo.h
  src/control/jobs/control_jobs.c
  src/libs/history.c
  src/views/map.c
Labels: enhancement

#2304 display a confirm message on export
  src/common/imageio_module.c
  src/common/imageio_module.h
  src/imageio/storage/disk.c
  src/imageio/storage/imageio_storage_api.h
  src/libs/export.c
  src/lua/luastorage.c
Labels: enhancement

#2309 lighttable : offsets & selection enhancements
  src/views/lighttable.c
Labels: enhancement
