Repository darktable-org/darktable, pull requests merged in 2019-01, with the labels that each got.

#1952 preferences: add section in preference dialog for better readability.
  data/darktable.css.in
  data/darktableconfig.dtd
  data/darktableconfig.xml.in
  tools/generate_prefs.xsl
Labels: enhancement

#1957 equalizer: new deblurring presets
  src/iop/atrous.c
Labels: enhancement

#1965 Updated Czech translation
  po/cs.po
Labels: translation

#1714 Add base-/tonecurves for Olympus OM-D E-M10 II
  src/iop/basecurve.c
  src/iop/tonecurve.c
Labels: camera-support

#1543 fixes switching to first google+ album after exporting an image
  src/imageio/storage/picasa.c
Labels: bug

#1969 colorbalance: BUGFIX
  src/iop/colorbalance.c
Labels: bug

#1976 Soft boundaries for denoising sliders
  src/iop/bilateral.cc
  src/iop/denoiseprofile.c
  src/iop/nlmeans.c
  src/iop/rawdenoise.c
Labels: bug, enhancement

#1982 colorbalance: add film-emulation presets
  src/iop/colorbalance.c
Labels: enhancement

#1972 exposure: rename the black setting
  src/iop/exposure.c
Labels: enhancement

#1701 Add OARS metadata
  data/darktable.appdata.xml.in
Labels: enhancement

#1998 mask jump - 12387
  src/develop/masks.h
  src/develop/masks/brush.c
  src/develop/masks/circle.c
  src/develop/masks/ellipse.c
  src/develop/masks/masks.c
  src/develop/masks/path.c
  src/views/darkroom.c
Labels: bug

#1991 presets: update documentation for import/export
  doc/usermanual/preferences/presets.xml
Labels: usermanual

#1529 Bugfix: keep selection in single image mode when changing filter
  src/views/lighttable.c
Labels: bug

#1636 temperature: find raw coeffs via a function
  src/iop/temperature.c
Labels: enhancement

#1996 imageio_tiff: support for 8/16bit tiff with CIELAB/ICCLAB photometric
  src/common/imageio_tiff.c
Labels: enhancement

#1530 Bugfix: rating was modified on pan in lighttable
  src/gui/gtk.c
  src/views/lighttable.c
  src/views/view.h
Labels: bug

#2012 added WB presets for missing Nikon D500
  src/external/wb_presets.c
Labels: camera-support

#2018 iop/denoiseprofile.c: initialize ISO for interpolation
  src/iop/denoiseprofile.c
Labels: bug

#2016 Bugfix: filtering of mouse move events flawed
  src/views/lighttable.c
  src/views/view.c
  src/views/view.h
Labels: bug, incomplete

#2021 Hint opacity
  src/develop/masks/masks.c
Labels: enhancement

#2022 Nlmeans: enable bilateral filtering (P=0)
  src/iop/nlmeans.c
Labels: bug

#2030 filmic: fix SSE bug introduced in #2025
  src/iop/filmic.c
Labels: bug

#2019 data/noiseprofiles.schema: reduce minimum ISO check
  data/noiseprofiles.schema
Labels: enhancement

#2020 [UI usability] [WIP] masks selection from icons in 1-click
  src/develop/blend.h
  src/develop/blend_gui.c
  src/dtgtk/paint.c
  src/dtgtk/paint.h
Labels: enhancement

#2033 Add version string to opencl kernel cache dir to rebuild caches after driver update
  src/common/opencl.c
Labels: bug, enhancement
