Repository darktable-org/darktable, pull requests merged in 2019-04, with the labels that each got.

#2326 lighttable : fix drag-n-drop and zoom center
  src/views/lighttable.c
  src/views/view.c
  src/views/view.h
Labels: bug, enhancement

#2325 lighttable : fix offset jump
  src/control/signal.c
  src/control/signal.h
  src/libs/collect.c
  src/libs/recentcollect.c
  src/libs/tools/timeline.c
  src/views/lighttable.c
Labels: bug

#2328 Spanish translation update
  po/es.po
Labels: translation

#2321 new lighttable mode: culling
  RELEASE_NOTES.md
  src/libs/tools/lighttable.c
  src/views/lighttable.c
  src/views/view.c
  src/views/view.h
Labels: enhancement

#2331 Expose zoom fix
  src/common/mipmap_cache.c
  src/views/lighttable.c
  src/views/view.c
Labels: bug

#2082 Add support for image renaming to the C and Lua APIs.
  src/common/image.c
  src/common/image.h
  src/common/image_cache.c
  src/control/jobs/control_jobs.c
  src/lua/database.c
Labels: enhancement, wip

#2334 culling: make filmstrip follow full preview
  src/control/control.h
  src/gui/gtk.c
  src/views/lighttable.c
Labels: enhancement

#2333 Lighttable panels + full preview filmstrip
  data/darktableconfig.xml.in
  src/control/control.c
  src/gui/gtk.c
  src/views/lighttable.c
  src/views/view.c
  src/views/view.h
Labels: enhancement

#2336 Expose culling : zoom and pan enhancements + return to filemanager on quit
  data/darktableconfig.xml.in
  src/libs/tools/lighttable.c
  src/views/lighttable.c
  src/views/view.c
  src/views/view.h
Labels: enhancement

#2337 guided filter: reduce consumption of temporary memory
  src/common/guided_filter.c
Labels: enhancement

#2338 lighttable : enhance full preview zoom memory
  src/common/mipmap_cache.c
  src/common/mipmap_cache.h
  src/views/lighttable.c
  src/views/view.c
Labels: bug

#2340 Spanish translation update
  po/es.po
Labels: translation

#2348 Polish translation update
  po/pl.po
Labels: translation

#2345 culling: keep zoom when selection changes
  src/views/lighttable.c
Labels: enhancement

#2350 expose culling : fix pan limits
  src/views/lighttable.c
Labels: bug

#2359 fix colorin and colorout profile filename size
  src/iop/colorin.c
  src/iop/colorout.c
Labels: bug

#2341 store modified data/time in XMP to properly restore it on import.
  src/common/exif.cc
Labels: bug, enhancement

#2358 culling: keep cache in memory
  src/views/lighttable.c
Labels: enhancement, wip

#2360 retouch : allow to change algorithm afterwards
  src/iop/retouch.c
Labels: enhancement, incomplete

#2353 Complete Italian translation for user manual
  doc/usermanual/po/it.po
Labels: usermanual

#2349 guided filter: OpenCL implementation
  data/kernels/guided_filter.cl
  data/kernels/programs.conf
  src/common/guided_filter.c
  src/common/guided_filter.h
  src/common/opencl.c
  src/common/opencl.h
Labels: enhancement

#2369 dt_show_times: increase buffer size
  src/common/darktable.c
Labels: enhancement

#2367 allow caching within OpenCL pixelpipe
  data/darktableconfig.xml.in
  doc/usermanual/topics/opencl.xml
  src/common/opencl.c
  src/common/opencl.h
  src/develop/pixelpipe_hb.c
Labels: enhancement

#2370 lighttable : hide scrollbar in preview/expose/culling
  src/views/lighttable.c
Labels: enhancement

#2371 mipmaps : increase default size
  data/darktableconfig.xml.in
  src/views/lighttable.c
Labels: enhancement

#2365 Darkroom second window
  RELEASE_NOTES.md
  src/common/colorspaces.c
  src/common/colorspaces.h
  src/common/iop_order.c
  src/common/opencl.c
  src/common/opencl.h
  src/control/jobs/develop_jobs.c
  src/control/jobs/develop_jobs.h
  src/control/signal.c
  src/control/signal.h
  src/develop/develop.c
  src/develop/develop.h
  src/develop/imageop.c
  src/develop/pixelpipe.c
  src/develop/pixelpipe.h
  src/develop/pixelpipe_hb.c
  src/develop/pixelpipe_hb.h
  src/dtgtk/paint.c
  src/dtgtk/paint.h
  src/gui/gtk.c
  src/iop/colorin.c
  src/iop/colorout.c
  src/iop/demosaic.c
  src/libs/history.c
  src/views/darkroom.c
  src/views/lighttable.c
  src/views/view.c
Labels: enhancement

#2375 Added PL usermanual translation
  doc/usermanual/darktable.xml
  doc/usermanual/po/LINGUAS
  doc/usermanual/po/pl.po
Labels: usermanual

#2387 Make info line non-modifiable
  src/libs/tools/image_infos.c
Labels: bug, enhancement

#2389 add error messages to colorin
  src/iop/colorin.c
Labels: enhancement

#2390 add new preview2 pipe opencl scheduling description
  src/common/opencl.c
Labels: enhancement

#2399 hazeremoval: OpenCL implementation
  data/kernels/hazeremoval.cl
  data/kernels/programs.conf
  src/common/dlopencl.c
  src/common/opencl.c
  src/common/opencl.h
  src/iop/hazeremoval.c
Labels: enhancement

#2401 do not create preview2 nodes if not needed
  src/views/darkroom.c
Labels: bug

#2403 Spanish translation update
  po/es.po
Labels: translation

#2411 UI: set font weight to normal in history stack
  data/darktable.css.in
Labels: enhancement

#2415 Update zh_CN.po
  po/zh_CN.po
Labels: translation

#2414 bauhaus: fix linker problem
  src/bauhaus/bauhaus.h
Labels: bug

#2417 bauhaus: fix zero-point of soft-bound sliders
  src/bauhaus/bauhaus.c
Labels: bug

#2391 Added second order sorting functionality to image collection.
  src/common/collection.c
  src/common/collection.h
Labels: enhancement

#2422 Spanish translation update
  po/es.po
Labels: translation

#2424 UI : Use medium font size instead of semi-bold for buttons
  data/darktable-elegant.css
  data/darktable.css
Labels: bug, enhancement

#2427 Invert black compensation and exposure sliders in UI
  src/iop/exposure.c
Labels: enhancement

#2426 Bump GTK required version to 3.22
  src/CMakeLists.txt
  src/iop/watermark.c
Labels: enhancement

#2423 Add different timeouts depending on the importance of the view.
  src/views/darkroom.c
Labels: enhancement

#2435 Spanish translation update
  po/es.po
Labels: translation

#2443 improve comments for CSS sections (help designers)
  data/darktable.css
Labels: enhancement

#2444 lighttable : redraw when moving view with keys
  src/views/lighttable.c
Labels: bug

#2442 preview : don't recompute each time
  src/common/mipmap_cache.c
  src/common/mipmap_cache.h
  src/views/view.c
Labels: bug

#2445 attempt to fix ugly scrollbars shades #2380
  data/darktable-elegant.css
  data/darktable.css
Labels: bug, enhancement

#2447 noiseprofile: add Canon Powershot SX160 IS
  data/noiseprofiles.json
  data/noiseprofiles.schema
Labels: noise profile

#2448 remove a bit of contrast on modules header (names)
  data/darktable-elegant.css
  data/darktable.css
Labels: enhancement

#2449 rgb curve: scale displayed values
  src/iop/rgbcurve.c
Labels: enhancement

#2128 3D LUT module
  data/darktableconfig.xml.in
  data/kernels/lut3d.cl
  data/kernels/programs.conf
  src/common/colorspaces.c
  src/common/colorspaces.h
  src/common/colorspaces_inline_conversions.h
  src/common/imageio_png.c
  src/common/imageio_png.h
  src/common/iop_order.c
  src/iop/CMakeLists.txt
  src/iop/lut3d.c
  tools/generate_prefs.xsl
  tools/iop-layout.sh
Labels: enhancement, wip

#2465 expose/culling : enhance layout
  src/common/image.c
  src/common/image.h
  src/views/lighttable.c
Labels: bug, enhancement

#2450 Update windows build instruction
  packaging/windows/BUILD.txt
Labels: enhancement

#2470 lighttable preview : fix zoom with hotkey
  src/views/lighttable.c
Labels: bug
