Repository darktable-org/darktable, pull requests merged in 2019-02, with the labels that each got.

#2000 Bugfix for opencl of nlmeans (denoiseprofile)
  data/kernels/denoiseprofile.cl
Labels: bug

#1999 Bugfix for opencl of nlmeans
  data/kernels/nlmeans.cl
Labels: bug

#1806 denoise profile NLmeans: fast coarse noise reduction
  src/iop/denoiseprofile.c
Labels: enhancement, incomplete

#2057 update for german translation
  po/de.po
Labels: translation

#2052 collection: fix group filtering
  src/common/collection.c
Labels: bug

#2058 bauhaus: fix format string
  src/bauhaus/bauhaus.c
Labels: bug, enhancement

#2063 main: fix memory leak & format string bug, minor reformating
  src/chart/main.c
Labels: bug

#2066 fix color pick
  src/develop/pixelpipe_hb.c
  src/iop/gamma.c
Labels: bug

#2062 Collect single-click
  data/darktableconfig.xml.in
  src/libs/collect.c
Labels: enhancement

#2068 masks: fix detection of mouse pointer inside a path
  src/develop/masks/masks.c
Labels: bug

#2070 view: return proper value when button event is handled by plugin
  src/views/view.c
Labels: bug

#2067 svd: fix check for non-convergence, minor refactoring
  src/iop/svd.h
Labels: bug

#2072 Add Spanish Translation
  po/es.po
Labels: translation

#2075 svd: refactoring
  src/iop/svd.h
Labels: enhancement

#2076 hazeremoval: fix median-of-three heuristic in quick_select
  src/iop/hazeremoval.c
Labels: enhancement

#2079 fix some format string related issues
  src/chart/main.c
  src/common/cups_print.c
  src/common/imageio_pnm.c
  src/imageio/storage/piwigo.c
  src/libs/camera.c
Labels: bug

#2084 collect : fix single-click with folders/tags
  src/libs/collect.c
Labels: bug

#2014 usermanual: German user manual with darktable 2.6 changes
  doc/usermanual/po/de.po
Labels: usermanual

#2096 fix color picker
  src/develop/pixelpipe_hb.c
Labels: bug

#2097 Updated Catalan translation
  po/ca.po
Labels: translation

#2090 fix memory leaks
  src/gui/gtk.c
  src/gui/preferences.c
Labels: bug, incomplete

#2098 tags: fix memory leak
  src/common/tags.c
Labels: bug

#2102 lighttable: fix memory leak
  src/views/lighttable.c
Labels: bug

#2069 add colorspace to color picker
  src/common/colorspaces.c
  src/common/colorspaces.h
  src/develop/pixelpipe_hb.c
  src/iop/colorout.c
  src/views/darkroom.c
Labels: enhancement

#2109 fix memory leaks
  src/imageio/storage/gallery.c
Labels: bug

#2107 fix color picker
  src/develop/pixelpipe_hb.c
  src/libs/colorpicker.c
  src/libs/colorpicker.h
  src/libs/lib.h
Labels: bug, enhancement

#1082 Send to trash: add an option to delete all files
  src/control/jobs/control_jobs.c
Labels: enhancement, incomplete

#2119 fix overexposed
  data/kernels/basic.cl
  src/iop/colorout.c
  src/iop/overexposed.c
Labels: bug

#2120 bugfix: halos in local contrast and other weird things
  src/CMakeLists.txt
Labels: bug

#2121 Bump OpenCL to version 1.2
  data/kernels/CMakeLists.txt
Labels: enhancement

#2122 OpenCL: remove -cl-fast-relaxed-math compiler flag
  src/common/opencl.c
Labels: enhancement

#2116 group: remove unused code
  src/develop/masks/group.c
Labels: enhancement

#2124 Updated Catalan translation
  po/ca.po
Labels: translation

#2125 watermark: avoid mixed precision arithmetic, remove redundant code
  src/iop/watermark.c
Labels: enhancement, incomplete

#2133 align all memory buffers on 64 bytes blocks
  src/chart/pfm.c
  src/common/bilateral.c
  src/common/cache.c
  src/common/imageio_png.c
  src/common/interpolation.c
  src/common/locallaplacian.c
  src/common/mipmap_cache.c
  src/common/opencl.c
  src/common/points.h
  src/develop/imageop_math.c
  src/develop/pixelpipe_cache.c
  src/imageio/format/pfm.c
  src/iop/amaze_demosaic_RT.cc
  src/iop/atrous.c
  src/iop/colorreconstruction.c
  src/iop/demosaic.c
  src/iop/denoiseprofile.c
  src/iop/globaltonemap.c
  src/iop/lens.c
  src/iop/liquify.c
  src/iop/rawoverexposed.c
  src/iop/sharpen.c
  src/iop/soften.c
Labels: enhancement

#2132 Updated Spanish translation
  po/es.po
Labels: translation

#2114 Lighttable undo
  src/common/colorlabels.c
  src/common/metadata.c
  src/common/metadata.h
  src/common/ratings.c
  src/common/tags.c
  src/common/undo.c
  src/common/undo.h
  src/develop/masks/masks.c
  src/libs/history.c
  src/libs/metadata.c
  src/libs/tagging.c
  src/views/lighttable.c
  src/views/map.c
Labels: enhancement
