Repository darktable-org/darktable, pull requests merged in 2019-05, with the labels that each got.

#2489 paste history duplicate masks
  src/develop/develop.c
Labels: bug

#2493 darkroom : fix gtk errors with some iop
  src/iop/rotatepixels.c
  src/iop/scalepixels.c
Labels: bug

#2487 Grey theme for new UI
  data/darktable-elegant-grey.css
  data/darktable-icons-grey.css
Labels: enhancement

#2488 Misc. typo fixes user and non-user facing
  doc/usermanual/README
  doc/usermanual/darkroom/concepts/colormanagement.xml
  doc/usermanual/darkroom/modules/color/colorbalance.xml
  doc/usermanual/darkroom/modules/tone/filmic.xml
  packaging/macosx/darktable-chart.sh
  packaging/macosx/darktable-cli.sh
  packaging/macosx/start
  src/common/collection.c
  src/common/colorspaces.c
  src/common/cups_print.c
  src/common/database.c
  src/common/dwt.c
  src/common/exif.cc
  src/common/focus.h
  src/common/guided_filter.c
  src/common/image.c
  src/common/image.h
  src/common/iop_order.c
  src/common/iop_order.h
  src/common/locallaplacian.c
  src/common/noiseprofiles.c
  src/common/opencl.c
  src/control/jobs/camera_jobs.c
  src/develop/blend_gui.c
  src/develop/develop.h
  src/develop/masks/masks.c
  src/develop/pixelpipe_hb.c
  src/dtgtk/paint.c
  src/gui/preferences.c
  src/imageio/storage/piwigo.c
  src/iop/ashift_lsd.c
  src/iop/colorbalance.c
  src/iop/demosaic.c
  src/iop/filmic.c
  src/iop/gaussian_elimination.h
  src/iop/liquify.c
  src/iop/mask_manager.c
  src/iop/retouch.c
  src/iop/tonecurve.c
  src/iop/zonesystem.c
  src/libs/history.c
  src/libs/import.c
  src/libs/metadata_view.c
  src/libs/print_settings.c
  src/libs/snapshots.c
  src/libs/tools/timeline.c
  src/lua/types.c
  src/lua/types.h
  src/views/knight.c
  src/views/lighttable.c
  src/views/view.c
  tools/noise/CMakeLists.txt
Labels: bug, enhancement, usermanual

#2471 expose : refactor to limit recompute
  src/gui/gtk.c
  src/views/lighttable.c
  src/views/view.c
Labels: enhancement

#2508 culling : prefetch next/previous images
  src/views/lighttable.c
Labels: enhancement

#2511 expose : fix image order
  src/views/lighttable.c
Labels: bug

#2513 Optional side panel mouse wheel scrolling
  data/darktableconfig.xml.in
  src/bauhaus/bauhaus.c
  src/gui/gtk.c
Labels: enhancement

#2504 CSS improvments for dialog headerbar and make separator transparent in grey css theme
  data/themes/darktable-elegant-grey.css
  data/themes/darktable.css
Labels: bug, wip

#2518 lib duplicate : preview with zoom
  src/libs/duplicate.c
  src/views/view.c
  src/views/view.h
Labels: enhancement

#2523 Spanish user manual: completed translation
  AUTHORS
  doc/usermanual/darktable.xml
  doc/usermanual/po/es.po
Labels: usermanual

#2521 expose/culling : limit call to database
  src/views/lighttable.c
Labels: enhancement

#2532 Spanish user manual translation update
  doc/usermanual/po/es.po
Labels: usermanual

#2530 Culling prefetch & selection fixes
  src/libs/tools/lighttable.c
  src/views/lighttable.c
  src/views/view.c
Labels: bug, enhancement

#2541 Spanish translation update
  po/es.po
Labels: translation

#2546 fix histogram not updated
  src/develop/pixelpipe_hb.c
Labels: bug

#2554 fix swap channels on histogram
  src/develop/pixelpipe_hb.c
Labels: bug

#2560 clear search text on module group change
  src/libs/modulegroups.c
Labels: enhancement

#2555 Fix 'crop and rotate' to not exceed picture boudaries
  src/iop/clipping.c
Labels: bug

#2572 Piwigo: escape username and password strings to support usage of special characters
  src/imageio/storage/piwigo.c
Labels: bug

#2573 Panasonic DC-LX100M2: add white balance profiles support
  src/external/wb_presets.c
Labels: camera-support

#2576 side panel scrollin update
  src/iop/atrous.c
  src/iop/basecurve.c
  src/iop/colorcorrection.c
  src/iop/colorzones.c
  src/iop/levels.c
  src/iop/lowlight.c
  src/iop/monochrome.c
  src/iop/rawdenoise.c
  src/iop/retouch.c
  src/iop/rgbcurve.c
  src/iop/tonecurve.c
  src/iop/zonesystem.c
Labels: enhancement

#2580 German translation: avoid random capitalization of initials
  po/de.po
Labels: translation

#2581 UI css minor tweaks
  data/themes/darktable-elegant.css
  data/themes/darktable-icons.css
  data/themes/darktable.css
Labels: enhancement

#2583 cmake: Fix building darktable-chart
  src/chart/CMakeLists.txt
  src/chart/dtcairo.c
  src/chart/dtcairo.h
  src/chart/main.c
Labels: bug

#2587 lighttable : define preview frame in css
  data/themes/darktable-elegant-grey.css
  data/themes/darktable-elegant.css
  data/themes/darktable.css
  src/gui/gtk.c
  src/gui/gtk.h
  src/views/view.c
Labels: enhancement

#2591 Spanish translation update
  po/es.po
Labels: translation

#2593 culling : Allow to zoom/pan specific image
  src/views/lighttable.c
Labels: enhancement

#2594 culling : fix if grouping active
  src/views/lighttable.c
Labels: bug

#2586 Correct some CSS issues remaining on UI
  data/themes/darktable-elegant-grey.css
  data/themes/darktable-elegant.css
  data/themes/darktable.css
Labels: bug

#2588 don't reset mouse_over_id
  src/libs/tools/filmstrip.c
  src/views/lighttable.c
  src/views/view.c
  src/views/view.h
Labels: bug, wip

#2595 2nd window: allow fullscreen
  src/views/darkroom.c
Labels: enhancement

#2601 culling : fix segfault if zoom > 9
  src/views/lighttable.c
Labels: bug

#2602 backport ssl changes to 2.6
  packaging/macosx/darktable-chart.sh
  packaging/macosx/darktable-cli.sh
  packaging/macosx/start
  src/CMakeLists.txt
  src/common/curl_tools.c
  src/common/curl_tools.h
  src/imageio/storage/facebook.c
  src/imageio/storage/picasa.c
  src/imageio/storage/piwigo.c
  src/libs/location.c
Labels: bug

#2611 Spanish translation update
  po/es.po
Labels: translation

#2612 preview : zoom fix
  src/views/lighttable.c
Labels: bug

#2614 Fix build with exiv2 >= 0.27
  tools/basecurve/exif-wrapper.cpp
Labels: bug

#2604 Do not run copy/paste from filmstrip if in lt mode.
  src/libs/tools/filmstrip.c
Labels: bug

#2628 do not run darktable-cli if db is out-of-date
  src/common/database.c
Labels: bug

#2626 themes : change bauhaus themes on the fly too
  src/bauhaus/bauhaus.c
  src/bauhaus/bauhaus.h
  src/gui/preferences.c
Labels: enhancement

#2629 colorzones: do not move nodes on x-axis
  src/iop/colorzones.c
Labels: bug

#2625 Lua : return image displayed in darkroom
  doc/usermanual/lua/lua_api.xml
  src/views/darkroom.c
Labels: enhancement

#2627 rgb curve - added preserve colors norms
  data/kernels/rgbcurve.cl
  src/iop/rgbcurve.c
Labels: enhancement

#2620 darkroom : add dynamic accels
  src/control/control.c
  src/control/control.h
  src/gui/accelerators.c
  src/gui/accelerators.h
  src/gui/gtk.c
  src/views/darkroom.c
  src/views/view.h
Labels: enhancement

#2636 tonecurve - fixed error init of scale in gui
  src/iop/tonecurve.c
Labels: bug

#2637 Spanish translation update
  po/es.po
Labels: translation

#2639 Spanish translation update
  po/es.po
Labels: translation

#2640 lut3d.cl: fix build error
  data/kernels/lut3d.cl
Labels: bug
