Repository darktable-org/darktable, pull requests merged in 2020-09, with the labels that each got.

#6163 temperature.c: avoid memleak in gui_cleanup
  src/iop/temperature.c
Labels: bugfix

#6167 [Issue #6134] Prevent corrupt collect module presets from causing a c…
  src/libs/collect.c
Labels: bugfix

#6157 [Issue #6124] "Update Preset" operation sometimes fails silently in e…
  src/libs/lib.c
Labels: bugfix

#6170 zoomable : fix nb of row computation
  src/dtgtk/thumbtable.c
Labels: bugfix, difficulty: trivial, scope: UI

#6168 signal_debug: check for execinfo.h header
  ConfigureChecks.cmake
  src/CMakeLists.txt
Labels: bugfix

#6146 Update preferences section in usermanual
  doc/usermanual/darkroom/concepts/colormanagement.xml
  doc/usermanual/darkroom/concepts/drawn_masks.xml
  doc/usermanual/darkroom/concepts/interacting.xml
  doc/usermanual/darkroom/concepts/parametric_masks.xml
  doc/usermanual/darkroom/modules/basic/basecurve.xml
  doc/usermanual/darkroom/modules/basic/crop_and_rotate.xml
  doc/usermanual/darkroom/modules/basic/demosaic.xml
  doc/usermanual/darkroom/modules/color/outputcolorprofile.xml
  doc/usermanual/darkroom/panels/bottom_panel.xml
  doc/usermanual/darkroom/panels/infoline.xml
  doc/usermanual/images/darkroom_preferences.png
  doc/usermanual/images/preferences_view.png
  doc/usermanual/lighttable/concepts/ratings_color.xml
  doc/usermanual/lighttable/concepts/sidecarfiles.xml
  doc/usermanual/lighttable/concepts/thumbnails.xml
  doc/usermanual/lighttable/lighttable.xml
  doc/usermanual/lighttable/panels/collect.xml
  doc/usermanual/lighttable/panels/history.xml
  doc/usermanual/lighttable/panels/selected_images.xml
  doc/usermanual/overview/overview.xml
  doc/usermanual/preferences/core_options.xml
  doc/usermanual/preferences/cpugpumemory.xml
  doc/usermanual/preferences/darkroom_options.xml
  doc/usermanual/preferences/general.xml
  doc/usermanual/preferences/gui_options.xml
  doc/usermanual/preferences/import.xml
  doc/usermanual/preferences/lighttable_options.xml
  doc/usermanual/preferences/lua.xml
  doc/usermanual/preferences/misc.xml
  doc/usermanual/preferences/otherviews.xml
  doc/usermanual/preferences/preferences.xml
  doc/usermanual/preferences/processing.xml
  doc/usermanual/preferences/security.xml
  doc/usermanual/preferences/session_options.xml
  doc/usermanual/preferences/storage.xml
  doc/usermanual/slideshow/slideshow.xml
  doc/usermanual/topics/memory.xml
  doc/usermanual/topics/opencl.xml
Labels: scope: usermanual

#6179 guided_filter: add missing include
  src/common/guided_filter.h
Labels: bugfix

#6184 Update darktable.xml
  doc/usermanual/darktable.xml
Labels: scope: usermanual

#6181 selection : fix range selection if collection has changed
  src/common/selection.c
Labels: bugfix, difficulty: trivial, scope: UI

#6185 culling : speedup for non zoomed image loading
  src/dtgtk/thumbnail.c
Labels: bugfix, scope: UI

#6188 Fixes typo in French translation
  po/fr.po
Labels: scope: translation

#6189 Load error message language improve, make translatable
  src/views/darkroom.c
Labels: bugfix, scope: translation

#6199 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6201 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6203 develop: fix scene-referred default modules.
  src/develop/develop.c
  src/iop/filmicrgb.c
Labels: bugfix

#6204 develop.c: add missing atomic.h include
  src/develop/develop.c
Labels: bugfix

#6212 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6211 correctly restore notebook page for color zones/contrast equalizer/raw denoise
  src/iop/atrous.c
  src/iop/colorzones.c
  src/iop/rawdenoise.c
Labels: bugfix

#6205 database.c: skip maintenance/optimization on :memory: dbs
  src/common/database.c
Labels: feature: enhancement

#6221 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6218 German translation updates
  po/de.po
Labels: scope: translation

#6183 [temperature.c] introspection, refactoring, janitorial
  src/iop/temperature.c
Labels: bugfix, feature: enhancement

#6217 exif: fix reading iop-order.
  src/common/exif.cc
Labels: bugfix, priority: high, reproduce: confirmed, scope: codebase

#6213 remove map center action on filmstrip click
  src/dtgtk/thumbtable.c
  src/views/map.c
Labels: bugfix

#6215 po/collect combo
  data/themes/darktable.css
  src/bauhaus/bauhaus.c
  src/bauhaus/bauhaus.h
  src/develop/blend_gui.c
  src/iop/temperature.c
  src/libs/collect.c
Labels: feature: enhancement

#6225 filmicrgb: remove line breaks in comments
  src/iop/filmicrgb.c
Labels: bugfix, scope: codebase, scope: translation

#6220 [db_maintenance] be resilient about unfinished statements
  src/common/darktable.c
  src/common/database.c
  src/common/database.h
Labels: bugfix, scope: DAM

#6228 darktable.css: increase dimensions of control button icon
  data/themes/darktable.css
Labels: bugfix

#6238 colorin: properly reset all default parameters.
  src/iop/colorin.c
Labels: bugfix, priority: high

#6236 demosaic: properly reset all default values.
  src/iop/demosaic.c
Labels: bugfix, priority: high

#6237 po/fix style edit
  src/common/styles.c
  src/gui/styles_dialog.c
Labels: bugfix

#6230 Support for reading 16-bit (half) float TIFFs
  src/common/imageio_tiff.c
Labels: feature: enhancement

#6231 po/lr import
  src/common/exif.cc
  src/develop/lightroom.c
Labels: bugfix, feature: enhancement

#6241 make sure lightroom metadata (label) are saved in dt xmp
  src/common/image.c
Labels: bugfix

#6232 don't register lightroom and exifEX to exiv2 at init time
  src/common/exif.cc
Labels: bugfix

#6245 German translation updates
  po/de.po
Labels: scope: translation

#6251 Init exiv2 - Catch exceptions instead of checking returned pointer.
  src/common/exif.cc
Labels: bugfix, duplicate

#6260 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6261 fix collection sort type
  src/libs/tools/filter.c
Labels: bugfix

#6256 fix compiler warning in ellipsize button code
  src/lua/widget/button.c
Labels: bugfix

#6254 darkroom: allow better translations
  src/views/darkroom.c
Labels: bugfix, scope: translation

#6264 [darkroom] remove memleak in styles menu generation
  src/views/darkroom.c
Labels: bugfix

#6263 [metadata_view]: correctly handlne invalid utf in strftime
  src/libs/metadata_view.c
Labels: bugfix, priority: high

#6253 over-exposure warning : add meaningfull modes
  data/darktableconfig.xml.in
  data/kernels/basic.cl
  src/develop/develop.c
  src/develop/develop.h
  src/iop/overexposed.c
  src/views/darkroom.c
Labels: feature: enhancement, scope: image processing

#6233 Update user manual for 3.2 release: crop and rotate module
  doc/usermanual/darkroom/modules/basic/crop_and_rotate.xml
Labels: scope: usermanual

#6267 fix string incorrectly marked for translation in rawprepare
  src/iop/rawprepare.c
Labels: bugfix

#6268 fix potential null pointer dereference
  src/cli/main.c
Labels: bugfix

#6266 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6274 [Issue #6270] WB Presets Nikon D3400 finetuning
  src/external/wb_presets.c
Labels: feature: enhancement, scope: camera support

#6271 Trying to fix #6246
  src/iop/demosaic.c
Labels: bugfix

#6269 implement clickable label in colorbalance
  data/darktableconfig.xml.in
  src/bauhaus/bauhaus.c
  src/iop/colorbalance.c
Labels: feature: enhancement

#6276 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6277 Updates to pr_BR
  po/pt_BR.po
Labels: scope: translation

#6284 [Issue #6283] WB Presets Sony ILCE-7RM4 with finetuning
  src/external/wb_presets.c
Labels: feature: enhancement, scope: camera support

#6281 change colorbalance layout names and fix settings update
  data/darktableconfig.xml.in
  src/iop/colorbalance.c
Labels: bugfix, feature: enhancement

#6286 [Issue #6283] WB Presets Sony ILCE-7RM4 with finetuning (no lens)
  src/external/wb_presets.c
Labels: bugfix, scope: camera support

#6289 Bug fix for grid+ histogram scaling with log scale in tonecurve, basecurve
  src/iop/basecurve.c
  src/iop/tonecurve.c
Labels: bugfix

#6300 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6299 fix 2 thumbtable issues
  src/dtgtk/thumbtable.c
Labels: bugfix, difficulty: trivial, scope: UI

#6301 set soft min for print exposure slider in negadoctor
  src/iop/negadoctor.c
Labels: bugfix

#6305 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6304 [Issue #6287] Fix scene-referred workflow for Digikam XMP
  src/common/exif.cc
Labels: bugfix

#4687 Update channelmixer to preserve highlights
  data/kernels/extended.cl
  src/iop/channelmixer.c
Labels: feature: enhancement, no-pr-activity, scope: image processing

#6297 po/usermanual
  doc/usermanual/darkroom/modules/color/colorbalance.xml
  doc/usermanual/darkroom/modules/correction/equalizer.xml
  doc/usermanual/darkroom/modules/images/atrous-1.png
  doc/usermanual/darkroom/modules/images/atrous-2.png
  doc/usermanual/darkroom/modules/images/atrous-4.png
  doc/usermanual/darkroom/modules/images/atrous-5.png
  doc/usermanual/darkroom/modules/images/atrous.png
  doc/usermanual/darkroom/modules/images/zonesystem.png
  doc/usermanual/preferences/darkroom_options.xml
Labels: scope: usermanual

#6308 Spanish translation update
  po/es.po
Labels: scope: translation

#6309 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6291 Fix the PPC64LE build.
  src/common/guided_filter.h
Labels: bugfix

#6314 Update import_from_camera section in basic workflow.
  doc/usermanual/overview/overview.xml
Labels: scope: usermanual

#6316 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6326 make sure xmp metadata are imported when write_sidecar_files is checked
  src/common/metadata.c
  src/gui/import_metadata.c
Labels: bugfix, priority: high

#6324 Improve thumbnails contrast in all themes
  data/themes/darktable-elegant-dark.css
  data/themes/darktable-elegant-grey.css
  data/themes/darktable.css
Labels: feature: enhancement, scope: UI

#6224 hide iop header buttons until mouse over
  data/darktableconfig.xml.in
  src/develop/imageop.c
  src/develop/imageop.h
  src/views/darkroom.c
Labels: feature: enhancement, scope: UI

#6327 po/import layout
  src/libs/import.c
Labels: feature: enhancement

#6338 fixed offset/power/slope headers in color balance
  src/iop/colorbalance.c
Labels: bugfix

#6332 dynamic header buttons optimisation and manual description
  doc/usermanual/preferences/darkroom_options.xml
  src/develop/imageop.c
Labels: feature: enhancement, scope: usermanual

#6345 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6346 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6349 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6340 Clamp mask values to [0,1]. Fix #6315
  data/kernels/blendop.cl
  src/develop/blend.c
Labels: bugfix, priority: high

#6350 Overhaul color picker module
  data/themes/darktable.css
  src/libs/colorpicker.c
  src/libs/colorpicker.h
Labels: feature: enhancement, scope: UI

#6353 German translation updates
  po/de.po
Labels: scope: translation

#6303 map - images grouping to speed up display
  data/darktableconfig.xml.in
  src/common/undo.h
  src/dtgtk/thumbtable.c
  src/gui/gtk.c
  src/gui/gtk.h
  src/libs/map_settings.c
  src/views/map.c
  src/views/view.h
Labels: feature: enhancement, wip

#6356 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6355 add lch presentation option to color picker module
  src/libs/colorpicker.c
Labels: feature: enhancement

#6365 German translation updates
  po/de.po
Labels: scope: translation

#6367 colorpicker: display live sample location even if display sample off.
  src/libs/colorpicker.c
  src/views/darkroom.c
Labels: feature: enhancement

#6368 make whole color picker sample row show location
  src/libs/colorpicker.c
Labels: feature: enhancement

#6369 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6371 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6375 resize notebook tabs using natural width of ellipsized labels
  src/gui/gtk.c
Labels: feature: enhancement, scope: UI

#6379 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6364 [masks] adjust overzealous clamping and allow for totally huge masks
  src/control/conf.c
  src/control/conf.h
  src/develop/masks/circle.c
  src/develop/masks/ellipse.c
  src/develop/masks/masks.c
Labels: bugfix, feature: enhancement, scope: image processing

#6383 [signal] allow to ignore print-trace if not available
  src/common/darktable.c
Labels: feature: enhancement

#6385 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6386 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6348 create database backups (snapshots), check database for corruption on start, restore working snapshot...
  data/darktableconfig.xml.in
  src/common/darktable.c
  src/common/database.c
  src/common/database.h
Labels: difficulty: average, feature: enhancement

#6387 [colormapping] only clear src/target on clusters change
  src/iop/colormapping.c
Labels: bugfix

#6389 [masks] make module window height adjustable, same as other modules
  data/darktableconfig.xml.in
  src/libs/masks.c
Labels: feature: enhancement

#6382 Fix bad thumbnails on hires displays
  data/darktableconfig.xml.in
  src/common/mipmap_cache.c
  src/dtgtk/thumbnail.c
  src/views/view.c
Labels: bugfix, difficulty: hard, priority: high, scope: UI

#6393 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6394 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6390 Improve appearance of combobox menu
  data/themes/darktable.css
Labels: feature: enhancement

#6402 Fix typo in Negadoctor documentation
  doc/usermanual/darkroom/modules/basic/negadoctor.xml
Labels: scope: usermanual

#6396 gphoto device updating in a thread instead of a misused job
  src/common/camera_control.c
  src/common/camera_control.h
  src/common/darktable.c
  src/control/control.c
  src/control/control.h
  src/control/jobs.c
  src/control/jobs.h
Labels: feature: enhancement

#6405 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6404 [prefs] remove tiny memleak from generate_prefs
  tools/generate_prefs.xsl
Labels: bugfix

#6403 [conf] get default conf val in case normal/overriden is garbage
  src/control/conf.c
Labels: feature: enhancement

#6413 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual
