Repository darktable-org/darktable, pull requests merged in 2020-10, with the labels that each got.

#6414 change 'show search module text entry' and add tooltip.
  data/darktableconfig.xml.in
Labels: feature: enhancement

#6421 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6422 updating italian translations
  po/it.po
Labels: scope: translation

#5516 don't run iops which don't contribute to mask display
  src/develop/pixelpipe_hb.c
Labels: feature: enhancement, no-pr-activity, scope: performance

#6424 fix error when hovering over blending slider while in Entry
  src/develop/blend_gui.c
Labels: bugfix

#6419 add noise profiles for issues #5876 and #6138
  data/noiseprofiles.json
Labels: scope: noise profile

#6426 [conf] don't truncate strings
  src/control/conf.c
Labels: bugfix

#6427 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6429 [prefs] highlight changed preferences
  data/themes/darktable.css
  src/control/conf.c
  src/control/conf.h
  tools/generate_prefs.xsl
Labels: feature: enhancement

#6428 po/conf validate enum
  src/control/conf.c
  src/control/conf.h
  tools/generate_darktablerc_conf.xsl
Labels: feature: enhancement, scope: codebase

#6398 [presets] add option to hide built-in presets of iops
  data/darktableconfig.xml.in
  data/themes/darktable.css
  src/gui/presets.c
Labels: feature: enhancement

#6425 Simplified approach for `screen_ppd_overwrite` and `ui/cairo_filter`
  data/darktableconfig.xml.in
  src/common/darktable.c
  src/develop/develop.h
  src/dtgtk/thumbnail.c
  src/gui/gtk.c
  src/gui/gtk.h
  src/gui/preferences.c
  src/views/darkroom.c
  src/views/view.c
Labels: difficulty: average, feature: redesign

#6434 cleanup minimal cairo version
  src/gui/gtk.h
  src/libs/live_view.c
Labels: feature: enhancement, scope: codebase

#6432 [temperature] make channel coeff sliders a bit more fine-graded
  src/iop/temperature.c
Labels: feature: enhancement

#6438 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6437 Improve display of combobox windows
  data/themes/darktable.css
Labels: scope: UI

#6446 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6445 [conf] hardening of dt_conf_get_* for no fun and no profit
  src/control/conf.c
  src/control/conf.h
Labels: feature: enhancement

#6439 Use same font as website for the logo
  data/pixmaps/dt_text.svg
  src/common/utility.c
  src/common/utility.h
  src/libs/tools/darktable.c
Labels: scope: UI

#6453 clipping: adjust keystone control area size depending on the downsamp…
  src/iop/clipping.c
Labels: bugfix, feature: enhancement, scope: UI

#6454 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6461 iop_layouts : fix dialog creation as child of main window
  data/themes/darktable.css
  src/gui/presets.c
  src/libs/modulegroups.c
Labels: bugfix, difficulty: trivial, scope: UI

#6408 make height of remaining libs modules configurable/refactor
  data/darktableconfig.xml.in
  data/themes/darktable.css
  src/gui/gtk.c
  src/gui/gtk.h
  src/libs/colorpicker.c
  src/libs/duplicate.c
  src/libs/history.c
  src/libs/masks.c
  src/libs/metadata_view.c
  src/libs/recentcollect.c
  src/libs/snapshots.c
  src/libs/styles.c
Labels: feature: enhancement

#5522 retouch speedup: bypass further iops when displaying wavelet scale
  src/develop/develop.h
  src/iop/retouch.c
Labels: bugfix, no-pr-activity, scope: performance

#6466 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6465 print export
  data/darktableconfig.xml.in
  src/libs/export.c
Labels: feature: enhancement, scope: UI

#6447 Improving monochrome images workflow
  data/darktableconfig.xml.in
  src/common/exif.cc
  src/common/image.c
  src/common/image.h
  src/common/imageio.c
  src/common/imageio.h
  src/dtgtk/thumbnail.c
  src/iop/cacorrect.c
  src/iop/demosaic.c
  src/iop/lens.cc
  src/libs/metadata_view.c
Labels: feature: enhancement

#6471 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6311 [l10n] try to set lang to match selected by user, based on parafin's 428b3f3
  src/common/l10n.c
  src/osx/osx.h
  src/osx/osx.mm
Labels: bugfix

#6472 colorbalance: add slider shortcuts
  src/iop/colorbalance.c
Labels: feature: enhancement

#6456 slightly improve squeezed fonts in colorpicker and blender
  data/themes/darktable.css
  src/develop/blend_gui.c
  src/libs/colorpicker.c
Labels: feature: enhancement

#6477 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6451 [imageio_tiff] faster half to float conversion
  src/common/imageio_tiff.c
Labels: difficulty: average, feature: enhancement, scope: performance

#6075 perform sanity check on module params before commit
  data/darktable.bash
  doc/man/darktable.pod
  doc/man/po/de.po
  doc/man/po/es.po
  doc/man/po/fr.po
  doc/usermanual/overview/overview.xml
  src/common/darktable.c
  src/common/darktable.h
  src/develop/imageop.c
  src/iop/retouch.c
Labels: feature: enhancement, no-pr-activity, scope: codebase

#6158 Bilateral fix
  src/iop/bilateral.cc
Labels: bug: wip, bugfix, no-pr-activity

#6474 Try to fix sdcard imports
  src/common/camera_control.c
Labels: feature: enhancement

#6480 map : don't move map view on undo/redo
  src/views/map.c
Labels: feature: enhancement

#6483 Update TRANSLATORS.md typos
  doc/TRANSLATORS.md
Labels: scope: translation, scope: usermanual

#5938 Remove unused code in buttons
  src/dtgtk/button.c
  src/dtgtk/togglebutton.c
Labels: no-pr-activity

#5709 Simplify tiff compress GUI, default level to 6
  data/darktableconfig.xml.in
  src/imageio/format/tiff.c
Labels: feature: redesign, no-pr-activity

#6491 Fixing size for g_file_get_contents
  src/common/camera_control.c
Labels: bugfix

#6498 manage module layouts: fix grammar
  src/gui/presets.c
  src/libs/modulegroups.c
Labels: bugfix

#6496 Monochrome workflow supporting presets
  src/develop/develop.c
  src/gui/preferences.c
  src/gui/presets.c
  src/gui/presets.h
Labels: feature: enhancement

#6501 Update preferences manual for performance mode and monochrome previews
  doc/usermanual/images/preferences_view.png
  doc/usermanual/preferences/general.xml
  doc/usermanual/preferences/processing.xml
Labels: scope: usermanual

#6505 user-manual: Add description of monochrome and color boxes in presets
  doc/usermanual/darkroom/concepts/presets.xml
Labels: scope: usermanual

#6478 map : highlights groups containing selected images
  src/views/map.c
Labels: feature: enhancement

#6499 Update colormanagement.xml
  doc/usermanual/darkroom/concepts/colormanagement.xml
Labels: scope: usermanual

#6509 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6510 no functional change. Makes CMake more consistent
  src/libs/CMakeLists.txt
Labels: scope: codebase

#6512 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6489 po/module groups
  src/libs/modulegroups.c
Labels: feature: enhancement

#6518 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6521 Fix popover padding
  data/themes/darktable.css
Labels: bugfix

#6520 po/safe history copy
  src/common/history.c
  src/develop/imageop.h
  src/iop/flip.c
  src/iop/gamma.c
  src/iop/lens.cc
  src/iop/mask_manager.c
  src/iop/rawprepare.c
  src/iop/rotatepixels.c
  src/iop/scalepixels.c
  src/iop/temperature.c
Labels: bugfix, feature: enhancement

#6516 Monochrome workflow 3: user can change monochrome image status
  src/common/exif.cc
  src/common/image.c
  src/control/jobs/control_jobs.c
  src/control/jobs/control_jobs.h
  src/dtgtk/thumbnail.c
  src/dtgtk/thumbnail.h
  src/libs/image.c
  src/views/view.c
  src/views/view.h
Labels: feature: enhancement

#6525 change color contrast labels so that there's less confusion
  src/iop/colorcontrast.c
Labels: feature: enhancement

#6536 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6533 [Issue #2451] Styles dialog updates
  src/gui/presets.c
  src/gui/styles_dialog.c
  src/libs/styles.c
Labels: bugfix, feature: enhancement

#6537 Fixing progress bars in control_jobs
  src/control/jobs/control_jobs.c
Labels: bugfix

#6538 Adjusting case for true -> TRUE, false -> FALSE
  src/control/jobs/control_jobs.c
  src/libs/image.c
Labels: bugfix

#6540 fixes calling a bash script on MSYS (Windows)
  CMakeLists.txt
  cmake/modules/FindSaxon.cmake
  doc/usermanual/CMakeLists.txt
  doc/usermanual/README
  packaging/windows/BUILD.txt
  src/libs/CMakeLists.txt
  tools/authors_h.sh
Labels: bugfix, scope: OS support

#6544 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6542 po/monochrome undo
  src/common/image.c
  src/common/image.h
  src/common/undo.h
  src/control/jobs/control_jobs.c
Labels: feature: enhancement

#6535 iop_layouts : fix module order in presets manager
  src/libs/modulegroups.c
Labels: bugfix, difficulty: trivial, scope: UI

#6560 iop_layouts : fix the list when we show all modules
  src/libs/modulegroups.c
Labels: bugfix, difficulty: trivial, scope: UI

#6556 Include stdint.h in grouping.h
  src/common/grouping.h
Labels: bugfix, scope: OS support

#6570 fixes 6552, DATADIR==SHAREDIR
  CMakeLists.txt
  src/config.cmake.h
Labels: bugfix

#6575 Revert "clang: Add workaround for upstream MinGW issue #6400"
  .ci/ci-script-windows.sh
Labels: scope: OS support

#6577 German translation updates
  po/de.po
Labels: scope: translation

#6584 do not treat enabling dynamic shortcuts as special
  src/control/control.c
  src/control/control.h
  src/develop/imageop.c
  src/gui/accelerators.c
  src/gui/accelerators.h
  src/gui/gtk.c
  src/views/darkroom.c
  src/views/view.h
Labels: bugfix, feature: enhancement

#6587 po/copy dialog
  src/gui/hist_dialog.c
  src/libs/copy_history.c
Labels: bugfix, feature: enhancement

#6589 thumbtable : don't change active image if not visible
  src/dtgtk/thumbtable.c
Labels: bugfix, difficulty: average, scope: UI

#6558 Travis Revamp - various builds & OSX support in travis
  .ci/Brewfile
  .ci/ci-script.sh
  .travis.yml
  CMakeLists.txt
Labels: feature: redesign

#6592 Quick presets fix + docs
  doc/usermanual/darkroom/panels/bottom_panel.xml
  src/gui/presets.c
Labels: bugfix, difficulty: trivial, scope: UI, scope: usermanual

#6595 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6591 rename shortcuts categories for modules in settings
  src/gui/accelerators.c
Labels: feature: enhancement

#6594 common:imageio: Add support for libavif >= 0.8.2
  src/CMakeLists.txt
  src/common/imageio_avif.c
Labels: feature: enhancement

#6598 fix preset popup accel
  src/develop/imageop.c
  src/libs/lib.c
Labels: bugfix

#6599 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6602 keyaccelerators: amend manual for renamed module sections
  doc/usermanual/preferences/keyaccelerators.xml
Labels: scope: usermanual

#6601 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6607 Fix preferences margin
  data/themes/darktable.css
Labels: bugfix, scope: UI

#5544 attempt at making tone EQ more robust and responsive
  src/iop/toneequal.c
Labels: bugfix, feature: enhancement, no-pr-activity, scope: performance

#6611 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6604 imageio: Add grayscale support to AVIF export
  src/imageio/format/avif.c
Labels: feature: enhancement

#6624 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6615 preferences: make the changed preferences with a little tick character.
  data/themes/darktable.css
  tools/generate_prefs.xsl
Labels: feature: enhancement

#6079 export: scaling improvement
  src/common/imageio.c
  src/common/imageio_module.c
  src/common/imageio_module.h
  src/libs/export.c
Labels: difficulty: trivial, feature: enhancement, priority: low

#6632 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6633 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6616 po/fix liquify handles
  src/iop/liquify.c
Labels: bugfix

#6630 thumbnail: use canonical ext for JPEG/RGBE/TIFF
  src/views/view.c
Labels: feature: enhancement

#6642 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6646 German translation updates
  po/de.po
Labels: scope: translation

#6653 generate-prefs: fix spacing of miscellaneous tab
  tools/generate_prefs.xsl
Labels: bugfix

#6640 thumbnail: record expose_again source ID and cancel timeout on destroy
  src/dtgtk/thumbnail.c
  src/dtgtk/thumbnail.h
Labels: bugfix

#6667 German translation updates
  po/de.po
Labels: scope: translation

#6671 Lua API Manual Update
  doc/usermanual/lua/lua_api.xml
Labels: lua, scope: usermanual

#5155 expand single darkroom module: make parameter work across groups
  data/darktableconfig.xml.in
  src/develop/imageop.c
Labels: feature: enhancement, feature: redesign, no-pr-activity

#6664 po/performance mode
  src/gui/preferences.c
  src/views/darkroom.c
Labels: bugfix, feature: enhancement

#6677 usermanual: collapse modules documentation
  doc/usermanual/preferences/darkroom_options.xml
Labels: scope: usermanual

#6680 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6685 zero out node past end of curve on delete
  src/iop/basecurve.c
  src/iop/colorzones.c
  src/iop/rgbcurve.c
  src/iop/tonecurve.c
Labels: bugfix

#6690 accelerators: always show toast message when adjusting controls
  src/gui/accelerators.c
Labels: feature: enhancement

#6694 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6693 add draw multiple shapes to liquify
  src/iop/liquify.c
Labels: bugfix, feature: enhancement, scope: UI

#6692 denoiseprofile: add preset wavelets chroma only
  src/iop/denoiseprofile.c
Labels: feature: enhancement, scope: noise profile
