Repository darktable-org/darktable, pull requests merged in 2020-06, with the labels that each got.

#5279 altered fix - when rotation on an image without history don't take it for auto-apply.
  src/develop/develop.c
Labels: bugfix

#5249 applies preview_downsampling correcting to crop in ashift.c
  src/iop/ashift.c
Labels: bugfix, difficulty: hard

#4920 keyboard shortcuts: minor reorg
  src/gui/accelerators.c
  src/gui/accelerators.h
  src/libs/histogram.c
  src/libs/navigation.c
  src/libs/tools/global_toolbox.c
  src/libs/tools/lighttable.c
  src/views/lighttable.c
Labels: feature: enhancement

#5281 accelerators: fix missing translated path
  src/gui/accelerators.c
Labels: bugfix

#5283 don't use a special layout for color assessment mode -
  src/views/darkroom.c
Labels: feature: redesign, scope: UI

#5268 polish thumbnails margins
  data/themes/darktable.css
  src/dtgtk/thumbnail.c
Labels: feature: enhancement

#5290 thumbs : update altered tooltip when mipmap change
  src/dtgtk/thumbnail.c
Labels: bugfix, difficulty: trivial, scope: UI

#5289 po/orientation undo
  src/common/history_snapshot.c
  src/common/image.c
  src/common/undo.c
  src/control/jobs/control_jobs.c
Labels: bugfix

#5292 Spanish translation update
  po/es.po
Labels: scope: translation

#5282 Gradient sliders, further improvement
  data/themes/darktable.css
  src/dtgtk/gradientslider.c
  src/dtgtk/gradientslider.h
Labels: feature: enhancement, scope: UI

#5302 Spanish translation update
  po/es.po
Labels: scope: translation

#5179 culling overlays
  data/darktableconfig.xml.in
  src/dtgtk/culling.c
  src/dtgtk/culling.h
  src/dtgtk/thumbnail.c
  src/dtgtk/thumbnail.h
  src/dtgtk/thumbtable.c
  src/dtgtk/thumbtable.h
  src/libs/tools/global_toolbox.c
  src/views/lighttable.c
  src/views/view.c
  src/views/view.h
Labels: difficulty: average, feature: enhancement, scope: UI

#5296 bauhaus sliders: Thinner baseline and triangle
  src/bauhaus/bauhaus.c
Labels: feature: redesign, scope: UI

#5246 fix duplicate module not being enabled on duplication
  src/develop/imageop.c
Labels: bugfix

#5247 fix copy/paste history dialog cancel issue on call-by-accel
  src/dtgtk/thumbtable.c
Labels: bugfix, feature: redesign

#5297 preferences: ensure that spin button values are saved
  tools/generate_prefs.xsl
Labels: bugfix

#5276 adjustable histogram height
  data/darktableconfig.xml.in
  src/develop/develop.c
  src/libs/histogram.c
Labels: feature: enhancement

#5310 histogram: minor code clean-up
  src/develop/develop.c
  src/libs/histogram.c
Labels: bugfix, difficulty: trivial, feature: redesign, scope: codebase

#5311 nicer list in map find-location
  src/libs/location.c
Labels: difficulty: trivial, feature: enhancement, scope: UI

#5313 Spanish translation update
  po/es.po
Labels: scope: translation

#5312 Optical balance: blending tabs icons
  src/dtgtk/paint.c
Labels: feature: redesign, scope: UI

#5270 purge_from_cache.sh: make sure alias is expanded
  tools/purge_from_cache.sh
Labels: scope: codebase

#5315 refactor shutter speed formatting code
  src/common/image.c
  src/common/utility.c
  src/common/utility.h
  src/common/variables.c
  src/libs/metadata_view.c
Labels: bugfix, difficulty: trivial, feature: redesign, priority: low, scope: codebase

#4881 give kbd focus to centre image when clicking module header
  src/develop/imageop.c
Labels: bugfix

#5319 Fixes float clipping limits that exceeded 1, avoids lost pixels with preview_downsampling<1.
  src/iop/clipping.c
Labels: bugfix

#5316 bauhaus controls: pass keypress event to view if not handled
  src/bauhaus/bauhaus.c
  src/views/darkroom.c
Labels: bugfix, scope: UI

#5320 filmstrip : ensure that image stay inside thumbnail
  src/dtgtk/thumbnail.c
Labels: bugfix, difficulty: trivial, scope: UI

#5257 make sure copy_history module buttons get updated
  src/common/history.c
  src/libs/copy_history.c
Labels: feature: enhancement

#5323 Dynamicly updating buttons on selected images module
  src/libs/image.c
Labels: difficulty: average, feature: redesign, scope: UI

#5325 watermark: enable font substitution when watermark text is empty
  src/iop/watermark.c
Labels: feature: redesign, scope: codebase

#5329 allow film rolls to be optionally ordered by folder name
  data/darktableconfig.xml.in
  src/libs/collect.c
Labels: feature: enhancement

#5331 dynamic enable/disable of export button
  src/libs/export.c
Labels: feature: enhancement, scope: UI

#5330 thumbnails : align icons on css margins
  src/dtgtk/thumbnail.c
Labels: difficulty: trivial, feature: enhancement, scope: UI

#2971 Fix the curve tool fit_curve initialization. (#2480)
  tools/basecurve/darktable-curve-tool.c
Labels: bugfix, no-pr-activity, scope: image processing

#5314 simplify painting API
  src/dtgtk/paint.c
Labels: feature: enhancement, scope: UI

#5342 Spanish translation update
  po/es.po
Labels: scope: translation

#5327 make select module buttons react to selection status
  src/common/selection.c
  src/libs/select.c
Labels: feature: enhancement, scope: UI

#5332 Make gradient sliders full themable custom widget
  data/themes/darktable.css
  src/develop/blend_gui.c
  src/dtgtk/gradientslider.c
  src/dtgtk/gradientslider.h
  src/iop/relight.c
Labels: feature: redesign, scope: UI

#5345 Continue a slider drag even if it ends up in quad area
  src/bauhaus/bauhaus.c
Labels: bugfix

#5333 Fix import thumbnails via gphoto
  src/common/camera_control.c
  src/common/camera_control.h
  src/gui/camera_import_dialog.c
Labels: bugfix, priority: high, scope: UI

#5340 thumb : allow to set tooltip visibility per size/mode
  data/darktableconfig.xml.in
  src/dtgtk/culling.c
  src/dtgtk/culling.h
  src/dtgtk/thumbnail.c
  src/dtgtk/thumbnail.h
  src/dtgtk/thumbtable.c
  src/dtgtk/thumbtable.h
  src/libs/duplicate.c
  src/libs/tools/global_toolbox.c
Labels: difficulty: average, feature: enhancement, scope: UI

#4424 keyboard shortcuts to better handle multiple instances
  data/darktableconfig.dtd
  data/darktableconfig.xml.in
  src/bauhaus/bauhaus.c
  src/control/control.c
  src/develop/blend_gui.c
  src/develop/develop.c
  src/develop/imageop.c
  src/develop/imageop.h
  src/gui/presets.c
  src/iop/exposure.c
  src/libs/history.c
  src/libs/modulelist.c
  src/views/darkroom.c
  tools/generate_prefs.xsl
Labels: bugfix, difficulty: average, feature: enhancement, scope: codebase

#4800 filmic RGB v4 update : new color science
  src/common/image.c
  src/common/image.h
  src/iop/filmicrgb.c
  src/tests/unittests/iop/test_filmicrgb.c
Labels: difficulty: hard, feature: enhancement, priority: medium, scope: image processing

#5324 init exposure with EXIF exposure bias
  data/darktableconfig.xml.in
  src/iop/basecurve.c
  src/iop/exposure.c
Labels: feature: enhancement

#5353 updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#5350 ellipsize buttons in snapshot and history stack modules
  src/libs/history.c
  src/libs/snapshots.c
Labels: feature: enhancement, scope: UI

#5349 exposure: ellipsize exposure compensation parameter
  src/iop/exposure.c
Labels: feature: enhancement, scope: UI

#5352 ellipsize created shapes label in mask manager
  src/libs/masks.c
Labels: feature: enhancement, scope: UI

#5356 filmicrgb: minor changes for narrower side panel
  data/themes/darktable.css
  src/iop/filmicrgb.c
Labels: feature: enhancement, scope: UI

#3251 Revise the altivec wrapper to make the #undefs unneeded.
  src/ppc64le/altivec.h
Labels: no-pr-activity, scope: hardware support

#5362 po/fix masks
  src/libs/lib.c
  src/libs/lib.h
  src/libs/masks.c
  src/views/darkroom.c
Labels: bugfix

#5346 activating module via shortcut adds to active group
  src/develop/develop.c
  src/develop/develop.h
  src/develop/imageop.c
  src/libs/modulegroups.c
Labels: bugfix

#5347 variables : add $(LABELS_ICONS) to use colorlabels in patterns
  src/common/variables.c
Labels: difficulty: average, feature: enhancement, scope: UI

#5354 overlays margins
  data/themes/darktable.css
  src/dtgtk/thumbnail.c
Labels: difficulty: average, feature: enhancement, scope: UI

#5373 Spanish translation update
  po/es.po
Labels: scope: translation

#5370 altered fix - in mipmap consider auto apply as altered
  src/common/history.c
  src/common/history.h
  src/common/image.c
  src/common/image.h
  src/common/mipmap_cache.c
  src/views/darkroom.c
Labels: bugfix, scope: DAM

#5375 German translation updates
  po/de.po
Labels: scope: UI

#5367 dynamic tagging module buttons
  src/libs/tagging.c
Labels: feature: enhancement, scope: UI

#5338 Lua scripts installer
  RELEASE_NOTES.md
  data/luarc
Labels: feature: new, lua, scope: codebase

#5376 histogram: reverse resize scroll direction
  src/libs/histogram.c
Labels: bugfix

#5355 handle multiple styles in styles module (action-wise) and dynamically update buttons
  src/common/styles.c
  src/common/styles.h
  src/libs/styles.c
Labels: feature: enhancement, scope: codebase

#5399 Spanish translation update
  po/es.po
Labels: scope: translation

#5400 enable hover effect for directory icon
  src/dtgtk/paint.c
Labels: scope: UI

#5397 Olympus TG-6 noise profiles
  data/noiseprofiles.json
Labels: scope: noise profile

#5384 New css fixes
  data/themes/darktable-elegant-dark.css
  data/themes/darktable-elegant-darker.css
  data/themes/darktable-elegant-grey.css
  data/themes/darktable.css
  src/libs/colorpicker.c
  src/libs/duplicate.c
  src/libs/tools/colorlabels.c
  src/libs/tools/global_toolbox.c
Labels: scope: UI

#5368 bauhaus: ellipsize slider names and give combobox extra space
  src/bauhaus/bauhaus.c
Labels: feature: enhancement, scope: UI

#5395 Retouch module: use gradient slider
  src/develop/blend_gui.c
  src/dtgtk/gradientslider.c
  src/dtgtk/gradientslider.h
  src/iop/relight.c
  src/iop/retouch.c
Labels: feature: redesign, scope: codebase

#5402 paint: makes directory icon a bit smaller.
  src/dtgtk/paint.c
Labels: scope: UI

#5405 cached images_to_act_on list
  src/common/image.c
  src/common/metadata.c
  src/common/selection.c
  src/common/styles.c
  src/common/tags.c
  src/control/jobs/control_jobs.c
  src/dtgtk/thumbtable.c
  src/libs/copy_history.c
  src/libs/export.c
  src/libs/image.c
  src/libs/metadata.c
  src/libs/styles.c
  src/libs/tagging.c
  src/libs/tools/colorlabels.c
  src/libs/tools/ratings.c
  src/lua/gui.c
  src/views/map.c
  src/views/view.c
  src/views/view.h
Labels: difficulty: average, feature: enhancement, scope: performance

#5369 Allows more precise aspect ratios in crop & rotate
  src/iop/clipping.c
Labels: bugfix

#5408 improve french translation on filmic
  po/fr.po
Labels: scope: translation

#5409 don't enter darkroom in full preview if user keep key pressed
  src/views/darkroom.c
Labels: bugfix, difficulty: trivial, scope: UI

#5415 reword tooltip for display-referred workflow preference
  data/darktableconfig.xml.in
Labels: feature: enhancement

#5420 Spanish translation update
  po/es.po
Labels: scope: translation

#5410 Fixes offset image border in clipping.c
  src/iop/clipping.c
Labels: bugfix, difficulty: hard, scope: UI, scope: codebase

#5419 Lua API fix: darktable.gui.libs[<module>].visible = true|false
  src/lua/lib.c
Labels: bugfix, lua

#5222 Bilateral filter data-race fix and speedup
  src/common/bilateral.c
  src/tests/integration/0018-shadhi-bilateral/shadhi-bilateral.xmp
  src/tests/integration/0019-lowpass-bilateral/lowpass-bilateral.xmp
  src/tests/integration/0020-monochrome/monochrome.xmp
  src/tests/integration/0021-perspective-corr/perspective-corr.xmp
  src/tests/integration/0022-color-mapping/color-mapping.xmp
Labels: bugfix, scope: performance

#5422 don't treat 'Tab' as an escape character in geotagging
  src/libs/geotagging.c
Labels: bugfix

#5413 try to cleanup import_session created dirs
  src/common/import_session.c
Labels: feature: enhancement, scope: codebase

#5388 filmicv4 : add a slight amount of gaussian noise in highlights
  src/develop/imageop_math.h
  src/iop/filmicrgb.c
Labels: feature: enhancement, scope: image processing

#5414 better initialisation of history stack
  src/develop/develop.c
  src/iop/exposure.c
  src/iop/filmicrgb.c
Labels: bugfix, feature: enhancement, priority: medium, scope: codebase

#5432 Fix histogram button tool tips
  src/libs/histogram.c
Labels: bugfix

#5417 Scripts installer not always maximized
  data/luarc
Labels: bugfix, lua

#5437 Enhancements to pt_BR translation of manual
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#5439 fix darktable-cli hang regression
  data/luarc
Labels: bugfix, lua

#5421 change schedule(dynamic) to schedule(static) in parallelized for loops
  src/iop/cacorrect.c
  src/iop/demosaic.c
  src/iop/highlights.c
  src/iop/liquify.c
Labels: feature: enhancement, scope: performance

#5427 lighttable : remove thumbtable at the end of leaving
  src/views/lighttable.c
Labels: bugfix, difficulty: trivial, scope: UI

#5444 Spanish translation update
  po/es.po
Labels: scope: translation

#5412 avoid to call DT_SIGNAL_TAG_CHANGED in loop
  src/common/exif.cc
  src/common/history.c
  src/common/history_snapshot.c
  src/common/image.c
  src/common/styles.c
  src/common/tags.c
  src/common/tags.h
  src/control/jobs/control_jobs.c
  src/develop/develop.c
  src/develop/lightroom.c
  src/dtgtk/thumbtable.c
  src/libs/duplicate.c
  src/libs/print_settings.c
  src/libs/tagging.c
  src/lua/image.c
  src/lua/styles.c
  src/lua/tags.c
  src/views/darkroom.c
Labels: bugfix, difficulty: average, scope: performance

#5440 make user css work on windows
  src/gui/gtk.c
Labels: bugfix

#5465 workflow preference: add a new line
  data/darktableconfig.xml.in
Labels: feature: enhancement

#5470 thumbs : ensure overlays sizes after change
  src/dtgtk/thumbnail.c
Labels: bugfix, difficulty: trivial, scope: UI

#5456 lua scripts installer usermanual documentation.
  doc/usermanual/lighttable/images/panel_lua_scripts_installer.png
  doc/usermanual/lighttable/images/panel_lua_scripts_installer_first_run.png
  doc/usermanual/lighttable/panels/panels.xml
  doc/usermanual/lighttable/panels/scripts_installer.xml
Labels: scope: usermanual

#5454 filmicrgb: separate highlight reconstruction mask button
  src/iop/filmicrgb.c
Labels: feature: redesign, scope: UI

#5458 update images in collection on tags_changed if filtering by tags
  src/libs/collect.c
Labels: bugfix

#5463 eliminate redundant pixelpipe recomputation while adjusting crop box
  src/iop/clipping.c
Labels: feature: enhancement, scope: performance

#5462 add keyboard shortcut to toggle tooltip visibility
  data/themes/darktable.css
  src/gui/gtk.c
Labels: feature: new, scope: UI

#5471 denoiseprofile: always display correct curve in Y0U0V0
  src/iop/denoiseprofile.c
Labels: bugfix, scope: codebase

#5467 introduce more responsible maintenance
  src/common/database.c
Labels: feature: enhancement, scope: codebase

#5445 Better icon themes in Windows HiDPI
  data/themes/darktable-icons.css
Labels: bugfix, feature: enhancement, scope: UI

#5453 fix duplicate preview in darkroom
  src/libs/duplicate.c
Labels: bugfix, scope: UI

#5438 Little transparency on tooltip (& block infos fix)
  data/themes/darktable.css
Labels: feature: enhancement, scope: UI

#5457 Properly raise DT_SIGNAL_IMAGE_INFO_CHANGED for compressed history.
  src/common/history.c
  src/dtgtk/thumbnail.c
Labels: bugfix, scope: UI

#5482 Spanish translation update
  po/es.po
Labels: scope: translation

#5480 variable $(SEQUENCEn), n added to control the number of digits
  doc/usermanual/lighttable/panels/export.xml
  src/common/variables.c
Labels: feature: enhancement, scope: DAM

#5479 Fix Lua API not reporting image rating correctly
  src/lua/image.c
Labels: bugfix

#5490 thumb : fix colorlabels size
  src/dtgtk/thumbnail.c
Labels: bugfix, difficulty: trivial, scope: UI

#5487 German translation updates
  po/de.po
Labels: scope: translation

#5477 forget margin-top offset as it doesn't works if using WM without compositing
  data/themes/darktable.css
Labels: bugfix, scope: UI

#5441 po/fast pipe
  src/develop/imageop.h
  src/develop/pixelpipe.h
  src/develop/pixelpipe_cache.c
  src/develop/pixelpipe_hb.c
  src/iop/ashift.c
  src/iop/atrous.c
  src/iop/basicadj.c
  src/iop/bilateral.cc
  src/iop/clipping.c
  src/iop/colormapping.c
  src/iop/colorout.c
  src/iop/colorreconstruction.c
  src/iop/colortransfer.c
  src/iop/colorzones.c
  src/iop/demosaic.c
  src/iop/denoiseprofile.c
  src/iop/dither.c
  src/iop/exposure.c
  src/iop/filmicrgb.c
  src/iop/globaltonemap.c
  src/iop/hazeremoval.c
  src/iop/hotpixels.c
  src/iop/lens.cc
  src/iop/levels.c
  src/iop/retouch.c
  src/iop/rgbcurve.c
  src/iop/rgblevels.c
  src/iop/tonecurve.c
  src/iop/toneequal.c
  src/iop/zonesystem.c
Labels: bugfix, difficulty: average, scope: performance

#5498 Reverted changes to introspection translation
  src/develop/imageop_gui.c
  tools/introspection/ast.pm
Labels: scope: translation

#5500 Spanish translation update
  po/es.po
Labels: scope: translation

#5510 Don't raise DT_SIGNAL_METADATA_UPDATE in dt_imageio_open
  src/common/imageio.c
Labels: bugfix

#5507 hsl base setting
  src/iop/colorzones.c
Labels: feature: enhancement, scope: image processing

#5506 Small fixes for breakage/step sizes caused by introspection merge #5335
  src/iop/bilat.c
  src/iop/colorbalance.c
  src/iop/demosaic.c
  src/iop/exposure.c
  src/iop/filmicrgb.c
Labels: bugfix

#5505 Correct the slider origin when factor and or offset used
  src/bauhaus/bauhaus.c
Labels: bugfix, scope: UI

#5503 thumbtable : fix scroll with trackpad
  src/dtgtk/thumbtable.c
Labels: bugfix, difficulty: trivial, scope: UI

#5512 fixes ‘colname’ may be used uninitialized
  src/common/collection.c
  src/libs/collect.c
Labels: bugfix

#5501 Thumbtable icon size 3
  src/dtgtk/paint.c
  src/dtgtk/thumbnail.c
Labels: bugfix, scope: UI

#5513 Spanish translation update
  po/es.po
Labels: scope: translation

#5515 thumbnail mouse hover fix
  src/dtgtk/culling.c
  src/dtgtk/thumbnail.c
Labels: bugfix, difficulty: trivial, scope: UI

#5517 Updates to pt_BR translation
  po/pt_BR.po
Labels: scope: translation

#5508 Eliminate unnecessary reprocessing for more responsive GUI
  src/develop/blend_gui.c
  src/iop/clipping.c
  src/iop/colorchecker.c
  src/iop/retouch.c
  src/iop/toneequal.c
Labels: feature: redesign, scope: performance

#5521 undef DT_IOP_COLORZONES_BANDS_HSL just for completness sake
  src/iop/colorzones.c
Labels: bugfix

#5468 edited fields focus fix
  src/dtgtk/thumbtable.c
  src/libs/metadata.c
  src/libs/tagging.c
Labels: bugfix, difficulty: average, scope: UI

#5518 Fix small(est possible) bug in enum introspection and remove workaround
  src/iop/filmicrgb.c
  tools/introspection/ast.pm
Labels: bugfix

#5519 Do not popup combobox when empty
  src/bauhaus/bauhaus.c
Labels: feature: enhancement

#5525 overlays block : force uniform margins
  data/themes/darktable.css
  src/dtgtk/thumbnail.c
Labels: feature: enhancement, scope: UI

#5538 thumb : ensure positive positions
  src/dtgtk/thumbnail.c
Labels: bugfix, difficulty: trivial, scope: UI

#5540 LABELS_ICONS : fix for non-english languages
  src/common/variables.c
Labels: bugfix, difficulty: trivial, scope: UI

#5539 Updates to pt_BR
  doc/usermanual/po/pt_BR.po
  po/pt_BR.po
Labels: scope: translation, scope: usermanual

#5529 make show/hide iop module shortcut more consistent
  src/develop/imageop.c
  src/libs/modulegroups.c
Labels: bugfix

#5527 Correct direction of slider moves if triggered via up/down or dynamic shortcuts
  src/bauhaus/bauhaus.c
Labels: bugfix

#5547 filmic rgb: rescale noise level depending on zoom level
  src/iop/filmicrgb.c
Labels: bugfix, difficulty: trivial, scope: image processing

#5546 modulegroups: ESC key cancels search
  src/libs/modulegroups.c
Labels: difficulty: trivial, feature: enhancement, scope: UI

#5549 dt_view_get_images_to_act_on() returns a const list
  src/common/colorlabels.c
  src/common/colorlabels.h
  src/common/history.c
  src/common/history.h
  src/common/image.c
  src/common/metadata.c
  src/common/metadata.h
  src/common/styles.c
  src/common/styles.h
  src/common/tags.c
  src/control/jobs/control_jobs.c
  src/dtgtk/thumbtable.c
  src/libs/copy_history.c
  src/libs/export.c
  src/libs/image.c
  src/libs/metadata.c
  src/libs/styles.c
  src/libs/tagging.c
  src/libs/tools/colorlabels.c
  src/libs/tools/ratings.c
  src/lua/gui.c
  src/views/map.c
  src/views/view.c
  src/views/view.h
Labels: feature: redesign, scope: codebase

#5531 xmp update fix
  src/common/exif.cc
  src/common/image.c
  src/common/metadata.c
  src/common/tags.c
  src/libs/image.c
  src/libs/metadata.c
  src/libs/tagging.c
  src/lua/tags.c
  src/views/view.h
Labels: bugfix

#5553 Ensure decent cairo scaling for duplicates
  src/dtgtk/thumbnail.c
  src/libs/duplicate.c
  src/views/print.c
  src/views/tethering.c
  src/views/view.c
  src/views/view.h
Labels: bugfix, difficulty: trivial, feature: enhancement, scope: UI

#5550 add LABELS_COLORICONS for span-color not-respecting colormoji
  src/common/variables.c
Labels: bugfix

#5469 expose DPI and GUI scaling factors in prefs
  src/gui/gtk.c
  src/gui/gtk.h
  src/gui/preferences.c
Labels: feature: enhancement

#5548 Align always-on icon
  data/themes/darktable-icons.css
  data/themes/darktable.css
Labels: bugfix, scope: UI

#5533 Color Balance: set different soft ranges for shadows midtones highlights
  src/iop/colorbalance.c
Labels: feature: enhancement, scope: UI, scope: image processing

#5567 variable : change exposure format for export
  src/common/variables.c
Labels: difficulty: trivial, feature: enhancement, scope: DAM

#5574 Spanish translation update
  po/es.po
Labels: scope: translation

#5573 preferences: change DPI tooltip
  src/gui/preferences.c
Labels: scope: UI

#5577 Spanish translation update
  po/es.po
Labels: scope: translation

#5569 Fix the moving lower border in clipping.c
  src/iop/clipping.c
Labels: bugfix

#5570 shortcut to change "keyboard shortcut slider adjustment precision"
  data/darktableconfig.xml.in
  src/gui/accelerators.c
  src/gui/accelerators.h
  src/views/darkroom.c
Labels: feature: enhancement

#5582 iop_order: sanity check to avoid crash when reloading boggus xmp.
  src/common/iop_order.c
Labels: bugfix

#5590 Blending tabs icons: enable hover effect
  src/dtgtk/paint.c
Labels: scope: UI
