Repository darktable-org/darktable, pull requests merged in 2020-07, with the labels that each got.

#5679 German translation updates
  po/de.po
Labels: scope: translation

#5676 po/fix xmp import
  src/common/image.c
Labels: bugfix, priority: high

#5685 hinter : ellipsize the text
  src/libs/tools/hinter.c
Labels: bugfix, difficulty: trivial, scope: UI

#5690 German translation updates
  po/de.po
Labels: scope: translation

#5688 lighttable: fix quadratic lag on Home/End
  src/dtgtk/thumbtable.c
Labels: bugfix, scope: performance

#5678 image: duplicate version caching bugfix
  src/common/image.c
Labels: bugfix

#5692 po/fix paste parts
  src/common/history.c
Labels: bugfix, priority: high

#5694 [denoiseprofile] restore previous stepsize for strength
  src/iop/denoiseprofile.c
Labels: bugfix

#5670 Documentation for the file renaming parameters introduced in PR #2082.
  doc/usermanual/lua/lua_api.xml
Labels: scope: usermanual

#5699 Spanish translation: improvements
  po/es.po
Labels: scope: translation

#5695 Add tooltip info when tone equalizer is selected (like other modules)
  src/iop/toneequal.c
Labels: feature: enhancement

#5702 scripts installer fix luarc backup
  data/luarc
Labels: feature: enhancement

#5704 import xmp-exif regression fix
  src/common/exif.cc
  src/control/jobs/control_jobs.c
Labels: bugfix

#5705 fix sqlite 3.15 (ubuntu 18) issue on duplicate image
  src/common/image.c
Labels: bugfix

#5628 Optional export to grayscale tiff files
  src/imageio/format/tiff.c
Labels: bugfix

#5710 image: _image_duplicate_with_version no signal no timestamp update.
  src/common/image.c
Labels: bugfix, priority: high, scope: DAM

#5715 Spanish translation update
  po/es.po
Labels: scope: translation

#5713 duplicate : fix offset if ratio is different
  src/libs/duplicate.c
Labels: bugfix, difficulty: trivial, scope: UI

#5717 Updates to pt_BR
  doc/usermanual/po/pt_BR.po
  po/pt_BR.po
Labels: scope: translation, scope: usermanual

#5718 Spanish translation update
  po/es.po
Labels: scope: translation

#5720 Spanish translation update
  po/es.po
Labels: scope: translation

#5719 Update to pt_BR
  po/pt_BR.po
Labels: scope: translation

#5723 bugfix #5712, add gui_reset to liquify modules
  src/iop/liquify.c
Labels: bugfix

#5721 Restore slider digits where lost in introspection changes
  src/iop/basicadj.c
  src/iop/bilat.c
  src/iop/borders.c
  src/iop/clipping.c
  src/iop/colorreconstruction.c
  src/iop/filmicrgb.c
  src/iop/toneequal.c
  src/iop/vignette.c
  src/iop/watermark.c
Labels: bugfix

#5724 clipping: display more digits.
  src/iop/clipping.c
Labels: bugfix

#5730 German translation updates
  po/de.po
Labels: scope: translation

#5738 German translation updates
  po/de.po
Labels: scope: translation

#5733 fix for "crawler: Hopefully better fix for #4133"
  src/control/crawler.c
Labels: bugfix

#5739 German translation updates
  po/de.po
Labels: scope: translation

#5745 filmstrip : ensure rowid is always valid
  src/dtgtk/thumbtable.c
Labels: bugfix, difficulty: trivial, scope: UI

#5746 German translation updates
  po/de.po
Labels: scope: translation

#5753 gui->reset brackets around gui_init for multi-instance styles and redo.
  src/develop/develop.c
  src/libs/history.c
Labels: bugfix

#5751 lut3d: add check to prevent buffer overrun and ensure string zero termination
  src/iop/lut3d.c
Labels: bugfix

#5744 Nikon D5600 white balance presets (fine)
  src/external/wb_presets.c
Labels: feature: enhancement

#5757 This patch almost disable any hightlight reconstruction by default.
  src/iop/filmicrgb.c
Labels: bugfix, scope: performance

#5758 min width
  data/themes/darktable.css
  src/libs/metadata_view.c
Labels: bugfix, feature: enhancement

#5764 German translation updates
  po/de.po
Labels: scope: translation

#5765 German translation updates
  po/de.po
Labels: scope: translation

#5767 German translation updates
  po/de.po
Labels: scope: translation

#5771 po/fix user aspect
  src/iop/clipping.c
Labels: bugfix

#5773 po/fix user aspect
  src/iop/clipping.c
Labels: bugfix

#5776 Noiseprofiles
  data/noiseprofiles.json
Labels: scope: noise profile

#5777 clipping: fix clipping using float values.
  src/iop/clipping.c
Labels: bugfix

#5781 imageio: Add support for libavif >= 0.8.0
  src/common/imageio_avif.c
  src/imageio/format/avif.c
Labels: feature: enhancement

#5787 Update italian translation
  po/it.po
Labels: scope: translation

#5789 German translation updates
  po/de.po
Labels: scope: translation

#5790 Spanish translation update
  po/es.po
Labels: scope: translation

#5791 images order on tags - update doc and RELEASE_NOTES
  RELEASE_NOTES.md
  doc/usermanual/lighttable/concepts/filtering.xml
Labels: scope: translation, scope: usermanual

#5794 German translation updates
  po/de.po
Labels: scope: translation

#5795 Spanish translation update
  po/es.po
Labels: scope: translation

#5796 Updating pt_BR
  doc/usermanual/po/pt_BR.po
  po/pt_BR.po
Labels: scope: translation, scope: usermanual

#5804 Hebrew translation update
  po/he.po
Labels: scope: translation

#5807 Spanish translation update
  po/es.po
Labels: scope: translation

#5800 Cannot select an area with the parametric mask color picker
  src/gui/color_picker_proxy.c
Labels: bugfix

#5663 fixes modules inadvertently responding to blending color pickers
  src/iop/colorzones.c
  src/iop/exposure.c
  src/iop/tonecurve.c
Labels: bugfix

#5805 histogram: update documentation
  doc/usermanual/darkroom/images/panel_histogram.png
  doc/usermanual/darkroom/images/panel_histogram_linear.png
  doc/usermanual/darkroom/images/panel_histogram_logarithmic.png
  doc/usermanual/darkroom/images/panel_histogram_rgb_parade.png
  doc/usermanual/darkroom/images/panel_histogram_waveform.png
  doc/usermanual/darkroom/panels/histogram.xml
Labels: scope: usermanual

#5827 init metadata flags at start time
  src/common/darktable.c
  src/common/metadata.c
  src/common/metadata.h
  src/libs/metadata.c
Labels: bugfix, priority: high, scope: DAM

#5832 correct vertical alignment of module icons in darkroom headers
  src/develop/imageop.c
Labels: feature: enhancement, scope: UI

#5839 Spanish translation update
  po/es.po
Labels: scope: translation

#5836 Use @RvRijsselts workaround to fix broken locallaplacian on AMD
  data/kernels/locallaplacian.cl
Labels: bugfix

#5838 [Issue #5837] Sony ILCE-7RM4 WB Presets FW 1.10
  src/external/wb_presets.c
Labels: feature: enhancement, scope: camera support

#5845 Spanish translation update
  po/es.po
Labels: scope: translation

#5844 Updates to pt_BR
  doc/usermanual/po/pt_BR.po
  po/pt_BR.po
Labels: scope: translation, scope: usermanual

#5848 Updates to pt_BR
  doc/usermanual/po/pt_BR.po
Labels: scope: translation
