Repository darktable-org/darktable, pull requests merged in 2020-02, with the labels that each got.

#4212 fix:filmicrgb: fixed rgb power norm for dark areas
  data/kernels/filmic.cl
  src/iop/filmicrgb.c
Labels: bugfix

#4210 Fixing pixelpipe cache data buffers if allocation goes wrong.
  src/develop/pixelpipe_cache.c
Labels: bugfix

#4219 Exif - fix DateTimeDigitized overwrite
  src/common/exif.cc
Labels: bugfix

#4221 database: Add some primary key to memory table.
  src/common/database.c
Labels: bugfix

#4222 tagging - set tag list view as default
  src/libs/tagging.c
Labels: bugfix

#4224 po/speed up sql
  src/common/database.c
  src/common/tags.c
Labels: bugfix

#4227 tags: dt_tag_get_suggestions remove similar_tags setting, not used.
  src/common/tags.c
Labels: difficulty: trivial, feature: enhancement, scope: DAM

#3242 fix spline interpolation in color zones module
  src/CMakeLists.txt
  src/common/splines.cpp
  src/common/splines.h
  src/gui/draw.h
  src/iop/colorzones.c
Labels: feature: enhancement, scope: UI, scope: codebase, scope: image processing

#4197 Another step to modern cmake
  CMakeLists.txt
  cmake/modules/DefineCMakeDefaults.cmake
  src/CMakeLists.txt
  src/chart/CMakeLists.txt
  src/cli/CMakeLists.txt
  src/cltest/CMakeLists.txt
  src/generate-cache/CMakeLists.txt
  src/imageio/format/CMakeLists.txt
  src/imageio/storage/CMakeLists.txt
  src/iop/CMakeLists.txt
  src/libs/CMakeLists.txt
  src/views/CMakeLists.txt
Labels: difficulty: average, feature: enhancement, scope: codebase

#4193 test if data base exists before backup and make backup non-writable
  src/common/database.c
Labels: bugfix

#4214 Fix for multiple lines fo the same lighttable module shortcut
  src/gui/accelerators.c
Labels: bug: pending, difficulty: average

#4154 Added simple unit test sample for demonstration
  .ci/ci-script.sh
  .travis.yml
  CMakeLists.txt
  DefineOptions.cmake
  cmake/modules/AddCMockaMockTest.cmake
  cmake/modules/AddCMockaTest.cmake
  src/CMakeLists.txt
  src/tests/CMakeLists.txt
  src/tests/unittests/CMakeLists.txt
  src/tests/unittests/test_filmicrgb.c
  src/tests/unittests/test_sample.c
Labels: difficulty: average, priority: high, scope: codebase

#4256 Add changes from Wolfgang Arndt into translation
  doc/usermanual/po/de.po
Labels: scope: usermanual

#4267 Spanish user manual translation 3.0
  doc/usermanual/po/es.po
Labels: scope: usermanual

#4268 Fix accelerator name for timeline
  src/gui/gtk.c
  src/views/lighttable.c
Labels: bugfix

#4272 Minor fix on collect.c
  src/libs/collect.c
Labels: bugfix, scope: translation

#4266 fix #4021
  data/kernels/blendop.cl
  data/kernels/guided_filter.cl
  src/common/guided_filter.c
  src/develop/blend.c
Labels: bugfix

#4276 Spanish translation update
  po/es.po
Labels: scope: translation

#4277 Spanish user manual: more fixes
  doc/usermanual/po/es.po
Labels: scope: usermanual

#4274 Improve german translation
  po/de.po
Labels: scope: translation

#4275 Finalize translation and add the latest translation from Wolfgang Arndt
  doc/usermanual/po/de.po
Labels: scope: usermanual

#4249 Created a build-doc helper script as discussed in darktable issue #4177
  build-doc.sh
Labels: difficulty: average, feature: enhancement, scope: usermanual

#4003 doc for last panel changes
  doc/usermanual/lighttable/panels/timeline.xml
  doc/usermanual/overview/overview.xml
Labels: no-pr-activity, scope: usermanual

#4282 tagging fixes
  src/libs/tagging.c
Labels: bugfix

#3015 moved doc tagging pictures from darktable-elegant-grey to darktable.css
  doc/usermanual/lighttable/images/panel_exportselected.png
  doc/usermanual/lighttable/images/panel_tagging-attached.png
  doc/usermanual/lighttable/images/panel_tagging-create.png
  doc/usermanual/lighttable/images/panel_tagging-default.png
  doc/usermanual/lighttable/images/panel_tagging-dttag.png
  doc/usermanual/lighttable/images/panel_tagging-edit.png
  doc/usermanual/lighttable/images/panel_tagging-overlay.png
  doc/usermanual/lighttable/images/panel_tagging-renamepath.png
  doc/usermanual/lighttable/images/panel_tagging-short.png
  doc/usermanual/lighttable/images/panel_tagging-sort.png
  doc/usermanual/lighttable/images/panel_tagging-submenu.png
  doc/usermanual/lighttable/images/panel_tagging-suggbutton.png
  doc/usermanual/lighttable/images/panel_tagging-treebutton.png
  doc/usermanual/lighttable/panels/export.xml
  doc/usermanual/lighttable/panels/tagging.xml
Labels: scope: usermanual

#4287 Spanish translation update
  po/es.po
Labels: scope: translation

#4289 imageio: Don't use the slowest speed which is not recommended
  src/imageio/format/avif.c
Labels: difficulty: trivial, feature: enhancement, priority: medium, scope: image processing, scope: performance, understood: clear

#4290 Made modules search case insensetive
  src/libs/modulegroups.c
Labels: difficulty: trivial, feature: enhancement, scope: codebase

#4299 updated PL translation to v. 3.0
  doc/usermanual/po/pl.po
Labels: scope: usermanual

#4301 Collect only based on enabled module in dev history
  src/common/collection.c
  src/libs/collect.c
Labels: bugfix, feature: enhancement

#4303 Introduce database maintenance into purging scripts
  tools/purge_non_existing_images.sh
  tools/purge_unused_tags.sh
Labels: difficulty: trivial, feature: enhancement, scope: performance, understood: clear

#4302 collect module - remove configuration hidden module
  src/common/collection.c
  src/libs/collect.c
  src/libs/collect.h
Labels: feature: enhancement

#4315 replace numerical constants by named constants
  data/kernels/blendop.cl
  src/develop/blend.c
Labels: difficulty: trivial, feature: enhancement, scope: codebase

#4316 avoid unnecessary mixed precision arithmetic
  src/iop/liquify.c
Labels: difficulty: trivial, feature: enhancement

#4317 fix macro usage in OpenCL kernel
  data/kernels/blendop.cl
Labels: bugfix

#4319 Update OpenMP to 4.5 and improve performance in compute_log_histogram
  CMakeLists.txt
  src/iop/toneequal.c
Labels: feature: enhancement, scope: performance

#4320 Spanish translation update
  po/es.po
Labels: scope: translation

#4321 metadataview fix - memory leak on tags
  src/libs/metadata_view.c
Labels: bugfix

#4326 fix cleanup module_order on remove image
  src/common/image.c
Labels: bugfix

#4318 reduce scope of variables, minor fixes
  src/common/cache.c
  src/common/calculator.c
  src/common/collection.c
  src/common/colorspaces.c
  src/common/database.c
  src/common/dwt.c
  src/common/film.c
  src/common/history.c
  src/common/image_cache.c
  src/common/imageio.c
  src/common/imageio_dng.h
  src/common/imageio_j2k.c
  src/common/imageio_jpeg.c
  src/common/imageio_rgbe.c
  src/common/opencl.c
  src/common/points.h
  src/common/pwstorage/backend_kwallet.c
  src/common/ratings.c
  src/common/styles.c
  src/common/tags.c
  src/common/utility.c
  src/common/variables.c
Labels: feature: enhancement, scope: codebase

#4336 info line lib : ellipsize by the middle
  src/libs/tools/image_infos.c
Labels: bugfix

#4331 fix format string errors
  src/common/image_cache.c
  src/common/mipmap_cache.c
Labels: bugfix

#4335 Update wb_presets.c (Nikon Coolpix P1000)
  src/external/wb_presets.c
Labels: feature: enhancement, scope: camera support

#4341 restrict scope of local variables
  src/control/jobs/control_jobs.c
  src/develop/imageop.c
  src/develop/masks/brush.c
  src/develop/masks/circle.c
  src/develop/masks/ellipse.c
  src/develop/masks/masks.c
  src/develop/masks/path.c
  src/dtgtk/expander.c
  src/gui/accelerators.c
  src/gui/gtkentry.c
  src/gui/preferences.c
  src/imageio/format/jpeg.c
  src/imageio/format/webp.c
Labels: feature: enhancement

#4342 Trs44
  po/es.po
Labels: scope: translation

#4349 use exclusively bash in all shell scripts
  .ci/ci-script.sh
  build-doc.sh
  build.sh
  tools/authors_h.sh
  tools/common.sh
  tools/create_control_svg.sh
  tools/create_release.sh
  tools/create_version_c.sh
  tools/generate-authors.sh
  tools/get_git_version_string.sh
  tools/get_last_commit_year.sh
  tools/iop-layout-legacy.sh
  tools/iop-layout.sh
  tools/keybinding2docbook.sh
  tools/listcams.sh
  tools/makeman.sh
  tools/noise/benchmark.sh
  tools/noise/graph.sh
  tools/noise/graph2.sh
  tools/parse_version_c.sh
  tools/purge_from_cache.sh
  tools/purge_non_existing_images.sh
  tools/purge_unused_tags.sh
  tools/update_modelines.sh
  tools/update_wb_presets_from_ufraw.sh
  tools/update_web_usermanual.sh
  tools/watch_folder.sh
Labels: feature: enhancement

#4325 Make tools use same paths and options as main binary
  tools/purge_from_cache.sh
  tools/purge_non_existing_images.sh
  tools/purge_unused_tags.sh
Labels: bugfix

#4351 Enable highlights reconstruction as default for raw and sraw images
  src/iop/highlights.c
Labels: bugfix, feature: enhancement, scope: image processing

#4353 Let exif.cc be more verbose in case of errors
  src/common/exif.cc
Labels: feature: enhancement, scope: codebase

#4337 Perform database maintenance on db upgrade and dt closing time
  data/darktableconfig.xml.in
  src/common/darktable.c
  src/common/database.c
  src/common/database.h
Labels: feature: enhancement

#4359 fix global toolbox 'open help url' error handling
  src/libs/tools/global_toolbox.c
Labels: bugfix

#4357 fix history export diff
  src/common/exif.cc
Labels: bugfix

#4365 noise profiles
  data/noiseprofiles.json
Labels: scope: noise profile

#4322 history MD5 hash calculation
  src/common/collection.c
  src/common/database.c
  src/common/exif.cc
  src/common/history.c
  src/common/history.h
  src/common/image.c
  src/develop/develop.c
  src/libs/collect.c
Labels: bugfix, feature: enhancement, scope: DAM

#4369 po/clean collection
  src/common/collection.c
  src/common/collection.h
  src/libs/collect.c
  src/libs/collect.h
  src/libs/recentcollect.c
Labels: difficulty: trivial, feature: enhancement, scope: DAM

#4271 po/copy module order
  src/common/database.c
  src/common/history.c
  src/common/history.h
  src/common/image.c
  src/common/styles.c
  src/common/styles.h
  src/control/jobs/control_jobs.c
  src/gui/hist_dialog.c
  src/gui/hist_dialog.h
  src/gui/styles_dialog.c
  src/libs/copy_history.c
  src/libs/duplicate.c
  src/libs/tools/filmstrip.c
  src/lua/styles.c
Labels: difficulty: average, feature: enhancement, priority: medium, scope: UI, scope: codebase, understood: clear

#4372 "duplicate : avoid unneeded pipe compute" commit cd97cc58 from AlicVB repository
  src/libs/duplicate.c
Labels: bugfix

#4361 resort and group blend modes
  src/bauhaus/bauhaus.c
  src/bauhaus/bauhaus.h
  src/develop/blend_gui.c
Labels: difficulty: trivial, feature: enhancement, priority: low, scope: codebase

#4383 fix metadata - allows " in the text
  src/common/metadata.c
Labels: bugfix

#4378 UX fix for XMP reload. fixes #4239
  src/control/crawler.c
Labels: difficulty: trivial, feature: enhancement

#4377 Fixing dt crashing while importing via libgphoto (V2)
  src/common/camera_control.c
  src/common/import_session.c
  src/gui/camera_import_dialog.c
Labels: bugfix

#4392 simplest way to fix #4381
  src/views/knight.c
Labels: bugfix

#4389 prevent globbing or splitting of arguments
  tools/basecurve/darktable-curve-tool-helper
Labels: feature: enhancement

#4395 fix double mask issue
  src/develop/develop.c
Labels: bugfix

#4399 fix memory allocation and remove superfluous casts
  src/common/locallaplaciancl.c
Labels: bugfix, scope: codebase

#4074 Folder, Directory, Filmroll. When to use what?
  doc/usermanual/lighttable/panels/import.xml
  src/libs/import.c
Labels: feature: enhancement, scope: UI, scope: usermanual
