Repository darktable-org/darktable, pull requests merged in 2020-12, with the labels that each got.

#7143 Update white balance spot picker to work with TIFF files
  src/develop/pixelpipe_hb.c
  src/gui/color_picker_proxy.c
  src/gui/color_picker_proxy.h
  src/iop/temperature.c
Labels: bugfix, priority: high

#7148 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#7130 DNG: fix white balance coeffs and embedded matrices
  src/common/colorspaces.c
  src/common/colorspaces.h
  src/common/illuminants.h
  src/iop/channelmixerrgb.c
  src/iop/demosaic.c
  src/iop/invert.c
  src/iop/temperature.c
Labels: bugfix, priority: high

#7151 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#7150 updated german translation
  po/de.po
Labels: scope: translation

#7139 slideshow : better handling of shortcuts
  src/control/control.c
  src/views/slideshow.c
Labels: bugfix, difficulty: trivial, scope: UI

#7161 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#7160 exif: copyright is mandatory, empty is ok
  src/common/exif.cc
Labels: bugfix

#7168 Spanish translation update
  po/es.po
Labels: scope: translation

#7165 further update german translation
  po/de.po
Labels: scope: translation

#7170 Show button who has focus in pop-up
  data/themes/darktable.css
Labels: bugfix, scope: UI

#7176 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#7183 German translation updates
  po/de.po
Labels: scope: translation

#7178 use embedded preview even if only auto history applied
  src/common/mipmap_cache.c
Labels: bugfix, difficulty: trivial, scope: UI

#7184 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#7187 remaining german translations
  po/de.po
Labels: scope: translation

#6723 exif: convert from APEX values
  src/common/exif.cc
Labels: bugfix

#6711 exif: use Exiv2 accessors that check multiple IFDs
  src/common/exif.cc
Labels: bugfix

#7188 Polish translation update for 3.4
  po/pl.po
Labels: scope: translation

#7179 thumbs : show busy msg if loading delay
  src/control/control.c
  src/control/control.h
  src/dtgtk/thumbnail.c
  src/dtgtk/thumbnail.h
Labels: difficulty: trivial, feature: enhancement, scope: UI

#7167 [performance] filmicrgb reconstruction speedup, part 2
  src/iop/filmicrgb.c
Labels: scope: performance

#7216 Update Finnish translation.
  po/fi.po
Labels: scope: translation

#7205 fix format string errors
  src/iop/lut3dgmic.cpp
Labels: bugfix

#7203 [performance] shadows and highlights
  src/iop/shadhi.c
Labels: scope: performance

#7200 Remove esc handler quitting fullscreen to enable quit-slideshow
  src/gui/gtk.c
Labels: bugfix

#7191 fix out-of-bound array access, some minor clean up
  src/win/rlimit.c
Labels: bugfix, priority: high

#7202 bugfix: unitialized values in rawdenoise X-Trans code path
  src/iop/rawdenoise.c
Labels: bugfix, priority: high

#7210 Fujifilm X-S10 noise profile
  data/noiseprofiles.json
Labels: scope: noise profile

#7194 refactor: move dwt_denoise into common/dwt.c
  src/common/dwt.c
  src/common/dwt.h
  src/iop/rawdenoise.c
Labels: scope: codebase

#7219 [extract_wb] fix handling of exif models with aliases
  tools/extract_wb.py
Labels: bugfix

#7221 [wb_presets] add finetuned presets for Canon EOS 200D/Rebel SL2/Kiss X9
  src/external/wb_presets.c
Labels: scope: camera support

#7226 [performance] adjust OpenMP directives for better scaling
  src/iop/liquify.c
Labels: scope: performance

#7224 refactor: consolidate edge-aware wavelets code
  src/CMakeLists.txt
  src/common/eaw.c
  src/common/eaw.h
  src/iop/atrous.c
  src/iop/denoiseprofile.c
Labels: scope: performance

#7215 Fix picker leave
  src/control/control.c
  src/develop/imageop.c
  src/gui/color_picker_proxy.c
  src/gui/gtk.c
  src/views/darkroom.c
Labels: bugfix

#7201 collect + tagging: fix tags case issues + uncategorized entry
  src/common/collection.c
  src/common/map_locations.c
  src/common/tags.c
  src/libs/collect.c
  src/libs/tagging.c
Labels: bugfix

#7209 lua: fix horizontal box child widgets not expanding and filling
  src/lua/widget/box.c
Labels: bugfix

#7180 add consts, fix and remove compiler generated default implementations
  src/iop/Permutohedral.h
Labels: bugfix

#7227 Update german translations
  po/de.po
Labels: scope: translation

#7232 remove color picker queue_draw from idle after run
  src/control/control.c
Labels: bugfix

#7237 ES translations
  po/es.po
Labels: scope: translation

#7236 collection(tags): avoid a case insensitive possibility.
  src/common/collection.c
Labels: bugfix

#7192 add a censorization module
  src/common/gaussian.h
  src/common/iop_order.c
  src/iop/CMakeLists.txt
  src/iop/censorize.c
Labels: feature: enhancement

#7244 Spanish translation update
  po/es.po
Labels: scope: translation

#7239 alternative working msg for small width
  src/control/control.c
Labels: bugfix, difficulty: trivial, scope: UI

#7248 match IOP_GUI_ALLOC/IOP_GUI_FREE
  src/iop/channelmixerrgb.c
Labels: feature: enhancement

#7257 Spanish translation update
  po/es.po
Labels: scope: translation

#7259 imageio: return early on write error
  src/common/imageio.c
Labels: bugfix

#7261 Finishing ES translations
  po/es.po
Labels: scope: translation

#7269 po/undo filmstrip history
  src/develop/develop.c
  src/develop/develop.h
  src/dtgtk/thumbtable.c
  src/libs/history.c
  src/views/darkroom.c
Labels: bugfix, priority: medium

#7276 Updated Hebrew translation
  po/he.po
Labels: scope: translation

#7280 rawdenoise xtrans: correct memory allocation and initialization
  src/iop/rawdenoise.c
Labels: bugfix

#7281 filmicrgb: change scaling of loop variable
  src/iop/filmicrgb.c
Labels: bugfix

#7288 only change opacity on exactly Ctrl-Scroll, not Ctrl-Shift-Scroll
  src/develop/masks/ellipse.c
  src/develop/masks/masks.c
Labels: bugfix, priority: medium

#7292 Workaround for compiler issue in Windows
  src/iop/filmicrgb.c
Labels: bugfix

#7290 Update German translation: consolidation scene
  po/de.po
Labels: scope: translation

#7302 fix memory leaks
  src/bauhaus/bauhaus.c
  src/common/darktable.c
Labels: bugfix

#7305 Updated Czech translation
  po/cs.po
Labels: scope: translation

#7295 Improve icons when panel is narrow - from dterrahe
  data/themes/darktable.css
Labels: bugfix

#7300 bugfix: [nlmeans] clamp position during init
  src/common/nlmeans_core.c
Labels: bugfix

#7310 Add Hasselblad L1D-20c (a.k.a. DJI Mavic 2) to noiseprofiles
  data/noiseprofiles.json
Labels: scope: noise profile

#7309 fix nlmeans non-SSE codepath
  src/common/nlmeans_core.c
Labels: bugfix, priority: high

#7298 channelmixerrgb: change the CAT check in warning
  src/iop/channelmixerrgb.c
Labels: bugfix

#7313 [noiseprofiles] add Hasselblad to allowed makers
  data/noiseprofiles.schema
Labels: bugfix

#7314 Complete Spanish translation
  po/es.po
Labels: scope: translation

#7316 Spanish translation improvements.
  po/es.po
Labels: scope: translation

#7311 Add Panasonic DC-G95 noise profile
  data/noiseprofiles.json
Labels: scope: noise profile

#7319 colorspaces: do not write whitepoint, lcms already does it.
  src/common/colorspaces.c
Labels: bugfix

#7320 fix false positive warning for CAT applied twice
  src/iop/channelmixerrgb.c
  src/views/darkroom.c
Labels: bugfix

#7321 [wb_presets] add eos m5 finetuned presets
  src/external/wb_presets.c
Labels: scope: camera support

#7323 Update Hungarian translation
  po/hu.po
Labels: scope: translation

#7328 po/fix cat support
  src/develop/develop.h
  src/develop/imageop.c
  src/develop/imageop.h
  src/iop/channelmixerrgb.c
Labels: bugfix, priority: high

#7329 channelmixerrg: don't copy buffer with simd
  src/iop/channelmixerrgb.c
Labels: bugfix

#7326 Update French translation of the user manual
  doc/usermanual/darkroom/concepts/interacting.xml
  doc/usermanual/darkroom/modules/technical/crop_and_rotate.xml
  doc/usermanual/darkroom/modules/technical/exposure.xml
  doc/usermanual/darkroom/panels/histogram.xml
  doc/usermanual/lua/lua.xml
  doc/usermanual/po/fr.po
  doc/usermanual/preferences/general.xml
  doc/usermanual/tethering/troubleshoot.xml
  doc/usermanual/topics/darktable-chart.xml
  doc/usermanual/topics/opencl.xml
Labels: scope: usermanual

#7331 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#7330 [wb_presets] take over Canon M5 wb values for Canon M6
  src/external/wb_presets.c
Labels: scope: camera support

#7334 added libavif + rsvg dep. to Windows installer
  cmake/windows-macros.cmake
Labels: bugfix

#7199 small refactor iop gui expander setup
  src/develop/develop.c
  src/develop/imageop.c
  src/develop/imageop.h
  src/libs/history.c
  src/views/darkroom.c
Labels: feature: enhancement

#7223 add shortcut esc to quit slideshow
  po/de.po
  src/views/slideshow.c
Labels: feature: enhancement

#7354 Update to pt_BR
  po/pt_BR.po
Labels: scope: translation

#7353 Fix plural image removal prompts in German translations
  po/de.po
Labels: scope: translation

#6968 Optimize colorspaces conversions
  data/kernels/colorspace.cl
  data/kernels/colorspaces.cl
  src/common/iop_profile.c
  src/common/iop_profile.h
Labels: feature: enhancement, scope: performance

#7287 Integrate low_quality_thumbnails preference into ui/performance
  data/darktableconfig.xml.in
  src/common/darktable.c
  src/common/imageio.c
Labels: feature: enhancement

#7342 [imageio] CMYK is BAD, explicitly don't hanle it
  build.sh
  src/common/imageio_gm.c
  src/common/imageio_im.c
  src/common/imageio_tiff.c
Labels: bugfix

#7350 [imageio] use dt_print more, make tiff io respect DT_DEBUG_IMAGEIO
  src/common/imageio_gm.c
  src/common/imageio_im.c
  src/common/imageio_tiff.c
Labels: bugfix

#7336 enhancement of thumb resizing (lt/culling/preview)
  src/dtgtk/culling.c
  src/dtgtk/culling.h
  src/dtgtk/thumbnail.c
  src/dtgtk/thumbnail.h
  src/libs/duplicate.c
  src/views/print.c
  src/views/tethering.c
  src/views/view.c
  src/views/view.h
Labels: difficulty: average, feature: enhancement, scope: UI

#7263 colorspaces: ICC v2.4 is more appropriate for profile content
  src/common/colorspaces.c
Labels: bugfix

#7357 refactor: deduplicate Log2, Log2Thresh, fastlog, fastlog2
  src/common/math.h
  src/iop/colorchecker.c
  src/iop/filmic.c
  src/iop/profile_gamma.c
Labels: scope: codebase

#7374 liquify: clear memory using calloc().
  src/iop/liquify.c
Labels: scope: codebase

#7367 dedup dwt_interleave_rows
  src/iop/filmicrgb.c
Labels: scope: codebase

#7356 refactor: remove duplicate definitions of clamp_simd() and sqf()
  src/develop/blends/blendif_lab.c
  src/develop/blends/blendif_raw.c
  src/develop/blends/blendif_rgb_hsl.c
  src/develop/blends/blendif_rgb_jzczhz.c
  src/iop/channelmixer.c
  src/iop/channelmixerrgb.c
Labels: scope: codebase

#7365 refactor: dedup file-copying code
  src/common/colorspaces.c
  src/common/exif.cc
  src/common/pdf.c
  src/common/utility.c
  src/common/utility.h
  src/imageio/format/copy.c
  src/imageio/storage/gallery.c
  src/imageio/storage/latex.c
Labels: scope: codebase

#7379 move conditional definition of M_LN10 into a common header
  src/common/math.h
  src/develop/blend_gui.c
  src/iop/ashift_lsd.c
Labels: scope: codebase

#7376 refactor: more consolidation of box filters
  src/common/box_filters.c
  src/common/box_filters.h
  src/common/fast_guided_filter.h
  src/common/focus_peaking.h
  src/iop/soften.c
Labels: scope: performance

#7253 collect: add config point for tags case insensitivity and Sqlite ICU extension
  DefineOptions.cmake
  cmake/modules/FindICU.cmake
  data/darktableconfig.xml.in
  src/CMakeLists.txt
  src/common/collection.c
  src/common/database.c
  src/common/sqliteicu.c
  src/common/sqliteicu.h
  src/libs/collect.c
Labels: bugfix, feature: enhancement, scope: DAM

#7231 Color zones: Make the colors in the interface background less saturated to prevent visual illusions
  data/darktableconfig.xml.in
  src/iop/colorzones.c
Labels: feature: enhancement

#7344 duplicate : disable preview for zoom >= 200%
  src/libs/duplicate.c
Labels: bugfix, difficulty: average, scope: UI

#7387 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#7388 collect-icu fix: add icu-uc and icu-data libraries
  cmake/modules/FindICU.cmake
Labels: bugfix

#7182 Update folders for filmrolls
  src/libs/collect.c
Labels: feature: new

#7396 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#7393 [presets] fixes import xml parser call not checking for null
  src/common/presets.c
Labels: bugfix

#7361 liquify: quick&dirty patch for osx
  src/iop/liquify.c
Labels: bugfix, priority: high, understood: unclear

#7373 make mask edit mode part of history undo.
  src/develop/masks.h
  src/develop/masks/masks.c
  src/libs/history.c
Labels: bugfix

#7364 tagging: add drag & drop actions
  src/gui/drag_and_drop.h
  src/libs/tagging.c
Labels: feature: enhancement

#7390 darkroom : show toast message on rating & colorlabels
  src/control/control.c
  src/control/control.h
  src/develop/masks/masks.c
  src/dtgtk/thumbtable.c
  src/gui/accelerators.c
  src/gui/gtk.c
  src/views/darkroom.c
Labels: difficulty: trivial, feature: enhancement, scope: UI

#7363 add missing thread-safety-analysis annotations to permit Debug build …
  src/common/dtpthread.h
  src/develop/develop.c
  src/gui/gtk.c
Labels: bugfix, priority: high, scope: codebase

#7399 Alt markup toast
  src/control/control.c
  src/control/control.h
  src/develop/masks/masks.c
  src/dtgtk/thumbtable.c
  src/gui/accelerators.c
  src/gui/gtk.c
  src/views/darkroom.c
Labels: bugfix, feature: enhancement

#7385 collect: shift-double click to switch from filmroll to corresponding folder
  src/libs/collect.c
Labels: feature: enhancement, priority: high

#7400 thumbnail: gtk-critical fix
  src/dtgtk/thumbnail.c
Labels: bugfix

#7411 po/fix box filter
  src/common/box_filters.c
Labels: bugfix, priority: high, scope: image processing

#7405 [presets] allow mass preset export
  data/themes/darktable.css
  src/common/presets.c
  src/gui/preferences.c
Labels: feature: enhancement

#7413 escape dt_control_log message so it is correct markup
  src/control/control.c
Labels: bugfix

#7416 po/fix box mean 2ch
  src/common/box_filters.c
Labels: bugfix, priority: high, scope: image processing, scope: performance

#7417 Czech translation update - minor corrections
  po/cs.po
Labels: scope: translation

#7418 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#7420 refactor: consolidate matrix multiplication functions
  src/common/colorspaces.c
  src/common/exif.cc
  src/common/iop_profile.c
  src/common/math.h
  src/common/matrices.c
  src/iop/ashift.c
  src/iop/clipping.c
  src/iop/colorin.c
  src/iop/rotatepixels.c
Labels: scope: codebase

#7434 bugfix: colorpicker crash on freeing aligned memory allocation
  src/common/color_picker.c
Labels: bugfix, difficulty: trivial

#7381 performance: parallelize circle-mask drawing
  src/develop/masks/circle.c
Labels: scope: performance

#7433 refactor: dedup clamping macros
  src/common/colorspaces_inline_conversions.h
  src/common/gaussian.c
  src/common/math.h
  src/common/pdf.c
  src/develop/blend_gui.c
  src/dtgtk/gradientslider.c
  src/imageio/format/tiff.c
  src/iop/bloom.c
  src/iop/clahe.c
  src/iop/clipping.c
  src/iop/defringe.c
  src/iop/dither.c
  src/iop/globaltonemap.c
  src/iop/graduatednd.c
  src/iop/grain.c
  src/iop/highpass.c
  src/iop/lowpass.c
  src/iop/relight.c
  src/iop/shadhi.c
  src/iop/soften.c
  src/iop/splittoning.c
  src/iop/velvia.c
  src/iop/vibrance.c
  src/iop/vignette.c
  src/iop/watermark.c
  src/iop/zonesystem.c
Labels: scope: codebase

#7443 tonecurve: cleanup parallel loop
  src/iop/tonecurve.c
Labels: scope: image processing, scope: performance

#7442 rgbcurve: cleanup parallel loop
  src/iop/rgbcurve.c
Labels: scope: image processing, scope: performance

#7439 cleanup: parallel loops in exposure iop
  src/iop/exposure.c
Labels: scope: performance

#7441 refactor: more consolidation of math utility functions
  data/kernels/basic.cl
  src/common/darktable.h
  src/common/eaw.c
  src/common/interpolation.c
  src/common/locallaplacian.c
  src/common/math.h
  src/common/nlmeans_core.c
  src/iop/basecurve.c
  src/iop/monochrome.c
Labels: scope: codebase

#7451 colorcorrection: cleanup process() to make it more vectorizable
  src/iop/colorcorrection.c
Labels: scope: performance

#7462 [exif] fix code copypaste mistake: Bag vs Seq
  src/common/exif.cc
Labels: difficulty: trivial, scope: codebase

#7454 Refactor: add common image-copy function
  src/CMakeLists.txt
  src/common/darktable.h
  src/common/imagebuf.c
  src/common/imagebuf.h
  src/develop/imageop_math.h
  src/iop/ashift.c
  src/iop/atrous.c
  src/iop/bilateral.cc
  src/iop/cacorrect.c
  src/iop/channelmixerrgb.c
  src/iop/choleski.h
  src/iop/colorin.c
  src/iop/colormapping.c
  src/iop/colorout.c
  src/iop/colorreconstruction.c
  src/iop/colortransfer.c
  src/iop/colorzones.c
  src/iop/defringe.c
  src/iop/demosaic.c
  src/iop/equalizer.c
  src/iop/hotpixels.c
  src/iop/lens.cc
  src/iop/lut3d.c
  src/iop/mask_manager.c
  src/iop/rawdenoise.c
  src/iop/rawoverexposed.c
  src/iop/retouch.c
  src/iop/sharpen.c
  src/iop/velvia.c
  src/iop/watermark.c
Labels: scope: codebase

#7435 prefs: remove import settings from pref dialog
  data/darktableconfig.xml.in
  src/control/conf.c
  src/control/conf.h
  src/gui/camera_import_dialog.c
  src/gui/import_metadata.c
  src/gui/preferences.c
  src/gui/preferences.h
  src/libs/import.c
  tools/generate_darktablerc_conf.xsl
  tools/generate_prefs.xsl
Labels: feature: enhancement

#7458 defringe: cleanup and improve vectorizability
  src/iop/defringe.c
Labels: scope: performance

#7460 refactor: consolidate code for displaying module trouble messages
  src/develop/imageop.c
  src/develop/imageop.h
  src/iop/channelmixerrgb.c
  src/iop/temperature.c
Labels: scope: codebase

#7486 French translation : buttons -> boutons
  po/fr.po
Labels: scope: translation

#7499 [brush/sharpen] fix memset size calculation after transition to align_float
  src/develop/masks/brush.c
  src/iop/sharpen.c
Labels: bugfix

#7440 colorout: cleanup parallel loops
  src/iop/colorout.c
Labels: scope: image processing, scope: performance

#7484 Add function to atomically allocate multiple buffers
  src/common/imagebuf.c
  src/common/imagebuf.h
  src/develop/imageop.c
  src/iop/denoiseprofile.c
  src/iop/overexposed.c
  src/iop/rawdenoise.c
  src/iop/sharpen.c
  src/iop/useless.c
Labels: scope: codebase

#7498 watermark: avoid calling expand variables with no input buffer
  src/common/variables.c
  src/iop/watermark.c
Labels: bugfix

#7490 Full translation of the user manual
  doc/usermanual/darkroom/panels/histogram.xml
  doc/usermanual/po/fr.po
Labels: scope: usermanual

#7475 export metadata: consider repeatable Iptc like Iptc.Application2.Keywords
  src/common/exif.cc
  src/common/tags.c
  src/common/variables.c
Labels: scope: DAM

#7511 po/fix virgin paste history
  src/common/history.c
  src/common/iop_order.c
  src/common/iop_order.h
  src/develop/develop.c
Labels: bugfix

#7478 add function to verify piece->colors and set module's trouble flag if…
  src/develop/imageop.c
  src/develop/imageop.h
  src/iop/bloom.c
  src/iop/channelmixerrgb.c
  src/iop/colorcontrast.c
  src/iop/colorcorrection.c
  src/iop/colormapping.c
  src/iop/colorout.c
  src/iop/defringe.c
  src/iop/denoiseprofile.c
  src/iop/nlmeans.c
  src/iop/rgbcurve.c
  src/iop/soften.c
  src/iop/splittoning.c
  src/iop/tonecurve.c
  src/iop/useless.c
  src/iop/vibrance.c
Labels: scope: codebase

#7518 OSX: Quick&Dirty fix for waveform histogram issues
  src/libs/histogram.c
Labels: bugfix

#7515 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#7337 Introducing a tiled RCD demosaicer
  src/iop/demosaic.c
  src/iop/rcd_demosaic.c
Labels: feature: new, scope: image processing

#7509 dither: cleanup and speedup Floyd-Steinberg dithering
  src/iop/dither.c
Labels: scope: performance

#7513 interpolation: switch from M_PI to M_PI_F in lanczos to avoid DP FLOPs
  src/common/interpolation.c
Labels: scope: codebase, scope: performance

#7470 two "monochromes" bugs in fr.po
  po/fr.po
Labels: scope: translation

#7539 collect: don't retrieve NULL dates
  src/libs/collect.c
Labels: bugfix

#7538 Updated dutch translation
  po/nl.po
Labels: scope: translation

#7540 Fixing RCD demosaicer using -Ofast elsewhere
  src/iop/rcd_demosaic.c
Labels: bugfix

#7532 Fix history hash computation.
  src/common/history.c
Labels: bugfix, priority: medium, scope: codebase, scope: image processing, understood: clear

#7541 Update de.po
  po/de.po
Labels: scope: translation

#7545 Update it.po
  po/it.po
Labels: scope: translation
