Repository darktable-org/darktable, pull requests merged in 2020-11, with the labels that each got.

#6699 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6700 parallelize colorcorrection iop
  src/iop/colorcorrection.c
  src/tests/integration/0029-color-correction/color-correction.xmp
Labels: feature: redesign, scope: performance

#6701 parallelize borders (framing) iop
  src/iop/borders.c
  src/tests/integration/0030-framing/framing.xmp
Labels: feature: redesign, scope: performance

#6702 paralellize loop in drago global tonemap operator
  src/iop/globaltonemap.c
  src/tests/integration/0031-globaltonemap-drago/globaltonemap-drago.xmp
Labels: feature: redesign, scope: performance

#6703 watermark iop parallelization
  src/iop/watermark.c
  src/tests/integration/0032-watermark/watermark.xmp
Labels: feature: enhancement, scope: performance

#6687 ctrl+click iop reset button to apply auto-presets
  src/develop/imageop.c
  src/gui/presets.c
  src/gui/presets.h
Labels: feature: enhancement

#6673 Final part of init_gui/reload/update cleanup
  src/bauhaus/bauhaus.c
  src/develop/blend_gui.c
  src/develop/develop.c
  src/develop/imageop.c
  src/develop/imageop.h
  src/gui/accelerators.c
  src/iop/ashift.c
  src/iop/atrous.c
  src/iop/bilat.c
  src/iop/bilateral.cc
  src/iop/cacorrect.c
  src/iop/channelmixer.c
  src/iop/clahe.c
  src/iop/colisa.c
  src/iop/colorbalance.c
  src/iop/colorchecker.c
  src/iop/colorcorrection.c
  src/iop/colorin.c
  src/iop/colorize.c
  src/iop/colorout.c
  src/iop/colorreconstruction.c
  src/iop/colorzones.c
  src/iop/denoiseprofile.c
  src/iop/dither.c
  src/iop/exposure.c
  src/iop/filmicrgb.c
  src/iop/globaltonemap.c
  src/iop/graduatednd.c
  src/iop/highlights.c
  src/iop/invert.c
  src/iop/lens.cc
  src/iop/lowpass.c
  src/iop/lut3d.c
  src/iop/profile_gamma.c
  src/iop/rawdenoise.c
  src/iop/rawprepare.c
  src/iop/relight.c
  src/iop/retouch.c
  src/iop/rotatepixels.c
  src/iop/scalepixels.c
  src/iop/shadhi.c
  src/iop/sharpen.c
  src/iop/soften.c
  src/iop/splittoning.c
  src/iop/temperature.c
  src/iop/toneequal.c
  src/iop/tonemap.cc
  src/iop/velvia.c
  src/iop/vibrance.c
  src/iop/vignette.c
  src/views/darkroom.c
Labels: feature: enhancement, feature: redesign

#6613 Map: add locations feature. Locations are visible in geotag collections.
  po/POTFILES.in
  src/CMakeLists.txt
  src/common/collection.c
  src/common/database.c
  src/common/image.c
  src/common/map_locations.c
  src/common/map_locations.h
  src/common/tags.c
  src/common/tags.h
  src/control/signal.c
  src/control/signal.h
  src/gui/gtk.c
  src/gui/gtk.h
  src/libs/CMakeLists.txt
  src/libs/collect.c
  src/libs/copy_history.c
  src/libs/map_locations.c
  src/libs/tagging.c
  src/views/map.c
  src/views/view.c
  src/views/view.h
Labels: feature: enhancement, scope: DAM, scope: UI

#6721 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6718 guard call to gui_update against missing implementation
  src/develop/imageop.c
Labels: bugfix, priority: high

#6720 iop: reset parameters tooltip to reference Ctrl+click functionality
  src/develop/imageop.c
Labels: feature: enhancement

#6719 mask-manager: fix cleanup unused shapes
  src/develop/masks/masks.c
Labels: bugfix

#6726 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6670 Implement styles dialog when exporting style[s].
  src/libs/styles.c
Labels: feature: enhancement

#6603 [CI/CD] remove travis, add gh actions: windows and osx builds, build windows nightly, check if dt runs...
  .ci/Brewfile
  .ci/ci-script.sh
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .travis.yml
  tools/authors_h.sh
Labels: feature: redesign

#6730 German translation updates
  po/de.po
Labels: scope: translation

#6729 Fix space between widget and notebook
  data/themes/darktable.css
Labels: feature: enhancement, scope: UI

#6733 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6735 ppd corrected dragging distance in culling/preview mode
  src/dtgtk/culling.c
Labels: feature: enhancement

#6741 Add darktable.gui->ppd_thb and preview_downsampling correction to focus display.
  src/common/focus.h
Labels: bugfix, priority: high

#6743 fix colorbalance sliders unhiding
  src/iop/colorbalance.c
Labels: bugfix, scope: UI

#6744 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6751 German translation updates
  po/de.po
Labels: scope: translation

#6746 Remove `plugins/slideshow/high_quality` preferences
  data/darktableconfig.xml.in
  src/views/slideshow.c
Labels: feature: redesign

#6756 update toneeq documentation
  doc/usermanual/darkroom/modules/grading/toneequalizer.xml
Labels: scope: usermanual

#6757 Allow to hide/show the borders controls on the slideshow.
  src/control/control.h
  src/gui/gtk.c
  src/views/slideshow.c
Labels: bugfix

#6758 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6759 German translation updates
  po/de.po
Labels: scope: translation

#6761 Corrections to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6760 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6715 don't force square aspect on graph in tone equaliser
  data/darktableconfig.xml.in
  src/iop/toneequal.c
Labels: feature: enhancement

#6769 fix repetition of exported tag with $CATEGORYn(category) when several leaves
  src/common/tags.c
Labels: bugfix

#6747 map: add view all locations button
  src/common/database.c
  src/common/image.c
  src/common/map_locations.c
  src/common/map_locations.h
  src/control/signal.c
  src/control/signal.h
  src/libs/collect.c
  src/libs/copy_history.c
  src/libs/map_locations.c
  src/views/map.c
  src/views/view.c
  src/views/view.h
Labels: feature: enhancement

#6780 German translation updates
  po/de.po
Labels: scope: translation

#6775 thumbtable : rework filemanager exit
  src/dtgtk/thumbtable.c
  src/dtgtk/thumbtable.h
  src/views/lighttable.c
Labels: bugfix, difficulty: average, scope: UI

#6777 attempt to fix #6774
  src/common/iop_profile.c
  src/common/iop_profile.h
  src/iop/colorin.c
  src/iop/colorout.c
Labels: bugfix, difficulty: hard, priority: high

#6788 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6779 introspectise channelmixer rgb
  src/common/chromatic_adaptation.h
  src/common/illuminants.h
  src/develop/imageop_gui.c
  src/iop/channelmixerrgb.c
Labels: feature: redesign

#6792 Showing duplicates must be corrected for ppd_thb
  src/libs/duplicate.c
Labels: bugfix

#6795 common: Fix DT_FMA macro
  src/common/darktable.h
Labels: bugfix

#6793 channelmixerrgb: remember last selected notebook page
  data/darktableconfig.xml.in
  src/iop/channelmixerrgb.c
  src/iop/toneequal.c
Labels: feature: enhancement, scope: UI

#6794 tagging: fix completion issue
  src/libs/tagging.c
Labels: bugfix

#6796 German translation updates (channel mixer rgb)
  po/de.po
Labels: scope: translation

#6786 Update french translation
  po/fr.po
  src/iop/channelmixerrgb.c
Labels: scope: translation

#6800 channel mixer rgb: more significant tooltips
  src/iop/channelmixerrgb.c
Labels: feature: enhancement

#6799 fix Lua widget not displayed in import options dialog box
  src/libs/import.c
Labels: lua

#6742 Map: better group of images based on cluster calculation (dbscan)
  data/darktableconfig.xml.in
  src/libs/map_settings.c
  src/views/map.c
Labels: feature: enhancement

#6808 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6809 Corrections to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6811 highpass: fix unaligned-load SSE crash
  src/iop/highpass.c
Labels: bugfix

#6813 borders (framing): fix unaligned-load SSE crash
  src/iop/borders.c
Labels: bugfix, priority: high

#6785 refactor: merge duplicated code in liquify.c back into develop.c
  src/develop/develop.c
  src/develop/develop.h
  src/iop/liquify.c
  src/tests/integration/0036-liquify/liquify.xmp
Labels: scope: codebase

#6814 module order: purge cache one step below
  src/develop/imageop.c
Labels: bugfix, difficulty: average, priority: medium

#6816 Updated Lua section of RELEASE_NOTES
  RELEASE_NOTES.md
Labels: lua

#6818 Spanish translation update
  po/es.po
Labels: scope: translation

#6819 map: better response time for images grouping + fixes
  src/libs/map_settings.c
  src/views/map.c
Labels: bugfix

#6828 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6823 add a chroma adaptation workflow
  data/darktableconfig.xml.in
  src/develop/develop.c
  src/iop/channelmixerrgb.c
  src/iop/temperature.c
Labels: feature: enhancement, scope: UI, scope: color management, scope: image processing

#6832 do not ellipse short notebook labels
  src/gui/gtk.c
Labels: bugfix, feature: enhancement, priority: medium, scope: UI

#6829 connect histogram scroll to right exposure instance
  src/develop/develop.c
  src/develop/develop.h
  src/develop/imageop.c
  src/iop/exposure.c
Labels: bugfix, priority: high

#6838 Fix blending and module more menu buttons
  data/themes/darktable.css
Labels: feature: enhancement, scope: UI

#6844 Spanish translation update
  po/es.po
Labels: scope: translation

#6850 illuminants.h: letter missed
  src/common/illuminants.h
Labels: bugfix

#6851 channelmixerrgb.h: typo fixed
  src/iop/channelmixerrgb.c
Labels: bugfix

#6839 xmp: doesn't consider that 0 value means no value
  src/common/exif.cc
  src/common/image.c
Labels: bugfix, priority: medium, scope: DAM

#6853 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6804 fix format strings and remove unneeded commas in array definitions
  src/iop/tonecurve.c
  tools/basecurve/darktable-curve-tool.c
Labels: bugfix

#6846 German translation updates
  po/de.po
Labels: scope: translation

#6849 rework modules set and workflow
  src/libs/modulegroups.c
Labels: feature: redesign

#6852 Keep parametric mask settings on colorspace change
  src/develop/blend_gui.c
  src/develop/develop.c
  src/develop/develop.h
Labels: bugfix, feature: enhancement

#6837 color_picker_proxy: default to module colorspace if not set.
  src/gui/color_picker_proxy.c
Labels: bugfix

#6845 Hide the output parametric mask channels by default
  src/develop/blend.h
  src/develop/blend_gui.c
  src/develop/imageop.c
Labels: feature: enhancement

#6842 add new blending fields to history diff
  src/develop/blend.h
  src/develop/blend_gui.c
  src/libs/history.c
Labels: feature: enhancement

#6857 po/fix default presets
  src/develop/blend.c
  src/gui/presets.c
  src/gui/presets.h
  src/iop/atrous.c
  src/iop/basecurve.c
  src/iop/borders.c
  src/iop/channelmixer.c
  src/iop/channelmixerrgb.c
  src/iop/colorchecker.c
  src/iop/colorcorrection.c
  src/iop/colorzones.c
  src/iop/denoiseprofile.c
  src/iop/dither.c
  src/iop/exposure.c
  src/iop/filmic.c
  src/iop/flip.c
  src/iop/graduatednd.c
  src/iop/lowlight.c
  src/iop/lowpass.c
  src/iop/monochrome.c
  src/iop/negadoctor.c
  src/iop/profile_gamma.c
  src/iop/rawprepare.c
  src/iop/relight.c
  src/iop/rgbcurve.c
  src/iop/sharpen.c
  src/iop/splittoning.c
  src/iop/tonecurve.c
  src/iop/toneequal.c
  src/iop/vignette.c
Labels: bugfix, priority: medium, scope: UI

#6859 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6834 map: scrolling over an images group scrolls the images of the group
  data/themes/darktable.css
  src/views/map.c
Labels: feature: enhancement

#6863 German translation updates
  po/de.po
Labels: scope: translation

#6862 fix buffer overflow
  src/libs/export.c
Labels: bugfix

#6867 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6869 map: fix drag and drop from and to filmstrip
  src/dtgtk/thumbnail.c
  src/dtgtk/thumbtable.c
Labels: bugfix, priority: medium

#6874 Spanish translation update
  po/es.po
Labels: scope: translation

#6870 update the cn translation
  po/zh_CN.po
Labels: scope: translation

#6873 po/fix gradient
  src/develop/masks/gradient.c
Labels: bugfix

#6877 German translation updates
  po/de.po
Labels: scope: translation

#6836 channelmixerrgb: display an error message when temperature.c does not…
  src/develop/develop.c
  src/develop/develop.h
  src/develop/imageop.c
  src/develop/imageop.h
  src/iop/channelmixerrgb.c
  src/iop/temperature.c
  src/libs/history.c
Labels: feature: enhancement

#6887 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6890 Enable default icon for color calibration module
  data/themes/darktable-icons.css
Labels: bugfix

#6889 modulegroups: set current group when entering darkroom
  src/libs/modulegroups.c
Labels: bugfix

#6892 modulegroups: fix regression caused by #6889
  src/libs/modulegroups.c
Labels: bugfix

#6895 export: add tooltip for intent.
  src/libs/export.c
Labels: feature: enhancement

#6897 [Issue #6655] Number of images in map module
  src/libs/tools/hinter.c
Labels: feature: enhancement

#6909 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6135 histogram: draw waveform in display profile
  data/themes/darktable.css
  src/bauhaus/bauhaus.c
  src/bauhaus/bauhaus.h
  src/iop/rgbcurve.c
  src/iop/rgblevels.c
  src/libs/histogram.c
  src/libs/lib.h
Labels: difficulty: average, feature: enhancement, scope: UI, scope: performance

#6910 Mask display is not always updated when defining parametric masks with the color picker
  src/develop/blend.c
  src/develop/blend.h
  src/develop/pixelpipe_hb.c
Labels: bugfix, priority: high

#6915 Soft deprecated
  data/themes/darktable.css
  src/develop/imageop.c
  src/develop/imageop.h
  src/iop/channelmixer.c
  src/iop/clahe.c
  src/iop/colortransfer.c
  src/iop/equalizer.c
  src/iop/filmic.c
  src/iop/globaltonemap.c
  src/iop/invert.c
  src/iop/iop_api.h
  src/iop/relight.c
  src/iop/tonemap.cc
  src/iop/zonesystem.c
  src/libs/modulegroups.c
Labels: difficulty: average, feature: enhancement, scope: UI

#6925 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6928 soft deprecated : fix crash + visibility
  src/develop/imageop.c
  src/libs/modulegroups.c
Labels: bugfix, difficulty: trivial, priority: high

#6927 fix disappearing dpi box in export
  src/libs/export.c
Labels: bugfix

#6929 colortransfert : redirect to color mapping
  src/iop/colortransfer.c
Labels: feature: enhancement

#6922 histogram: brighten primaries
  src/libs/histogram.c
Labels: feature: enhancement

#6931 Update usermanual to document blending changes
  doc/usermanual/darkroom/concepts/blend_operators.xml
  doc/usermanual/darkroom/concepts/blending.xml
  doc/usermanual/darkroom/concepts/parametric_masks.xml
Labels: scope: usermanual

#6933 Improve deprecated CSS
  data/themes/darktable.css
Labels: feature: enhancement

#6934 Update french translation
  po/fr.po
  src/iop/graduatednd.c
  src/libs/modulegroups.c
Labels: scope: translation

#6932 Map: doc update + fix regression on location drag icon
  doc/usermanual/map/images/map_locations.png
  doc/usermanual/map/map.xml
  doc/usermanual/map/panels/locations.xml
  doc/usermanual/map/panels/map_settings.xml
  doc/usermanual/map/panels/panels.xml
  src/views/map.c
Labels: bugfix, scope: usermanual

#5762 filmic v4: add OpenCL kernel
  data/kernels/CMakeLists.txt
  data/kernels/common.h
  data/kernels/filmic.cl
  data/kernels/noise_generator.h
  src/common/focus_peaking.h
  src/develop/imageop_math.h
  src/develop/noise_generator.h
  src/develop/openmp_maths.h
  src/iop/filmicrgb.c
  src/iop/negadoctor.c
  src/views/tethering.c
Labels: no-pr-activity, scope: image processing, scope: performance

#6942 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6943 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6941 imageop: prevent module being re-enabled
  src/develop/imageop.c
Labels: bugfix, priority: high, scope: codebase, understood: unclear

#6944 channelmixerrgb: when creating new instances avoid two CAT.
  src/iop/channelmixerrgb.c
Labels: bugfix, priority: high

#6947 src:common: Add missing string.h for strerror() in grealpath.h
  src/common/grealpath.h
Labels: bugfix

#6916 Correct channel display of JzCzhz hue
  src/common/colorspaces_inline_conversions.h
  src/iop/gamma.c
Labels: bugfix

#6948 modulegroup search options refactor
  data/darktableconfig.xml.in
  src/gui/gtk.c
  src/libs/modulegroups.c
Labels: bugfix, difficulty: average, scope: UI

#6954 Spanish Translation Update
  po/es.po
Labels: scope: translation

#6959 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6961 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6957 suppress nan/inf history diffs
  src/libs/history.c
Labels: bugfix

#6963 temperature: fix as-shot setting, fixes #6926
  src/iop/temperature.c
Labels: bugfix, priority: high

#6967 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6970 modulegroup fix : quick way to add modules
  src/libs/modulegroups.c
Labels: bugfix, scope: UI

#6977 modulegroups : no right-click for deprecated group
  src/libs/modulegroups.c
Labels: bugfix, difficulty: trivial, scope: UI

#6973 culling : ensure we don't loose focus
  src/dtgtk/culling.c
Labels: bugfix, difficulty: average, scope: UI

#6976 lut3d: fix dependencies with GMIC 9.0-3 on windows
  cmake/modules/FindGMIC.cmake
  cmake/windows-macros.cmake
  packaging/windows/BUILD.txt
Labels: bugfix, scope: OS support

#6982 Updates to pt_BR
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6981 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6985 map loc: change toggle button to check box
  src/libs/map_locations.c
Labels: bugfix, scope: UI

#6989 Improve modulegroups GUI
  data/themes/darktable.css
Labels: scope: UI

#6999 draw histogram widget using CSS colors in display colorspace
  data/themes/darktable.css
  src/bauhaus/bauhaus.c
  src/bauhaus/bauhaus.h
  src/iop/rgbcurve.c
  src/iop/rgblevels.c
  src/libs/histogram.c
  src/libs/lib.h
Labels: bugfix, scope: UI

#7005 docs : update modulegroups
  doc/usermanual/darkroom/panels/modulegroups.xml
  doc/usermanual/preferences/darkroom_options.xml
Labels: scope: usermanual

#7010 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#7016 Modulegroups : remove deprecated modules from built-in presets
  src/libs/modulegroups.c
Labels: bugfix, difficulty: trivial, scope: UI

#7015 Enable always-on module when history disabled it
  src/develop/pixelpipe_hb.c
Labels: bugfix, priority: high, understood: incomplete

#7007 fix crash when right border of frame completely fills viewport
  src/develop/pixelpipe_hb.c
Labels: bugfix, priority: medium, wip

#7009 [performance] rewrite borders.c CPU codepath for speed
  src/iop/borders.c
Labels: bugfix

#7003 libs preset : reorder like iop
  data/darktableconfig.xml.in
  src/gui/presets.c
  src/libs/lib.c
Labels: difficulty: trivial, incomplete, scope: UI

#7013 gui_cleanup before destroying multi-instance widget
  src/views/darkroom.c
Labels: bugfix

#7008 Update lua code example
  doc/usermanual/lua/lua.xml
Labels: bugfix, lua

#7001 bauhaus: fix background & borders
  data/themes/darktable.css
  src/bauhaus/bauhaus.c
Labels: bugfix

#7021 po/pref sections
  data/darktableconfig.dtd
  data/darktableconfig.xml.in
  src/gui/preferences.c
  tools/generate_prefs.xsl
Labels: bugfix, feature: enhancement, scope: UI

#7024 modules : use deprecated message as tooltip if needed
  src/develop/imageop.c
Labels: bugfix

#7033 darktableconfig: use consistent terminology
  data/darktableconfig.xml.in
Labels: feature: enhancement, scope: UI

#7032 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#7034 darktableconfig: fix minor grammar error
  data/darktableconfig.xml.in
Labels: scope: UI

#7023 modules : last descriptions
  src/iop/bilateral.cc
  src/iop/colorize.c
  src/iop/flip.c
  src/iop/levels.c
  src/iop/monochrome.c
  src/iop/rawprepare.c
  src/iop/rgbcurve.c
  src/iop/rgblevels.c
  src/iop/rotatepixels.c
  src/iop/scalepixels.c
  src/iop/shadhi.c
  src/iop/sharpen.c
  src/iop/soften.c
  src/iop/splittoning.c
  src/iop/tonecurve.c
  src/iop/velvia.c
  src/iop/vibrance.c
Labels: difficulty: average, scope: UI, wip

#7046 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#7038 imageop: prevent always on/off modules being enabled/disabled
  src/develop/imageop.c
Labels: bugfix, priority: high

#7049 fix memory leak in set_label
  src/bauhaus/bauhaus.c
Labels: bugfix

#7048 [extract_wb] deal with possible sony half-steps
  tools/extract_wb.py
Labels: bugfix

#7052 pref : remove unused "show text sidecar"
  data/darktableconfig.xml.in
Labels: difficulty: trivial, scope: UI

#7057 po/iop tooltips
  src/develop/imageop.c
  src/iop/bilateral.cc
  src/iop/colorchecker.c
  src/iop/flip.c
  src/iop/levels.c
  src/iop/monochrome.c
  src/iop/profile_gamma.c
  src/iop/rgbcurve.c
  src/iop/rgblevels.c
  src/iop/sharpen.c
  src/iop/soften.c
  src/iop/tonecurve.c
  src/iop/velvia.c
Labels: priority: medium, scope: UI

#7064 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation
