Repository darktable-org/darktable, pull requests merged in 2020-04, with the labels that each got.

#4591 Update german manual translations
  doc/usermanual/po/de.po
Labels: scope: usermanual

#4581 add dynamic accelerators to comboboxes
  src/gui/accelerators.c
  src/views/darkroom.c
Labels: difficulty: average, feature: enhancement, scope: codebase

#4592 add Exif.Photo.ExposureBiasValue to variables and image info
  src/common/database.c
  src/common/exif.cc
  src/common/image.c
  src/common/image.h
  src/common/image_cache.c
  src/common/variables.c
  src/libs/metadata_view.c
  src/lua/image.c
Labels: difficulty: average, feature: enhancement, scope: codebase

#4598 resolve issues with gradient mask rotation
  src/develop/masks/gradient.c
Labels: bugfix

#4559 metadata - import configuration
  data/themes/darktable.css
  src/common/collection.c
  src/common/exif.cc
  src/common/exif.h
  src/common/image.c
  src/common/imageio_exr.cc
  src/common/imageio_rawspeed.cc
  src/common/metadata.c
  src/common/metadata.h
  src/develop/lightroom.c
  src/libs/collect.c
  src/libs/export_metadata.c
  src/libs/import.c
  src/libs/metadata.c
  src/libs/metadata_view.c
Labels: difficulty: average, feature: redesign, scope: DAM

#4602 tagging update
  src/common/exif.cc
  src/common/image.c
  src/common/image.h
  src/common/tags.c
  src/common/tags.h
  src/libs/tagging.c
Labels: bugfix

#4600 keyboard shortcuts to show/hide lib modules
  src/libs/lib.c
Labels: difficulty: trivial, feature: enhancement, scope: codebase

#4603 Polish translation update
  po/pl.po
Labels: scope: translation

#4605 $(CATEGORYn(category)) - accepts 10 levels instead of 4 [0-9]
  doc/usermanual/lighttable/panels/export.xml
  src/common/variables.c
Labels: feature: enhancement

#4618 wire metadata on dt_view_get_images_to_act_on()
  src/common/metadata.c
  src/common/metadata.h
  src/libs/image.c
  src/libs/metadata.c
Labels: scope: DAM, scope: codebase

#4575 Powerfull extract_wb for superior wb presets extraction and finetuning
  CMakeLists.txt
  doc/README.md
  tools/CMakeLists.txt
  tools/extract_wb
  tools/extract_wb_from_images.sh
Labels: difficulty: average, feature: enhancement

#4609 Updated Nikon Coolpix P1000 WB presets
  src/external/wb_presets.c
Labels: scope: camera support

#4612 configurable overlay line colors
  src/develop/develop.c
  src/develop/develop.h
  src/develop/masks/brush.c
  src/develop/masks/circle.c
  src/develop/masks/ellipse.c
  src/develop/masks/gradient.c
  src/develop/masks/path.c
  src/dtgtk/paint.c
  src/dtgtk/paint.h
  src/gui/draw.h
  src/iop/clipping.c
  src/iop/graduatednd.c
  src/iop/vignette.c
  src/views/darkroom.c
Labels: difficulty: average, feature: enhancement, scope: UI

#4621 keyboard shortcut: toggle last snapshot
  src/libs/snapshots.c
Labels: feature: enhancement, scope: UI

#4613 Write correct sidecar including history after applying presets
  src/common/exif.cc
  src/develop/develop.c
Labels: bugfix, difficulty: hard, scope: codebase

#4627 guides: make grid use selected overlay color
  src/gui/guides.c
Labels: bugfix

#4629 Updated Italian translation
  po/it.po
Labels: scope: translation

#4631 collect fix
  src/libs/collect.c
Labels: scope: DAM, scope: codebase

#4632 WB Presets for Pentax K-1 firmware ver. 1.52
  src/external/wb_presets.c
Labels: scope: camera support

#4636 Update Sony ILCE-7 WB presets
  src/external/wb_presets.c
Labels: scope: camera support

#4641 Finetuned WB Presets for Nikon D850
  src/external/wb_presets.c
Labels: scope: camera support

#4642 Finetuned WB Presets for Nikon D750
  src/external/wb_presets.c
Labels: scope: camera support

#4639 WB Presets for Samsung NX1 firmware ver. 1.41
  src/external/wb_presets.c
Labels: scope: camera support

#4649 fix $(EXIF_EXPOSURE) issue on watermark
  src/iop/watermark.c
Labels: bugfix

#4640 Code cleanup _tree_query_tooltip in libs/masks.c
  src/libs/masks.c
Labels: bugfix

#4648 fix history hash on discard, copy and compress history actions
  src/common/history.c
Labels: bugfix

#4654 Allowing larger vignette scales
  src/iop/vignette.c
Labels: difficulty: trivial, feature: enhancement, scope: image processing

#4647 show lib module shortcut: respect lighttable expand pref
  src/libs/lib.c
Labels: bugfix, difficulty: average

#4657 fix lut 3d cube files
  src/iop/lut3d.c
Labels: bugfix

#4658 Finetuned WB presets for Pentax K-S2
  src/external/wb_presets.c
Labels: scope: camera support

#4665 Add hex encoded rgb to colorpickers tooltips
  src/libs/colorpicker.c
Labels: feature: enhancement, scope: UI

#4660 set thumbnails margins via css
  data/themes/darktable.css
  src/dtgtk/thumbnail.c
  src/dtgtk/thumbnail.h
Labels: difficulty: average, feature: enhancement, scope: UI

#4652 Finetuned WB presets for various Panasonic bodies
  src/external/wb_presets.c
Labels: scope: camera support

#4676 Improve white balance module now (fixing #3521)
  src/iop/temperature.c
Labels: feature: enhancement

#4683 Updates to pt_BR translation
  po/pt_BR.po
Labels: scope: translation

#4678 Only show masks in darkrooms expose for valid modules. Fix #4668
  src/views/darkroom.c
Labels: bugfix

#4684 po/snapsep
  src/bauhaus/bauhaus.c
  src/libs/snapshots.c
Labels: difficulty: average, feature: enhancement, scope: UI

#4694 Updates to pt_BR translation
  po/pt_BR.po
Labels: scope: translation

#4697 snapshot: fix rotation click action
  src/libs/snapshots.c
Labels: bugfix

#4699 Polish translation update
  po/pl.po
Labels: scope: translation

#4705 Increase the falloff range in vignetting module
  src/iop/vignette.c
Labels: difficulty: trivial, feature: enhancement, scope: image processing

#4698 Finetuned WB Presets for Canon 750D
  src/external/wb_presets.c
Labels: feature: enhancement, scope: camera support

#4706 Polish translation update
  po/pl.po
Labels: scope: translation

#4704 Speed & clean up purging script
  tools/purge_non_existing_images.sh
Labels: feature: redesign, scope: performance

#4709 crop and rotate: restrict movement with modifiers
  src/iop/clipping.c
Labels: difficulty: trivial, feature: enhancement

#4712 Unify timestamp
  src/common/database.c
  src/common/film.c
Labels: difficulty: average, scope: codebase

#4708 thumbs : fix calculation of image margin if specified separatly
  src/dtgtk/thumbnail.c
Labels: bugfix, difficulty: trivial, scope: UI

#4710 styles: add append/overwrite mode
  src/common/styles.c
  src/common/styles.h
  src/libs/styles.c
Labels: difficulty: trivial, feature: enhancement

#4719 Tag fix
  src/common/colorlabels.c
  src/common/colorlabels.h
  src/common/image.c
  src/common/image.h
  src/common/metadata.c
  src/common/metadata.h
  src/common/ratings.c
  src/common/ratings.h
  src/common/tags.c
  src/common/tags.h
  src/dtgtk/thumbtable.c
  src/libs/image.c
  src/libs/metadata.c
  src/libs/tools/ratings.c
Labels: bugfix

#4721 module search: lose focus when clicking module header
  src/develop/imageop.c
Labels: bugfix

#4715 Fine-graded finetuned WB Presets for Nikon D7500
  src/external/wb_presets.c
Labels: scope: camera support

#4720 finetuned WB presets for Nikon D7000
  src/external/wb_presets.c
Labels: scope: camera support

#4724 update redefined color matrix for Nikon Z6
  src/external/adobe_coeff.c
Labels: scope: camera support

#4707 darkroom: keyboard shortcut to show/hide drawn masks
  src/views/darkroom.c
Labels: difficulty: trivial, feature: enhancement, scope: UI

#4725 Updates to pt_BR translation
  po/pt_BR.po
Labels: scope: translation

#4729 retouch: various fixes and enhancements
  src/iop/retouch.c
Labels: difficulty: average, feature: enhancement, scope: codebase

#4732 Spanish translation update
  po/es.po
Labels: scope: translation

#4735 Spanish translation update
  po/es.po
Labels: scope: translation

#4736 spot removal: various enhancements
  src/develop/develop.c
  src/develop/develop.h
  src/iop/spots.c
Labels: bugfix, feature: enhancement

#4733 dynamic shortcuts: allow shift modifier
  src/gui/accelerators.c
Labels: bugfix

#4738 retouch: fix button toggle
  src/iop/retouch.c
Labels: bugfix

#4737 thumb overlays enhancements
  data/darktableconfig.xml.in
  data/themes/darktable.css
  src/dtgtk/thumbnail.c
  src/dtgtk/thumbnail.h
  src/dtgtk/thumbtable.c
  src/dtgtk/thumbtable.h
  src/libs/duplicate.c
  src/libs/tools/darktable.c
  src/libs/tools/global_toolbox.c
Labels: difficulty: average, feature: enhancement, scope: UI

#4742 thumb overlays : add mixed mode
  data/themes/darktable.css
  src/dtgtk/thumbnail.c
  src/dtgtk/thumbnail.h
  src/dtgtk/thumbtable.c
  src/libs/tools/global_toolbox.c
Labels: difficulty: average, feature: enhancement, scope: UI

#4744 Spanish translation update
  po/es.po
Labels: scope: translation

#4745 Correct reload_defaults in colorin module fixing #4106
  src/iop/colorin.c
Labels: bugfix, priority: high

#4477 new metadata field "version name"
  src/common/exif.cc
  src/common/metadata.c
  src/common/metadata.h
  src/common/variables.c
  src/gui/gtkentry.c
  src/libs/duplicate.c
  src/libs/metadata.c
Labels: feature: enhancement, scope: DAM

#4756 Fix indexing out of bounds in Chromatic Aberration module.
  src/iop/cacorrect.c
Labels: bugfix

#4740 introduce universal toast message for sliders and comboboxes
  src/gui/accelerators.c
  src/gui/accelerators.h
  src/views/darkroom.c
Labels: difficulty: average, feature: enhancement, scope: UI

#4765 Spanish translation update
  po/es.po
Labels: scope: translation

#4763 small fixes and enhancements to new overlays
  data/darktableconfig.xml.in
  data/themes/darktable.css
  src/common/variables.c
  src/dtgtk/thumbnail.c
  src/dtgtk/thumbnail.h
  src/dtgtk/thumbtable.c
  src/libs/tools/global_toolbox.c
Labels: bugfix, difficulty: trivial, feature: enhancement, scope: UI

#4727 Finetuned WB presets for Olympus E-M5 Mark II
  src/external/wb_presets.c
Labels: scope: camera support

#4768 RGB parade as histogram alternative
  data/darktableconfig.xml.in
  src/develop/develop.c
  src/develop/develop.h
  src/develop/pixelpipe_hb.c
  src/libs/histogram.c
Labels: difficulty: average, feature: enhancement

#4774 Spanish translation update
  po/es.po
Labels: scope: translation

#4778 metadata import fix
  src/common/metadata.c
  src/libs/import.c
Labels: bugfix

#4762 CSS rework from new overlays modes and some cleaning
  data/themes/darktable-elegant-dark.css
  data/themes/darktable-elegant-grey.css
  data/themes/darktable.css
Labels: bugfix, feature: enhancement, scope: UI

#4781 fix reject toggle issue
  src/common/ratings.c
Labels: bugfix

#4787 histogram fix - dt_free_align for windows
  src/libs/histogram.c
Labels: bugfix, priority: high

#4790 Use dt_collection_get_query_no_group() to get selected images
  src/common/collection.c
Labels: bugfix

#4670 easier management of user CSS tweaks
  src/gui/gtk.c
  src/gui/preferences.c
Labels: difficulty: trivial, feature: enhancement, scope: UI

#4793 metadata fix - import also when hidden
  src/common/metadata.c
Labels: bugfix

#4789 Local laplacian speedup (fixes #4788)
  src/common/locallaplacian.c
Labels: scope: performance

#4779 po/reject toggle
  src/common/exif.cc
  src/common/image.h
  src/common/ratings.c
  src/common/ratings.h
  src/dtgtk/thumbnail.c
  src/views/view.c
  src/views/view.h
Labels: bugfix

#4801 Spanish translation update
  po/es.po
Labels: scope: translation

#4803 thumbs : ensure mouse_over_id on double-click
  src/dtgtk/thumbnail.c
Labels: bugfix

#4617 removes unnecessarily adding the source to include_directories:
  src/CMakeLists.txt
  src/cli/CMakeLists.txt
  src/cltest/CMakeLists.txt
  src/generate-cache/CMakeLists.txt
  src/imageio/format/CMakeLists.txt
  src/imageio/storage/CMakeLists.txt
  src/iop/CMakeLists.txt
  src/libs/CMakeLists.txt
  src/tests/CMakeLists.txt
  src/views/CMakeLists.txt
Labels: feature: redesign, scope: codebase

#4807 Updates to pt_BR manual
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#4775 Optimization of Denoise (bilateral filter) iop
  src/iop/Permutohedral.h
  src/iop/bilateral.cc
Labels: bugfix, difficulty: hard, feature: enhancement, scope: performance

#4817 Polish translation update
  po/pl.po
Labels: scope: translation

#4819 Update readme file
  README.md
Labels: feature: enhancement

#4747 preferences: rework
  data/darktableconfig.dtd
  data/darktableconfig.xml.in
  data/themes/darktable.css
  src/dtgtk/thumbtable.c
  src/gui/preferences.c
  src/views/darkroom.c
  tools/generate_prefs.xsl
Labels: difficulty: average, feature: redesign, scope: UI, wip

#4809 Locallaplacian speedup 2
  src/common/locallaplacian.c
Labels: scope: performance

#4671 Powerfull extract wb v2 + python version
  tools/extract_wb
  tools/extract_wb.py
Labels: difficulty: average, feature: enhancement, scope: camera support

#4825 preferences: amend buttons on header bar
  src/gui/preferences.c
Labels: feature: enhancement

#4324 Add four new timestamps columns in library.db
  src/common/database.c
  src/common/exif.cc
  src/common/history.c
  src/common/image.c
  src/common/image.h
  src/common/image_cache.c
  src/common/image_cache.h
  src/common/styles.c
  src/control/jobs/control_jobs.c
  src/develop/develop.c
  src/libs/metadata_view.c
  src/libs/print_settings.c
Labels: feature: enhancement

#4828 tag fix - improvement
  src/common/tags.c
  src/common/tags.h
  src/libs/tagging.c
Labels: difficulty: average, feature: enhancement, scope: DAM

#4831 Fix the filters support for rejected images.
  src/common/collection.c
  src/common/collection.h
  src/libs/tools/filter.c
Labels: bugfix, scope: DAM

#4833 fix export private tag
  src/common/tags.c
  src/common/tags.h
Labels: bugfix

#4835 imageio: avif: Add support for libavif >= 0.7.0
  src/imageio/format/avif.c
Labels: difficulty: trivial, feature: enhancement

#4844 lighttable : ensure redraw after empty window
  src/dtgtk/thumbtable.c
Labels: bugfix, scope: UI

#4852 Update pt_BR translation and manual
  doc/usermanual/po/pt_BR.po
  po/pt_BR.po
Labels: scope: translation, scope: usermanual

#4851 preferences: remove header bar and buttons
  src/gui/preferences.c
  tools/generate_prefs.xsl
Labels: feature: enhancement

#4782 Fix overlays icons size for HiDPI Windows 10
  src/dtgtk/button.c
  src/dtgtk/paint.c
  src/dtgtk/togglebutton.c
  src/libs/metadata.c
  src/libs/tools/global_toolbox.c
Labels: bugfix, scope: UI

#4856 Fix rating stars and group icon and fix preferences
  data/themes/darktable-elegant-grey.css
  data/themes/darktable.css
Labels: bugfix, scope: UI

#4802 group fix - mirror images group changes to thumbnails
  src/common/grouping.c
  src/control/signal.c
  src/control/signal.h
  src/dtgtk/thumbtable.c
  src/dtgtk/thumbtable.h
Labels: bugfix

#4859 Updates to pt_BR
  doc/usermanual/po/pt_BR.po
  po/pt_BR.po
Labels: scope: translation, scope: usermanual

#4846 Use new slider_set_soft_range instead of confusing enable_soft_boundaries
  src/bauhaus/bauhaus.c
  src/bauhaus/bauhaus.h
  src/iop/filmicrgb.c
Labels: feature: enhancement, scope: UI, scope: codebase

#4845 crop and rotate : allow float/real cropping format ratios at input
  src/iop/clipping.c
Labels: feature: enhancement, scope: codebase

#4863 fix file extension label in thumbnails
  src/dtgtk/thumbnail.c
Labels: bugfix

#4866 Spanish translation update
  po/es.po
Labels: scope: translation

#4858 Improve dblock err msg
  src/common/collection.c
  src/common/database.c
Labels: feature: enhancement

#4862 overlays: show toast message when cycling colors
  src/views/darkroom.c
Labels: feature: enhancement
