Repository darktable-org/darktable, pull requests merged in 2020-03, with the labels that each got.

#4404 avoid variable length array syntax
  src/iop/colormapping.c
  src/iop/colortransfer.c
Labels: controversial

#4414 Spanish user manual update
  doc/usermanual/po/es.po
Labels: scope: translation

#4416 Simple padding fix on export module
  data/themes/darktable.css
Labels: scope: UI

#4415 tagging fixes
  src/libs/tagging.c
Labels: bugfix, difficulty: average, feature: enhancement, scope: DAM

#4421 polish translation update
  po/pl.po
Labels: scope: translation

#4422 lut 3d cube file fix
  src/iop/lut3d.c
Labels: bugfix

#4426 history_hash fix
  src/common/history.c
Labels: bugfix

#4379 Add db maintenance options, change wording and add maintenance debug messages for better maintenance UX
  data/darktableconfig.xml.in
  src/common/database.c
Labels: feature: enhancement, scope: codebase

#4410 add Canon EOS 77D WB Presets
  src/external/wb_presets.c
Labels: scope: camera support

#4428 Sqlite version required >= 3.15
  src/CMakeLists.txt
  src/common/history.c
Labels: bugfix, difficulty: trivial, feature: enhancement, priority: medium, scope: DAM

#4430 bugfix: tone equalizer with masking
  src/iop/toneequal.c
Labels: bugfix, difficulty: trivial, priority: medium, understood: clear

#4431 Fixing Colorpicker ranges Issue #3353
  src/views/darkroom.c
Labels: bugfix

#4423 negadoctor : inital commit
  data/kernels/negadoctor.cl
  data/kernels/programs.conf
  src/common/iop_order.c
  src/iop/CMakeLists.txt
  src/iop/negadoctor.c
Labels: difficulty: trivial, feature: new, scope: image processing

#4436 Prohibit pollution of darkroom borders
  src/views/darkroom.c
Labels: bugfix

#4439 Fix issue on focus peaking in culling mode #4156
  src/views/view.c
Labels: bugfix

#4447 Fix: Missing legacy_params in Basic Adjustment module
  src/iop/basicadj.c
Labels: bugfix

#4444 not so simple padding fix around spinbuttons
  data/themes/darktable.css
  src/libs/export.c
Labels: bugfix, difficulty: average, feature: enhancement

#4453 Spanish translation update
  po/es.po
Labels: scope: translation

#4460 Polish translation update
  po/pl.po
Labels: scope: translation

#4457 conditionally compile `knight.c` via `USE_GAME` option. fixes #4381
  DefineOptions.cmake
  build.sh
  src/CMakeLists.txt
  src/common/darktable.c
  src/control/control.c
  src/views/CMakeLists.txt
Labels: bugfix

#4465 Spanish translation update
  po/es.po
Labels: scope: translation

#4464 shift-click to rename iop module
  src/develop/imageop.c
Labels: feature: enhancement, scope: UI, understood: clear

#4472 Add traditional Chinese (Taiwan) translation
  po/LINGUAS
  po/zh_TW.po
Labels: scope: translation

#4470 Only show forms and color picker when module is enabled
  src/views/darkroom.c
Labels: bugfix

#4448 darkroom, reset mipmap & save xmp only if image has changed
  src/common/database.c
  src/common/history.c
  src/common/history.h
  src/common/image.c
  src/generate-cache/main.c
  src/views/darkroom.c
Labels: difficulty: average, feature: enhancement, scope: codebase

#4483 watermark - GLib-ERROR fix
  src/iop/watermark.c
Labels: bugfix

#4488 thumb : fix crash if zoom or scroll with empty list
  src/dtgtk/thumbtable.c
Labels: bugfix

#4491 open right folder after import
  src/views/lighttable.c
Labels: bugfix

#4494 import : ensure we refresh all at the end
  src/common/collection.c
Labels: bugfix

#4495 Fixing several colorpicker issues V2 (Issues #4471 #3631)
  src/views/darkroom.c
Labels: bugfix

#4458 Bugfix: Windows fails to delete version-zero xmp files
  src/common/image.c
  src/win/filepath.c
  src/win/filepath.h
Labels: bugfix

#4497 fix build error if map unavailable
  src/views/view.h
Labels: bug: pending

#4456 Add support for libavif >= 0.6.0
  src/CMakeLists.txt
  src/common/imageio_avif.c
  src/imageio/format/avif.c
Labels: difficulty: average, feature: enhancement, priority: low, scope: codebase

#4468 keyboard shortcuts to cycle through iop module combobox options
  src/bauhaus/bauhaus.c
  src/common/darktable.c
  src/common/imageio_module.c
  src/gui/accelerators.c
  src/gui/accelerators.h
  src/iop/ashift.c
  src/iop/basecurve.c
  src/iop/basicadj.c
  src/iop/bilat.c
  src/iop/borders.c
  src/iop/channelmixer.c
  src/iop/clipping.c
  src/iop/colorbalance.c
  src/iop/colorchecker.c
  src/iop/colorin.c
  src/iop/colorout.c
  src/iop/colorreconstruction.c
  src/iop/colorzones.c
  src/iop/defringe.c
  src/iop/demosaic.c
  src/iop/denoiseprofile.c
  src/iop/dither.c
  src/iop/exposure.c
  src/iop/filmicrgb.c
  src/iop/globaltonemap.c
  src/iop/highlights.c
  src/iop/lens.cc
  src/iop/levels.c
  src/iop/lut3d.c
  src/iop/profile_gamma.c
  src/iop/rgbcurve.c
  src/iop/rgblevels.c
  src/iop/shadhi.c
  src/iop/temperature.c
  src/iop/tonecurve.c
  src/iop/toneequal.c
  src/iop/watermark.c
Labels: difficulty: average, feature: enhancement, scope: UI

#4393 bugfix: remove extra duplicate version on import
  src/common/image.c
  src/common/image.h
Labels: bugfix

#4509 Fix invalid CMake syntax
  data/kernels/CMakeLists.txt
Labels: bugfix

#4513 Clear bg also in lighttables expose_empty note.
  src/views/lighttable.c
Labels: bugfix

#4510 Respect scrollbar option while in filestrip mode
  src/dtgtk/thumbtable.c
Labels: bugfix

#4499 metadata update
  src/common/exif.cc
  src/common/metadata.c
  src/common/metadata.h
  src/libs/import.c
  src/libs/metadata.c
  src/libs/metadata_view.c
Labels: feature: enhancement, priority: low, scope: DAM

#4505 Update CSS on @AlicVB lighttable rewrite
  data/themes/darktable-elegant-dark.css
  data/themes/darktable-elegant-grey.css
  data/themes/darktable.css
Labels: feature: enhancement

#4520 fix some glitchs after filemananger rewrite
  src/dtgtk/thumbtable.c
  src/libs/copy_history.c
Labels: bugfix

#4523 fix regression with importing single image
  src/common/image.c
Labels: bugfix

#4524 colorspace profiles sinc between linux and windows work environments
  src/common/colorspaces.c
Labels: bugfix, feature: enhancement, scope: color management

#4530 Fixing darkroom seizures, fixing #4286
  src/views/darkroom.c
Labels: bugfix

#4526 more top/bottom panels accels
  src/control/control.c
  src/control/control.h
  src/gui/gtk.c
  src/gui/gtk.h
  src/views/darkroom.c
  src/views/lighttable.c
  src/views/map.c
  src/views/print.c
  src/views/tethering.c
Labels: feature: enhancement

#4522 thumb : add configurable tooltip
  data/darktableconfig.xml.in
  src/common/usermanual_url.c
  src/dtgtk/thumbnail.c
  src/dtgtk/thumbtable.c
Labels: feature: enhancement

#4532 Color picker and masks must respect PPD. Fixes #4531
  src/views/darkroom.c
Labels: bugfix, scope: UI

#4536 Folder levels code redundancy
  data/darktableconfig.xml.in
  src/common/image.c
Labels: scope: codebase

#4548 fix Nikon P1000 wb presets
  src/external/wb_presets.c
Labels: bugfix

#4540 collection - generic metadata
  src/common/collection.c
  src/common/collection.h
  src/common/metadata.c
  src/common/metadata.h
  src/control/signal.c
  src/control/signal.h
  src/libs/collect.c
  src/libs/import.c
  src/libs/metadata.c
Labels: difficulty: average, feature: redesign, scope: DAM

#4547 thumb : rating shouldn't select image
  src/dtgtk/thumbnail.c
Labels: bugfix

#4550 zoomable : ensure we always see some image on screen
  src/dtgtk/thumbtable.c
Labels: bugfix, difficulty: average, scope: UI

#4557 Ensure a single definition is controling the max zoom level.
  src/dtgtk/thumbtable.c
  src/libs/tools/lighttable.c
  src/views/lighttable.c
  src/views/view.h
Labels: bugfix, difficulty: trivial, priority: medium, scope: UI

#4561 Recent sort
  data/darktableconfig.xml.in
  src/libs/collect.c
Labels: feature: enhancement

#4571 bugfix: prevent extra duplicate image on import
  src/common/image.c
  src/common/image.h
Labels: bugfix

#4580 thumb : fix missing variables.h include
  src/dtgtk/thumbnail.c
Labels: bugfix, difficulty: trivial

#4565 Allow more than 500 images for timelapse
  src/libs/camera.c
Labels: difficulty: trivial, feature: enhancement

#4585 bugfix - reimport image with xmp
  src/common/image.c
Labels: bugfix

#4579 Improve UI for hdr and monochrome images
  src/common/exif.cc
  src/common/imageio.c
  src/common/imageio.h
  src/common/imageio_rawspeed.cc
  src/dtgtk/thumbnail.c
  src/dtgtk/thumbnail.h
  src/views/view.c
  src/views/view.h
Labels: difficulty: trivial, feature: enhancement, priority: low, scope: UI, understood: clear

#4408 Use #!/usr/bin/env bash shebang in script rather than #!/bin/bash
  tools/create_version_c.sh
  tools/get_git_version_string.sh
  tools/get_last_commit_year.sh
  tools/makeman.sh
  tools/parse_version_c.sh
Labels: feature: enhancement, wip

#4517 bugfix: set/lose focus when expanding/collapsing modules
  src/develop/imageop.c
Labels: bugfix

#4284 doc/manual: update section about module order
  doc/usermanual/darkroom/concepts/pixelpipe.xml
Labels: no-pr-activity, scope: usermanual
