Repository darktable-org/darktable, pull requests merged in 2020-08, with the labels that each got.

#5851 Update de.po
  po/de.po
Labels: scope: translation

#5849 Add Nikon Z 50 white balance presets (fine)
  src/external/wb_presets.c
Labels: scope: camera support

#5846 demosaicing option: changing outdated tooltip
  data/darktableconfig.xml.in
Labels: feature: enhancement

#5828 improve imported metadata tooltip
  src/gui/import_metadata.c
Labels: feature: enhancement, scope: DAM

#5859 Updating pt_BR translation
  po/pt_BR.po
Labels: scope: translation

#5865 Spanish translation update
  po/es.po
Labels: scope: translation

#5857 Fix darktable open single image hang
  data/luarc
Labels: bugfix, lua

#5861 lighttable: don't change layout when returning from the darkroom
  src/dtgtk/thumbtable.c
Labels: bugfix, feature: enhancement

#5860 lighttable: fix arrow navigation in file manager view
  src/dtgtk/thumbtable.c
Labels: bugfix

#5867 Update to pt_BR translation
  po/pt_BR.po
Labels: scope: translation

#5889 Updated Czech translation
  po/cs.po
Labels: scope: translation

#5888 German translation updates
  po/de.po
Labels: scope: translation

#5882 Update Hungarian translation
  po/hu.po
Labels: scope: translation

#5881 imageio: Fix possible compile error in avif.c
  src/imageio/format/avif.c
Labels: bugfix

#5873 Spanish translation update
  po/es.po
Labels: scope: translation

#5902 Updated Afrikaans translation
  po/af.po
Labels: scope: translation

#5913 update de.po
  po/de.po
Labels: scope: translation

#5901 fix for "No timestamps are displayed on Windows" #5892
  src/libs/metadata_view.c
Labels: bugfix

#5869 crawler fix - update write timestamp in db if required but do not write back the xmp file
  src/common/history.c
  src/common/image_cache.c
  src/control/crawler.c
Labels: bugfix

#5879 fix read_xmp_timestamps() - write to cache instead of db
  src/common/exif.cc
Labels: bugfix

#5907 fix font not freed memory leak in show_pango_text
  src/bauhaus/bauhaus.c
Labels: bugfix

#5497 Retouch GUI rework
  src/dtgtk/paint.c
  src/dtgtk/paint.h
  src/iop/retouch.c
Labels: feature: redesign, no-pr-activity, scope: UI

#5890 revert ellipsize comboboxes and labels to the middle
  src/bauhaus/bauhaus.c
Labels: bugfix

#5910 Export grayscale tiff documentation
  doc/usermanual/lighttable/panels/export.xml
Labels: scope: usermanual

#5775 darkroom: better visual indication of drag-drop operations
  data/themes/darktable.css
  src/views/darkroom.c
Labels: feature: enhancement

#5785 Demosaic: Remove unused parameter on Amaze and delete some dead code.
  src/iop/amaze_demosaic_RT.cc
  src/iop/demosaic.c
Labels: scope: codebase

#5476 cmake: Silence some cmake 3.17 warnings
  cmake/modules/FindMacIntegration.cmake
  src/CMakeLists.txt
Labels: no-pr-activity, scope: codebase

#5691 Transition negadoctor, colorbalance and retouch to introspection framework
  src/develop/imageop_gui.c
  src/gui/gtk.h
  src/iop/colorbalance.c
  src/iop/negadoctor.c
  src/iop/retouch.c
Labels: feature: enhancement, no-pr-activity, scope: codebase

#5927 clipping: ensure orientation is not altered by use of freehand aspect
  src/iop/clipping.c
Labels: bugfix

#5925 introduce combo items ellipsis control
  src/bauhaus/bauhaus.c
  src/bauhaus/bauhaus.h
  src/iop/lut3d.c
Labels: feature: enhancement

#5634 Some cleaning up of blending gui
  src/bauhaus/bauhaus.c
  src/bauhaus/bauhaus.h
  src/develop/blend.h
  src/develop/blend_gui.c
  src/develop/imageop_gui.c
  src/develop/imageop_gui.h
  src/iop/demosaic.c
  src/iop/tonecurve.c
Labels: feature: enhancement

#5936 Updates to pt_BR manual
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#5944 Fix stack corruption when creating slider from long variable name
  src/develop/imageop_gui.c
Labels: bugfix

#5940 Restore separate saturation soft limits in color balance
  src/iop/colorbalance.c
Labels: bugfix

#5948 Update to pt_BR
  po/pt_BR.po
Labels: scope: translation

#5204 Wavelets denoising speedup
  src/iop/denoiseprofile.c
Labels: no-pr-activity, scope: performance

#5205 Wavelet transform (e.g. retouch) speedup
  src/common/dwt.c
  src/tests/integration/0016-retouch-wavelets/retouch-wavelets.xmp
Labels: no-pr-activity, scope: performance

#5953 Spanish translation update
  po/es.po
Labels: scope: translation

#5556 refactoring: eliminate duplicate boilerplate in iops
  src/develop/imageop.c
  src/develop/imageop.h
  src/iop/atrous.c
  src/iop/basecurve.c
  src/iop/colorzones.c
  src/iop/lowlight.c
  src/iop/rawdenoise.c
  src/iop/rgbcurve.c
  src/iop/tonecurve.c
Labels: feature: redesign, no-pr-activity, scope: performance

#5951 darkroom: only show module header when moving modules
  src/views/darkroom.c
Labels: feature: enhancement

#5526 colorzones: minor refactoring
  src/iop/colorzones.c
Labels: no-pr-activity, scope: codebase

#5891 Adding developers demosaic algo showing photosite values
  src/iop/demosaic.c
Labels: feature: enhancement, scope: image processing

#5957 preferences: display toast message if restart is required
  data/darktableconfig.dtd
  data/darktableconfig.xml.in
  src/gui/preferences.c
  tools/generate_prefs.xsl
Labels: feature: enhancement, scope: UI

#5520 Improve Sqlite3 debug infos in dt code
  src/common/database.c
  src/common/selection.c
Labels: feature: redesign, no-pr-activity

#5959 Fix scripts installer not starting
  data/luarc
Labels: lua

#5960 Elllipsize lua button labels
  doc/usermanual/lua/lua_api.xml
  src/lua/configuration.h
  src/lua/widget/button.c
Labels: lua

#5965 tether: properly initialize job name from conf
  data/darktableconfig.xml.in
  src/views/tethering.c
Labels: bugfix

#5958 imageop: don't try to change group while duplicating modules
  src/develop/imageop.c
Labels: bugfix

#5969 preferences: improved theme tweaks workflow
  data/darktableconfig.xml.in
  src/gui/preferences.c
Labels: bugfix, feature: enhancement

#5977 Spanish translation update
  po/es.po
Labels: scope: translation

#5970 toneequal: restrict hinter message to 2 lines
  src/iop/toneequal.c
Labels: feature: enhancement

#5856 Lua fix thumbnail not updating when rating or colorlabel changed
  src/lua/image.c
Labels: bugfix, lua

#5990 Fix scripts installer not running when locale is not english
  data/luarc
Labels: lua

#5961 Make lua stack resizable
  doc/usermanual/lua/lua_api.xml
  src/lua/widget/stack.c
Labels: lua

#5989 Bilateral filter memory limits
  src/common/bilateral.c
  src/common/bilateral.h
  src/common/bilateralcl.c
Labels: bugfix

#5998 Bilateral filter rewrite: faster and less memory
  src/common/bilateral.c
  src/common/bilateral.h
Labels: feature: enhancement, scope: performance

#5995 remove stack.c leftover debug messages
  src/lua/widget/stack.c
Labels: bugfix, lua

#5985 imageop: replace module rename popup with GtkPopover
  src/develop/imageop.c
Labels: feature: enhancement

#6005 imageop: update module visibility after duplicating
  src/develop/imageop.c
Labels: bugfix

#6012 draw accurate boxes for color picker live samples
  src/libs/colorpicker.c
  src/views/darkroom.c
Labels: bugfix, feature: enhancement

#6013 introduce a way to have single button to discard history
  src/libs/history.c
Labels: feature: enhancement

#6017 fix osx compilation error caused by #6013
  src/libs/history.c
Labels: bugfix

#6016 preferences: separate options for delete and discard
  data/darktableconfig.xml.in
  src/libs/copy_history.c
  src/libs/history.c
Labels: feature: enhancement

#6021 rename iop modules inline
  data/themes/darktable.css
  src/develop/imageop.c
Labels: feature: enhancement

#6022 copy_history: Take copy of images list before discarding history
  src/libs/copy_history.c
Labels: bugfix

#5755 allow shift or control modifiers to scroll slider even with sidebar_scroll_default
  src/bauhaus/bauhaus.c
  src/dtgtk/gradientslider.c
  src/gui/gtk.c
  src/gui/gtk.h
  src/iop/atrous.c
  src/iop/basecurve.c
  src/iop/colorcorrection.c
  src/iop/colorzones.c
  src/iop/denoiseprofile.c
  src/iop/levels.c
  src/iop/lowlight.c
  src/iop/monochrome.c
  src/iop/rawdenoise.c
  src/iop/retouch.c
  src/iop/rgbcurve.c
  src/iop/rgblevels.c
  src/iop/tonecurve.c
  src/iop/zonesystem.c
Labels: bugfix

#6023 ratings: respect rating_one_double_tap preference
  src/common/ratings.c
Labels: bugfix

#6024 add db paths to sql debugging output
  src/common/database.c
Labels: feature: enhancement

#6028 enable lighttable scrollbars by default
  data/darktableconfig.xml.in
Labels: bugfix

#5872 thumbtable: change how file manager row is calculated
  src/dtgtk/thumbtable.c
Labels: bugfix

#5928 export: replace max size spin buttons with entry widgets
  data/themes/darktable.css
  src/libs/export.c
Labels: feature: enhancement

#6034 export(disk): set entry cursor position to end by default
  src/imageio/storage/disk.c
Labels: difficulty: trivial, feature: enhancement

#5714 Tether histogram fix
  data/darktableconfig.xml.in
  src/common/camera_control.c
  src/common/camera_control.h
  src/develop/develop.c
  src/develop/develop.h
  src/develop/pixelpipe_hb.c
  src/iop/colorzones.c
  src/iop/levels.c
  src/iop/rgbcurve.c
  src/iop/rgblevels.c
  src/iop/tonecurve.c
  src/libs/histogram.c
  src/libs/lib.h
  src/libs/live_view.c
  src/views/tethering.c
Labels: bugfix, no-pr-activity, scope: codebase

#6035 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6039 Spanish translation update
  po/es.po
Labels: scope: translation

#6036 preferences: add restart required toast for general tab
  src/gui/preferences.c
Labels: feature: enhancement

#6073 Update to pt_BR manual
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6058 histogram: clear scopes when leave live view
  src/libs/histogram.c
  src/views/tethering.c
Labels: bug: pending

#6060 Fix darktable crash when view changed at startup
  data/luarc
Labels: bugfix

#6071 culling-preview zoom fixes
  src/dtgtk/culling.c
  src/dtgtk/thumbnail.c
Labels: bugfix, difficulty: average, scope: UI

#6076 filmic : fix silent bug, optimize defaults
  src/iop/filmicrgb.c
Labels: bugfix, scope: image processing

#6084 Updates to pt_BR translation of the manual
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6080 Guided filter speedup
  src/common/guided_filter.c
  src/common/guided_filter.h
  src/iop/hazeremoval.c
  src/tests/integration/0025-exposure-guided-filter/exposure-guided-filter.xmp
  src/tests/integration/0026-haze-removal/haze-removal.xmp
Labels: feature: enhancement, scope: performance

#6066 make "work profile" work in tether view histogram
  src/common/colorspaces.c
  src/common/colorspaces.h
  src/common/iop_profile.c
  src/common/iop_profile.h
  src/develop/pixelpipe_hb.c
  src/iop/overexposed.c
  src/libs/histogram.c
  src/views/tethering.c
Labels: bugfix, feature: enhancement

#6070 theme module name edit entry background color
  data/themes/darktable.css
Labels: feature: enhancement

#5974 Non-local means denoising speedup (v3)
  src/CMakeLists.txt
  src/common/nlmeans_core.c
  src/common/nlmeans_core.h
  src/iop/denoiseprofile.c
  src/iop/nlmeans.c
  src/tests/integration/0023-denoiseprofile-nlmeans/denoiseprofile-nlmeans.xmp
  src/tests/integration/0023-denoiseprofile-nlmeans/expected.png
Labels: feature: enhancement, scope: performance

#5728 Make branding consistent as per faq
  build-doc.sh
  build.sh
  doc/README.md
  doc/pdf/hacking.tex
  doc/usermanual/darkroom/modules/tone/filmicrgb.xml
  packaging/ubuntu/README
  packaging/windows/BUILD.txt
  src/common/colorspaces.c
  src/gui/gtk.c
Labels: no-pr-activity

#5530 refactoring: eliminate duplicated boilerplate in lighttable modules
  src/libs/copy_history.c
  src/libs/export.c
  src/libs/image.c
  src/libs/lib.c
  src/libs/lib.h
  src/libs/metadata.c
  src/libs/styles.c
  src/libs/tagging.c
Labels: feature: redesign, no-pr-activity, scope: codebase

#6089 Updates to pt_BR manual
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6094 [Issue #5806] Adding Nikon 1 V2 WB Presets
  src/external/wb_presets.c
Labels: scope: camera support

#6096 Filmic RGB charts: apply dpi to label spacing
  src/iop/filmicrgb.c
Labels: bugfix

#5770 add history changes tooltip
  data/themes/darktable.css
  src/develop/blend.h
  src/develop/blend_gui.c
  src/iop/colormapping.c
  src/iop/liquify.c
  src/libs/history.c
Labels: difficulty: average, feature: enhancement, scope: UI

#6102 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6104 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#6105 add manual paragraph to describe tooltip in history
  doc/usermanual/darkroom/panels/history.xml
Labels: scope: usermanual

#6095 live view histogram improvements
  src/libs/histogram.c
  src/libs/live_view.c
  src/views/tethering.c
Labels: feature: enhancement

#6110 Spanish translation update
  po/es.po
Labels: scope: translation

#6108 Fix missing include
  src/libs/lib.h
Labels: bugfix

#6112 Typo fix on fr.po
  po/fr.po
Labels: scope: translation

#6115 Updates to pt_BR (user manual)
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6097 po/dynamic workflow
  data/darktableconfig.xml.in
  src/develop/develop.c
  src/iop/basecurve.c
  src/iop/exposure.c
  src/iop/filmicrgb.c
Labels: feature: redesign

#6118 fix filmstrip glitches in darkroom
  src/common/collection.c
  src/views/darkroom.c
Labels: bugfix, difficulty: trivial, scope: UI

#6119 Spanish translation update
  po/es.po
Labels: scope: translation

#6130 nlmeans: fix crash due to memory overwrite
  src/common/nlmeans_core.c
Labels: bugfix

#6128 lightable : ensure selection background is updated in any cases
  src/dtgtk/thumbtable.c
Labels: bugfix, difficulty: trivial, scope: UI

#6126 zoomable : fix offset on filter change
  src/dtgtk/thumbtable.c
Labels: bugfix, difficulty: average, scope: UI

#6129 export: disable insert-text handler when programatically inserting
  src/libs/export.c
Labels: bugfix

#6136 export: try to be defensive about potential problems in insert-text
  src/libs/export.c
Labels: bugfix

#6141 Improve grey theme contrast
  data/themes/darktable-elegant-grey.css
  data/themes/darktable.css
Labels: feature: enhancement, scope: UI

#6140 Updates to pt_BR user manual
  doc/usermanual/po/pt_BR.po
Labels: scope: usermanual

#6142 culling : avoid flickering when switching between images
  src/dtgtk/culling.c
  src/dtgtk/thumbnail.c
Labels: bugfix, scope: UI

#6109 Add validation check and fix combobox logic when typing aspect ratio of "1" into crop module
  src/bauhaus/bauhaus.c
  src/iop/clipping.c
Labels: bug: pending, feature: enhancement

#6143 zoomable : avoid grid move on collection change
  src/dtgtk/thumbtable.c
Labels: bugfix, difficulty: average, scope: UI

#5532 Refactoring: remove massive duplicated pixelpipe code
  src/CMakeLists.txt
  src/common/atomic.c
  src/common/atomic.h
  src/develop/develop.c
  src/develop/pixelpipe_hb.c
  src/develop/pixelpipe_hb.h
Labels: feature: redesign, no-pr-activity

#6144 Guided filter scalability improvement
  src/common/guided_filter.c
  src/common/guided_filter.h
Labels: feature: enhancement, scope: performance

#6148 Spanish translation update
  po/es.po
Labels: scope: translation

#5576 More effective use of pixelpipe cache for faster UI
  src/develop/blend_gui.c
  src/develop/imageop.c
  src/develop/imageop.h
  src/develop/pixelpipe_cache.c
  src/develop/pixelpipe_cache.h
  src/develop/pixelpipe_hb.c
  src/iop/colorzones.c
  src/iop/retouch.c
  src/iop/toneequal.c
Labels: no-pr-activity, scope: performance

#6145 thumbtable : redefine mousover after collection change
  src/dtgtk/thumbtable.c
Labels: bugfix, difficulty: trivial, scope: UI

#6154 set history tooltip widget background to match tooltip border
  data/themes/darktable.css
  src/libs/history.c
Labels: feature: enhancement, scope: UI

#6159 Spanish translation update
  po/es.po
Labels: scope: translation

#6093 presets rework - easier removal, no undeletable presets
  src/gui/preferences.c
  src/gui/presets.c
Labels: bugfix, feature: enhancement

#4360 Better white balance ui/ux: buttons, sections, colored sliders!
  data/darktableconfig.xml.in
  src/bauhaus/bauhaus.c
  src/bauhaus/bauhaus.h
  src/dtgtk/paint.c
  src/dtgtk/paint.h
  src/gui/gtk.h
  src/iop/temperature.c
Labels: difficulty: average, feature: enhancement, no-pr-activity, scope: UI, scope: image processing

#6161 preferences.c: fix wrong param in call to dt_osx_disallow_fullscreen
  src/gui/preferences.c
Labels: bugfix

#6152 thumbtable : limit flickering
  src/dtgtk/thumbtable.c
Labels: bugfix, difficulty: average, scope: UI

#6149 Usermanual - add exposure bias
  doc/usermanual/darkroom/modules/basic/exposure.xml
Labels: scope: usermanual
