Repository darktable-org/darktable, pull requests merged in 2021-10, with the labels that each got.

#10129 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#10131 export metadata: disable tags options when tags not selected
  src/libs/export_metadata.c
Labels: bugfix, feature: enhancement

#10130 avif: fix matrix coefficients used on sRGB export
  src/common/imageio_avif.c
  src/imageio/format/avif.c
Labels: bugfix

#10067 exif: special handling of Nikon F lenses on recent bodies
  src/common/exif.cc
Labels: bugfix

#10132 Update de.po
  po/de.po
Labels: scope: translation

#10134 Fix/7402 import css broken on windows
  src/gui/gtk.c
Labels: bugfix, scope: windows support

#10125 Add some darkening of the rejected thumb's background.
  data/themes/darktable.css
Labels: scope: UI

#10136 copy & import: in case of raw+jpeg make sure they keep the same name
  src/common/utility.c
  src/common/utility.h
  src/control/jobs/control_jobs.c
Labels: bugfix

#10146 map view: keep mouse position on thumbnail while dragging
  src/views/map.c
Labels: bugfix

#10144 lens: use trouble message for missing lens warning
  src/iop/lens.cc
Labels: feature: enhancement, difficulty: trivial, scope: UI

#10142 ignore mouse moves and long press shortcuts
  src/gui/accelerators.c
Labels: bugfix, scope: UI

#10154 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#10133 color zones and combos shortcuts roundoff and new action for contrast equalizer
  src/bauhaus/bauhaus.c
  src/common/ratings.c
  src/gui/accelerators.c
  src/iop/atrous.c
  src/iop/colorzones.c
Labels: feature: enhancement

#10156 map view: typo
  src/views/map.c
Labels: bugfix

#10155 Fix color picker Lab display
  src/libs/colorpicker.c
Labels: bugfix

#10152 accelerators: assign iop shortcuts to preferred instance by default
  data/darktableconfig.xml.in
  src/gui/accelerators.c
  tools/generate_prefs.xsl
Labels: feature: redesign, documentation-pending

#10137 import camera: make sure RAW+JPEG keep the same filename
  src/common/camera_control.c
Labels: bugfix

#10159 exif: test for minimal exiv2 for new Nikon LensData
  src/common/exif.cc
Labels: bugfix

#10147 Better rejected thumb css
  data/themes/darktable-elegant-grey.css
  data/themes/darktable.css
Labels: feature: enhancement, difficulty: trivial, scope: UI

#10162 Update pt_BR translation
  po/pt_BR.po
Labels: scope: translation

#10163 ioporder: destroy widget before freeing
  src/libs/ioporder.c
Labels: bugfix

#10186 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#10191 Update lua lighttable layout enums
  src/libs/tools/lighttable.c
Labels: bugfix, lua

#10183 correctly display change indicator when resetting some prefs
  data/darktableconfig.xml.in
  src/control/conf.c
  src/control/conf.h
  tools/generate_darktablerc_conf.xsl
  tools/generate_prefs.xsl
Labels: scope: codebase

#10201 actions don't check visibility of missing widgets
  src/gui/accelerators.c
Labels: bugfix

#10190 Add new lua event - darkroom-image-history-changed
  src/lua/events.c
  src/views/darkroom.c
Labels: feature: enhancement, lua

#10214 modulegroups: simplify the minimal new preset.
  src/libs/modulegroups.c
Labels: feature: enhancement

#10218 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#10222 ashift: rename to rotate and perspective
  src/iop/ashift.c
  src/iop/clipping.c
Labels: feature: enhancement, scope: UI, documentation-pending

#10221 denoiseprofile: fix partially black thumbnails in lighttable
  src/iop/denoiseprofile.c
Labels: bugfix, scope: image processing

#10235 fix copy&import path in Windows
  src/common/import_session.c
  src/common/utility.c
  src/common/utility.h
Labels: bugfix, scope: windows support

#10237 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#10236 masks: fix opacity action to be consistent.
  src/develop/masks/masks.c
Labels: bugfix

#10295 Update esperanto translation.
  po/eo.po
Labels: scope: translation

#10297 Update de.po
  po/de.po
Labels: scope: translation

#10293 histogram: move position definition to global prefs
  data/darktableconfig.xml.in
  src/libs/histogram.c
Labels: scope: UI

#10305 Update Ukrainian translation
  po/uk.po
Labels: scope: translation

#10298 imageio: properly set the loader flag used to load the picture.
  src/common/imageio.c
  src/common/imageio_avif.c
  src/common/imageio_exr.cc
  src/common/imageio_gm.c
  src/common/imageio_heif.c
  src/common/imageio_im.c
  src/common/imageio_j2k.c
  src/common/imageio_jpeg.c
  src/common/imageio_pfm.c
  src/common/imageio_png.c
  src/common/imageio_rawspeed.cc
  src/common/imageio_rgbe.c
  src/common/imageio_tiff.c
Labels: bugfix, priority: medium, difficulty: trivial, scope: DAM
