Repository darktable-org/darktable, pull requests merged in 2021-03, with the labels that each got.

#8362 Update de.po
  po/de.po
Labels: scope: translation

#8351 Metadata update speed
  src/common/selection.c
  src/common/selection.h
  src/libs/metadata.c
  src/views/view.c
  src/views/view.h
Labels: difficulty: average, feature: enhancement, scope: UI, scope: performance

#8366 get path's list node, not data pointed at by that node
  src/develop/masks/path.c
Labels: bugfix, priority: high

#8270 Set node as tag
  src/libs/tagging.c
Labels: feature: enhancement

#8359 reorder blending buttons to save 2 lines
  src/develop/blend_gui.c
  src/gui/gtk.h
Labels: documentation-pending, scope: UI

#8356 performance: skip Liquify distortion map when possible
  src/iop/liquify.c
Labels: scope: performance

#8363 database v34
  src/common/collection.c
  src/common/database.c
  src/libs/tools/timeline.c
Labels: scope: performance

#8336 reorganise module api specification and loading
  src/common/imageio_module.c
  src/common/imageio_module.h
  src/common/module_api.h
  src/develop/imageop.c
  src/develop/imageop.h
  src/imageio/format/imageio_format_api.h
  src/imageio/storage/imageio_storage_api.h
  src/iop/iop_api.h
  src/libs/lib.c
  src/libs/lib.h
  src/libs/lib_api.h
  src/views/view.c
  src/views/view.h
  src/views/view_api.h
Labels: scope: codebase

#8375 collect: fix sql "id" ambiguity
  src/libs/collect.c
Labels: bugfix

#8380 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#8358 OpenCL code for RCD and dual demosaicers
  data/kernels/demosaic_ppg.cl
  data/kernels/demosaic_rcd.cl
  data/kernels/programs.conf
  src/iop/demosaic.c
  src/iop/dual_demosaic.c
Labels: feature: enhancement, scope: image processing, scope: performance

#8374 po/fix legacy spots
  src/develop/develop.c
  src/develop/masks/masks.c
  src/iop/spots.c
Labels: bugfix, difficulty: hard, priority: high, wip

#8384 Ensure that preview is centered when zooming out
  src/libs/navigation.c
Labels: bugfix, priority: high, reproduce: confirmed

#8386 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#8381 geotagging : only get the selection size at startup
  src/libs/geotagging.c
Labels: difficulty: trivial, feature: enhancement, scope: performance

#8376 [RFC] move blending drawing shapes to match retouch
  src/develop/blend_gui.c
Labels: scope: UI

#8248 Improve color picker for the parametric mask channels
  src/develop/blend_gui.c
Labels: documentation-pending, feature: enhancement, scope: image processing

#8343 Invert parametric mask when needed on reset
  src/develop/blend_gui.c
  src/dtgtk/gradientslider.c
Labels: feature: enhancement

#8352 introduce mask indicators in module headers
  data/darktableconfig.xml.in
  data/themes/darktable.css
  src/develop/blend_gui.c
  src/develop/imageop.c
  src/develop/imageop.h
  src/dtgtk/paint.c
  src/views/darkroom.c
Labels: documentation-pending, feature: new, scope: UI

#8388 Some optimizing for RDC OpenCL code
  data/kernels/demosaic_rcd.cl
  src/iop/demosaic.c
Labels: feature: enhancement

#8368 refactor: GList loops (Phase 1)
  src/bauhaus/bauhaus.c
  src/chart/colorchart.c
  src/chart/dtcairo.c
  src/common/cache.c
  src/common/camera_control.c
  src/common/collection.c
  src/common/colorlabels.c
  src/common/colorspaces.c
  src/common/cups_print.c
  src/common/darktable.c
  src/common/database.c
  src/common/exif.cc
  src/common/gpx.c
  src/common/grouping.c
  src/common/history.c
  src/common/image.c
  src/common/imageio.c
  src/common/imageio_module.c
  src/common/iop_profile.c
  src/common/metadata.c
  src/common/ratings.c
  src/common/styles.c
  src/common/tags.c
  src/common/undo.c
  src/common/utility.c
  src/common/variables.c
  src/control/conf.c
  src/control/crawler.c
  src/control/jobs/control_jobs.c
  src/control/jobs/film_jobs.c
  src/develop/develop.c
  src/develop/imageop.c
  src/develop/masks/brush.c
  src/develop/masks/circle.c
  src/develop/masks/ellipse.c
  src/develop/masks/gradient.c
  src/develop/masks/group.c
  src/develop/masks/masks.c
  src/develop/masks/path.c
  src/develop/pixelpipe_hb.c
  src/dtgtk/culling.c
Labels: bugfix, scope: codebase

#8395 gradient: make it easier to click rotate handle
  src/develop/masks/gradient.c
Labels: feature: enhancement, reproduce: peculiar, understood: incomplete

#8394 Export format and storage ui and geotagging fixes for narrow panel
  src/imageio/format/copy.c
  src/imageio/format/pdf.c
  src/imageio/storage/gallery.c
  src/imageio/storage/latex.c
  src/imageio/storage/piwigo.c
  src/libs/export.c
  src/libs/geotagging.c
Labels: bugfix

#8392 channelmixerrgb: declare cat on pipe when processing
  src/iop/channelmixerrgb.c
Labels: bugfix

#8398 denoiseprofile preset: set blending mode to rgb scene
  src/iop/denoiseprofile.c
Labels: bugfix

#8397 thumbtable : fix re-enabling drag and drop
  src/dtgtk/thumbtable.c
Labels: bugfix, difficulty: trivial, scope: UI

#8406 mask indicators: improve preference text
  data/darktableconfig.xml.in
Labels: feature: enhancement

#8408 * thumbtable: enabled smooth scrolling
  src/dtgtk/thumbtable.c
  src/dtgtk/thumbtable.h
Labels: feature: enhancement

#8400 memleak fix: ensure return from dt_util_str_to_glist fully freed
  src/common/collection.c
  src/common/iop_order.c
  src/libs/collect.c
  src/libs/import.c
Labels: bugfix, scope: codebase

#8401 memleak fix: free return value from gtk_tree_model_get_path
  src/gui/preferences.c
  src/iop/lut3d.c
  src/libs/tagging.c
Labels: bugfix, scope: codebase

#8413 Updated Dutch translation
  po/nl.po
Labels: scope: translation

#8393 gradient: fix rotation angle
  src/develop/masks/gradient.c
Labels: bugfix, difficulty: hard

#8416 Fix export settings reset on init
  src/imageio/format/jpeg.c
  src/libs/export.c
Labels: bugfix, feature: enhancement, priority: high, scope: DAM

#8390 startup speedup
  src/common/tags.c
  src/libs/collect.c
  src/libs/tools/global_toolbox.c
Labels: difficulty: average, feature: enhancement, scope: performance

#8417 blend-gui: improve mask display precision
  src/develop/blend_gui.c
Labels: feature: enhancement, scope: UI

#8420 export: fix crash with lua modules.
  src/libs/export.c
Labels: bugfix, priority: high

#8421 import: fix possible crash (see 8e9e3c3e).
  src/libs/import.c
Labels: bugfix, priority: high

#8414 memleak fix: free return from dt_util_glist_to_str
  src/common/collection.c
Labels: bugfix

#8409 refactor: GList loops (Phase 3)
  src/common/history.c
  src/common/imageio.c
  src/common/iop_order.c
  src/develop/blend_gui.c
  src/develop/develop.c
  src/develop/imageop.c
  src/libs/modulegroups.c
  src/libs/print_settings.c
  src/libs/styles.c
  src/libs/tools/lighttable.c
  src/libs/tools/module_toolbox.c
  src/libs/tools/view_toolbox.c
  src/lua/glist.c
  src/lua/gui.c
  src/lua/luastorage.c
  src/lua/tags.c
  src/lua/widget/box.c
  src/lua/widget/container.c
  src/views/darkroom.c
  src/views/lighttable.c
  src/views/tethering.c
  src/views/view.c
Labels: bugfix, scope: codebase

#8422 collect: fix folder counts
  src/libs/collect.c
Labels: bugfix

#8425 reduce bauhaus widget_space vs INNER_PADDING confusion
  src/bauhaus/bauhaus.c
Labels: bugfix

#8424 Update Windows Build Instructions to use Markdown
  packaging/windows/BUILD.md
  packaging/windows/BUILD.txt
Labels: feature: enhancement

#8412 fix $(LABELS_COLORICONS) substitution
  src/common/variables.c
Labels: bugfix

#8430 memleak fix: free return value from gtk_tree_selection_get_selected_rows
  src/libs/collect.c
Labels: bugfix

#8427 preferences: remove auto-set parameters for lib module presets
  src/gui/preferences.c
Labels: bugfix, documentation-pending, scope: UI

#8428 remember show mask and suppress status while module is in focus
  src/develop/blend_gui.c
  src/views/darkroom.c
Labels: bugfix

#8439 make module header mask indicator actually show mask
  src/develop/blend_gui.c
  src/develop/imageop.c
  src/develop/imageop.h
  src/views/darkroom.c
Labels: feature: enhancement

#8444 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#8429 Adding another pixel interpolator option
  data/darktableconfig.xml.in
  src/common/interpolation.c
  src/common/interpolation.h
  src/iop/ashift.c
  src/iop/clipping.c
  src/iop/finalscale.c
  src/iop/lens.cc
  src/iop/liquify.c
Labels: bugfix, feature: enhancement

#8452 Spanish translation update
  po/es.po
Labels: scope: translation

#8450 Fix recent-collection segfault
  src/common/collection.c
Labels: bugfix

#8446 improve mask indicator for raster mask
  src/develop/blend_gui.c
  src/develop/imageop.c
Labels: documentation-pending, feature: enhancement, scope: UI

#8451 collection : reset expanded group when query change
  src/common/collection.c
Labels: bugfix, difficulty: average, priority: high, scope: UI

#8458 Update de.po
  po/de.po
Labels: scope: translation

#8455 In color calibration, leave hue slider unchanged when chroma is zero
  src/iop/channelmixerrgb.c
Labels: bugfix, feature: enhancement

#8463 Dutch translation
  po/nl.po
Labels: scope: translation

#8460 exif: improve handling of more mandatory tags
  src/common/exif.cc
  src/imageio/format/jpeg.c
  src/imageio/format/tiff.c
Labels: scope: DAM, scope: codebase, scope: software support

#8459 don't use "menuitem *" in CSS
  data/themes/darktable.css
Labels: scope: codebase

#8477 map locations: correct tooltip and toast text
  src/libs/map_locations.c
Labels: scope: UI

#8471 fix broken link to windows build instructions
  README.md
Labels: scope: usermanual

#8473 darkroom: update gui after setting expanded status
  src/views/darkroom.c
Labels: bugfix, scope: UI

#8372 Import session
  data/darktableconfig.xml.in
  src/common/import_session.c
  src/control/jobs/control_jobs.c
  src/control/jobs/control_jobs.h
  src/gui/camera_import_dialog.c
  src/gui/preferences.c
  src/gui/preferences.h
  src/libs/import.c
  src/libs/map_settings.c
Labels: difficulty: average, feature: enhancement, scope: DAM

#8470 avoid repeated calls to g_list_last
  src/common/iop_order.c
Labels: scope: codebase, scope: performance

#8469 GTimeVal: move all instances of GTimeVal to GDateTime
  src/CMakeLists.txt
  src/common/gpx.c
  src/common/gpx.h
  src/control/jobs/control_jobs.c
  src/libs/geotagging.c
Labels: scope: codebase, scope: software support

#8468 geotagging: fix tracks and images glitches
  src/libs/geotagging.c
Labels: bugfix

#8478 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#8475 fix bauhaus popup left jump and margins
  src/bauhaus/bauhaus.c
  src/gui/gtk.c
Labels: feature: enhancement, scope: UI

#8481 Update de.po
  po/de.po
Labels: scope: translation

#8479 import dialog: attempt to manage widget focus
  data/themes/darktable.css
  src/libs/import.c
Labels: difficulty: trivial, feature: enhancement, scope: UI

#7289 ensure that mouse actions aren't performed if extraneous modifier keys held
  src/bauhaus/bauhaus.c
  src/common/darktable.h
  src/control/control.h
  src/develop/blend_gui.c
  src/develop/imageop.c
  src/develop/masks/brush.c
  src/develop/masks/circle.c
  src/develop/masks/ellipse.c
  src/develop/masks/gradient.c
  src/develop/masks/masks.c
  src/develop/masks/path.c
  src/dtgtk/culling.c
  src/dtgtk/gradientslider.c
  src/dtgtk/thumbnail.c
  src/dtgtk/thumbtable.c
  src/gui/color_picker_proxy.c
  src/gui/gtk.c
  src/iop/ashift.c
  src/iop/basecurve.c
  src/iop/clipping.c
  src/iop/colorchecker.c
  src/iop/colorcorrection.c
  src/iop/colorzones.c
  src/iop/graduatednd.c
  src/iop/liquify.c
  src/iop/retouch.c
  src/iop/rgbcurve.c
  src/iop/spots.c
  src/iop/tonecurve.c
  src/iop/toneequal.c
  src/iop/vignette.c
  src/libs/collect.c
  src/libs/geotagging.c
  src/libs/histogram.c
  src/libs/history.c
  src/libs/lib.c
  src/libs/map_locations.c
  src/libs/masks.c
  src/libs/metadata.c
  src/libs/tagging.c
  src/libs/tools/lighttable.c
  src/libs/tools/timeline.c
  src/views/darkroom.c
  src/views/map.c
Labels: bugfix, no-pr-activity, scope: UI

#8492 tags: fix double free
  src/common/tags.c
Labels: bugfix, priority: high, understood: clear

#8499 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#8504 blend_gui: makes channels button work better with small panel size.
  src/develop/blend_gui.c
Labels: bugfix

#8508 import: make labels translatable
  src/libs/import.c
Labels: bugfix, scope: translation

#8505 grouping : fix start state
  src/common/darktable.c
Labels: bugfix, difficulty: average, scope: UI

#8511 Update de.po
  po/de.po
Labels: scope: translation

#8486 replace middle-click actions with right-click
  src/develop/imageop.c
  src/gui/presets.c
Labels: difficulty: trivial, documentation-pending, feature: redesign, scope: UI

#8496 Usability improvements for darktable-cli
  src/cli/main.c
Labels: feature: enhancement, priority: low

#8516 pref label: fix label shaking when ellipsizing
  src/gui/import_metadata.c
  src/gui/preferences.c
Labels: bugfix, scope: UI

#8346 New CSS optimization part 1
  data/themes/darktable-elegant-dark.css
  data/themes/darktable-elegant-darker.css
  data/themes/darktable-elegant-grey.css
  data/themes/darktable.css
Labels: difficulty: average, feature: redesign, priority: low, scope: UI

#8419 make darkroom loading screen optional
  data/darktableconfig.xml.in
  src/views/darkroom.c
Labels: documentation-pending, feature: enhancement, scope: UI

#8509 Import camera
  data/darktableconfig.xml.in
  src/CMakeLists.txt
  src/common/camera_control.c
  src/common/camera_control.h
  src/control/jobs/camera_jobs.c
  src/control/jobs/camera_jobs.h
  src/gui/camera_import_dialog.c
  src/gui/camera_import_dialog.h
  src/libs/import.c
Labels: feature: enhancement, scope: DAM

#8518 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#8526 initial esperanto translation for GUI
  po/LINGUAS
  po/eo.po
Labels: scope: translation

#8532 Spanish translation update
  po/es.po
Labels: scope: translation

#8431 refactor: dedupe code iterating over container's children
  src/develop/develop.c
  src/develop/imageop.c
  src/gui/gtk.c
  src/gui/gtk.h
  src/iop/watermark.c
  src/libs/backgroundjobs.c
  src/libs/duplicate.c
  src/libs/export.c
  src/libs/history.c
  src/libs/import.c
  src/libs/lib.c
  src/libs/location.c
  src/libs/modulegroups.c
  src/lua/widget/container.c
  src/views/darkroom.c
  src/views/view.c
Labels: scope: codebase

#8500 set mask indicator insensitive if module is switched off
  src/develop/blend_gui.c
  src/develop/imageop.c
Labels: bugfix, feature: enhancement

#8495 better thumbnail rendering tooltips.
  data/darktableconfig.xml.in
Labels: documentation-pending, feature: enhancement

#8521 fixes #8483: copy WB data from Pentax K20D to Samsung GX20 + copy adobe coeff from…
  data/noiseprofiles.json
  src/common/colormatrices.c
  src/external/adobe_coeff.c
  src/external/wb_presets.c
Labels: scope: camera support, scope: noise profile

#8530 import: fix lua filter regression due to ee9ac74
  src/control/jobs/control_jobs.c
  src/control/jobs/film_jobs.c
  src/libs/import.c
Labels: bugfix, priority: high

#8538 Spanish translation update
  po/es.po
Labels: scope: translation

#8539 improve tooltips for mask indicator
  src/develop/imageop.c
Labels: documentation-pending, feature: enhancement

#8544 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#8545 Updated Esperanto translation.
  po/eo.po
Labels: scope: translation

#8543 Make sure masks are saved even if the module is not enabled.
  src/develop/imageop.c
  src/develop/pixelpipe_hb.c
Labels: difficulty: hard, priority: high, understood: clear

#8540 make export overwrite prompt optional
  data/darktableconfig.xml.in
  src/imageio/storage/disk.c
Labels: documentation-pending, feature: enhancement

#8548 Make sure that the creation of the duplicate do not create an xmp.
  src/common/image.c
Labels: bugfix, priority: high, understood: clear

#8549 Update de.po
  po/de.po
Labels: scope: translation

#8502 modulegroups preset autoapply + code refactor
  src/gui/preferences.c
  src/gui/presets.c
  src/gui/presets.h
  src/libs/lib.c
  src/libs/lib.h
  src/libs/lib_api.h
  src/libs/modulegroups.c
Labels: difficulty: hard, documentation-pending, feature: new, scope: UI, scope: codebase

#8550 thumbnail preference: minor description change
  data/darktableconfig.xml.in
Labels: documentation-pending

#8552 Update Esperanto translation.
  po/eo.po
Labels: scope: translation

#8554 Use American spelling of gray
  data/darktableconfig.xml.in
  src/iop/channelmixerrgb.c
  src/iop/filmicrgb.c
  src/iop/profile_gamma.c
  src/iop/rgbcurve.c
Labels: difficulty: trivial, documentation-pending, feature: enhancement, scope: UI

#8556 fix various typos
  .github/ISSUE_TEMPLATE/bug_report.md
  CMakeLists.txt
  CONTRIBUTING.md
  README.md
  data/kernels/demosaic_vng.cl
  data/themes/darktable.css
  src/develop/masks.h
  src/develop/masks/brush.c
  src/dtgtk/culling.c
  src/dtgtk/culling.h
  src/dtgtk/thumbnail.c
  src/dtgtk/thumbnail.h
  src/dtgtk/thumbtable.c
  src/dtgtk/thumbtable.h
  src/gui/import_metadata.c
  src/imageio/storage/piwigo.c
  src/iop/cacorrect.c
  src/iop/channelmixerrgb.c
  src/iop/dual_demosaic.c
  src/iop/filmicrgb.c
  src/iop/rgbcurve.c
  src/iop/temperature.c
  src/libs/history.c
  src/libs/tools/timeline.c
  src/lua/events.c
  src/lua/types.h
  src/views/darkroom.c
  src/views/knight.c
  src/views/tethering.c
  src/views/view.c
Labels: scope: codebase

#8559 modulegroup + presets fix focus
  src/gui/presets.c
  src/libs/modulegroups.c
Labels: bugfix, difficulty: trivial, scope: UI

#8564 manage module groups: unset keyboard focus
  src/libs/modulegroups.c
Labels: feature: enhancement

#8565 Update de.po
  po/de.po
Labels: scope: translation

#8572 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#8571 fix import in-place dialog size
  src/libs/import.c
Labels: bugfix

#8573 Update Esperanto translation.
  po/eo.po
Labels: scope: translation

#8574 Add Sony ILCE-7C noise profile
  data/noiseprofiles.json
Labels: scope: noise profile

#8585 Updated Dutch translation
  po/nl.po
Labels: scope: translation

#8586 ellipse: fix rotation angle when there are pipe distortions
  src/develop/masks/ellipse.c
Labels: bugfix, difficulty: trivial

#8580 Remove now unneeded scripts.
  tools/iop-layout-legacy.sh
  tools/iop-layout.sh
  tools/keybinding2docbook.awk
  tools/keybinding2docbook.sh
  tools/update_web_usermanual.sh
Labels: scope: codebase
