Repository darktable-org/darktable, pull requests merged in 2021-01, with the labels that each got.

#7575 split tiling->factor into CPU and GPU requirements
  src/develop/pixelpipe_hb.c
  src/develop/tiling.c
  src/develop/tiling.h
  src/iop/atrous.c
  src/iop/bloom.c
  src/iop/denoiseprofile.c
  src/iop/highpass.c
  src/iop/monochrome.c
  src/iop/soften.c
  src/iop/useless.c
Labels: scope: codebase, scope: performance

#3648 basic module replacement
  data/darktableconfig.xml.in
  data/themes/darktable.css
  src/control/control.c
  src/control/control.h
  src/dtgtk/paint.c
  src/dtgtk/paint.h
  src/gui/accelerators.c
  src/gui/preferences.c
  src/libs/history.c
  src/libs/modulegroups.c
  src/libs/modulegroups.h
  src/views/darkroom.c
  src/views/view.c
Labels: feature: enhancement, scope: UI, scope: image processing

#7606 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#7255 add a censorization module
  src/common/gaussian.h
  src/common/iop_order.c
  src/iop/CMakeLists.txt
  src/iop/censorize.c
Labels: scope: image processing

#7584 [wb_presets] add presets for Olympus E-M10 Mark IV
  src/external/wb_presets.c
Labels: scope: camera support

#7608 filmstrip : resize current darkroom image with panel
  src/dtgtk/thumbnail.c
Labels: bugfix, difficulty: average, scope: UI

#7548 Fix yellow color label contrast with thumbnail background
  data/themes/darktable.css
Labels: feature: enhancement, scope: UI

#7617 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#7585 import exif: use comment() for correct reading of UserComment and disregard the "binary comment"
  src/common/exif.cc
Labels: bugfix

#7596 [masks/shapes] make hinter messages match what's possible
  src/develop/masks/brush.c
  src/develop/masks/circle.c
  src/develop/masks/ellipse.c
  src/develop/masks/gradient.c
  src/develop/masks/masks.c
  src/develop/masks/path.c
Labels: bugfix, difficulty: trivial, scope: UI

#7624 Detect module name edit Entry after buttons pressed
  data/darktableconfig.xml.in
  src/develop/imageop.c
Labels: bugfix

#7591 basecurve: cleanup parallel for loops
  src/iop/basecurve.c
Labels: scope: codebase

#7347 add a new colorbalancergb module
  src/common/chromatic_adaptation.h
  src/common/colorspaces_inline_conversions.h
  src/common/iop_order.c
  src/iop/CMakeLists.txt
  src/iop/colorbalancergb.c
Labels: feature: enhancement

#7601 [windows/ninja] allow using ninja as generator for windows
  CMakeLists.txt
  data/CMakeLists.txt
  doc/man/CMakeLists.txt
  doc/man/po/CMakeLists.txt
Labels: scope: OS support

#7629 [modulegroups] fix wrong data setting
  src/libs/modulegroups.c
Labels: bugfix

#7531 histogram: handle manually selected display profile
  src/common/colorspaces.c
  src/develop/pixelpipe_hb.c
  src/iop/overexposed.c
  src/libs/histogram.c
Labels: bugfix, scope: color management

#7517 po/add collect filters
  src/libs/collect.c
Labels: feature: enhancement

#7634 [masks/path] try not to break on null points with oob search
  src/develop/masks/path.c
Labels: bugfix

#7620 Dedup image-buffer operations
  src/common/dwt.c
  src/common/imagebuf.c
  src/common/imagebuf.h
  src/develop/blend.c
  src/develop/blends/blendif_lab.c
  src/develop/blends/blendif_raw.c
  src/develop/blends/blendif_rgb_hsl.c
  src/develop/blends/blendif_rgb_jzczhz.c
  src/develop/masks/brush.c
  src/develop/masks/path.c
  src/iop/borders.c
  src/iop/retouch.c
  src/libs/histogram.c
Labels: scope: codebase

#7639 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#7642 fix colorbalancergb.c compile error on gcc 7.5
  src/iop/colorbalancergb.c
Labels: bugfix

#7648 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#7626 [CI] add fuller GCC7 tests - make sure build target is built as well as all Release targets
  .github/workflows/ci.yml
  src/iop/cacorrect.c
Labels: scope: codebase

#7636 RCD fixing (1)
  src/iop/demosaic.c
  src/iop/rcd_demosaic.c
Labels: bugfix

#7616 introduce macro for_each_channel to aid vectorization
  src/common/darktable.h
  src/common/nlmeans_core.c
Labels: scope: performance

#7645 rgblevels: cleanup parallel for loop
  src/iop/rgblevels.c
Labels: scope: codebase

#7653 iop_profile: remove duplicated _apply_trc_{in,out}
  src/common/iop_profile.h
Labels: scope: codebase

#7656 Mac M1 cpu supports ARMv8-A instructions
  src/is_supported_platform.h
Labels: scope: OS support

#7607 [styles] introduce easy way to remove all styles
  src/common/styles.c
  src/common/styles.h
  src/libs/styles.c
Labels: feature: enhancement, scope: DAM, scope: UI, scope: codebase

#7663 basics : disable on canvas controls
  src/develop/imageop.c
  src/libs/modulegroups.c
Labels: difficulty: average, feature: enhancement, scope: UI

#7665 Fix for #7267 (lighttable - collect images: boolean problem when searching for multiple file names)
  src/common/collection.c
Labels: bugfix, feature: enhancement

#7294 presets menu: add preferences entry. applied to metadata_view and metadata plugins
  src/gui/gtk.h
  src/libs/export.c
  src/libs/metadata.c
  src/libs/metadata_view.c
Labels: feature: enhancement

#7666 import preferences: fix position of set_preferences() inside USE_LUA clauses
  src/libs/import.c
Labels: bugfix

#7672 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#7674 Fix dereference of deleted module elements in mask manager
  src/libs/masks.c
Labels: bugfix

#7675 import preferences: do save metadata
  src/libs/import.c
Labels: bugfix

#7677 metadata view: give more room to values than to name
  src/libs/metadata_view.c
Labels: bugfix

#7680 modulegroups : hide window border
  src/libs/modulegroups.c
Labels: feature: enhancement, scope: UI

#7676 nlmeans_core: optimize pixel_difference with for_each_channel macro
  src/common/nlmeans_core.c
Labels: scope: performance

#7681 tagging: remove tick from treeview tag's image is not selected anymore
  src/libs/tagging.c
Labels: bugfix

#7679 noise profiles
  data/noiseprofiles.json
Labels: scope: noise profile

#7683 New set of css improvement
  data/themes/darktable.css
Labels: feature: enhancement, scope: UI

#7690 [lua widget] added name property so that widgets can be styled using CSS
  src/lua/widget/widget.c
Labels: feature: enhancement

#7670 Decode JPEG-2000 with using multiple threads
  src/common/imageio_j2k.c
Labels: feature: enhancement, scope: performance

#7693 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#7701 colorspaces: output non supported profile under dev control.
  src/common/colorspaces.c
Labels: feature: enhancement

#7706 metadata view: revert usage of treeview to grid
  src/libs/metadata_view.c
Labels: feature: enhancement, scope: UI

#7711 [paint.c] make paint.c independent of darktable.bauhaus
  src/dtgtk/paint.c
  src/dtgtk/thumbnail.c
  src/dtgtk/thumbnail_btn.c
  src/libs/tools/colorlabels.c
Labels: bugfix, scope: codebase

#7708 add collect windowheigt in xml for darktablerc
  data/darktableconfig.xml.in
Labels: bugfix

#7652 iop_profile: fix order of matrix multiplications
  src/common/iop_profile.c
Labels: bugfix

#7664 thumb generation prefs rework
  data/darktableconfig.xml.in
  src/common/image.c
  src/common/mipmap_cache.c
  src/common/mipmap_cache.h
  src/iop/demosaic.c
  src/views/view.c
Labels: difficulty: average, feature: enhancement, scope: UI, scope: color management

#7630 overexposed: fix and clean up color profile handling
  src/common/iop_profile.c
  src/develop/pixelpipe_hb.c
  src/iop/overexposed.c
  src/libs/histogram.c
  src/views/tethering.c
Labels: bugfix, scope: codebase

#7709 Color checker calibration : various minor fixes
  src/common/colorchecker.h
  src/iop/channelmixerrgb.c
Labels: bugfix

#7712 [tools] some python corrections
  tools/dtstyle_to_xmp.py
  tools/extract_wb.py
Labels: difficulty: trivial, scope: codebase

#7715 [style/tag] change darktable|style|sytlename to dtstyle|stylename
  src/common/history.c
  src/libs/tagging.c
Labels: bugfix

#7716 [lua] make darktable.gui.libs visibility work correctly.
  src/libs/lib.c
  src/lua/lib.c
Labels: bugfix

#7667 [masks/imageio] track module name changes in mask manager
  src/develop/imageop.c
  src/develop/masks.h
  src/develop/masks/masks.c
Labels: bugfix, scope: UI, scope: codebase

#7710 import: add a pref to give priority to initial import rating on exif rating
  data/darktableconfig.xml.in
  src/common/image.c
  src/libs/import.c
Labels: bugfix

#7724 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#7729 imageio_tiff: restore recommended orientation tag
  src/imageio/format/tiff.c
Labels: bugfix

#7726 Update thumbnails while importing a folder
  src/control/jobs/camera_jobs.c
  src/control/jobs/film_jobs.c
Labels: bugfix

#7722 Fixes encoding issue on Windows when pathes contain non-ASCII symbols
  src/common/file_location.c
Labels: bugfix, priority: high, scope: OS support

#7721 Fixes encoding issue on Windows when pathes contain non-ASCII symbols
  src/common/file_location.c
Labels: bugfix, priority: high, scope: OS support

#7671 Fix syntetic bold
  data/themes/darktable-elegant-darker.css
  src/develop/blend_gui.c
  src/gui/presets.c
Labels: bugfix, scope: UI

#7737 chore: use existing define for rating mask
  src/libs/import.c
Labels: scope: codebase

#7735 collect: discriminate camera with same prefix
  src/common/collection.c
Labels: bugfix, scope: DAM

#7744 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#7738 [threadsafety] localtime is not threadsafe, use localtime_r
  src/control/crawler.c
  src/libs/metadata_view.c
Labels: difficulty: trivial, scope: codebase

#7743 [lua] enhance preferences
  src/lua/preferences.c
Labels: feature: enhancement, lua

#7741 gui reset on empty pref acc to idea of phweyland pr7733
  src/libs/metadata_view.c
Labels: bugfix

#7750 channelmixerrgb: fix a typo and a bug in params
  src/iop/channelmixerrgb.c
Labels: bugfix, priority: high

#7740 [size_t] make sure multiplications are done in size_t, correct allocations etc
  src/common/bilateral.c
  src/common/box_filters.c
  src/common/dwt.c
  src/common/eaw.c
  src/common/focus_peaking.h
  src/common/imageio.c
  src/common/imageio_dng.h
  src/common/map_locations.c
  src/common/mipmap_cache.c
  src/control/jobs/control_jobs.c
  src/develop/masks/circle.c
  src/develop/masks/ellipse.c
  src/develop/pixelpipe_hb.c
  src/develop/tiling.c
  src/iop/ashift_lsd.c
  src/iop/atrous.c
  src/iop/bilat.c
  src/iop/cacorrect.c
  src/iop/censorize.c
  src/iop/colorcontrast.c
  src/iop/colormapping.c
  src/iop/colorreconstruction.c
  src/iop/defringe.c
  src/iop/demosaic.c
  src/iop/denoiseprofile.c
  src/iop/equalizer.c
  src/iop/exposure.c
  src/iop/filmic.c
  src/iop/filmicrgb.c
  src/iop/globaltonemap.c
  src/iop/highlights.c
  src/iop/levels.c
  src/iop/liquify.c
  src/iop/lowpass.c
  src/iop/lut3d.c
  src/iop/monochrome.c
  src/iop/negadoctor.c
  src/iop/retouch.c
  src/iop/shadhi.c
  src/iop/toneequal.c
  src/libs/tools/darktable.c
  src/views/knight.c
  src/views/map.c
  src/views/view.c
Labels: scope: codebase

#7739 basics : allow colorpickers to work as intended
  src/develop/imageop.c
  src/iop/ashift.c
  src/iop/clipping.c
  src/libs/modulegroups.c
  src/views/darkroom.c
Labels: bugfix

#7621 [gtk] protect against nulls
  src/dtgtk/button.c
  src/dtgtk/gradientslider.c
  src/dtgtk/icon.c
  src/dtgtk/thumbnail_btn.c
  src/dtgtk/togglebutton.c
Labels: bugfix

#7520 [safe copy] mark deprecateed modules as unsafe too
  src/common/history.c
  src/common/history.h
  src/gui/hist_dialog.c
Labels: bugfix, feature: enhancement, scope: UI

#7758 [icons] fix comments in paint.h so that all icons are picked by show_icons_in_paint_c.pl
  src/dtgtk/paint.h
Labels: difficulty: trivial, scope: codebase

#7752 collect: add the entry "not tagged" to tag collection
  src/common/collection.c
  src/libs/collect.c
Labels: scope: DAM

#7755 [wb_presets] Nikon Z 7 II Finetuned white balance presets
  src/external/wb_presets.c
Labels: scope: camera support

#7748 liquify handles
  src/iop/liquify.c
Labels: bugfix, feature: enhancement

#7700 channelmixerrgb: handle rotated orientations of color checker
  src/iop/channelmixerrgb.c
Labels: bugfix, feature: enhancement

#7763 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#7747 [database] bump version to 31 adding second columns to some indices
  src/common/database.c
Labels: scope: performance

#7766 collect tags: not tagged. improve a bit response time for images query
  src/common/collection.c
Labels: feature: enhancement, scope: performance

#7764 channelmixerrgb: fix normalization of colorfulness
  src/iop/channelmixerrgb.c
Labels: bugfix

#7762 [5926] Icons for lighttable-modes
  src/dtgtk/paint.c
  src/dtgtk/paint.h
Labels: feature: enhancement, scope: UI

#7765 Continue work on RCD demosaicer
  src/iop/rcd_demosaic.c
Labels: bugfix

#7736 Update french translation
  po/fr.po
Labels: scope: translation

#7777 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#7779 simplification of dt_ui_notebook_clear
  src/gui/gtk.c
Labels: scope: codebase

#7791 nlmeans_core: optimize diff of pixel_difference
  src/common/nlmeans_core.c
Labels: feature: redesign, scope: performance

#7790 imageio_avif: preserve default UNSPECIFIED enums for CICP
  src/imageio/format/avif.c
Labels: scope: codebase

#7793 Correct links for context sensitive help for technical group modules
  packaging/windows/BUILD.txt
  src/common/usermanual_url.c
Labels: scope: codebase

#7754 collect tags: fix sensitivity regression. make work back image order on tags
  src/common/tags.c
  src/common/tags.h
Labels: bugfix

#7802 [mask group] Fix wrong group formid assignment & complete refactoring
  src/develop/masks/masks.c
Labels: bugfix

#7810 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#7801 fix search while in basics tab
  src/libs/modulegroups.c
Labels: bugfix

#7796 Debug option -d demosaic
  src/common/darktable.c
  src/common/darktable.h
  src/iop/demosaic.c
Labels: scope: codebase

#7807 channelmixerrgb: fix a bug with RGB handling
  src/iop/channelmixerrgb.c
Labels: bugfix, priority: high

#7813 export metadata: when metadata is unchecked make sure no xmp are exported
  src/common/exif.cc
Labels: bugfix

#7767 histogram: waveform processing/drawing fixes/cleanups
  src/libs/histogram.c
Labels: bugfix, feature: redesign, scope: UI, scope: codebase

#7771 [codebase] use align_float, protect against nulls, don't leak memory etc
  src/common/database.c
  src/common/gaussian.c
  src/common/history.c
  src/common/history.h
  src/common/imageio.c
  src/common/iop_order.c
  src/common/l10n.c
  src/common/map_locations.c
  src/common/map_locations.h
  src/common/metadata.c
  src/common/metadata.h
  src/common/opencl.c
  src/common/ratings.c
  src/common/ratings.h
  src/common/tags.c
  src/common/tags.h
  src/develop/masks.h
  src/develop/masks/path.c
  src/gui/accelerators.c
  src/gui/gtk.c
  src/imageio/storage/piwigo.c
  src/iop/channelmixerrgb.c
  src/iop/highlights.c
  src/libs/collect.c
  src/libs/colorpicker.c
  src/libs/metadata.c
  src/libs/tagging.c
  src/libs/tools/darktable.c
  src/views/map.c
Labels: scope: codebase

#7719 thumb : limit flickering in culling & preview
  data/themes/darktable.css
  src/dtgtk/culling.c
  src/dtgtk/thumbnail.c
  src/dtgtk/thumbnail.h
  src/dtgtk/thumbtable.c
  src/libs/duplicate.c
Labels: bugfix, difficulty: hard, scope: UI

#7657 Profile list: clarify which system display profile is preview
  src/common/colorspaces.c
Labels: feature: enhancement

#7635 basics : add an option to hide the group directly
  src/libs/modulegroups.c
Labels: feature: enhancement, scope: UI

#7778 basics: rework links to full iops
  data/themes/darktable.css
  src/dtgtk/paint.c
  src/dtgtk/paint.h
  src/libs/modulegroups.c
Labels: scope: UI, scope: image processing

#7825 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#7817 rework lighttable toolbar
  data/themes/darktable.css
  src/dtgtk/culling.c
  src/libs/tools/lighttable.c
  src/views/lighttable.c
  src/views/view.c
  src/views/view.h
Labels: difficulty: average, feature: enhancement, scope: UI

#7829 import: move preferences to module parameters (under expander)
  data/darktableconfig.xml.in
  data/themes/darktable.css
  src/gui/import_metadata.c
  src/gui/import_metadata.h
  src/gui/preferences.c
  src/gui/preferences.h
  src/libs/import.c
Labels: feature: enhancement

#7812 po/mask sizes
  src/develop/masks/circle.c
  src/develop/masks/ellipse.c
  src/develop/masks/path.c
Labels: difficulty: average, feature: enhancement, scope: UI

#7838 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#7840 channelmixerrgb: restore warning label
  src/iop/channelmixerrgb.c
Labels: bugfix

#7836 tests: update delta E
  src/tests/integration/deltae
Labels: feature: enhancement, scope: codebase

#7832 import parameters: expand left column
  src/gui/preferences.c
Labels: feature: enhancement

#7837 filmicrgb: fix a bug with highlights reconstruction
  data/kernels/filmic.cl
  src/iop/filmicrgb.c
Labels: bugfix

#7831 fix for lighttable accels
  src/gui/gtk.c
  src/libs/tools/lighttable.c
Labels: feature: enhancement

#7582 dynamically add warning label to iop when needed
  data/themes/darktable.css
  src/common/database.c
  src/common/variables.c
  src/develop/imageop.c
  src/develop/imageop.h
  src/dtgtk/paint.c
  src/dtgtk/thumbtable.c
  src/gui/presets.c
  src/iop/temperature.c
  src/iop/useless.c
  src/libs/lib.c
Labels: feature: enhancement

#7842 filmicrgb OpenCL : fix an inconsistency with C path
  data/kernels/filmic.cl
Labels: bugfix

#7843 metadata: proper search on double list
  src/common/metadata.c
Labels: bugfix

#7835 fix bold for module presets in lighttable
  data/themes/darktable-elegant-darker.css
  data/themes/darktable.css
  src/libs/lib.c
Labels: bugfix

#7846 import: layout update on prefs and metadata list changes
  src/gui/import_metadata.c
  src/gui/import_metadata.h
Labels: bugfix, feature: enhancement

#7845 modulegroups: fix right-click sort order
  src/libs/modulegroups.c
Labels: bugfix

#7855 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#7844 improve styling of module section expander button
  data/themes/darktable.css
  src/iop/temperature.c
  src/libs/import.c
Labels: scope: UI

#7865 channelmixerrgb: don't leak strings
  src/iop/channelmixerrgb.c
Labels: scope: codebase

#7839 channelmixerrgb: change the saturation control
  src/iop/channelmixerrgb.c
Labels: feature: enhancement

#7867 histogram: bugfix, set black point on drag
  src/libs/histogram.c
Labels: bugfix

#7851 French translation
  po/fr.po
Labels: scope: translation

#7870 histogram: drag behavior tidying
  src/libs/histogram.c
Labels: scope: codebase

#7878 RCD demosaicer code maintenance
  src/iop/rcd_demosaic.c
Labels: scope: codebase, scope: performance

#7880 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#7872 Update de.po - Filmic as a trademark
  po/de.po
Labels: scope: translation

#7863 Database version 33
  src/common/database.c
  src/gui/legacy_presets.h
Labels: feature: enhancement

#7874 channelmixerrgb: fix color checker drawing and sampling
  src/chart/common.c
  src/chart/common.h
  src/iop/channelmixerrgb.c
Labels: bugfix, scope: UI

#7869 Improve stars, colorlabels and some spacing
  data/themes/darktable-elegant-dark.css
  data/themes/darktable-elegant-grey.css
  data/themes/darktable.css
  src/dtgtk/paint.c
Labels: scope: UI

#7884 Fix stars in all overlays
  data/themes/darktable-elegant-grey.css
  data/themes/darktable.css
Labels: scope: UI

#7887 lighttable : remove conflicting accels preview with focus
  src/libs/tools/lighttable.c
Labels: bugfix, difficulty: trivial, scope: UI

#7885 lighttable : fix scrollbars flickering in rare cases
  src/dtgtk/thumbtable.c
Labels: bugfix, difficulty: average, scope: UI

#7901 colormapping: fix dt_alloc_align/free and malloc/dt_free_align mismatches
  src/iop/colormapping.c
Labels: bugfix

#7896 database version 33: delete images with invalid film id
  src/common/database.c
Labels: bugfix

#7900 denoiseprofiled: changes to improve vectorizability
  src/iop/denoiseprofile.c
Labels: bugfix, scope: performance

#7911 fix memleaks in various places
  src/common/database.c
  src/libs/ioporder.c
  src/libs/modulegroups.c
  src/views/view.c
Labels: bugfix, difficulty: trivial, scope: codebase, scope: performance

#7903 Improve debugging output for demosaic & pixelpipe
  src/develop/pixelpipe_hb.c
  src/iop/demosaic.c
Labels: scope: codebase

#7614 Avoid gcc-11 stringop-overflow error
  src/common/illuminants.h
  src/iop/channelmixerrgb.c
Labels: bugfix, scope: codebase, scope: image processing

#7895 Codebase fixes from static analysis reports
  src/common/colorchecker.h
  src/common/exif.cc
  src/common/exif.h
  src/common/usermanual_url.c
  src/develop/masks/masks.c
  src/gui/styles_dialog.c
  src/libs/export_metadata.c
  src/views/knight.c
Labels: scope: codebase

#7897 Fix ungroup button and dt_grouping_remove_from_group
  src/common/grouping.c
  src/libs/image.c
Labels: bugfix, difficulty: trivial, feature: enhancement, scope: UI

#7883 homography: use single precision floats at interfaces
  src/chart/common.c
  src/chart/common.h
  src/chart/dtcairo.c
  src/chart/dtcairo.h
  src/chart/main.c
  src/iop/channelmixerrgb.c
Labels: scope: codebase

#7902 overexposed: use for_each_channel and copy_pixel
  src/iop/overexposed.c
Labels: scope: codebase, scope: performance

#7862 import: disable labels when necessary and update presets when initialized
  src/common/metadata.h
  src/gui/import_metadata.c
  src/gui/import_metadata.h
  src/gui/preferences.c
  src/gui/preferences.h
  src/libs/collect.c
  src/libs/import.c
  src/libs/metadata.c
Labels: bugfix

#7827 reorder profile/intent tool box entries.
  data/themes/darktable.css
  src/views/darkroom.c
  src/views/lighttable.c
Labels: difficulty: trivial, feature: enhancement

#7921 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation
