Repository darktable-org/darktable, pull requests merged in 2021-11, with the labels that each got.

#10290 imageio_avif: make legacy overrides AVIF specific
  src/common/colorspaces.c
  src/common/colorspaces.h
  src/common/imageio_avif.c
Labels: scope: color management, scope: codebase

#10308 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#10314 Ensure that highlighted combobox item is selected on button press
  src/bauhaus/bauhaus.c
Labels: bugfix

#10323 Spanish translation update
  po/es.po
Labels: scope: translation

#10325 Spanish translation update
  po/es.po
Labels: scope: translation

#10331 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#10334 Spanish translation update
  po/es.po
Labels: scope: translation

#10263 Fix Windows GCC 11 build
  CMakeLists.txt
  src/common/imageio_dng.h
  src/iop/colorbalance.c
  src/win/win.h
Labels: bugfix, wip, scope: codebase, scope: windows support

#10338 Update de.po
  po/de.po
Labels: scope: translation

#10335 po/fix print area
  src/common/cups_print.c
  src/common/cups_print.h
  src/common/printing.c
  src/common/printing.h
  src/libs/print_settings.c
  src/views/print.c
Labels: bugfix, feature: enhancement, priority: high, scope: codebase, documentation-pending, release notes: pending

#10345 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#10351 Improve up/down french translation
  po/fr.po
Labels: scope: translation

#10346 Spanish translation update
  po/es.po
Labels: scope: translation

#10347 Updates to eo.po
  po/eo.po
Labels: scope: translation

#10353 Better spacing for filter-box area and collections arrow
  data/themes/darktable.css
Labels: bugfix, difficulty: trivial, scope: UI

#10356 Better filter-box spacing
  data/themes/darktable.css
Labels: scope: UI

#10340 qap : use module gui order
  src/libs/modulegroups.c
Labels: bugfix, priority: medium, difficulty: average, scope: UI

#10355 build: add -ftree-vectorize in RELWITHDEBINFO mode.
  src/CMakeLists.txt
Labels: scope: performance, scope: codebase

#10361 noise profiles
  data/noiseprofiles.json
Labels: scope: noise profile

#10358 show all modules in history in modulegroup active group
  src/libs/history.c
  src/libs/modulegroups.c
Labels: feature: enhancement, feature: new, difficulty: average, scope: UI, documentation-pending, release notes: pending

#10363 modulegroups : fix save if no group
  src/libs/modulegroups.c
Labels: bugfix, difficulty: trivial

#10364 modulegroups: amend label and add tooltip
  src/libs/modulegroups.c
Labels: documentation-pending

#10365 Update Esperanto translation.
  po/eo.po
Labels: scope: translation

#10377 Spanish translation update
  po/es.po
Labels: scope: translation

#10374 Fix segfault in waveform scope
  src/libs/histogram.c
Labels: bugfix

#10376 Fix as shot combobox option
  src/iop/channelmixerrgb.c
Labels: bugfix, priority: high

#10378 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#10379 Update Esperanto translation.
  po/eo.po
Labels: scope: translation

#10383 Spanish translation update
  po/es.po
Labels: scope: translation

#10387 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#10390 Spanish translation update
  po/es.po
Labels: scope: translation

#10392 Updated Swedish translation
  po/sv.po
Labels: scope: translation

#10394 Update de.po
  po/de.po
Labels: scope: translation

#10397 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#10395 geotagging: extends date before unix epoch -> 01/01/01 00:00:00
  src/libs/geotagging.c
Labels: bugfix, feature: enhancement, scope: DAM

#10406 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#10403 culling : fix ctrl-shift-scroll to zoom specific image
  src/dtgtk/culling.c
Labels: bugfix, priority: high, difficulty: trivial, scope: UI

#10407 Spanish translation update
  po/es.po
Labels: scope: translation

#10402 Fix: correct name for Canon EOS M50 Mark II in adobe_coeff.c
  src/external/adobe_coeff.c
Labels: bugfix

#10415 Update Esperanto translation.
  po/eo.po
Labels: scope: translation

#10417 colorbalancergb: fix black pixels in gamut mapping
  data/kernels/extended.cl
  src/iop/colorbalancergb.c
Labels: bugfix, priority: high, scope: image processing

#10404 export exif tag: use rational type when necessary
  src/common/exif.cc
Labels: bugfix, scope: DAM

#10408 add act_on debug switch to show the ids of the images to act on list
  src/common/darktable.c
  src/common/darktable.h
  src/views/view.c
Labels: feature: enhancement, difficulty: trivial, scope: codebase

#10427 Spanish translation update
  po/es.po
Labels: scope: translation

#10429 cmake: Make sure libraw is a static library
  src/external/LibRaw-cmake/CMakeLists.txt
Labels: scope: codebase

#10431 Spanish translation update
  po/es.po
Labels: scope: translation

#10420 colorbalancergb: don't soft-clip the sat fallback value
  data/kernels/extended.cl
  src/iop/colorbalancergb.c
Labels: bugfix, priority: high

#10436 Spanish translation update
  po/es.po
Labels: scope: translation

#10424 Do not overwrite link between action and widget if exists
  src/gui/accelerators.c
  src/views/darkroom.c
Labels: bugfix

#10442 imageio_libraw: minor error reporting improvements
  src/common/imageio_libraw.c
  src/external/LibRaw-cmake/CMakeLists.txt
  src/external/LibRaw-cmake/cmake/data/libraw.pc.cmake
  src/external/LibRaw-cmake/cmake/data/libraw_r.pc.cmake
Labels: feature: enhancement

#10444 export exif tag: if value already rational use it
  src/common/exif.cc
Labels: bugfix

#10447 po/help-l10n
  data/darktableconfig.xml.in
  src/libs/tools/global_toolbox.c
Labels: bugfix

#10450 Spanish translation update
  po/es.po
Labels: scope: translation

#10456 Update de.po
  po/de.po
Labels: scope: translation

#10454 usermanual_url: remove extraneous slash
  src/common/usermanual_url.c
Labels: bugfix

#10458 shortcuts: add global/no-op action
  src/gui/gtk.c
Labels: scope: UI, documentation-pending

#10455 ashift : fix reuse of direct straigthening
  src/iop/ashift.c
Labels: bugfix, difficulty: trivial

#10459 correctly count input drivers
  src/gui/accelerators.c
Labels: bugfix

#10462 ignore unmatched moves if fallbacks disabled
  src/gui/accelerators.c
Labels: bugfix, scope: UI

#10428 noiseprofiles: update Leica M10 model string
  data/noiseprofiles.json
Labels: feature: enhancement, scope: noise profile

#10463 windows packaging: add packages to support midi devices for NG Input
  packaging/windows/BUILD.md
Labels: feature: enhancement, scope: windows support

#10357 wb_presets: sync Ricoh GR II w/ rawspeed
  src/external/wb_presets.c
Labels: scope: camera support

#10464 update 'location' french translation
  po/fr.po
Labels: scope: translation

#10469 fix stuck grabs in mapping mode
  src/gui/accelerators.c
Labels: bugfix

#10471 Spanish translation update
  po/es.po
Labels: scope: translation

#10466 collect : fix folder expand
  src/libs/collect.c
Labels: bugfix, difficulty: trivial, scope: DAM

#10476 translation to french: small fixes
  po/fr.po
Labels: scope: translation

#10472 cmake: use global OPENMP option for libraw as well
  src/CMakeLists.txt
Labels: scope: windows support

#10484 ci: cover more features on Linux and Windows
  .ci/Dockerfile
  .github/workflows/ci.yml
  .github/workflows/manualrun.yml
  .github/workflows/nightly.yml
Labels: bugfix

#10485 prevent accidental mouse move direction changes
  src/gui/accelerators.c
Labels: bugfix

#10487 export iptc: clean up the original ones when necessary
  src/common/exif.cc
Labels: bugfix, scope: DAM

#10491 Remove modules deprecated in 3.4 from deprecated module group.
  src/libs/modulegroups.c
Labels: difficulty: trivial, scope: codebase, documentation-pending

#10492 ashift: do now go back to lighttable on double click.
  src/iop/ashift.c
Labels: bugfix, priority: high, difficulty: trivial, scope: UI

#10493 crop : remove double-click to apply feature
  src/iop/crop.c
Labels: bugfix, difficulty: trivial, scope: UI

#10490 fixes small issues pinpointed by lgtm
  src/common/gpx.c
  src/views/map.c
Labels: bugfix

#10494 Update italian translation
  po/it.po
Labels: scope: translation

#10495 Update Esperanto translation.
  po/eo.po
Labels: scope: translation

#10496 colorzones: fix creating curve based on area picker
  src/iop/colorzones.c
Labels: bugfix, priority: high, scope: UI

#10479 imageio_libraw: skip dcraw_process()
  .github/workflows/ci.yml
  src/common/imageio_libraw.c
Labels: bugfix, feature: enhancement, priority: high, scope: image processing

#10506 utility: correctly handle SVG scale with librsvg 2.52
  src/common/utility.c
Labels: bugfix, priority: high

#10500 Add context to some strings to allow for correct translations
  src/gui/accelerators.c
Labels: scope: translation

#10509 Update de.po
  po/de.po
Labels: scope: translation

#10510 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#10512 po/fix print box
  src/libs/print_settings.c
Labels: bugfix, priority: high, understood: clear, scope: codebase

#10513 lens: only display trouble warning if enabled
  src/iop/lens.cc
Labels: bugfix

#10515 only keep modules with no earlier history entry
  src/develop/develop.c
Labels: bugfix

#10516 collect: return focus to center after changing collection
  src/libs/collect.c
Labels: bugfix

#10504 use proxy function to obtain wb coefficients
  src/develop/develop.c
  src/develop/develop.h
  src/iop/channelmixerrgb.c
  src/iop/temperature.c
  src/views/darkroom.c
Labels: bugfix, priority: high, difficulty: average, scope: codebase

#10517 move focus widget before deleting multi-instance
  src/develop/imageop.c
  src/libs/history.c
Labels: bugfix
