Repository darktable-org/darktable, pull requests merged in 2021-04, with the labels that each got.

#8591 Fix lua text view wrap
  RELEASE_NOTES.md
  src/lua/widget/text_view.c
Labels: bugfix, lua

#8593 colorbalancergb : improve the saturation equation
  src/iop/colorbalancergb.c
Labels: feature: enhancement

#8602 denoiseprofile: fix legacy support.
  src/iop/denoiseprofile.c
Labels: bugfix, priority: high

#8601 Update Esperanto translation.
  po/eo.po
Labels: scope: translation

#8607 [CI] Explicitly add dependency on python3-six
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
Labels: scope: codebase

#8608 windows: Add openssl libraries to windows package (fixes #6856)
  cmake/windows-macros.cmake
Labels: scope: OS support

#8603 Fix liveview scaling for proper display on 4k HiDPI screen.
  src/libs/live_view.c
  src/views/tethering.c
Labels: bugfix, priority: medium, scope: UI

#8599 po/fix wb modern old
  src/develop/blend.c
  src/develop/develop.c
Labels: bugfix, difficulty: average, priority: high, scope: color management, scope: image processing, understood: clear

#8624 Update zh_CN.po
  po/zh_CN.po
Labels: scope: translation

#8622 Update de.po
  po/de.po
Labels: scope: translation

#8621 import fix: remove redundant "ignore jpeg" flags in module parameters
  src/libs/import.c
Labels: bugfix

#8615 Using RCD demosaicer as default for bayer sensors
  src/iop/demosaic.c
Labels: documentation-pending, feature: redesign, scope: image processing

#8625 Fixing local contrast CPU code precision
  src/common/locallaplacian.c
Labels: bugfix, scope: image processing, scope: performance

#8617 Make modules and user aware of history problems via dt_dev_pixelpipe_synch
  src/develop/pixelpipe_hb.c
Labels: documentation-pending, feature: enhancement, scope: UI, scope: codebase

#8626 Changing RCD demosaicer also in the darkroom preferences
  data/darktableconfig.xml.in
  src/common/darktable.c
Labels: documentation-pending, feature: enhancement

#8628 RCD and dual demosaicer maintenance updates
  data/kernels/demosaic_rcd.cl
  src/develop/masks.h
  src/develop/masks/detail.c
  src/develop/masks/masks.c
  src/iop/demosaic.c
  src/iop/dual_demosaic.c
  src/iop/rcd_demosaic.c
Labels: difficulty: average, scope: codebase

#8631 collect: use integer focal lengths
  src/common/collection.c
  src/libs/collect.c
Labels: bugfix, difficulty: trivial, scope: UI

#8568 Map locations: add polygon shape (kind of)
  data/darktableconfig.xml.in
  src/common/database.c
  src/common/geo.h
  src/common/map_locations.c
  src/common/map_locations.h
  src/control/jobs/control_jobs.c
  src/control/signal.c
  src/control/signal.h
  src/dtgtk/paint.c
  src/dtgtk/paint.h
  src/gui/preferences.c
  src/libs/geotagging.c
  src/libs/location.c
  src/libs/map_locations.c
  src/libs/map_settings.c
  src/views/map.c
Labels: documentation-pending, feature: enhancement, feature: new

#8633 import fix: fix seg fault regression due to pr #8621
  src/libs/import.c
Labels: bugfix

#8638 rcd and dual demosaicers used sqf( inline function wrongfully
  src/develop/masks/detail.c
  src/develop/masks/masks.c
  src/iop/demosaic.c
  src/iop/dual_demosaic.c
  src/iop/rcd_demosaic.c
Labels: bugfix, priority: high

#8641 fix mask manager crash
  src/libs/masks.c
Labels: bugfix, priority: high

#8639 colorbalancergb: make the mask preview checkerboard parametric
  src/iop/colorbalancergb.c
Labels: feature: enhancement

#8652 Update Esperanto translation.
  po/eo.po
Labels: scope: translation

#8655 add explicit dependency on generate_conf
  src/CMakeLists.txt
Labels: scope: codebase

#8648 preferences: remember previous dialog size
  data/darktableconfig.xml.in
  src/gui/preferences.c
  tools/generate_prefs.xsl
Labels: difficulty: trivial, feature: enhancement, scope: UI

#8658 Update de.po
  po/de.po
Labels: scope: translation

#8640 po/fix duplicate old hist
  src/common/image_cache.c
  src/common/image_cache.h
  src/control/jobs/control_jobs.c
  src/dtgtk/thumbtable.c
Labels: bugfix, priority: high

#8660 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#8663 accelerators: clarify accel tooltip
  src/gui/accelerators.c
Labels: feature: enhancement

#8662 export: set tab order
  src/libs/export.c
Labels: feature: enhancement

#8095 usermanual: update links to new manual.
  src/common/usermanual_url.c
  src/develop/blend_gui.c
  src/develop/imageop.c
  src/libs/camera.c
  src/libs/copy_history.c
  src/libs/export.c
  src/libs/image.c
  src/libs/import.c
  src/libs/live_view.c
  src/libs/metadata.c
  src/libs/print_settings.c
  src/libs/select.c
  src/libs/session.c
  src/libs/snapshots.c
  src/libs/styles.c
  src/libs/tagging.c
  src/libs/tools/global_toolbox.c
  src/views/view.c
Labels: bugfix, priority: high, scope: UI, scope: usermanual

#8668 Spanish translation update
  po/es.po
Labels: scope: translation

#8672 dt_conf : check default value for existence too
  data/darktableconfig.xml.in
  src/control/conf.c
Labels: bugfix, difficulty: trivial

#8670 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#8674 po/lens transform
  src/develop/blend.c
  src/iop/lens.cc
Labels: bugfix, feature: enhancement, priority: high

#8616 Sidepanel continuous scrolling for macOS
  src/bauhaus/bauhaus.c
  src/dtgtk/gradientslider.c
  src/gui/gtk.c
  src/iop/basecurve.c
  src/iop/colorchecker.c
  src/iop/colorcorrection.c
  src/iop/colorzones.c
  src/iop/levels.c
  src/iop/monochrome.c
  src/iop/retouch.c
  src/iop/rgbcurve.c
  src/iop/rgblevels.c
  src/iop/tonecurve.c
  src/iop/toneequal.c
  src/libs/geotagging.c
  src/views/darkroom.c
Labels: bugfix, priority: high

#8679 fix full preview zoom crash
  src/common/image.c
Labels: bugfix, priority: high

#8678 fix function declaration
  src/common/iop_profile.h
Labels: scope: codebase

#8098 colorspaces: check for CLUT in all ICC intents before extracting matrix
  src/common/colorspaces.c
  src/common/colorspaces.h
  src/common/iop_profile.c
  src/iop/colorin.c
  src/iop/colorout.c
Labels: feature: redesign, no-pr-activity

#8683 Updated Dutch translation
  po/nl.po
Labels: scope: translation

#8684 Update de.po
  po/de.po
Labels: scope: translation

#8688 Parallelize distorts
  src/common/math.h
  src/iop/ashift.c
  src/iop/borders.c
  src/iop/clipping.c
  src/iop/flip.c
  src/iop/lens.cc
  src/iop/liquify.c
  src/iop/rawprepare.c
  src/iop/rotatepixels.c
Labels: feature: enhancement, scope: performance

#8669 Fix timeline zooming for smooth scroll devices
  src/libs/tools/timeline.c
Labels: feature: enhancement, scope: UI

#8689 Fix misaligned drawn masks.
  src/iop/rawprepare.c
Labels: bugfix, priority: high

#8693 Update Esperanto translation.
  po/eo.po
Labels: scope: translation

#8694 Add noise profiles for Olympus E-M10 Mark IV
  data/noiseprofiles.json
Labels: scope: noise profile

#8682 masks : make the samples aware of distortions
  src/develop/masks.h
  src/develop/masks/brush.c
  src/develop/masks/circle.c
  src/develop/masks/ellipse.c
  src/develop/masks/gradient.c
  src/develop/masks/masks.c
  src/develop/masks/path.c
Labels: difficulty: hard, documentation-pending, feature: enhancement, scope: UI

#8696 Fixing rcd border zipper artefacts
  data/kernels/demosaic_rcd.cl
  src/develop/masks/detail.c
  src/iop/demosaic.c
  src/iop/dual_demosaic.c
  src/iop/rcd_demosaic.c
Labels: scope: codebase, scope: image processing

#8698 iop: resize drawing areas with Ctrl+scroll
  data/darktableconfig.xml.in
  src/iop/atrous.c
  src/iop/colorzones.c
  src/iop/denoiseprofile.c
  src/iop/filmicrgb.c
  src/iop/levels.c
  src/iop/lowlight.c
  src/iop/rawdenoise.c
  src/iop/rgblevels.c
Labels: documentation-pending, feature: enhancement

#8676 retouch : fix shift compute if distortion before
  data/darktableconfig.xml.in
  src/iop/retouch.c
Labels: bugfix, difficulty: hard, documentation-pending, scope: image processing

#8709 colorbalancergb: allow drawing area to be resized with Ctrl+scroll
  data/darktableconfig.xml.in
  src/iop/colorbalancergb.c
Labels: documentation-pending, feature: enhancement

#8712 spots : deprecate in favor of retouch
  src/iop/spots.c
  src/libs/modulegroups.c
Labels: difficulty: trivial, documentation-pending, feature: new, scope: image processing

#8723 prefs ui: use dt_ui_label_new()
  src/gui/preferences.c
Labels: scope: UI, scope: codebase

#8713 preferences: make scene-referred workflow the default
  data/darktableconfig.xml.in
Labels: scope: codebase, scope: image processing

#8720 interpolation: use for_each_channel macro to vectorize the loops
  src/common/interpolation.c
Labels: scope: performance

#8721 po/overlapping path sel
  src/develop/masks.h
  src/develop/masks/brush.c
  src/develop/masks/circle.c
  src/develop/masks/ellipse.c
  src/develop/masks/gradient.c
  src/develop/masks/group.c
  src/develop/masks/masks.c
  src/develop/masks/path.c
Labels: bugfix, scope: UI, wip

#8711 Add a parallel for in gradient points computation.
  src/common/darktable.h
  src/develop/masks/gradient.c
Labels: scope: codebase

#8719 correct the order in which images are exported
  src/common/selection.c
Labels: bugfix

#8707 allow modules to be resized larger than current content
  src/gui/gtk.c
Labels: bugfix

#8666 Clarify delete button (part 2)
  data/darktableconfig.xml.in
  src/control/jobs/control_jobs.c
  src/libs/image.c
Labels: documentation-pending, feature: enhancement, scope: UI

#8704 make module section labels stand out more
  data/themes/darktable-elegant-dark.css
  data/themes/darktable-elegant-grey.css
  data/themes/darktable.css
Labels: scope: UI

#8730 Update de.po
  po/de.po
Labels: scope: translation

#8732 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#8726 gradient mask : lower curvature step + allow to set up at creation
  src/develop/masks/gradient.c
Labels: bugfix, difficulty: trivial, documentation-pending, feature: enhancement, scope: UI

#8724 watermark: simple-text preserve spaces.
  data/watermarks/simple-text.svg
Labels: bugfix, feature: enhancement

#8722 qap : show masks if search is active
  src/develop/develop.c
  src/develop/develop.h
  src/iop/ashift.c
  src/iop/clipping.c
  src/libs/modulegroups.c
  src/views/darkroom.c
Labels: bugfix, difficulty: average, scope: UI

#8706 PPG demosaicer maintenance
  data/kernels/demosaic_ppg.cl
  src/iop/demosaic.c
Labels: scope: codebase, scope: performance

#8736 liquify: do not run the pipe on button press.
  src/iop/liquify.c
Labels: bugfix, difficulty: trivial, priority: medium, scope: performance

#8740 Filmicrgb fix resize inadvertently scrolling sidpanel
  src/iop/filmicrgb.c
Labels: bugfix, priority: high

#8743 Update Dutch translation
  po/nl.po
Labels: scope: translation

#8746 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#8734 import: remove first stage dialog and add folder pane
  data/darktableconfig.xml.in
  src/libs/import.c
Labels: difficulty: hard, documentation-pending, feature: redesign, priority: high, scope: DAM, scope: UI

#8754 vibrance: change deprecation message
  src/iop/vibrance.c
Labels: documentation-pending

#8751 Enable exiv2 ISOBMFF support for CR3 and HEIF files
  DefineOptions.cmake
  cmake/modules/FindExiv2.cmake
  src/CMakeLists.txt
  src/common/exif.cc
Labels: feature: enhancement

#8756 import: save the 10 last root folders + fix default root values
  src/libs/import.c
Labels: documentation-pending, feature: enhancement

#8759 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#8005 vectorscope variant for histogram
  data/darktableconfig.xml.in
  data/themes/darktable.css
  src/bauhaus/bauhaus.c
  src/bauhaus/bauhaus.h
  src/dtgtk/paint.c
  src/dtgtk/paint.h
  src/iop/rgbcurve.c
  src/iop/rgblevels.c
  src/libs/histogram.c
Labels: documentation-pending, feature: new, scope: UI

#8760 Update Esperanto translation.
  po/eo.po
Labels: scope: translation

#8767 Disable fast math for RCD demosaicer again
  src/iop/rcd_demosaic.c
Labels: bugfix

#8747 module warnings: add a pref to hide them
  data/darktableconfig.xml.in
  src/develop/imageop.c
Labels: difficulty: trivial, feature: enhancement

#8758 import: on root folder change set it as last directory by default
  src/libs/import.c
Labels: feature: enhancement

#8772 Update de.po
  po/de.po
Labels: scope: translation

#8770 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#8764 filmicrgb: add rational function to toe/shoulder
  data/kernels/filmic.cl
  src/iop/filmicrgb.c
Labels: difficulty: trivial, feature: enhancement, scope: image processing

#8771 exposure: increase soft limit
  src/iop/exposure.c
Labels: documentation-pending, feature: enhancement

#8244 Clickable link in shortened lock-error-message
  src/common/database.c
Labels: feature: redesign, scope: UI, wip

#8783 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#8786 import from camera: bug fix
  src/libs/import.c
Labels: bugfix

#8784 interpolations: clip negative RGB
  data/kernels/basic.cl
  src/common/interpolation.c
Labels: bugfix, priority: high, scope: image processing

#8777 limit GUI update rate for faster import
  src/control/jobs/control_jobs.c
Labels: feature: enhancement, scope: performance

#8778 lua fix dirty stack
  src/lua/events.c
  src/lua/luastorage.c
Labels: bugfix

#8775 Fix build with OpenEXR 3
  src/CMakeLists.txt
Labels: feature: enhancement

#8788 enable entering of exponential expressions with German keyboard layout
  src/bauhaus/bauhaus.c
Labels: bugfix

#8789 gradient mask : update hint msg
  src/develop/masks/gradient.c
Labels: difficulty: trivial, feature: enhancement, scope: UI

#8787 import: speed up files list and folders views
  src/libs/import.c
Labels: feature: enhancement

#8795 iops: fix GtkDarktableDrawingArea resize on scroll
  src/iop/atrous.c
  src/iop/colorbalancergb.c
  src/iop/colorzones.c
  src/iop/denoiseprofile.c
  src/iop/filmicrgb.c
  src/iop/levels.c
  src/iop/lowlight.c
  src/iop/rawdenoise.c
  src/iop/rgblevels.c
Labels: bugfix, priority: high

#8796 histogram: move waveform math from draw to process
  src/libs/histogram.c
Labels: priority: high, scope: performance

#8802 import: fix pref issue (use bool instead of string)
  src/libs/import.c
Labels: bugfix

#8801 fix collect tooltips
  src/libs/collect.c
Labels: feature: enhancement, scope: UI

#8798 po/skip already imported
  data/darktableconfig.xml.in
  src/common/image.c
  src/common/image.h
  src/libs/import.c
Labels: documentation-pending, feature: enhancement, scope: DAM

#8812 improve waveform and RGB parade appearance
  src/libs/histogram.c
Labels: feature: enhancement, scope: UI, scope: codebase, scope: performance

#8811 import: fix unworking gtk_tree_view_scroll_to_cell()
  src/libs/import.c
Labels: bugfix, feature: enhancement, scope: UI

#8817 Allow RCD fast-math again after checks
  data/kernels/demosaic_rcd.cl
  src/iop/rcd_demosaic.c
Labels: scope: codebase, scope: performance

#8808 FIX: ImageMagick is missing in loaders name list
  src/libs/metadata_view.c
Labels: bugfix

#8815 slightly increase padding between module sections and centre-align
  data/themes/darktable.css
  src/gui/gtk.h
Labels: feature: enhancement, scope: UI

#8819 remove button/checkbox focus highlighting
  data/themes/darktable.css
Labels: bugfix

#8785 po/help new module
  data/darktableconfig.xml.in
  src/common/darktable.c
  src/common/darktable.h
  src/common/usermanual_url.c
  src/libs/tools/global_toolbox.c
  src/libs/tools/lighttable.c
  src/libs/tools/timeline.c
Labels: feature: enhancement

#8821 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#8828 import: small spacing between selection buttons
  src/libs/import.c
Labels: difficulty: trivial, feature: enhancement, scope: UI
