Repository darktable-org/darktable, pull requests merged in 2021-07, with the labels that each got.

#9361 fix a use-after free in concurrent code
  src/control/jobs/control_jobs.c
Labels: bugfix, scope: DAM, scope: codebase

#9356 use g_strcmp0 in widget warn mechanism to prevent crash on null
  src/views/darkroom.c
Labels: scope: codebase

#9364 perspective : don't try to crop if image is nor ready
  src/iop/ashift.c
Labels: bugfix, difficulty: trivial, scope: image processing

#9133 crop : sanitize values in crop and c&r
  src/iop/clipping.c
  src/iop/crop.c
Labels: bugfix, difficulty: trivial, scope: image processing

#9327 add flip actions to orientation module
  src/dtgtk/paint.c
  src/iop/flip.c
Labels: difficulty: trivial, documentation-pending, feature: new, scope: image processing

#9379 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#9276 Introducing a LMMSE demosaicer
  po/POTFILES.in
  src/iop/demosaic.c
  src/iop/lmmse_demosaic.c
Labels: documentation-pending, scope: image processing

#8955 Getting rid of the background jobs config parameter
  data/darktableconfig.xml.in
  src/common/darktable.c
  src/common/darktable.h
  src/common/mipmap_cache.c
  src/control/jobs.c
Labels: feature: enhancement, scope: performance

#9278 Rcd maintenance 6
  src/iop/rcd_demosaic.c
Labels: scope: codebase, scope: image processing, scope: performance

#9330 preferences: only text should be translatable
  src/gui/preferences.c
Labels: bugfix, scope: UI, scope: translation

#9388 partially revert 3202ff6 to fix #9380
  src/develop/imageop.c
Labels: bugfix, priority: high

#9394 flag preview shortcuts as handled by lighttable
  src/views/lighttable.c
Labels: bugfix

#9405 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#9396 fix altgr and virtual modifiers
  src/gui/accelerators.c
Labels: bugfix, scope: UI

#9406 channelmixerrgb : try to fix #9399 / partially revert ff3eb7e
  data/kernels/channelmixer.cl
  src/iop/channelmixerrgb.c
Labels: bugfix, priority: high, scope: image processing

#9390 (docs) update README.md
  README.md
Labels: scope: usermanual

#9408 import: fix already imported flag in subfolders
  src/common/image.c
  src/common/image.h
  src/libs/import.c
Labels: bugfix, scope: UI

#9368 import: open in darkroom when [add to library] a unique image
  src/control/jobs/control_jobs.c
  src/libs/import.c
Labels: bugfix, documentation-pending, scope: DAM, scope: UI

#9383 add incremental search to tooltips in shortcuts dialog
  src/gui/accelerators.c
Labels: feature: enhancement, scope: UI

#9401 Fixing green equilibration in RCD cpu code path
  src/iop/demosaic.c
Labels: bugfix, scope: image processing

#9410 qap : don't try to expand full module on module on/off
  src/develop/imageop.c
Labels: bugfix, scope: UI

#9343 refactor: encapsulate getting/setting folders in preferences
  src/control/conf.c
  src/control/conf.h
  src/control/jobs/control_jobs.c
  src/gui/preferences.c
  src/gui/presets.c
  src/libs/copy_history.c
  src/libs/geotagging.c
  src/libs/import.c
  src/libs/styles.c
Labels: scope: codebase

#9416 exif: fix syntax error
  src/common/exif.cc
Labels: bugfix, scope: codebase

#9398 windows/build.md: remove gmic outdated comment (library mismatches have gone)
  packaging/windows/BUILD.md
Labels: bugfix

#9415 more robustly find double/triple press shortcuts
  src/gui/accelerators.c
Labels: bugfix

#9395 make show/expand default for module shortcut
  src/develop/imageop.c
Labels: scope: UI

#7669 add a diffusion module
  data/kernels/diffuse.cl
  data/kernels/programs.conf
  po/POTFILES.in
  src/common/iop_order.c
  src/common/opencl.c
  src/iop/CMakeLists.txt
  src/iop/diffuse.c
Labels: documentation-pending, feature: new, release notes: pending, scope: image processing

#9430 colorbalancergb: rename global brilliance slider
  src/iop/colorbalancergb.c
Labels: difficulty: trivial, documentation-pending, scope: UI

#9424 More precise error message for non-standard bayer filters
  src/iop/cacorrect.c
Labels: bugfix, scope: UI

#9442 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#9437 print: skip areas not populated with an image.
  src/libs/print_settings.c
Labels: bugfix

#9422 Remember the shortcuts dialog size between sessions.
  data/darktableconfig.xml.in
  src/libs/tools/global_toolbox.c
Labels: feature: enhancement, priority: low, scope: UI

#9419 When try-enter fails make sure we select back the previous view.
  src/views/view.c
Labels: bugfix, priority: low

#9423 Selecting the best illuminant for dng images
  src/common/exif.cc
  src/common/exif.h
Labels: bugfix, feature: enhancement, scope: camera support, scope: image processing

#9409 Update simplified chinese translation
  po/zh_CN.po
Labels: scope: translation

#8891 generalize guides
  data/themes/darktable.css
  src/develop/develop.c
  src/develop/develop.h
  src/develop/imageop.c
  src/develop/imageop.h
  src/gui/gtk.c
  src/gui/guides.c
  src/gui/guides.h
  src/gui/presets.c
  src/iop/ashift.c
  src/iop/borders.c
  src/iop/clipping.c
  src/iop/crop.c
  src/iop/flip.c
  src/iop/iop_api.h
  src/iop/lens.cc
  src/iop/liquify.c
  src/iop/retouch.c
  src/libs/live_view.c
  src/views/darkroom.c
  src/views/view.h
Labels: difficulty: hard, documentation-pending, feature: redesign, scope: UI, wip

#9446 Add default values to plugins/lighttable/collect/num_rules and plugins/lighttable/collect/string0
  data/darktableconfig.xml.in
Labels: bugfix

#9455 fix translation of key_pressed_accel
  src/gui/accelerators.c
Labels: bugfix

#9441 select area color picker with right-click
  src/gui/color_picker_proxy.c
  src/libs/colorpicker.c
Labels: documentation-pending, feature: enhancement, scope: UI

#9440 cleanup: prefer g_strdup_printf over dt_util_dstrcat
  src/bauhaus/bauhaus.c
  src/common/collection.c
  src/common/database.c
  src/common/history.c
  src/common/iop_group.c
  src/common/metadata.c
  src/common/metadata_export.c
  src/common/selection.c
  src/common/tags.c
  src/develop/imageop.c
  src/dtgtk/culling.c
  src/dtgtk/thumbnail.c
  src/dtgtk/thumbtable.c
  src/gui/gtk.c
  src/gui/import_metadata.c
  src/gui/presets.c
  src/iop/retouch.c
  src/libs/collect.c
  src/libs/export.c
  src/libs/export_metadata.c
  src/libs/geotagging.c
  src/libs/import.c
  src/libs/lib.c
  src/libs/location.c
  src/libs/map_locations.c
  src/libs/metadata.c
  src/libs/metadata_view.c
  src/libs/modulegroups.c
  src/libs/tagging.c
  src/libs/tools/global_toolbox.c
  src/views/darkroom.c
  src/views/lighttable.c
  src/views/map.c
  src/views/slideshow.c
  src/views/view.c
Labels: scope: codebase

#9465 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#9462 cleanup: g_strdup_printf("%s", ...) -> g_strdup(...)
  src/common/database.c
  src/control/conf.c
  src/develop/develop.c
  src/develop/imageop.c
  src/dtgtk/thumbnail.c
  src/gui/presets.c
  src/libs/history.c
  src/libs/modulegroups.c
Labels: scope: codebase, scope: performance

#9467 change 'enable' to 'toggle' in focus-peaking button tooltip
  src/gui/gtk.c
Labels: scope: UI

#9122 Monochrome images need one blackpoint correction in rawprepare, performance gains
  src/iop/rawprepare.c
Labels: feature: new, scope: image processing, scope: performance

#9479 Fixing wrong exiv2 version check for color illuminants
  src/common/exif.cc
Labels: bugfix, priority: high

#9373 Pollish Input NG buttons
  src/libs/history.c
  src/libs/tagging.c
Labels: bugfix

#9488 Update of preset scene-referred default blend mode in exposure module
  src/iop/exposure.c
Labels: bugfix

#9355 minimize copying of configuration/preference strings
  src/common/collection.c
  src/common/collection.h
  src/common/colorspaces.c
  src/common/database.c
  src/common/imageio_module.c
  src/common/import_session.c
  src/common/interpolation.c
  src/common/iop_order.c
  src/common/l10n.c
  src/common/metadata_export.c
  src/common/mipmap_cache.c
  src/common/mipmap_cache.h
  src/common/opencl.c
  src/common/pwstorage/pwstorage.c
  src/control/conf.c
  src/control/conf.h
  src/control/jobs/camera_jobs.c
  src/develop/blend.c
  src/develop/develop.c
  src/develop/imageop.c
  src/develop/masks/brush.c
  src/dtgtk/thumbnail.c
  src/dtgtk/thumbtable.c
  src/gui/gtk.c
  src/gui/import_metadata.c
  src/gui/preferences.c
  src/gui/presets.c
  src/imageio/format/avif.c
  src/imageio/format/pdf.c
  src/imageio/format/png.c
  src/imageio/format/tiff.c
  src/imageio/format/xcf.c
  src/imageio/storage/disk.c
  src/imageio/storage/gallery.c
  src/imageio/storage/latex.c
  src/iop/colorbalance.c
  src/iop/demosaic.c
  src/iop/filmicrgb.c
  src/iop/temperature.c
  src/iop/watermark.c
  src/libs/collect.c
  src/libs/export.c
  src/libs/histogram.c
  src/libs/import.c
  src/libs/location.c
  src/libs/map_settings.c
  src/libs/metadata_view.c
  src/libs/modulegroups.c
  src/libs/print_settings.c
  src/libs/recentcollect.c
  src/libs/session.c
  src/libs/tagging.c
  src/libs/tools/image_infos.c
  src/lua/format.c
  src/lua/preferences.c
  src/views/darkroom.c
  src/views/map.c
  src/views/tethering.c
Labels: scope: codebase, scope: performance

#9489 guides : don't store translated settings
  src/gui/guides.c
Labels: bugfix, difficulty: trivial, scope: UI

#9354 lib preset dialog refactor + allow iop order to autoapply
  src/common/presets.c
  src/common/presets.h
  src/gui/preferences.c
  src/gui/presets.c
  src/libs/ioporder.c
  src/libs/lib.c
Labels: bugfix, documentation-pending, feature: enhancement, scope: UI, scope: codebase

#9434 expand right action tree in preferences/shortcuts
  src/gui/accelerators.c
Labels: scope: UI

#9493 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#9494 Fix recently introduced free/double_free error while importing
  src/libs/import.c
Labels: bugfix

#9358 geotagging gpx: count collapsed grouped images as well (displayed message count)
  src/control/jobs/control_jobs.c
Labels: bugfix, scope: DAM, scope: UI

#9476 improve support for view::key_pressed shortcuts
  src/gui/accelerators.c
  src/views/darkroom.c
Labels: bugfix

#9089 Don't restrict roi_in for passthrough monochrome demosaicers
  src/iop/demosaic.c
Labels: feature: enhancement, scope: image processing

#9502 Fix minor french translation
  po/fr.po
Labels: scope: translation

#9498 Fix Windows import
  src/common/utility.c
Labels: bugfix, scope: windows support

#9420 collect: avoid folder status checking at display time
  src/common/darktable.c
  src/common/database.c
  src/common/film.c
  src/common/film.h
  src/libs/collect.c
Labels: bugfix

#9453 diffuse: remove unnecessary trigonometry
  data/kernels/diffuse.cl
  src/iop/diffuse.c
Labels: scope: image processing, scope: performance

#9288 variables.c: add substitutable variables for image dimensions
  src/common/variables.c
Labels: bugfix, documentation-pending, feature: enhancement, scope: DAM, scope: UI

#9431 use gtk_widget_activate to click non-toggle button
  src/gui/accelerators.c
Labels: bugfix

#9516 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#9341 make preset applicability wording a bit more obvious
  src/gui/presets.c
Labels: difficulty: trivial, documentation-pending, scope: UI

#9262 Expose OpenCL building options in darktablerc
  src/common/opencl.c
  src/common/opencl.h
Labels: feature: enhancement, scope: hardware support, scope: performance

#9524 bugfix: correctly manage strings for Places in import dialog
  src/libs/import.c
Labels: bugfix, priority: high

#9525 Fix typo in cmake/modules/FindLua54.cmake
  cmake/modules/FindLua54.cmake
Labels: bugfix

#9535 Update de.po
  po/de.po
Labels: scope: translation

#9533 collect: don't strike non folder leaves
  src/libs/collect.c
Labels: bugfix, scope: UI

#9537 Fix internal lua build
  src/external/lua/CMakeLists.txt
Labels: bugfix

#9534 zonesystem: ensure auto-vectorization and remove SSE codepath
  src/iop/zonesystem.c
Labels: scope: codebase, scope: image processing, scope: performance

#9536 velvia: remove SSE codepath
  src/iop/velvia.c
Labels: scope: codebase, scope: image processing, scope: performance

#9539 highlights: remove SSE code path
  src/iop/highlights.c
Labels: scope: codebase, scope: performance

#9541 fix focus peaking
  src/common/focus_peaking.h
Labels: bugfix, scope: UI, scope: codebase, scope: performance

#9540 update warning messages when using non-default codepath settings
  src/common/darktable.c
Labels: scope: codebase

#9545 sharpen: optimize code and remove SSE
  src/iop/sharpen.c
Labels: scope: performance

#9552 retouch: optimize heal tool and remove its SSE codepath
  src/common/heal.c
  src/common/heal.h
  src/develop/openmp_maths.h
  src/iop/retouch.c
Labels: scope: codebase, scope: image processing, scope: performance

#9555 whitebalance: optimize, remove SSE codepath
  src/iop/temperature.c
Labels: scope: codebase, scope: image processing, scope: performance

#9564 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#9561 [CI] Fix mac & windows ci to stop it from exploding on us
  .github/workflows/ci.yml
Labels: scope: macos support, scope: windows support

#9557 use gtk check menus to indicate choosen preset/blendmode
  data/themes/darktable.css
  src/develop/blend_gui.c
  src/gui/presets.c
  src/libs/lib.c
Labels: scope: UI

#9558 simplify preferences content
  data/darktableconfig.xml.in
  src/gui/preferences.c
  tools/generate_prefs.xsl
Labels: documentation-pending, feature: redesign, scope: UI

#9569 Fix add to library crash
  src/control/jobs/control_jobs.c
  src/control/jobs/film_jobs.c
Labels: bugfix

#9563 Show slider units in gui where units are known/meaningful
  src/develop/blend_gui.c
  src/iop/colorize.c
  src/iop/colorreconstruction.c
  src/iop/graduatednd.c
  src/iop/retouch.c
Labels: documentation-pending, feature: enhancement, scope: UI

#9556 [import] add browse button to base dir naming pattern
  src/libs/import.c
Labels: documentation-pending, feature: enhancement, scope: DAM, scope: UI

#9500 Add glib, gtk and other translation files to windows package
  cmake/windows-macros.cmake
Labels: scope: translation, scope: windows support

#9571 channelmixerrgb: clear color checker report on reset
  src/iop/channelmixerrgb.c
Labels: bugfix, feature: enhancement

#9553 retouch: remove clone/fill SSE codepaths
  src/iop/retouch.c
Labels: scope: codebase, scope: image processing, scope: performance, wip

#9578 eaw.c speedups
  src/common/eaw.c
Labels: scope: codebase, scope: performance

#9579 Ignore Windows key and language switches
  src/gui/accelerators.c
Labels: bugfix

#9583 Fixing module->trouble widget
  src/develop/imageop.c
Labels: bugfix

#9521 add module : scene-referred blurs
  data/kernels/blurs.cl
  data/kernels/programs.conf
  po/POTFILES.in
  src/common/iop_order.c
  src/iop/CMakeLists.txt
  src/iop/blurs.c
Labels: documentation-pending, release notes: pending, scope: image processing

#9605 Update de.po
  po/de.po
Labels: scope: translation

#9604 fix shortcut for compress history button
  src/libs/history.c
Labels: bugfix

#9606 little css fix and cleanup
  data/themes/darktable.css
Labels: scope: UI

#9609 diffuse: add central radius parameter
  src/iop/diffuse.c
Labels: documentation-pending, manual: update request, scope: image processing

#9610 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#9620 remove unnecessary memset
  src/develop/pixelpipe_hb.c
Labels: scope: codebase, scope: performance

#9607 let action list grab focus (so search works)
  src/gui/accelerators.c
Labels: bugfix

#9622 add type dt_boundingbox_t to hold a pair of point coordinates
  src/common/darktable.h
  src/common/exif.cc
  src/common/image.h
  src/develop/imageop.h
  src/develop/pixelpipe_hb.c
  src/gui/color_picker_proxy.c
  src/iop/ashift.c
  src/iop/basicadj.c
  src/iop/clipping.c
  src/iop/crop.c
  src/iop/graduatednd.c
  src/iop/rawoverexposed.c
  src/iop/retouch.c
  src/iop/rgblevels.c
  src/iop/rotatepixels.c
  src/iop/spots.c
  src/libs/colorpicker.h
Labels: scope: codebase

#9618 iop order: add pipe default pipe order for v3.0 JPEG
  src/common/iop_order.c
  src/common/iop_order.h
  src/libs/ioporder.c
Labels: feature: enhancement

#9332 update irc link
  CONTRIBUTING.md
Labels: scope: usermanual

#9632 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#9628 Improve preset checkbox
  data/themes/darktable-elegant-grey.css
  data/themes/darktable.css
  src/develop/blend_gui.c
  src/gui/presets.c
  src/libs/lib.c
Labels: feature: enhancement, scope: UI

#9634 rcd_demosaic: fix uninitialized-data access
  src/iop/rcd_demosaic.c
Labels: bugfix

#9636 metadata: update the fields after applying preset
  src/libs/metadata.c
Labels: bugfix, scope: DAM, scope: UI

#9646 lighttable filters: add sorting options
  src/libs/tools/filter.c
Labels: feature: enhancement, release notes: pending

#9652 Update lua enums in filter.c
  src/libs/tools/filter.c
Labels: bug: fixed, lua

#9651 iop: initialize variable in `dsvd()`
  src/iop/svd.h
Labels: scope: codebase

#9650 Fix crash in lua import filter
  src/control/jobs/control_jobs.c
  src/control/jobs/film_jobs.c
Labels: bugfix, lua

#9658 lua print toast and hinter messages
  src/lua/print.c
Labels: documentation-pending, feature: new, lua, release notes: pending

#9657 cleanup: use new dt_colormatrix_t type (Phase 1)
  src/CMakeLists.txt
  src/common/chromatic_adaptation.h
  src/common/color_picker.c
  src/common/colorspaces.c
  src/common/colorspaces.h
  src/common/colorspaces_inline_conversions.h
  src/common/darktable.h
  src/common/dttypes.h
  src/common/iop_profile.c
  src/common/iop_profile.h
  src/common/math.h
  src/common/matrices.c
  src/common/matrices.h
  src/develop/blend.c
  src/develop/blends/blendif_lab.c
  src/develop/blends/blendif_rgb_jzczhz.c
  src/develop/imageop_math.c
  src/develop/imageop_math.h
  src/iop/channelmixerrgb.c
  src/iop/colorbalancergb.c
  src/iop/colorin.c
  src/iop/colorout.c
  src/iop/denoiseprofile.c
  src/iop/retouch.c
  src/iop/toneequal.c
  src/libs/colorpicker.c
  src/libs/histogram.c
Labels: scope: codebase, scope: performance

#9659 speed up drawing ellipse mask
  src/develop/masks/ellipse.c
Labels: scope: codebase, scope: performance

#9637 exif: guard empty string writing by exiv2 version
  src/common/exif.cc
Labels: bugfix, scope: DAM, scope: software support

#9638 Add back support for DNG previews in import dialog
  src/libs/import.c
Labels: bugfix, feature: redesign

#9170 histogram: add vertical waveform
  data/darktableconfig.xml.in
  src/gui/draw.h
  src/libs/histogram.c
Labels: documentation-pending, no-pr-activity, scope: UI, scope: color management

#9661 mask indicator tooltip to show the source module for raster mask
  src/develop/imageop.c
Labels: feature: enhancement

#9018 Double click to unfold tree and include subfolders
  src/common/collection.c
  src/libs/collect.c
  src/libs/import.c
Labels: documentation-pending, feature: enhancement, scope: DAM, scope: UI

#7803 Add several clean options to the build script
  build.sh
Labels: feature: enhancement, no-pr-activity

#9325 Canonical path to env is /usr/bin/env
  src/tests/benchmark/darktable-bench
Labels: no-pr-activity, scope: OS support, scope: codebase

#9175 Translators.md update
  doc/TRANSLATORS.md
Labels: scope: translation

#9666 darktable.collection requires pure lua ipairs implementation
  data/luarc
Labels: lua

#9667 [build.sh] add clean options to help
  build.sh
Labels: scope: codebase, scope: usermanual

#9669 OpenCL Bradford non-linear: return a value
  data/kernels/colorspace.h
Labels: bugfix, priority: high

#9677 Update de.po
  po/de.po
Labels: scope: translation

#9679 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#9687 cleanup: remove extraneous memset() calls
  src/common/bilateral.c
  src/common/darktable.h
  src/common/imagebuf.c
  src/develop/masks/brush.c
  src/develop/masks/ellipse.c
  src/develop/masks/gradient.c
  src/develop/masks/group.c
  src/develop/masks/path.c
  src/iop/equalizer_eaw.h
Labels: scope: codebase

#9681 Lazy xmp writing (v3)
  data/darktableconfig.xml.in
  src/common/exif.cc
  src/common/image.c
  src/common/image.h
  src/common/metadata.c
  src/control/crawler.c
  src/develop/develop.c
  src/develop/lightroom.c
  src/develop/lightroom.h
  src/gui/import_metadata.c
  src/views/darkroom.c
Labels: documentation-pending, feature: new, priority: high, release notes: pending, scope: codebase

#9693 cleanup and tuning of masks code
  src/common/imagebuf.c
  src/develop/masks/brush.c
  src/develop/masks/path.c
Labels: scope: performance
