Repository darktable-org/darktable, pull requests merged in 2021-08, with the labels that each got.

#9691 eliminate discrepancy in definition of DT_IOP_COLOR_ICC_LEN
  src/common/colorspaces.h
  src/common/iop_profile.h
  src/develop/lightroom.c
Labels: bugfix, scope: codebase

#9698 determine if image is altered from lua
  src/lua/image.c
Labels: feature: enhancement, lua

#9703 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#9701 [tiling] use size_t cast for operation in case we could have int overshoot in tile
  src/develop/tiling.c
Labels: bugfix, scope: codebase

#9705 [masks] use query tooltip to have always up to date mask indicatr tooltip
  src/develop/imageop.c
Labels: bugfix, scope: UI

#9689 InputNG: add keyboard shortcut icon
  src/dtgtk/paint.c
  src/dtgtk/paint.h
  src/libs/tools/global_toolbox.c
Labels: scope: UI

#9704 Lua image generate cache mipmap
  src/lua/image.c
Labels: feature: enhancement, lua

#9678 po/fix liquify
  src/iop/liquify.c
Labels: bugfix, difficulty: average

#9672 Port special case handling of keys in views to Input NG
  src/bauhaus/bauhaus.c
  src/common/action.h
  src/common/darktable.h
  src/control/control.c
  src/control/control.h
  src/develop/imageop.c
  src/dtgtk/culling.c
  src/dtgtk/thumbtable.c
  src/gui/accelerators.c
  src/gui/accelerators.h
  src/gui/gtk.c
  src/gui/gtk.h
  src/gui/import_metadata.c
  src/gui/preferences.c
  src/imageio/format/pdf.c
  src/imageio/storage/disk.c
  src/imageio/storage/gallery.c
  src/imageio/storage/latex.c
  src/imageio/storage/piwigo.c
  src/iop/lens.cc
  src/iop/lut3d.c
  src/iop/watermark.c
  src/libs/camera.c
  src/libs/collect.c
  src/libs/duplicate.c
  src/libs/export.c
  src/libs/geotagging.c
  src/libs/location.c
  src/libs/metadata.c
  src/libs/modulegroups.c
  src/libs/print_settings.c
  src/libs/session.c
  src/libs/styles.c
  src/libs/tagging.c
  src/libs/tools/lighttable.c
  src/lua/widget/entry.c
  src/lua/widget/text_view.c
  src/views/darkroom.c
  src/views/knight.c
  src/views/lighttable.c
  src/views/slideshow.c
  src/views/view.c
  src/views/view.h
  src/views/view_api.h
Labels: feature: enhancement, scope: codebase, scope: hardware support

#9713 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#9382 add permanent search entries for shortcuts dialog
  src/gui/accelerators.c
Labels: bugfix, scope: UI

#9716 improve and add toasts for shortcuts
  src/bauhaus/bauhaus.c
  src/develop/imageop.c
  src/gui/accelerators.c
  src/gui/accelerators.h
  src/gui/gtk.c
Labels: bugfix, scope: UI

#9712 module-search: add some padding after search icon
  data/themes/darktable.css
Labels: difficulty: trivial, feature: enhancement, scope: UI

#9720 Update german translation
  po/de.po
Labels: scope: translation

#9723 preserve alpha on in-place colorspace conversions
  src/common/iop_profile.c
  src/develop/blends/blendif_lab.c
Labels: bugfix, priority: high, scope: image processing

#9721 make click on module header open correct action
  src/gui/accelerators.c
Labels: bugfix, scope: UI

#9714 macOS: fix button-press on "by scale" in "export selected"
  src/libs/export.c
Labels: bugfix, scope: UI, scope: macos support

#9719 ignore window state changes during shortcut
  src/gui/accelerators.c
Labels: scope: UI, scope: codebase

#9729 Lua fix storage issue and tag issue
  src/lua/luastorage.c
  src/lua/tags.c
Labels: bugfix, lua

#9731 Fix lua table creation to be compatible with Lua 5.4
  src/libs/collect.c
  src/libs/image.c
  src/libs/select.c
  src/lua/events.c
  src/lua/glist.c
  src/lua/gui.c
  src/lua/image.c
  src/lua/lib.c
  src/lua/preferences.c
Labels: bugfix, lua

#9732 clean up darkroom popovers
  src/develop/develop.h
  src/gui/gtk.c
  src/gui/guides.c
  src/gui/guides.h
  src/libs/tools/global_toolbox.c
  src/views/darkroom.c
Labels: scope: UI, scope: codebase

#9733 Update osx Build instructions for lua support
  packaging/macosx/BUILD.txt
Labels: scope: usermanual, lua, scope: macos support

#9742 update german translation
  po/de.po
Labels: scope: translation

#9735 Remove check for Gtk > 3.16, 3.20 & 3.22 as the minimal Gtk required …
  src/bauhaus/bauhaus.c
  src/common/colorspaces.c
  src/control/control.c
  src/develop/imageop.c
  src/gui/gtk.c
  src/libs/collect.c
  src/libs/lib.c
  src/libs/map_locations.c
  src/libs/masks.c
  src/libs/recentcollect.c
  src/libs/tagging.c
  src/libs/tools/global_toolbox.c
  src/views/darkroom.c
  src/views/lighttable.c
  src/views/slideshow.c
Labels: priority: low, difficulty: trivial, scope: codebase

#9750 use dt_bauhaus_combobox_add_section for "drawn mask" headings
  src/develop/masks/masks.c
Labels: feature: enhancement, scope: UI

#9737 geotagging: improve timezone entry
  src/libs/geotagging.c
Labels: bugfix, scope: UI, scope: DAM

#9747 add shortcut tooltips and visual mapping to more widgets
  src/gui/accelerators.c
  src/gui/gtk.c
  src/libs/histogram.c
  src/libs/modulegroups.c
  src/libs/navigation.c
  src/libs/tools/lighttable.c
  src/libs/tools/viewswitcher.c
Labels: bugfix, feature: enhancement, scope: UI

#9764 [performance] scale up performance to 2021 reality
  src/common/darktable.c
  src/common/darktable.h
  src/control/jobs/control_jobs.c
Labels: feature: enhancement, scope: hardware support, scope: performance

#9765 Fix build of unittests on Windows
  packaging/windows/BUILD.md
  src/tests/unittests/CMakeLists.txt
  src/tests/unittests/iop/test_filmicrgb.c
  src/tests/unittests/test_sample.c
  src/tests/variables.c
Labels: bugfix, scope: codebase, scope: windows support

#9769 blendif: initialize transposed color conversion matrix
  src/develop/blend.c
Labels: bugfix, priority: high, scope: image processing

#9717 fix for windows copy and import
  src/common/import_session.c
  src/libs/import.c
Labels: bugfix, scope: DAM, scope: windows support

#9770 Make Tests runnable on Windows
  cmake/windows-macros.cmake
  src/tests/CMakeLists.txt
  src/tests/unittests/CMakeLists.txt
  src/tests/unittests/iop/CMakeLists.txt
Labels: scope: codebase, scope: windows support

#9763 [iop] add option to prompt rename on new instance
  data/darktableconfig.xml.in
  src/develop/imageop.c
Labels: feature: enhancement, scope: UI, documentation-pending

#9781 german translation: changed term for "scene referred"
  po/de.po
Labels: scope: translation

#9778 avoid duplicate free of Dbus connection
  src/common/dbus.c
  src/control/progress.c
Labels: bugfix

#9779 tagging: remove double separator in suggestions view context menu
  src/libs/tagging.c
Labels: bugfix, scope: UI

#9771 distinguish on/off toggles when mouse hovering
  src/dtgtk/togglebutton.c
Labels: scope: UI

#9782 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#9786 Fixing xmp disabling regression (9776)
  src/cli/main.c
  src/common/image.c
  src/generate-cache/main.c
  src/tests/variables.c
  tools/regression_tests/src/lib/build.rb
Labels: bugfix, priority: high, scope: DAM

#9784 exif: remove dead code as minimum required Exiv2 is 0.24
  src/common/exif.cc
Labels: scope: software support, scope: codebase

#9799 bugfix: ensure proper init of brush/path stamps
  src/develop/masks/brush.c
  src/develop/masks/path.c
Labels: bugfix, scope: image processing

#9795 [ci] switch nightly from llvm to gcc in hopes of alleviating some issues
  .github/workflows/nightly.yml
Labels: bugfix

#9697 dedup ellipse mask fill
  src/develop/masks/ellipse.c
Labels: scope: image processing, scope: performance, scope: codebase

#9800 secure refresh in color zones when "select by" changes
  src/iop/colorzones.c
Labels: bugfix, scope: UI

#7695 Unset target_clones attribute for -march=native build
  cmake/march-mtune.cmake
  src/common/darktable.h
Labels: scope: performance, scope: codebase

#9777 fix hold key regressions and modifier only fallbacks
  src/control/control.c
  src/control/control.h
  src/gui/accelerators.c
Labels: bugfix, priority: high, scope: UI

#9805 cleanup: use dt_aligned_pixel_t for formal args
  src/common/box_filters.c
  src/common/bspline.h
  src/common/color_picker.c
  src/common/color_picker.h
  src/common/eaw.c
  src/develop/blends/blendif_lab.c
  src/develop/blends/blendif_rgb_jzczhz.c
  src/develop/imageop_math.c
  src/develop/imageop_math.h
  src/develop/pixelpipe_hb.c
  src/iop/ashift.c
Labels: scope: codebase

#9758 guides button: replace button-press-event with clicked
  src/views/darkroom.c
Labels: bugfix

#9814 Unify formating of strings across modules
  src/iop/colorbalance.c
  src/iop/colorchecker.c
  src/iop/filmic.c
  src/iop/filmicrgb.c
  src/iop/velvia.c
Labels: bugfix, scope: UI, documentation-pending

#9722 improve search fields and some buttons alignement
  data/themes/darktable.css
Labels: feature: enhancement, difficulty: trivial, scope: UI

#9820 Update de.po
  po/de.po
Labels: scope: translation

#9824 Fix wrong css for shortcuts dialog
  data/themes/darktable.css
Labels: bugfix, difficulty: trivial, scope: UI

#9209 vectorscope appearance update
  src/libs/histogram.c
Labels: feature: enhancement, documentation-pending

#9828 don't override navigation event selection when adding ENTER_NOTIFY
  src/libs/navigation.c
Labels: bugfix

#9045 configurable number of recent collections
  data/darktableconfig.dtd
  data/darktableconfig.xml.in
  src/gui/preferences_dialogs.h
  src/libs/recentcollect.c
  tools/generate_prefs.xsl
Labels: feature: enhancement, scope: UI, documentation-pending

#9830 split-toning: display hues in degrees
  src/iop/splittoning.c
Labels: feature: enhancement, scope: UI

#9832 Denoise profiled: change default to wavelets
  src/iop/denoiseprofile.c
Labels: feature: redesign, scope: image processing, documentation-pending, release notes: pending

#9806 Lua: add darkroom-image-loaded event and clear_snapshots() function
  src/libs/snapshots.c
  src/views/darkroom.c
Labels: feature: enhancement, lua

#9817 Add support for png files in watermark module
  src/iop/watermark.c
Labels: bugfix, feature: enhancement, scope: image processing, documentation-pending, release notes: pending

#9838 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#9829 add shortcuts export, import and restore
  src/bauhaus/bauhaus.c
  src/common/darktable.c
  src/gui/accelerators.c
  src/gui/accelerators.h
  src/gui/preferences.c
Labels: feature: enhancement, scope: UI, scope: codebase, documentation-pending

#9852 Fix dual demosaic mask display
  src/iop/demosaic.c
  src/iop/dual_demosaic.c
Labels: bugfix

#9840 Fix Potential integer overflow in image pfm/pnm image loading
  src/common/imageio_pfm.c
  src/common/imageio_pnm.c
Labels: bugfix, scope: codebase

#9848 make values in color picker selectable for copy/paste
  src/libs/colorpicker.c
Labels: feature: enhancement, scope: UI

#9845 toneeq: visualize cursor on focus, activate on scroll
  src/iop/toneequal.c
Labels: bugfix, feature: enhancement, scope: UI

#9853 fix master compile
  src/gui/accelerators.h
  src/libs/tools/gamepad.c
Labels: bugfix, priority: high

#9855 [midi.c] add const declarations to match accelerators.h definitions
  src/libs/tools/midi.c
Labels: bugfix

#9857 diffuse: correct spelling of directionality
  src/iop/diffuse.c
Labels: difficulty: trivial, scope: UI

#9858 midtones --> mid-tones
  src/common/locallaplacian.c
  src/common/locallaplacian.h
  src/common/locallaplaciancl.c
  src/common/locallaplaciancl.h
  src/iop/bilat.c
  src/iop/colorbalance.c
  src/iop/colorbalancergb.c
  src/iop/filmic.c
  src/iop/filmicrgb.c
  src/iop/grain.c
  src/iop/negadoctor.c
  src/iop/shadhi.c
  src/iop/splittoning.c
  src/iop/toneequal.c
  src/iop/velvia.c
Labels: difficulty: trivial, scope: UI, documentation-pending

#9864 guides : split golden means in different guides
  src/gui/guides.c
Labels: feature: enhancement, difficulty: trivial, scope: UI

#9861 Make demosaic module supporting DT_DEV_PIXELPIPE_DISPLAY_PASSTHRU
  src/iop/demosaic.c
Labels: feature: enhancement, scope: image processing

#9867 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#9868 copy & import: secure filename is set before variables expansion
  src/control/jobs/control_jobs.c
Labels: bugfix, scope: DAM

#9885 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#9895 Update de.po
  po/de.po
Labels: scope: translation

#9889 Algumas correções ortográficas e novas traduções
  po/pt_BR.po
Labels: scope: translation

#9901 crop : safeguard against undefined gui_data
  src/iop/crop.c
Labels: bugfix, difficulty: trivial, scope: UI

#9892 colorchecker: unstick slider when using saved colors
  src/iop/colorchecker.c
Labels: bugfix, scope: UI, scope: performance

#9893 c&r : show alert msg if crop module is enabled
  src/iop/clipping.c
Labels: feature: enhancement, difficulty: trivial, scope: image processing

#9866 display live samples in vectorscope
  src/libs/colorpicker.c
  src/libs/colorpicker.h
  src/libs/histogram.c
  src/libs/lib.h
Labels: feature: new, scope: UI, documentation-pending, release notes: pending

#9854 timeline : use specific css colors
  data/themes/darktable.css
  src/gui/gtk.c
  src/gui/gtk.h
  src/libs/tools/timeline.c
Labels: feature: enhancement, difficulty: trivial, scope: UI

#9909 Adding HSV reading to color picker
  src/libs/colorpicker.c
Labels: feature: enhancement, priority: low, scope: UI, scope: image processing, documentation-pending, release notes: pending

#9906 vectorscope: fix visibility of primary sample
  src/libs/histogram.c
Labels: bugfix, scope: UI
