Repository darktable-org/darktable, pull requests merged in 2021-02, with the labels that each got.

#8053 refactor: use dt_alloc_perthread for per-thread buffers
  src/common/darktable.h
  src/common/eaw.c
  src/common/nlmeans_core.c
  src/iop/bilateral.cc
  src/iop/clahe.c
  src/iop/demosaic.c
  src/iop/equalizer_eaw.h
  src/iop/lens.cc
  src/iop/rawoverexposed.c
Labels: scope: codebase

#8062 updated german translation
  po/de.po
Labels: scope: translation

#8068 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#8070 Add Fujifilm X-Pro3 Noise Profiles
  data/noiseprofiles.json
Labels: scope: noise profile

#8072 histogram: buttons and conf cleanups
  data/themes/darktable.css
  src/libs/histogram.c
Labels: feature: redesign, scope: UI

#8063 geotagging: add offset lock button
  src/libs/geotagging.c
Labels: bugfix

#8050 Expose tca_overwrite to gui, fixes #8039
  src/iop/lens.cc
Labels: documentation-pending, feature: enhancement

#8067 avoid integer wraparound
  src/common/box_filters.c
Labels: bugfix, scope: codebase

#8089 translation update de.po
  po/de.po
Labels: scope: translation

#8045 guided_filter.c: consolidate and optimize box-mean filters
  src/common/box_filters.c
  src/common/box_filters.h
  src/common/darktable.h
  src/common/eaw.c
  src/common/guided_filter.c
  src/common/guided_filter.h
  src/common/math.h
  src/common/nlmeans_core.c
  src/iop/bilateral.cc
  src/iop/lens.cc
Labels: scope: performance

#8042 Color checker calibration : minor bugs and improvements
  src/iop/channelmixerrgb.c
Labels: bugfix, documentation-pending, feature: enhancement

#8071 lua - add event callback indexing and destruction
  data/luarc
  src/libs/tools/global_toolbox.c
  src/lua/configuration.h
  src/lua/database.c
  src/lua/events.c
  src/lua/events.h
  src/lua/gui.c
  src/lua/init.c
  src/lua/view.c
Labels: lua

#8037 Remove unsuitable color profiles from histogram and work profile menus
  src/common/colorspaces.c
  src/iop/colorin.c
Labels: bugfix, feature: enhancement, priority: medium

#8091 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#8093 Add Serbian translation
  po/CMakeLists.txt
  po/LINGUAS
  po/sr.po
  po/sr@latin.po
Labels: scope: translation

#8090 map: keep location proportions when dragged + mouse geo position
  src/common/map_locations.c
  src/common/map_locations.h
  src/views/map.c
Labels: bugfix, feature: enhancement

#8082 import: on refresh exif don't update rating if ignore exif rating set
  src/control/jobs/control_jobs.c
Labels: bugfix

#8075 modulegroups: Amend add/remove popup menu titles
  data/themes/darktable.css
  src/libs/modulegroups.c
Labels: feature: redesign

#8092 box mean: ensure correct behavior when radius exceeds half of image size
  src/common/box_filters.c
Labels: bugfix, priority: high

#8103 define target_clones attribute only for x86-64 builds
  src/common/darktable.h
Labels: bugfix, priority: high

#8108 fix memory leaks and uninitialized variable
  src/common/exif.cc
  src/common/imageio.c
  src/control/conf.c
  src/develop/imageop.c
  src/gui/gtk.c
  src/gui/preferences.c
  src/iop/toneequal.c
  src/libs/collect.c
  src/libs/export.c
  src/libs/metadata.c
  src/libs/modulegroups.c
Labels: bugfix, scope: codebase, scope: performance

#8113 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#8115 Prevent colorpicker labels causing continuous resize loop
  src/dtgtk/expander.c
  src/dtgtk/sidepanel.c
  src/gui/gtk.c
  src/libs/colorpicker.c
Labels: bugfix, priority: high

#8107 illuminants: don't declare non-inline function as static
  src/common/illuminants.h
Labels: bugfix, priority: high

#8118 popup preset menu at right click for libs like iops
  src/develop/imageop.c
  src/libs/lib.c
Labels: documentation-pending, feature: enhancement, scope: UI

#8124 updated german translation
  po/de.po
Labels: scope: translation

#8129 Fix colorin legacy_params() versioning
  src/iop/colorin.c
Labels: bugfix

#8121 liquify: ensure that we an element is selected no panning is done.
  src/iop/liquify.c
Labels: bugfix

#8111 UI: harmonize draw area in colorzones and contrast equalizer …
  src/iop/atrous.c
  src/iop/colorzones.c
Labels: scope: UI

#6875 Add shortcuts for blending and group shapes
  src/bauhaus/bauhaus.c
  src/develop/blend_gui.c
  src/develop/imageop.c
  src/develop/imageop_gui.c
  src/develop/imageop_gui.h
  src/gui/accelerators.c
  src/iop/liquify.c
  src/iop/retouch.c
  src/iop/spots.c
  src/iop/temperature.c
  src/iop/toneequal.c
Labels: feature: enhancement, scope: UI

#8134 fix longitude string in tooltips
  src/common/variables.c
Labels: bugfix

#8136 remove brush size shortcuts that clash with rotation
  src/views/darkroom.c
Labels: bugfix, documentation-pending

#8139 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#8133 Replace picasa by piwigo in translations
  po/de.po
Labels: controversial

#8144 Spanish translation update
  po/es.po
Labels: scope: translation

#8142 fix liquify taking focus when button pressed
  src/iop/liquify.c
Labels: bugfix, scope: UI

#8138 colorcorrection: code cleanup
  src/iop/colorcorrection.c
Labels: scope: codebase

#8140 gamma: changes to aid vectorizability
  src/iop/gamma.c
Labels: scope: image processing, scope: performance

#8099 modulegroups : contextmenus refinments
  data/themes/darktable.css
  src/libs/modulegroups.c
Labels: difficulty: average, documentation-pending, feature: enhancement, scope: UI

#7983 Show subfolders using Shift-Click like tags
  src/common/collection.c
  src/libs/collect.c
Labels: documentation-pending, scope: DAM, scope: UI

#8147 common:cpuid: Fix __get_cpuid() support check
  src/common/cpuid.c
Labels: bugfix

#8149 Improve module groups UI
  data/themes/darktable.css
Labels: feature: enhancement, scope: UI

#8141 flip/borders/rawprepare: distort_transform speedup
  src/iop/borders.c
  src/iop/flip.c
  src/iop/rawprepare.c
Labels: scope: image processing, scope: performance

#8148 Make css editor behavior clearer
  src/gui/preferences.c
Labels: documentation-pending, scope: UI

#8152 Adds a target_clone for the ppc64 builds.
  src/common/darktable.h
Labels: feature: enhancement, scope: performance

#8154 modulegroups: further adjustments to right-click menu
  src/libs/modulegroups.c
Labels: bugfix

#8110 blend_gui: do not tweak the blendif when output channel is hidden.
  src/develop/blend_gui.c
Labels: bugfix, difficulty: average, priority: high, scope: image processing

#8159 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#8167 Spanish translation update
  po/es.po
Labels: scope: translation

#8169 Updated Dutch translation
  po/nl.po
Labels: scope: translation

#8166 map_locations.c: letter missed
  src/libs/map_locations.c
Labels: scope: translation

#8150 small fixes for spydercheckr and spydercheckr 24
  src/common/colorchecker.h
  src/iop/channelmixerrgb.c
Labels: bugfix

#8162 Color calibration: bug/inconsistencies fix
  src/iop/channelmixerrgb.c
Labels: bugfix, feature: enhancement

#8170 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#8106 geotagging on map
  data/darktableconfig.xml.in
  data/themes/darktable.css
  src/common/geo.h
  src/common/gpx.c
  src/common/gpx.h
  src/common/image.c
  src/common/undo.h
  src/control/jobs/control_jobs.c
  src/develop/lightroom.c
  src/libs/geotagging.c
  src/libs/image.c
  src/views/map.c
Labels: documentation-pending, feature: enhancement

#8080 import : lower the number of raised signals
  src/cli/main.c
  src/common/darktable.c
  src/common/film.c
  src/common/image.c
  src/common/image.h
  src/common/import_session.c
  src/control/jobs/camera_jobs.c
  src/control/jobs/control_jobs.c
  src/control/jobs/film_jobs.c
  src/control/jobs/image_jobs.c
  src/dtgtk/thumbnail.c
  src/dtgtk/thumbnail.h
  src/dtgtk/thumbtable.c
  src/libs/import.c
  src/lua/database.c
Labels: bugfix, difficulty: hard, feature: enhancement

#8171 modulegroups: rename basic > quick access + tooltip changes
  src/libs/modulegroups.c
Labels: documentation-pending, feature: redesign, scope: image processing

#8175 imageio:avif: Use tiles of size 1024x1024 pixels
  src/imageio/format/avif.c
Labels: feature: enhancement

#8184 Spanish translation update
  po/es.po
Labels: scope: translation

#8181 Update french translation
  po/fr.po
Labels: scope: translation

#8183 quick access panel - fix alignment of on-off option in module sub-menu
  src/libs/modulegroups.c
Labels: bugfix, scope: UI

#8179 update german translation
  po/de.po
Labels: scope: translation

#8185 Fixing hotpixels in green_equilibration_lavg
  data/kernels/demosaic_ppg.cl
  src/iop/demosaic.c
Labels: bugfix

#8187 ptbr
  po/pt_BR.po
Labels: scope: translation

#8189 Updated Dutch translation
  po/nl.po
Labels: scope: translation

#8190 Fix missing translated strings and translate them in french
  po/fr.po
  src/libs/modulegroups.c
Labels: scope: translation

#8193 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#8199 updated german translation
  po/de.po
Labels: scope: translation

#8177 map: refactor preferences; add thumbnail options
  data/darktableconfig.xml.in
  src/gui/preferences.c
  src/gui/preferences.h
  src/libs/map_settings.c
  src/views/map.c
  src/views/view.c
  src/views/view.h
Labels: documentation-pending, feature: enhancement

#8120 show export lib in darkroom
  data/darktableconfig.xml.in
  src/libs/export.c
  src/views/darkroom.c
Labels: bugfix, documentation-pending, feature: enhancement, scope: UI

#8198 collect: fix Ctrl+Shift+click to switch folder <> filmroll
  src/libs/collect.c
Labels: bugfix

#8208 map: on leave reset drop_filsmtrip_activated flag
  src/views/map.c
Labels: bugfix

#8196 collect: avoid to refresh collection when scrolling the list
  src/bauhaus/bauhaus.c
  src/bauhaus/bauhaus.h
  src/libs/collect.c
Labels: bugfix

#8213 culling/preview : update image if focus value change
  src/dtgtk/culling.c
Labels: bugfix, difficulty: trivial, scope: UI

#8207 collect: Fix Ctrl+click/Shift+click in folders/filmrolls
  src/libs/collect.c
Labels: bugfix, scope: UI

#8218 manage module layouts: fit quick access panel name
  src/libs/modulegroups.c
Labels: bugfix, feature: enhancement

#8204 Speeding up large imports
  src/common/collection.c
  src/common/image.c
  src/control/jobs/film_jobs.c
Labels: scope: DAM, scope: performance

#8212 modulegroups : fix contextmenu with own defined groups
  src/libs/modulegroups.c
Labels: bugfix, difficulty: trivial, scope: UI

#8220 geotag: timezone clean up
  data/darktableconfig.xml.in
  src/libs/geotagging.c
Labels: bugfix

#8125 Lua selection changes
  RELEASE_NOTES.md
  src/libs/select.c
  src/lua/configuration.h
Labels: feature: enhancement, lua

#8232 Updated Dutch translation
  po/nl.po
Labels: scope: translation

#8233 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#8236 update de.po
  po/de.po
Labels: scope: translation

#8237 modulegroups basics : more compact ui
  src/libs/modulegroups.c
Labels: feature: enhancement, scope: UI

#8240 image: fix memory leak in dt_image_set_locations (introduced in #8106)
  src/common/image.c
Labels: bugfix

#8246 Spanish translation update
  po/es.po
Labels: scope: translation

#8219 po/atrous mix
  src/iop/atrous.c
Labels: documentation-pending, feature: enhancement

#8250 fix number of selected images
  src/common/collection.c
Labels: bugfix

#8253 update german translation
  po/de.po
Labels: scope: translation

#8247 Fine tune and compact more quick access panel
  data/themes/darktable.css
Labels: documentation-pending, feature: redesign, scope: UI

#8192 histogram: fix button tooltips
  src/libs/histogram.c
Labels: bugfix, scope: UI

#8258 Spanish translation update
  po/es.po
Labels: scope: translation

#8255 add/amend iop deprecation messages
  src/iop/basicadj.c
  src/iop/channelmixer.c
  src/iop/globaltonemap.c
  src/iop/invert.c
  src/iop/relight.c
  src/iop/tonemap.cc
  src/iop/vibrance.c
  src/iop/zonesystem.c
Labels: scope: UI

#8241 Fix hdr-dng white balance
  src/common/imageio_dng.h
  src/control/jobs/control_jobs.c
Labels: bugfix

#8245 allow widgets from all modules in quick acces panel
  src/libs/modulegroups.c
  src/libs/modulegroups.h
Labels: difficulty: average, documentation-pending, feature: enhancement, scope: UI

#8260 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#8261 modulegroups: update preset name change immediately
  src/libs/modulegroups.c
Labels: bugfix

#8264 modulegroups: improve deprecation group message
  src/libs/modulegroups.c
Labels: feature: enhancement

#8271 Spanish translation update
  po/es.po
Labels: scope: translation

#8279 ptbr
  po/pt_BR.po
Labels: scope: translation

#8278 quick access: improve hover effect
  data/themes/darktable.css
  src/libs/modulegroups.c
Labels: feature: enhancement, scope: UI

#8288 Raise trouble message only for true dev struct.
  src/develop/imageop.c
Labels: bugfix, difficulty: hard, priority: high

#8293 Update translation de
  po/de.po
Labels: scope: translation

#7971 [export] make export module gui_reset actually reset stuff
  data/darktableconfig.xml.in
  src/imageio/format/avif.c
  src/imageio/format/exr.cc
  src/imageio/format/j2k.c
  src/imageio/format/jpeg.c
  src/imageio/format/png.c
  src/imageio/format/tiff.c
  src/imageio/format/webp.c
  src/imageio/format/xcf.c
  src/imageio/storage/disk.c
  src/imageio/storage/gallery.c
  src/imageio/storage/latex.c
  src/libs/export.c
Labels: bugfix, difficulty: average, feature: redesign, scope: UI, scope: codebase

#8280 GList optimization: use g_list_prepend where possible
  src/cmstest/main.c
  src/common/collection.c
  src/common/colorspaces.c
  src/common/cups_print.c
  src/common/exif.cc
  src/common/film.c
  src/common/grouping.c
  src/common/history.c
  src/common/image.c
  src/common/iop_order.c
  src/common/metadata.c
  src/common/module.c
  src/common/noiseprofiles.c
  src/common/ratings.c
  src/common/styles.c
  src/common/tags.c
  src/common/variables.c
  src/control/crawler.c
  src/control/jobs/camera_jobs.c
  src/control/jobs/control_jobs.c
  src/develop/develop.c
  src/develop/masks/masks.c
  src/dtgtk/culling.c
  src/dtgtk/thumbnail.c
  src/dtgtk/thumbtable.c
  src/gui/hist_dialog.c
  src/iop/liquify.c
  src/iop/watermark.c
  src/libs/duplicate.c
  src/libs/image.c
  src/libs/modulegroups.c
  src/libs/print_settings.c
  src/libs/styles.c
  src/libs/tagging.c
  src/lua/database.c
  src/lua/image.c
  src/views/darkroom.c
Labels: scope: codebase

#8274 geotagging: bug fixes and enhancements
  src/common/image.c
  src/common/image.h
  src/control/jobs/control_jobs.c
  src/control/jobs/control_jobs.h
  src/control/jobs/film_jobs.c
  src/libs/geotagging.c
Labels: bugfix, documentation-pending, feature: enhancement

#8281 refactor: dedup circle-drawing code for retouch shapes
  src/develop/masks/circle.c
Labels: scope: codebase

#8283 refactor: dedup path-drawing code for retouch shapes
  src/develop/masks/path.c
Labels: scope: codebase

#8300 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#8290 Refactor masks
  src/CMakeLists.txt
  src/develop/masks.h
  src/develop/masks/brush.c
  src/develop/masks/circle.c
  src/develop/masks/ellipse.c
  src/develop/masks/gradient.c
  src/develop/masks/group.c
  src/develop/masks/masks.c
  src/develop/masks/path.c
Labels: scope: codebase

#8305 Spanish translation update
  po/es.po
Labels: scope: translation

#8304 bugfix: don't pass rectangle with negative size to pixman
  src/iop/liquify.c
Labels: bugfix

#8297 po/undo duplicate
  src/common/image.c
  src/common/undo.h
  src/control/jobs/control_jobs.c
  src/dtgtk/thumbtable.c
  src/libs/image.c
Labels: documentation-pending, feature: new

#8307 prevent ctrl+click on module header initiating drag/drop
  src/develop/imageop.c
Labels: bugfix, priority: high

#6971 Implement overwrite dialog when importing style[s].
  src/common/styles.c
  src/libs/styles.c
Labels: feature: enhancement

#8310 imageop: consistent module expansion on new image
  src/views/darkroom.c
Labels: bugfix

#8282 refactor: dedup ellipse-drawing code for retouch shapes
  src/develop/masks/ellipse.c
Labels: scope: codebase

#8284 refactor: dedup brush-drawing code for retouch shapes
  src/develop/masks/brush.c
Labels: scope: codebase

#8256 Lua: API 6.2.3 changes (register_action, destroy_action, action_set_sensitive)
  RELEASE_NOTES.md
  src/libs/image.c
  src/lua/configuration.h
Labels: bugfix, feature: enhancement

#8298 histogram: restrict waveform to selection via global colorpicker
  src/libs/histogram.c
Labels: documentation-pending, feature: enhancement

#8324 Spanish translation update
  po/es.po
Labels: scope: translation

#8325 refactor: replace repeated boilerplate by utility functions
  src/develop/masks/brush.c
  src/develop/masks/circle.c
  src/develop/masks/ellipse.c
  src/develop/masks/gradient.c
  src/develop/masks/group.c
  src/develop/masks/masks.c
  src/develop/masks/path.c
  src/iop/ashift.c
  src/iop/clipping.c
  src/iop/graduatednd.c
  src/iop/toneequal.c
  src/iop/useless.c
  src/iop/vignette.c
  src/views/darkroom.c
  src/views/lighttable.c
  src/views/map.c
  src/views/slideshow.c
  src/views/view.c
  src/views/view.h
Labels: scope: codebase

#8326 Change "copy parts..." to "selective copy...".
  src/libs/copy_history.c
Labels: documentation-pending, feature: enhancement, scope: UI

#8229 More GList speedups: don't scan/copy entire list if not necessary
  src/common/collection.c
  src/common/colorlabels.c
  src/common/darktable.h
  src/common/history.c
  src/common/image.c
  src/common/iop_order.c
  src/common/metadata.c
  src/common/ratings.c
  src/common/styles.c
  src/common/tags.c
  src/develop/masks/brush.c
  src/develop/masks/circle.c
  src/develop/masks/ellipse.c
  src/develop/masks/gradient.c
  src/develop/masks/path.c
  src/dtgtk/culling.c
  src/dtgtk/thumbtable.c
  src/gui/preferences.c
  src/libs/copy_history.c
  src/libs/history.c
  src/libs/image.c
  src/libs/location.c
  src/libs/masks.c
  src/libs/modulegroups.c
  src/libs/print_settings.c
  src/libs/styles.c
  src/views/map.c
  src/views/tethering.c
  src/views/view.c
Labels: scope: codebase

#8322 image to act on speedups
  src/views/view.c
  src/views/view.h
Labels: difficulty: average, feature: enhancement, scope: UI, scope: performance

#8332 view: remove another g_list_reverse, use SQL query DESC order.
  src/views/view.c
Labels: scope: codebase, scope: performance

#8321 blend: use correct terminology
  src/develop/blend.h
  src/develop/blend_gui.c
  src/develop/blends/blendif_lab.c
  src/develop/blends/blendif_rgb_hsl.c
  src/develop/blends/blendif_rgb_jzczhz.c
Labels: feature: enhancement

#8315 refactor: revise GSList loops and use prepend instead of append
  src/control/conf.c
  src/develop/pixelpipe_hb.c
  src/dtgtk/thumbnail.c
  src/dtgtk/thumbtable.c
  src/gui/accelerators.c
  src/iop/colorzones.c
  src/iop/rgbcurve.c
  src/iop/tonecurve.c
  src/libs/camera.c
  src/libs/import.c
  src/views/darkroom.c
  src/views/lighttable.c
  src/views/print.c
  src/views/view.c
Labels: scope: codebase, scope: performance

#8335 Update de.po
  po/de.po
Labels: scope: translation

#8334 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#8226 Invert unused channels on combine mode change
  src/develop/blend_gui.c
Labels: feature: enhancement

#8333 view: finally using rowid to keep insertion order.
  src/views/view.c
Labels: scope: codebase, scope: performance

#8344 masks: refactor/optimize dt_masks_dynbuf_*
  src/develop/masks.h
  src/develop/masks/brush.c
  src/develop/masks/circle.c
  src/develop/masks/ellipse.c
  src/develop/masks/path.c
Labels: feature: enhancement, scope: performance

#8342 image_to_act_on : specify gui order for images
  src/common/image.c
  src/common/metadata.c
  src/common/selection.c
  src/common/selection.h
  src/common/styles.c
  src/common/tags.c
  src/control/jobs/control_jobs.c
  src/dtgtk/thumbtable.c
  src/libs/copy_history.c
  src/libs/export.c
  src/libs/image.c
  src/libs/metadata.c
  src/libs/styles.c
  src/libs/tagging.c
  src/libs/tools/colorlabels.c
  src/libs/tools/ratings.c
  src/lua/gui.c
  src/views/map.c
  src/views/view.c
  src/views/view.h
Labels: feature: enhancement

#8355 Updated Dutch translation
  po/nl.po
Labels: scope: translation

#8354 Lua: return act_on images in sorted order
  src/lua/gui.c
Labels: lua
