Repository darktable-org/darktable, pull requests merged in 2021-05, with the labels that each got.

#8830 Update Esperanto translation.
  po/eo.po
Labels: scope: translation

#8829 darkroom: amend image change message without loading screen
  src/views/darkroom.c
Labels: bugfix, feature: enhancement

#8835 Update de.po
  po/de.po
Labels: scope: translation

#8836 manage module groups - further ui amendments
  data/themes/darktable.css
  src/libs/modulegroups.c
Labels: difficulty: trivial, feature: enhancement, scope: UI

#8841 Updated Ukrainian translation
  po/uk.po
Labels: scope: translation

#8845 Update de.po - consolidation terms tag/tagging
  po/de.po
Labels: scope: translation

#8842 Modify the RCD border calculation
  src/iop/rcd_demosaic.c
Labels: scope: codebase

#8837 module groups: ctrl+click on preset button to manage
  src/libs/modulegroups.c
Labels: documentation-pending, feature: enhancement

#8849 Fix mask fast 9x9blurring
  data/kernels/demosaic_rcd.cl
  src/develop/blend.c
  src/iop/dual_demosaic.c
Labels: scope: codebase

#8848 vectorscope: fixes, speed-ups, cleanups, & appearance updates
  src/develop/pixelpipe_hb.c
  src/libs/histogram.c
  src/libs/lib.h
  src/views/tethering.c
Labels: feature: enhancement, scope: codebase, scope: performance

#8850 Improving dual demosaicer user interface
  src/iop/demosaic.c
  src/iop/dual_demosaic.c
Labels: scope: codebase

#7633 chromatic aberration correction
  src/common/iop_order.c
  src/iop/CMakeLists.txt
  src/iop/cacorrect.c
  src/iop/cacorrectrgb.c
Labels: documentation-pending, feature: new, scope: image processing

#8856 Fix rotate by 90° crashes in rcd
  src/iop/demosaic.c
Labels: bugfix, priority: high

#8863 presets: rename save button to export
  src/gui/presets.c
Labels: scope: UI

#8838 new crop module
  data/darktableconfig.xml.in
  src/common/iop_order.c
  src/common/usermanual_url.c
  src/iop/CMakeLists.txt
  src/iop/crop.c
  src/libs/modulegroups.c
Labels: difficulty: hard, documentation-pending, feature: new, scope: image processing

#8853 Add CSS chunk for label inside section label.
  data/themes/darktable-elegant-darker.css
  data/themes/darktable.css
  src/bauhaus/bauhaus.c
  src/bauhaus/bauhaus.h
  src/develop/blend_gui.c
Labels: bugfix, scope: UI

#8866 Fix opencl kernel includes
  data/kernels/basecurve.cl
  data/kernels/basic.cl
  data/kernels/basicadj.cl
  data/kernels/blendop.cl
  data/kernels/bloom.cl
  data/kernels/extended.cl
  data/kernels/retouch.cl
  data/kernels/rgbcurve.cl
  data/kernels/rgblevels.cl
  data/kernels/soften.cl
Labels: bugfix, priority: high

#8864 Fix stupid mistakes for "very high CA" mode
  src/iop/cacorrectrgb.c
Labels: bug: fixed, bugfix, priority: high

#8867 Make some rcd kernel input data const
  data/kernels/demosaic_rcd.cl
Labels: scope: codebase

#8869 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#8877 Spanish translation update
  po/es.po
Labels: scope: translation

#8874 bilateral_slice should ensure L >= 0.0f
  data/kernels/bilateral.cl
  src/common/bilateral.c
Labels: bugfix, priority: high

#8879 Fix fuji dual demosaicing
  src/iop/demosaic.c
Labels: bugfix, priority: high

#8889 Update de.po
  po/de.po
Labels: scope: translation

#8883 module management, import and some other css tweaks
  data/themes/darktable.css
Labels: difficulty: trivial, feature: enhancement, scope: UI

#8217 Blending enhancements
  data/kernels/blendop.cl
  src/develop/blend.c
  src/develop/blend.h
  src/develop/blend_gui.c
  src/develop/blends/blendif_lab.c
  src/develop/blends/blendif_raw.c
  src/develop/blends/blendif_rgb_hsl.c
  src/develop/blends/blendif_rgb_jzczhz.c
  src/libs/history.c
Labels: documentation-pending, feature: enhancement, scope: image processing

#8885 vectorscope: add log scaling
  src/libs/histogram.c
Labels: documentation-pending, feature: enhancement, priority: high, scope: UI

#8873 lens: fix roi_in computation
  data/kernels/basic.cl
  src/iop/lens.cc
Labels: bugfix, priority: high

#8896 lighttable : fix btn state with right click
  src/libs/tools/lighttable.c
Labels: bugfix, difficulty: trivial, scope: UI

#8907 lighttable: improve performance of zoom changes
  src/libs/tools/lighttable.c
Labels: difficulty: trivial, scope: performance

#8892 import: attempt to remove jump to first image when importing
  src/control/jobs/camera_jobs.c
  src/control/jobs/control_jobs.c
Labels: bugfix, scope: UI

#8905 libraries & collections: clarify terminology
  data/darktableconfig.xml.in
  src/control/jobs/control_jobs.c
  src/libs/collect.c
  src/libs/image.c
  src/libs/import.c
  src/views/lighttable.c
Labels: scope: UI

#8870 Get into ppd related bugs
  src/libs/navigation.c
  src/views/darkroom.c
Labels: bugfix, priority: high, scope: UI

#8919 rename and update help link for collect module
  data/darktableconfig.xml.in
  src/common/usermanual_url.c
  src/libs/collect.c
  src/views/lighttable.c
Labels: documentation-pending, feature: enhancement, priority: high

#8922 collect: remove last reference to "collect images"
  src/libs/collect.c
Labels: bugfix

#8920 Control lua widget visibility
  src/lua/widget/widget.c
  src/lua/widget/widget.h
Labels: lua

#8924 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#8930 Update de.po
  po/de.po
Labels: scope: translation

#8936 Updated Ukrainian translation
  po/uk.po
Labels: scope: translation

#8923 Performance: re-enable -ffast-math
  src/CMakeLists.txt
  src/common/opencl.c
  src/tests/unittests/iop/test_filmicrgb.c
Labels: scope: performance

#8939 tools: don't truncate long output for dngmeta.sh script
  tools/dngmeta.sh
Labels: bugfix, scope: codebase, scope: software support

#8949 Smaller demosaic module header
  src/iop/demosaic.c
Labels: feature: enhancement, scope: UI

#8950 Fix dual demosaicer smoothing
  src/iop/demosaic.c
  src/iop/dual_demosaic.c
Labels: bugfix, priority: high, scope: image processing

#8934 bauhaus: fix slider background on popovers
  data/themes/darktable.css
  src/bauhaus/bauhaus.c
Labels: bugfix, scope: UI

#8944 color balance rgb: more usable soft ranges
  src/iop/colorbalancergb.c
Labels: feature: enhancement

#8945 c&r : fix double crop with crop module
  src/develop/develop.c
  src/develop/pixelpipe_cache.c
  src/develop/pixelpipe_hb.c
  src/iop/clipping.c
  src/iop/crop.c
Labels: bugfix, difficulty: average, priority: high, scope: image processing

#8953 Add noise profile for the Canon EOS R5
  data/noiseprofiles.json
Labels: scope: noise profile

#8960 Fix typo in user visible string
  src/develop/masks/path.c
Labels: scope: UI

#8954 Avoid div by zero in dt_iop_clip_and_zoom_mosaic_half_size
  src/develop/imageop_math.c
Labels: bugfix, priority: high

#8964 Remove sse code from raw cacorrect
  src/iop/cacorrect.c
Labels: scope: codebase

#8965 histogram: slightly increase maximum height
  data/darktableconfig.xml.in
  src/libs/histogram.c
Labels: feature: enhancement, scope: UI

#8969 Add noise profiles for Canon M50
  data/noiseprofiles.json
Labels: scope: noise profile

#8970 Add Canon M50 WB presets with finetuning
  src/external/wb_presets.c
Labels: scope: camera support

#8971 performance: date-time rules in collect module
  src/libs/collect.c
Labels: scope: DAM, scope: UI, scope: performance

#8972 Update Esperanto trnaslaiton
  po/eo.po
Labels: scope: translation

#8973 Add Canon EOS R5 white balance presets with finetuning
  src/external/wb_presets.c
Labels: scope: camera support

#8976 bugfix : Fix filmlight RGB / color balance RGB
  data/kernels/colorspace.h
  data/kernels/extended.cl
  src/common/chromatic_adaptation.h
  src/common/colorspaces_inline_conversions.h
  src/common/illuminants.h
  src/common/math.h
  src/iop/colorbalancergb.c
Labels: bugfix, priority: high

#8978 css: add missing icons
  data/themes/darktable-icons.css
Labels: bugfix

#6899 create benchmark test
  src/tests/benchmark/README.txt
  src/tests/benchmark/darktable-bench
  src/tests/benchmark/darktable-bench-3.4.xmp
  src/tests/benchmark/darktable-bench-3.4legacy-inv.xmp
  src/tests/benchmark/darktable-bench-3.4legacy.xmp
  src/tests/benchmark/darktable-bench-3.6.xmp
  src/tests/benchmark/darktable-bench-null.xmp
Labels: feature: enhancement, no-pr-activity, scope: performance

#8982 crop : fix focus when entering from c&r
  src/iop/crop.c
Labels: bugfix, difficulty: trivial, priority: high, scope: UI

#8990 Update de.po
  po/de.po
Labels: scope: translation

#8986 keep final sizes up to date
  src/common/history.c
  src/common/image.c
  src/common/image.h
  src/common/image_cache.c
  src/common/styles.c
  src/develop/imageop.c
  src/iop/crop.c
  src/views/darkroom.c
Labels: bugfix, difficulty: average, feature: enhancement, scope: DAM

#8989 culling : fix oddities when enter/quit dynamic mode
  src/views/lighttable.c
Labels: bugfix, difficulty: trivial, scope: UI

#8996 info line : update on images infos change
  src/libs/tools/image_infos.c
Labels: bugfix, difficulty: trivial, scope: UI

#8995 Channel mixer RGB/ color calibration : add OpenCL kernel
  data/kernels/basic.cl
  data/kernels/blendop.cl
  data/kernels/channelmixer.cl
  data/kernels/color_conversion.h
  data/kernels/colorspace.h
  data/kernels/dwt.cl
  data/kernels/filmic.cl
  data/kernels/programs.conf
  src/common/chromatic_adaptation.h
  src/iop/channelmixerrgb.c
Labels: feature: enhancement

#8997 culling : fixed/dynamic switch : handle no selection
  src/dtgtk/culling.c
Labels: bugfix, difficulty: trivial, scope: UI

#8897 Add places instead of root-folder in import-dialog
  data/darktableconfig.xml.in
  src/libs/import.c
Labels: feature: enhancement, priority: medium, scope: DAM, scope: UI

#8957 Improve grouped metadata
  RELEASE_NOTES.md
  src/common/image_cache.c
  src/libs/metadata.c
  src/libs/metadata_view.c
Labels: feature: enhancement, priority: low, scope: DAM, scope: UI

#8933 Fix zoom 100/200 bounds also in second window
  src/views/darkroom.c
Labels: bugfix

#8999 histogram: conf cleanup for vectorscope scale
  data/darktableconfig.xml.in
  src/libs/histogram.c
Labels: scope: codebase

#9000 common: Include stddef.h for size_t
  src/common/math.h
Labels: bugfix, scope: codebase

#9001 only compute size for valid images
  src/common/image.c
Labels: bugfix

#9006 Update de.po
  po/de.po
Labels: scope: translation

#9005 infoline : fix crash on image info change
  src/libs/tools/image_infos.c
Labels: bugfix, difficulty: trivial, priority: high

#9004 colorbalancergb: Use American spelling of gray in UI
  src/iop/colorbalancergb.c
Labels: difficulty: trivial, scope: UI

#9009 Escape text if it goes into markup render in quick presets
  src/gui/presets.c
Labels: bugfix, difficulty: trivial, priority: low, scope: UI, scope: codebase

#9012 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#9019 help: add version string to release help url.
  data/darktableconfig.xml.in
  src/common/darktable.c
  src/common/darktable.h
  src/libs/tools/global_toolbox.c
Labels: feature: enhancement, priority: high, scope: usermanual

#8929 qap : ensure to have the right widget label
  src/bauhaus/bauhaus.c
  src/bauhaus/bauhaus.h
  src/libs/modulegroups.c
Labels: bugfix, difficulty: average, scope: UI

#9020 add noise profiles canon eos rp
  data/noiseprofiles.json
  src/external/wb_presets.c
Labels: scope: camera support, scope: noise profile

#9023 A slightly more informative warning before database updating
  src/common/database.c
Labels: priority: low, scope: codebase

#9031 tether: on hidpi displays, scale center view image properly
  src/views/tethering.c
Labels: bugfix, scope: UI

#9030 speed up 'tag' filter rule SQL query
  src/common/collection.c
Labels: feature: enhancement, priority: high, scope: performance

#9017 collections: speed up display of tags for tag filter
  src/libs/collect.c
Labels: feature: enhancement, priority: high, scope: performance

#9028 performance: speed up collection hinter for large libraries
  src/common/collection.c
Labels: feature: enhancement, scope: DAM, scope: UI, scope: performance

#9038 Update de.po
  po/de.po
Labels: scope: translation

#9032 timeline: use 'date' filter instead of 'date-time' filter whenever possible
  src/libs/tools/timeline.c
Labels: feature: enhancement, scope: DAM, scope: UI, scope: performance

#9044 noise profiles
  data/noiseprofiles.json
  data/noiseprofiles.schema
Labels: scope: camera support, scope: noise profile

#9050 Updated Dutch translation
  po/nl.po
Labels: scope: translation

#9051 Fix typos in user visible strings
  src/iop/filmic.c
  src/iop/filmicrgb.c
Labels: scope: codebase

#9048 crop : fix behavior whith shift
  src/iop/clipping.c
  src/iop/crop.c
Labels: bugfix, difficulty: average, scope: image processing

#9041 image ordering - preserve order of drag&drop images when using custom sort
  src/common/selection.c
Labels: bugfix, scope: DAM, scope: UI

#9011 Safer gphoto2 device handling
  src/common/camera_control.c
  src/common/camera_control.h
  src/control/jobs/camera_jobs.c
  src/libs/import.c
Labels: bugfix, difficulty: hard, priority: high, scope: codebase, scope: software support

#9033 tags: fix darktable tags table initialization
  src/common/collection.c
  src/common/darktable.c
  src/common/tags.c
  src/common/tags.h
Labels: scope: DAM, scope: codebase

#9056 import: fix labels and tooltips
  src/libs/import.c
Labels: scope: UI

#9055 Remove const type qualifiers from image2d_t to fix OpenCL kernel compilation
  data/kernels/channelmixer.cl
  data/kernels/color_conversion.h
  data/kernels/colorspaces.cl
  data/kernels/demosaic_rcd.cl
  data/kernels/extended.cl
  data/kernels/filmic.cl
Labels: bugfix, scope: hardware support, scope: image processing

#9066 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#9057 Fix display of the first image (imported) in tethering mode.
  src/views/tethering.c
Labels: bugfix

#9067 raise selection changed signal on query update if needed
  src/common/collection.c
Labels: bugfix, difficulty: trivial, scope: UI

#9058 collect : limit refresh
  src/common/collection.c
  src/common/collection.h
  src/common/film.c
  src/common/image.c
  src/common/selection.c
  src/common/undo.c
  src/control/jobs/camera_jobs.c
  src/control/jobs/control_jobs.c
  src/control/jobs/film_jobs.c
  src/control/signal.c
  src/control/signal.h
  src/dtgtk/thumbnail.c
  src/dtgtk/thumbtable.c
  src/libs/collect.c
  src/libs/copy_history.c
  src/libs/duplicate.c
  src/libs/export.c
  src/libs/image.c
  src/libs/import.c
  src/libs/metadata.c
  src/libs/recentcollect.c
  src/libs/select.c
  src/libs/styles.c
  src/libs/tagging.c
  src/libs/tools/colorlabels.c
  src/libs/tools/filter.c
  src/libs/tools/global_toolbox.c
  src/libs/tools/image_infos.c
  src/libs/tools/ratings.c
  src/libs/tools/timeline.c
  src/lua/database.c
  src/lua/image.c
  src/views/darkroom.c
  src/views/map.c
Labels: difficulty: average, feature: enhancement, priority: high, scope: DAM, scope: performance

#9068 Update Ukrainian translation
  po/uk.po
Labels: scope: translation

#9078 fix copy-paste-bug
  src/dtgtk/thumbnail_btn.c
Labels: bugfix, scope: codebase

#9081 initialize variable
  src/common/imageio.c
Labels: bugfix, scope: codebase

#9079 fix memory access violation
  src/iop/watermark.c
Labels: bugfix, scope: codebase

#9083 fix mask indicator visibility
  src/develop/imageop.c
Labels: bugfix

#9080 fix memory leak
  src/lua/events.c
Labels: bugfix, lua

#9053 Fixing hires scales with middle button mouseclick #9021
  src/libs/navigation.c
  src/views/darkroom.c
Labels: bugfix, priority: high, scope: UI

#9093 import: fix memory-leaks
  src/libs/import.c
Labels: bugfix

#9074 Improve thumbnails CSS and font-weight
  data/themes/darktable.css
Labels: difficulty: trivial, scope: UI

#9092 culling : redraw center after zoom change
  src/libs/tools/lighttable.c
Labels: bugfix, difficulty: trivial, priority: high, scope: UI

#9035 Install the AppStream file to the canonical location
  data/CMakeLists.txt
Labels: scope: OS support

#9071 converts license expression operators to uppercase
  data/darktable.appdata.xml.in
Labels: bugfix, scope: OS support, scope: codebase

#9097 Initialize n->details for DEVELOP_BLEND_VERSION update 10->11
  src/develop/blend.c
Labels: bugfix, priority: high, scope: codebase

#9096 colorin/iop_profile: better handling of CLUT profiles
  src/common/iop_profile.c
  src/iop/colorin.c
Labels: bugfix, priority: high, scope: image processing

#9108 Update Esperanto translation.
  po/eo.po
Labels: scope: translation

#9109 Updated Dutch translation
  po/nl.po
Labels: scope: translation

#9113 Revert lighter font-weight
  data/themes/darktable.css
Labels: bugfix, scope: UI

#9105 Nikon D780 Finetuned WB Presets
  src/external/wb_presets.c
Labels: scope: camera support

#9094 thumbnail : ensure we get the right size, avoiding rounding errors
  src/views/view.c
Labels: bugfix, priority: medium, scope: UI

#9104 GUI scale : clip scaling factor to 1 in denoise profiled
  src/iop/denoiseprofile.c
Labels: bugfix

#9115 cacorrectrgb: restrict EV difference between channels to [-3,3] EV
  src/iop/cacorrectrgb.c
Labels: bugfix, scope: image processing

#9107 colorbalancergb: alleviate some of the issues in #9095
  data/kernels/extended.cl
  src/iop/colorbalancergb.c
Labels: bugfix

#9088 fix sscanf in cups for systems with different local number format
  src/common/cups_print.c
  src/common/utility.c
  src/common/utility.h
Labels: bugfix

#9120 Update Ukrainian translation
  po/uk.po
Labels: scope: translation

#9116 fix retrieval of final size for untouched images
  src/common/image.c
  src/common/image.h
  src/common/image_cache.c
  src/libs/metadata_view.c
Labels: bugfix, difficulty: average, priority: medium, scope: UI

#9117 thumbnail : avoid rounding error when getting from preview
  src/dtgtk/thumbnail.c
Labels: bugfix, difficulty: trivial, scope: UI

#9119 channelmixerrgb: avoid division by zero, improve NORM_MIN handling
  data/kernels/channelmixer.cl
  src/iop/channelmixerrgb.c
Labels: bugfix, scope: image processing

#9124 speedup final size retrieval
  src/common/image.c
Labels: bugfix, difficulty: average, feature: enhancement, scope: performance
