Repository darktable-org/darktable, pull requests merged in 2021-06, with the labels that each got.

#9127 Fix double free on lua event destruction
  src/lua/events.c
Labels: bugfix, priority: high

#9072 Remember the last selected piwigo album.
  data/darktableconfig.xml.in
  src/common/collection.c
  src/imageio/storage/piwigo.c
Labels: feature: enhancement, release notes: pending, scope: DAM

#9114 Handle gphoto2 ptp protocol errors
  src/common/camera_control.c
  src/common/camera_control.h
Labels: scope: DAM, scope: hardware support, scope: software support

#9128 Fix inaccurate message about Exiv2 version
  src/CMakeLists.txt
Labels: scope: codebase

#9129 fix patch size tooltip in denoise profiled
  src/iop/denoiseprofile.c
Labels: bugfix, scope: UI

#9110 c&r : rework the preview ready detection
  src/iop/clipping.c
Labels: bugfix, difficulty: trivial, scope: image processing

#9132 Update de.po
  po/de.po
Labels: scope: translation

#9103 Ricoh GR III Finetuned WB Presets
  src/external/wb_presets.c
Labels: scope: camera support

#8773 rgbcurve: makes compensate middle grey not set by default.
  src/iop/rgbcurve.c
Labels: bugfix, difficulty: trivial, feature: redesign, no-pr-activity

#9146 noise profiles
  data/noiseprofiles.json
Labels: scope: noise profile

#9144 Update Ukrainian translation
  po/uk.po
Labels: scope: translation

#9140 Apply a style in overwrite & duplicate mode must not remove history of originals
  src/common/styles.c
  src/common/styles.h
  src/lua/styles.c
  src/views/darkroom.c
Labels: bugfix

#9154 po/fix brush
  src/develop/masks/brush.c
Labels: bugfix, priority: high

#9153 crop + c&r : sanitize crop datas for processing
  src/iop/clipping.c
  src/iop/crop.c
Labels: bugfix, difficulty: trivial, scope: image processing

#9155 fix hang when starting darktable in darkroom view
  src/libs/metadata_view.c
Labels: bugfix, lua

#9143 More robust image and xmp file testing
  src/common/database.c
  src/common/image.c
  src/common/utility.c
  src/common/utility.h
  src/generate-cache/main.c
  src/imageio/storage/disk.c
  src/iop/lut3d.c
Labels: bugfix, difficulty: average, scope: CLI, scope: DAM, scope: codebase

#8902 Add the support for FujiFilm GFX100S
  src/external/wb_presets.c
Labels: scope: camera support

#9161 darktable.css: remove padding for entries.
  data/themes/darktable.css
Labels: bugfix, priority: high, scope: UI

#9163 fix compile error with disabled OpenMP
  src/iop/denoiseprofile.c
Labels: bugfix, priority: high

#9152 More robust dt_import_session_path checks
  src/common/import_session.c
  src/common/utility.c
  src/common/utility.h
Labels: bugfix, scope: DAM

#9166 Update de.po
  po/de.po
Labels: scope: translation

#9167 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#9169 Update Esperanto translation.
  po/eo.po
Labels: scope: translation

#9179 Fixing color picker crashes with monochrome images
  src/common/color_picker.c
Labels: bugfix

#9164 cacorrectrgb: better handling of noisy pixels
  src/iop/cacorrectrgb.c
Labels: bugfix

#9185 Update Ukrainian translation
  po/uk.po
Labels: scope: translation

#9180 geotagging: fix direct entry issue on month and day.
  src/libs/geotagging.c
Labels: bugfix, scope: DAM, scope: UI

#9178 Fix crash in orientation module when resetting orientation
  src/dtgtk/resetlabel.c
Labels: bugfix

#9190 fix memory leak
  src/lua/events.c
Labels: bugfix

#9189 Pentax K-3 Mark III noise profile
  data/noiseprofiles.json
  data/noiseprofiles.schema
Labels: scope: noise profile

#9188 crop + c&r : fix max-size compute on quick focus in-out
  src/iop/clipping.c
  src/iop/crop.c
Labels: bugfix, difficulty: trivial, priority: high, scope: image processing

#9187 brush: fix moving whole brush (source and destination).
  src/develop/masks/brush.c
  src/develop/masks/path.c
Labels: bugfix, priority: high

#9195 unbreak mac CI
  .github/workflows/ci.yml
Labels: bugfix

#9194 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#9192 GPL is not EULA, no need to agree
  cmake/modules/NSIS.template.in
Labels: bugfix

#9193 don't crash when importing invalid style files
  src/libs/styles.c
Labels: bugfix

#9196 fix singlebuffer_limit tooltip
  data/darktableconfig.xml.in
Labels: bugfix, scope: UI

#9197 po/fix brush
  src/develop/masks/brush.c
Labels: bugfix

#8940 Add basic Sony ILCE-7SM3 support
  src/external/adobe_coeff.c
Labels: scope: camera support

#8935 Add basic Fujifilm X-E4 support
  src/external/adobe_coeff.c
Labels: scope: camera support

#9202 Use American spelling of gray (corrects the remaining cases of British spelling)
  src/iop/basicadj.c
  src/iop/channelmixerrgb.c
  src/iop/filmic.c
Labels: bugfix

#9200 colorbalancergb: add basic preset
  src/iop/colorbalancergb.c
Labels: documentation-pending, feature: enhancement

#9203 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#9208 Update de.po
  po/de.po
Labels: scope: translation

#9204 duplicate : fix output_width/height copying
  src/common/image.c
Labels: bugfix, difficulty: average, scope: UI

#9211 Update Ukrainian translation
  po/uk.po
Labels: scope: translation

#9216 Use American spelling of localization
  tools/generate_prefs.xsl
Labels: bugfix, scope: UI, scope: translation

#9220 Pentax K-3 Mark III noise profile redux
  data/noiseprofiles.json
  data/noiseprofiles.schema
Labels: scope: noise profile

#9222 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#9219 culling : fix quick zoom in position
  src/dtgtk/culling.c
Labels: bugfix, difficulty: average, scope: UI

#9225 Update de.po
  po/de.po
Labels: scope: translation

#9226 Updated Dutch translation
  po/nl.po
Labels: scope: translation

#9229 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#9227 colorbalancergb gamut mapping : better fix for #9095
  data/kernels/extended.cl
  src/iop/colorbalancergb.c
Labels: bugfix, scope: image processing

#9232 Update de.po
  po/de.po
Labels: scope: translation

#9233 Update Ukrainian translation
  po/uk.po
Labels: scope: translation

#9235 denoise opencl : try to fix #9136
  data/kernels/denoiseprofile.cl
Labels: bugfix, priority: high

#9240 EOS R6 WB presets
  src/external/wb_presets.c
Labels: scope: camera support

#9239 Add panasonic DMC-G8 finetuned wb presets
  src/external/wb_presets.c
Labels: scope: camera support

#9238 Finetuned X-E4 WB Presets
  src/external/wb_presets.c
Labels: scope: camera support

#9236 basecurve : clip RGB at 0
  data/kernels/basecurve.cl
  src/iop/basecurve.c
Labels: bugfix, priority: medium

#9250 Updated Dutch translation
  po/nl.po
Labels: scope: translation

#9249 Panasonic DC-FZ10002 finetuned wb
  src/external/wb_presets.c
Labels: scope: camera support

#9259 Update italian translation
  po/it.po
Labels: scope: translation

#9257 Color calibration: disable Yxy <-> XYZ roundtrip if no gamut compression is requested
  data/kernels/channelmixer.cl
  src/iop/channelmixerrgb.c
Labels: bugfix, priority: high

#9265 Panasonic DC-FZ10002 noise profile
  data/noiseprofiles.json
Labels: scope: noise profile

#9267 Update hu.po
  po/hu.po
Labels: scope: translation

#9245 fix various small memory leaks
  src/gui/preferences.c
  src/gui/presets.c
  src/imageio/storage/gallery.c
  src/imageio/storage/piwigo.c
  src/libs/collect.c
  src/libs/export_metadata.c
  src/libs/masks.c
  src/libs/styles.c
  src/libs/tagging.c
Labels: bugfix, scope: codebase

#9269 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#9256 exif: sanitize datetime on reading metadata
  src/common/exif.cc
  src/common/image.c
Labels: bugfix

#9275 Update Esperanto translation
  po/eo.po
Labels: scope: translation

#9205 dt_imageio_export_with_flags should keep history for append style
  src/common/imageio.c
Labels: bugfix, priority: medium

#9272 report separate memory requirements for CPU vs GPU to reduce CPU tiling
  src/common/gaussian.c
  src/common/gaussian.h
  src/iop/defringe.c
  src/iop/lowpass.c
  src/iop/shadhi.c
Labels: bugfix, scope: performance

#9284 Updated Hebrew translation
  po/he.po
Labels: scope: translation

#9289 Spanish translation update
  po/es.po
Labels: scope: translation

#9287 crop : remove unneeded distort compute
  src/iop/crop.c
Labels: difficulty: trivial, priority: low, scope: performance

#9282 ashift : update cropped size on focus out
  src/iop/ashift.c
Labels: bugfix, difficulty: trivial, scope: image processing

#9292 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#9291 [presets] fix incorrect reading from import presets
  src/common/presets.c
Labels: bugfix, difficulty: trivial, scope: codebase

#9283 modulegroups : respect single expanded setting in search mode
  src/develop/imageop.c
Labels: bugfix, difficulty: trivial, scope: UI

#9286 crop : update all sliders when one is changed
  src/iop/crop.c
Labels: bugfix, difficulty: trivial, scope: image processing

#9273 crop : keep params in synch with gui settings
  src/iop/crop.c
Labels: bugfix, difficulty: trivial, scope: image processing

#9294 nlmeans_core.c: avoid out-of-bounds references
  src/common/nlmeans_core.c
Labels: bugfix, priority: high, scope: image processing

#9304 Update Ukrainian translation
  po/uk.po
Labels: scope: translation

#9305 Spanish translation update
  po/es.po
Labels: scope: translation

#9307 Update italian translation
  po/it.po
Labels: scope: translation

#9310 Update Ukrainian translation
  po/uk.po
Labels: scope: translation

#9306 image infos : fix case where only one image from a selection is shown
  src/libs/metadata_view.c
Labels: bugfix, difficulty: trivial, scope: UI

#9317 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#9314 use dt_modifier_is to check for Control-key pressed
  src/dtgtk/thumbnail.c
  src/iop/vignette.c
Labels: bugfix, scope: UI

#9323 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#9321 Update hu.po
  po/hu.po
Labels: scope: translation

#9322 clip negative in B&W presets
  src/iop/channelmixerrgb.c
Labels: bugfix

#9324 Fix error font size
  src/views/darkroom.c
Labels: bugfix, scope: UI

#9319 Check if Sony Exif tag for focus distance has valid information
  src/common/exif.cc
Labels: bugfix, scope: codebase, scope: software support

#9329 Update italian translation
  po/it.po
Labels: scope: translation

#9326 Fix typos
  src/develop/develop.c
  src/develop/masks/detail.c
  src/gui/presets.c
  src/libs/histogram.c
  src/libs/import.c
  src/libs/tools/global_toolbox.c
  src/lua/widget/widget.c
Labels: scope: codebase

#9335 channelmixerrgb: remove references to red, green, blue
  src/iop/channelmixerrgb.c
Labels: difficulty: trivial, documentation-pending, feature: enhancement, scope: UI

#9345 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#9334 [crawler] use dt internal path normalization
  src/control/crawler.c
Labels: bugfix, difficulty: trivial, scope: DAM

#9316 memory leak fixes
  src/control/jobs/control_jobs.c
  src/develop/imageop.c
  src/gui/gtk.c
  src/gui/gtkentry.c
  src/gui/preferences.c
  src/iop/watermark.c
  src/libs/copy_history.c
  src/libs/import.c
  src/libs/tagging.c
  src/lua/preferences.c
  src/lua/widget/file_chooser.c
  src/lua/widget/text_view.c
Labels: bugfix, scope: codebase, scope: performance

#9298 fix wrong preset name
  src/iop/channelmixerrgb.c
Labels: bugfix

#9230 add device cname to debugging output
  src/common/opencl.c
Labels: difficulty: trivial, feature: enhancement, scope: hardware support

#9311 Mark more strings for translation
  src/iop/channelmixerrgb.c
Labels: scope: codebase, scope: translation

#9244 new debug option --enforce-tiling
  src/common/darktable.c
  src/common/darktable.h
  src/develop/pixelpipe_hb.c
  src/develop/tiling.c
Labels: documentation-pending, feature: enhancement, scope: codebase

#9349 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#9350 Update Esperanto translation
  po/eo.po
Labels: scope: translation

#9258 tools: use same make & model parsing everywhere
  tools/dngmeta.sh
  tools/noise/subr.sh
Labels: bugfix, feature: enhancement, scope: codebase, scope: software support

#9342 run import of commandline args as background job
  src/common/darktable.c
  src/control/jobs/film_jobs.c
  src/control/jobs/film_jobs.h
Labels: bugfix, scope: DAM, scope: UI, scope: performance

#9351 don't run import if no commandline args
  src/common/darktable.c
Labels: bugfix, priority: high

#9336 speed up filename matches in collections module
  src/libs/collect.c
Labels: scope: DAM, scope: UI, scope: performance
