Repository darktable-org/darktable, pull requests merged in 2021-09, with the labels that each got.

#9913 Fix duplicate UI issue
  data/themes/darktable.css
Labels: bugfix, difficulty: trivial, scope: UI

#9890 thumb : rating class + allow to fade the image drawing
  data/themes/darktable.css
  src/dtgtk/thumbnail.c
Labels: feature: enhancement, difficulty: trivial, scope: UI, documentation-pending, release notes: pending

#9916 color picker: fix sample info tooltip
  src/libs/colorpicker.c
  src/libs/history.c
Labels: bugfix, scope: UI

#9923 Update de.po
  po/de.po
Labels: scope: translation

#9903 Windows UNC support: add copy/move operations and fixes
  src/control/conf.c
  src/control/conf.h
  src/control/jobs/control_jobs.c
  src/gui/accelerators.c
  src/gui/preferences.c
  src/gui/presets.c
  src/libs/copy_history.c
  src/libs/geotagging.c
  src/libs/import.c
  src/libs/styles.c
Labels: bugfix, feature: redesign, scope: windows support

#9924 Copy & Import in Windows: more robust detection of film roll name
  src/common/image.c
Labels: bugfix, feature: enhancement, scope: windows support

#9925 color picker: misc. improvements
  src/control/signal.h
  src/develop/pixelpipe_hb.c
  src/gui/color_picker_proxy.c
  src/gui/gtk.c
  src/iop/colorzones.c
  src/iop/rgbcurve.c
  src/iop/tonecurve.c
  src/libs/colorpicker.c
  src/libs/colorpicker.h
  src/libs/histogram.c
  src/views/darkroom.c
Labels: bugfix, feature: enhancement

#9929 fix popup shortcut for invisible bauhaus widgets
  src/bauhaus/bauhaus.c
Labels: bugfix, feature: enhancement, scope: UI

#9938 [noiseprofiles] correct GR III name
  data/noiseprofiles.json
Labels: bugfix, scope: noise profile

#9939 collect: refresh the folders' status after relocating a lost folder
  src/libs/collect.c
Labels: bugfix

#9930 more native filechooser dialogs
  src/common/presets.c
  src/control/conf.c
  src/control/jobs/control_jobs.c
  src/gui/accelerators.c
  src/gui/preferences.c
  src/gui/presets.c
  src/imageio/storage/disk.c
  src/imageio/storage/gallery.c
  src/imageio/storage/latex.c
  src/iop/lut3d.c
  src/libs/collect.c
  src/libs/copy_history.c
  src/libs/import.c
  src/libs/styles.c
  src/libs/tagging.c
Labels: feature: enhancement, scope: UI, scope: OS support

#9933 minor usability: change position of "module order" tickbox in selective copy-paste dialog to the end (fixes #9671)
  src/gui/hist_dialog.c
Labels: feature: enhancement, scope: UI

#9947 Update Ukrainian translation (only corrections for 3.6.1)
  po/uk.po
Labels: scope: translation

#9894 let shortcut directly select a specific value in a combobox
  data/themes/darktable.css
  src/bauhaus/bauhaus.c
  src/bauhaus/bauhaus.h
  src/common/action.h
  src/control/control.c
  src/control/control.h
  src/develop/imageop_gui.c
  src/gui/accelerators.c
  src/gui/guides.c
  src/gui/guides.h
  src/iop/channelmixerrgb.c
  src/iop/filmicrgb.c
  src/libs/colorpicker.c
  src/libs/copy_history.c
  src/libs/export.c
  src/libs/tools/filter.c
  src/views/darkroom.c
  src/views/view.h
Labels: bugfix, feature: enhancement, scope: UI

#9904 vectorscope: add RYB option
  src/common/colorspaces_inline_conversions.h
  src/dtgtk/paint.c
  src/dtgtk/paint.h
  src/libs/histogram.c
Labels: feature: enhancement, scope: image processing, scope: color management, documentation-pending, release notes: pending

#9961 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#9963 tagging: retrieve properly attached tags
  src/common/tags.c
Labels: bugfix, scope: DAM

#9959 uniquify colorbalancergb sliders using sections
  src/iop/channelmixerrgb.c
  src/iop/colorbalancergb.c
Labels: bugfix, scope: UI, release notes: pending

#9927 fallback from midi knob press to knob turn for reset
  src/bauhaus/bauhaus.c
  src/gui/accelerators.c
  src/gui/accelerators.h
  src/libs/tools/midi.c
Labels: feature: enhancement

#9641 Add missing Canon cameras with CR3 format to adobe_coeff.c
  src/external/adobe_coeff.c
Labels: scope: camera support

#9910 adobe_coeff: Nikon Z fc support
  src/external/adobe_coeff.c
Labels: scope: camera support

#9917 adobe_coeff: Panasonic DC-GH5M2 support
  src/external/adobe_coeff.c
Labels: scope: camera support

#9972 Update de.po
  po/de.po
Labels: scope: translation

#9974 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#9951 denoiseprofile: fix wavelet preset
  src/iop/denoiseprofile.c
Labels: feature: redesign, scope: image processing

#9986 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#9985 Add Panasonic S5 noise profiles
  data/noiseprofiles.json
Labels: scope: noise profile

#9982 vectoscope ryb: set graphic icon
  src/dtgtk/paint.c
Labels: scope: UI

#9984 colorchecker: Draw active patch marker in black when patch is bright
  src/iop/colorchecker.c
Labels: feature: enhancement, scope: UI

#9987 add deployment targets to macOS CI
  .github/workflows/ci.yml
Labels: scope: macos support

#9996 fix losing lighttable selection on shortcut
  src/dtgtk/culling.c
  src/dtgtk/thumbtable.c
Labels: bugfix, scope: UI

#9926 Introduce dt_action_process to execute any action from LUA
  src/bauhaus/bauhaus.c
  src/common/action.h
  src/common/colorlabels.c
  src/common/ratings.c
  src/control/control.c
  src/develop/imageop.c
  src/gui/accelerators.c
  src/gui/accelerators.h
  src/gui/gtk.c
  src/iop/colorzones.c
  src/iop/rgblevels.c
  src/libs/lib.c
  src/libs/tools/midi.c
  src/lua/gui.c
  src/views/darkroom.c
  src/views/lighttable.c
Labels: feature: enhancement, lua

#10006 Map fixes
  src/views/map.c
Labels: bugfix, scope: UI, scope: DAM

#10012 imageio: refactor some ICC profile reading
  src/common/imageio_avif.c
  src/common/imageio_j2k.c
  src/common/imageio_jpeg.c
  src/common/imageio_png.c
  src/common/imageio_tiff.c
Labels: bugfix, scope: codebase

#10023 Update pt_BR translation
  po/pt_BR.po
Labels: scope: translation

#10022 print correct message when applying style using double click
  src/common/styles.c
Labels: bugfix, scope: UI

#10019 Optimize dt_apply_transposed_color_matrix
  src/common/colorspaces_inline_conversions.h
Labels: scope: performance, scope: codebase

#10031 Update pt_BR translation
  po/pt_BR.po
Labels: scope: translation

#10021 Fix blurring 9x9 kernel and introduce a weighed mask blur
  src/develop/blend.c
  src/develop/masks.h
  src/develop/masks/detail.c
  src/iop/dual_demosaic.c
Labels: scope: image processing, scope: performance, scope: codebase

#9981 Fix for - Drag and drop into lighttable fails if it's empty #8914 - feedback needed
  src/dtgtk/thumbtable.c
  src/dtgtk/thumbtable.h
  src/views/lighttable.c
Labels: bugfix, scope: UI

#10020 Check if we're importing actual darktable preset
  src/common/presets.c
  src/common/styles.c
  src/libs/styles.c
Labels: bugfix, scope: UI

#10026 Check for librsvg 2.52 and replace deprecated functions with new ones
  src/common/utility.c
  src/common/utility.h
  src/iop/watermark.c
Labels: bugfix, scope: software support

#10027 tone equalizer: improve pickers
  src/bauhaus/bauhaus.c
  src/iop/toneequal.c
Labels: bugfix, feature: enhancement, scope: UI, scope: image processing

#10050 Add a search box in presets perferences and shortcuts fixes
  data/themes/darktable.css
  src/gui/accelerators.c
  src/gui/gtk.c
  src/gui/gtk.h
  src/gui/preferences.c
  src/gui/presets.c
  src/libs/modulegroups.c
Labels: bugfix, feature: enhancement, scope: UI, documentation-pending, release notes: pending

#10057 Install translations in the correct directories
  cmake/windows-macros.cmake
Labels: bugfix, scope: windows support

#10061 guides : don't draw guides on image margins
  src/views/darkroom.c
Labels: bugfix, difficulty: trivial, scope: UI

#10064 use custom yes/no dialog for shortcuts confirmations
  src/develop/imageop.c
  src/gui/accelerators.c
  src/gui/accelerators.h
  src/libs/history.c
  src/libs/tools/global_toolbox.c
  src/views/darkroom.c
Labels: bugfix, feature: enhancement

#10058 collect: Fix/collect use imagetime not importtime
  src/libs/collect.c
Labels: feature: enhancement, scope: DAM, documentation-pending, release notes: pending

#10059 Improve shortcuts view showing default elements/effects
  src/gui/accelerators.c
Labels: feature: enhancement

#10066 group global shortcuts for views and panels
  src/gui/gtk.c
  src/libs/tools/viewswitcher.c
Labels: feature: enhancement

#10073 Fix tiling
  src/iop/colorbalancergb.c
  src/iop/diffuse.c
  src/iop/filmicrgb.c
Labels: bugfix

#10071 magic wand icon for TE
  src/dtgtk/paint.c
  src/dtgtk/paint.h
  src/iop/toneequal.c
Labels: scope: UI

#10078 Update pt_BR translation
  po/pt_BR.po
Labels: scope: translation

#10030 Add collection rating filter
  src/common/collection.c
  src/common/collection.h
  src/libs/collect.c
  src/libs/lib.c
Labels: feature: enhancement, priority: low, scope: DAM, documentation-pending, release notes: pending

#9456 ashift rework
  data/darktableconfig.xml.in
  src/dtgtk/paint.c
  src/dtgtk/paint.h
  src/iop/ashift.c
Labels: feature: redesign, difficulty: hard, scope: image processing, documentation-pending

#10094 Update pt_BR translation
  po/pt_BR.po
Labels: scope: translation

#10101 ashift : enhance a little tooltips
  src/iop/ashift.c
Labels: feature: enhancement, difficulty: trivial, scope: UI

#10089 show current order in order lib module's header
  src/libs/ioporder.c
  src/libs/lib.c
Labels: documentation-pending, release notes: pending

#10084 Introducing a distance transform algorithm
  src/common/distance_transform.h
Labels: feature: new

#10113 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#10114 Update de.po
  po/de.po
Labels: scope: translation

#10108 ashift : various small fix
  data/darktableconfig.xml.in
  src/iop/ashift.c
Labels: bugfix, difficulty: trivial, scope: image processing

#10123 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#10107 rejected thumb css improvement
  data/themes/darktable.css
Labels: difficulty: trivial, scope: UI
