Repository darktable-org/darktable, pull requests merged in 2021-12, with the labels that each got.

#10529 Update Esperanto translation.
  po/eo.po
Labels: scope: translation

#10530 Spanish translation update
  po/es.po
Labels: scope: translation

#10541 Spanish translation update
  po/es.po
Labels: scope: translation

#10539 ashift : various small fix
  src/iop/ashift.c
Labels: bugfix, difficulty: trivial, scope: UI

#10544 po/fix mask tree refresh
  src/develop/develop.c
  src/develop/develop.h
  src/develop/masks/brush.c
  src/develop/masks/circle.c
  src/develop/masks/ellipse.c
  src/develop/masks/gradient.c
  src/develop/masks/masks.c
  src/develop/masks/path.c
  src/libs/masks.c
  src/libs/tagging.c
Labels: bugfix, documentation-pending

#10542 opencl: handle fast pipe on GPU
  src/common/opencl.c
Labels: bugfix, difficulty: trivial, scope: performance

#10549 po/fix masks manager menu
  src/libs/masks.c
Labels: bugfix

#10558 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#10555 po/fix style mi
  src/common/styles.c
  src/gui/styles_dialog.c
Labels: bugfix, priority: high, scope: DAM

#10561 Fix-calibration
  src/iop/channelmixerrgb.c
Labels: bugfix, release notes: pending

#10563 Polish translation update: polishing it a bit
  po/pl.po
Labels: scope: translation

#10562 final update the italian translation and fix minor typo
  po/it.po
Labels: scope: translation

#10568 french translation: small fix
  po/fr.po
Labels: bugfix

#10565 color calibration : fix suggested exposure/black
  src/iop/channelmixerrgb.c
Labels: bugfix

#10570 Update live picker when picker is not active
  src/gui/color_picker_proxy.c
Labels: bugfix, priority: medium

#10576 french translation: some fixes on shortcuts settings
  po/fr.po
Labels: bugfix

#10585 Metadata: fixes segfault when leaving dt with a metadata field in focus
  src/libs/metadata.c
Labels: bugfix

#10586 Remove message if key press absorbed by entry widget
  src/gui/accelerators.c
Labels: difficulty: trivial

#10591 avoid gtk_button_set_label clearing ellipsize
  src/libs/image.c
  src/libs/map_locations.c
  src/libs/modulegroups.c
Labels: bugfix, difficulty: trivial

#10590 french translation: small fix for color reconstruction
  po/fr.po
Labels: bugfix

#10584 metadata: fix auto-resizing of textview widgets
  src/libs/metadata.c
Labels: bugfix

#10596 Spanish translation update
  po/es.po
Labels: scope: translation

#10272 adobe_coeff: Sony ZV-E10 support
  src/external/adobe_coeff.c
Labels: scope: camera support

#10603 Update de.po
  po/de.po
Labels: scope: translation

#10615 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#10616 Set back highlighted view in main header
  data/themes/darktable.css
Labels: difficulty: trivial, scope: UI

#10621 Spanish translation update
  po/es.po
Labels: scope: translation

#10629 Updated Hebrew translation
  po/he.po
Labels: scope: translation

#10630 More translation warning fixes
  po/gl.po
  po/ro.po
Labels: scope: translation

#10632 Relicense promo svg
  data/darktable.appdata.xml.in
  data/watermarks/promo.svg
Labels: priority: high, scope: codebase

#10636 Spanish translation update: some corrections
  po/es.po
Labels: scope: translation

#10633 Fix #10609
  src/develop/blend.c
  src/develop/pixelpipe_hb.c
Labels: bugfix, priority: high, scope: codebase

#10571 Update translations for zh_CN for 3.8 string freeze
  po/zh_CN.po
Labels: scope: translation

#10648 Fix typo in German translation
  po/de.po
Labels: scope: translation

#10693 Update de.po
  po/de.po
Labels: scope: translation

#10681 crop: remove double-click hints
  src/iop/crop.c
Labels: bugfix

#10690 Resolve issue 10664 (remove blank nodes when parsing XML of darktable style)
  src/libs/styles.c
Labels: bugfix

#10667 thumbtable : fix mouse over when cursor leave
  src/dtgtk/culling.c
  src/dtgtk/thumbtable.c
Labels: bugfix, difficulty: trivial, scope: UI

#10697 #10654 - import: Fixed crash when importing images with copy to path …
  src/common/import_session.c
  src/common/utility.c
Labels: bugfix

#10699 export tags: roll back #9963 taking care #9949 is still fixed
  src/common/tags.c
Labels: bugfix

#10714 print settings: fix units display in image layout overlay
  src/libs/print_settings.c
Labels: bugfix

#10649 images to act on : refactor + fix
  src/CMakeLists.txt
  src/common/act_on.c
  src/common/act_on.h
  src/common/colorlabels.c
  src/common/image.c
  src/common/metadata.c
  src/common/ratings.c
  src/common/selection.c
  src/common/styles.c
  src/common/tags.c
  src/control/jobs/control_jobs.c
  src/dtgtk/thumbtable.c
  src/libs/copy_history.c
  src/libs/export.c
  src/libs/geotagging.c
  src/libs/image.c
  src/libs/metadata.c
  src/libs/metadata_view.c
  src/libs/styles.c
  src/libs/tagging.c
  src/libs/tools/colorlabels.c
  src/libs/tools/ratings.c
  src/lua/gui.c
  src/views/darkroom.c
  src/views/map.c
  src/views/print.c
  src/views/slideshow.c
  src/views/view.c
  src/views/view.h
Labels: bugfix, feature: redesign, difficulty: average, scope: UI, scope: DAM

#10730 Fix GIO/gnunixmounts.h error on NixOS
  cmake/modules/FindGIO.cmake
Labels: bugfix

#10727 Fix yellow border
  data/themes/darktable.css
Labels: bugfix, difficulty: trivial, scope: UI

#10720 Correct a typo in the UI string
  src/libs/geotagging.c
Labels: scope: translation

#10723 README: change lua version
  README.md
Labels: lua

#10726 Pass is_scaling to dt_imageio_export_with_flags.
  src/common/imageio.c
  src/common/imageio.h
  src/common/mipmap_cache.c
  src/control/jobs/control_jobs.c
  src/libs/print_settings.c
  src/views/slideshow.c
  src/views/tethering.c
Labels: bugfix, priority: high

#10704 utility: fix for librsvg 2.52
  src/common/utility.c
Labels: bugfix, priority: high

#10735 Fix variable expansion for import path in Windows
  src/common/import_session.c
Labels: bugfix, scope: windows support

#10738 Selecting a range with Shift-Mouseclick requires a starting point
  src/common/selection.c
Labels: bugfix

#10744 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#10737 po/fix ctrl pts
  src/develop/masks/brush.c
  src/develop/masks/path.c
Labels: bugfix, priority: medium
