Repository darktable-org/darktable, pull requests merged in 2022-10, with the labels that each got.

#12570 Fix OpenCL 'photosite color' debug demosaicer for xtrans
  data/kernels/demosaic_other.cl
  src/iop/demosaic.c
Labels: bugfix, scope: codebase

#12574 Visualize highlights gives exact info according to the used recovery mode
  src/iop/highlights.c
Labels: bugfix

#12576 po/liquify missed updates
  src/iop/liquify.c
Labels: bugfix, priority: medium, understood: incomplete, scope: codebase, release notes: pending

#12586 po/introspection types
  src/develop/imageop.c
  src/iop/liquify.c
Labels: feature: enhancement, scope: codebase

#12560 Add WebP read support using libwebp
  data/CMakeLists.txt
  src/CMakeLists.txt
  src/common/image.h
  src/common/imageio.c
  src/common/imageio_webp.c
  src/common/imageio_webp.h
Labels: feature: enhancement, difficulty: average, scope: software support, documentation-pending, release notes: pending

#12565 imageio_im: read image profile, add WebP read fallback
  data/supported_extensions.cmake
  src/CMakeLists.txt
  src/common/imageio_im.c
Labels: feature: enhancement, scope: image processing, release notes: pending

#12594 imageio: enable JXL fallback reading
  src/CMakeLists.txt
  src/common/imageio_gm.c
  src/common/imageio_im.c
Labels: feature: new, scope: codebase, documentation-pending, release notes: pending

#12578 Inpaint opposed means highlights reconstruction
  src/iop/highlights.c
  src/iop/opposed.c
Labels: feature: enhancement, scope: image processing, documentation-pending, release notes: pending

#12595 po/fix liquify update
  src/develop/imageop.c
  src/iop/liquify.c
Labels: bugfix, priority: high, difficulty: hard, scope: image processing, scope: codebase

#12597 PL translation
  po/pl.po
Labels: scope: translation

#12601 Update de.po
  po/de.po
Labels: scope: translation

#12600 Support build with ImageMagick 6
  src/CMakeLists.txt
  src/common/darktable.c
  src/common/imageio.c
  src/common/imageio_im.c
Labels: scope: codebase

#12566 dt_selection_select_unaltered: Fix code to use the hashes.
  src/common/selection.c
Labels: bugfix, scope: DAM, release notes: pending

#12585 imageio_exr: handle APP1 prefix on exif import
  src/common/image.c
  src/common/imageio_exr.cc
Labels: feature: enhancement, scope: DAM, release notes: pending

#12599 imageio_tiff: use Imath for 16-bit half float export
  README.md
  data/darktableconfig.xml.in
  src/CMakeLists.txt
  src/common/imageio_tiff.c
  src/imageio/format/tiff.c
Labels: priority: low, scope: codebase, release notes: pending, scope: macos support

#12618 update zh_TW.po
  po/zh_TW.po
Labels: scope: translation

#12614 CMakeLists.txt: Check for LLVM 7 or above.
  CMakeLists.txt
Labels: scope: codebase

#12605 Version 2 of segmentation highlights reconstruction supports xtrans
  src/common/distance_transform.h
  src/develop/masks/detail.c
  src/iop/highlights.c
  src/iop/hlrecovery_v2.c
  src/iop/opposed.c
  src/iop/segmentation.h
Labels: feature: redesign, scope: image processing, release notes: pending

#12619 CMake: simplify libheif search
  cmake/modules/Findlibheif.cmake
  src/CMakeLists.txt
Labels: scope: codebase

#12593 Silence the webp loader's complaint about failed metadata reading
  src/common/imageio_webp.c
Labels: feature: redesign, scope: codebase

#12561 Manipulate masks without scrolling for tablet users
  src/bauhaus/bauhaus.c
  src/develop/blend_gui.c
  src/develop/develop.c
  src/develop/develop.h
  src/develop/masks.h
  src/develop/masks/brush.c
  src/develop/masks/circle.c
  src/develop/masks/ellipse.c
  src/develop/masks/gradient.c
  src/develop/masks/masks.c
  src/develop/masks/path.c
  src/dtgtk/range.c
  src/gui/accelerators.c
  src/gui/gtk.c
  src/iop/retouch.c
  src/iop/spots.c
  src/libs/filtering.c
  src/libs/masks.c
  src/libs/tools/filter.c
Labels: feature: new, scope: UI, scope: codebase, documentation-pending, release notes: pending

#12622 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#12625 Improve XMP spelling consistency in darktable UI
  data/darktableconfig.dtd
  data/darktableconfig.xml.in
  src/cli/main.c
  src/common/exif.cc
  src/control/crawler.c
  src/gui/import_metadata.c
  src/libs/export_metadata.c
Labels: scope: codebase

#12626 fix range of gradient mask curvature slider
  src/libs/masks.c
Labels: bugfix, priority: high

#12623 Further work on highlights reconstruction
  src/iop/highlights.c
  src/iop/opposed.c
Labels: feature: enhancement, priority: high, scope: image processing, scope: codebase, documentation-pending, release notes: pending

#12629 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#12630 Lua processing events
  src/develop/develop.c
  src/lua/events.c
  src/views/darkroom.c
Labels: lua

#12631 Make all OpenCl code use the default symbolic error
  src/iop/ashift.c
  src/iop/atrous.c
  src/iop/basecurve.c
  src/iop/bloom.c
  src/iop/blurs.c
  src/iop/borders.c
  src/iop/censorize.c
  src/iop/channelmixer.c
  src/iop/channelmixerrgb.c
  src/iop/clipping.c
  src/iop/colisa.c
  src/iop/colorbalance.c
  src/iop/colorbalancergb.c
  src/iop/colorchecker.c
  src/iop/colorcontrast.c
  src/iop/colorcorrection.c
  src/iop/colorin.c
  src/iop/colorize.c
  src/iop/colormapping.c
  src/iop/colorout.c
  src/iop/colorzones.c
  src/iop/crop.c
  src/iop/denoiseprofile.c
  src/iop/diffuse.c
  src/iop/exposure.c
  src/iop/filmic.c
  src/iop/filmicrgb.c
  src/iop/finalscale.c
  src/iop/flip.c
  src/iop/globaltonemap.c
  src/iop/graduatednd.c
  src/iop/highpass.c
  src/iop/invert.c
  src/iop/lens.cc
  src/iop/levels.c
  src/iop/liquify.c
  src/iop/lowlight.c
  src/iop/lowpass.c
  src/iop/mask_manager.c
  src/iop/monochrome.c
  src/iop/negadoctor.c
  src/iop/nlmeans.c
  src/iop/overexposed.c
  src/iop/profile_gamma.c
  src/iop/rawoverexposed.c
  src/iop/rawprepare.c
  src/iop/relight.c
  src/iop/shadhi.c
  src/iop/sharpen.c
  src/iop/soften.c
  src/iop/splittoning.c
  src/iop/temperature.c
  src/iop/tonecurve.c
  src/iop/velvia.c
  src/iop/vibrance.c
  src/iop/vignette.c
  src/iop/zonesystem.c
Labels: scope: codebase

#12634 develop: Try fixing compilation issue on old compilers.
  src/develop/develop.c
Labels: bugfix, priority: high, lua

#12633 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#12635 fix darkroom-image-loaded event when changing to darkroom view
  src/views/darkroom.c
Labels: scope: codebase, lua

#12636 Bugfix: Early sanitizing the highlights reconstruction mode
  src/iop/highlights.c
Labels: bugfix, priority: high

#12620 show image count in filter toolbox instead of hinter
  src/common/collection.c
  src/gui/gtk.c
  src/libs/tools/filter.c
  src/views/view.c
  src/views/view.h
Labels: feature: redesign, scope: UI, documentation-pending, release notes: pending

#12644 Update de.po
  po/de.po
Labels: scope: translation

#12637 Keep modules in place or fully visible when opening or expanding
  data/darktableconfig.xml.in
  src/common/darktable.c
  src/develop/blend.h
  src/develop/blend_gui.c
  src/develop/imageop.c
  src/dtgtk/expander.c
  src/gui/gtk.c
  src/gui/gtk.h
  src/libs/lib.c
  src/views/darkroom.c
  src/views/view.c
Labels: bugfix, scope: UI, release notes: pending

#12651 Make "inpaint opposed" and "segmentation" hl reconstruction ROI immune
  src/iop/highlights.c
  src/iop/hlrecovery_v2.c
  src/iop/opposed.c
Labels: feature: enhancement, priority: high, scope: image processing

#12632 imageio_libraw: also keep the base black level
  src/common/imageio_libraw.c
Labels: bugfix, release notes: pending

#12652 po/default inpaint opposed
  src/common/image.h
  src/iop/highlights.c
Labels: priority: high, feature: redesign, difficulty: average, scope: image processing

#12668 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11696 piwigo-export: update existing photos
  data/darktableconfig.xml.in
  src/imageio/storage/piwigo.c
Labels: feature: enhancement, scope: DAM, scope: software support, documentation-pending, release notes: pending

#12659 Support for regional date and time format in thumbnail tooltips.
  data/darktableconfig.xml.in
  src/common/variables.c
Labels: feature: new, difficulty: trivial, documentation-pending, release notes: pending

#12671 po/fix style shortcut
  src/common/styles.c
  src/common/styles.h
  src/views/darkroom.c
Labels: bugfix, priority: high, release notes: pending

#12676 Introduce ROI debugging helpers
  src/common/darktable.c
  src/common/darktable.h
  src/develop/pixelpipe_hb.c
  src/develop/tiling.c
Labels: scope: codebase

#12683 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#12685 Update de.po
  po/de.po
Labels: scope: translation

#12681 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#12680 Allow adding filmic auto-tune to quick access panel
  data/themes/darktable.css
  src/bauhaus/bauhaus.c
  src/iop/filmicrgb.c
Labels: bugfix, wip, difficulty: trivial, scope: UI

#12682 Proper fix for highlights reconstruction ROI problems
  src/iop/highlights.c
  src/iop/hlrecovery_v2.c
  src/iop/opposed.c
Labels: bugfix, priority: high, difficulty: hard, scope: codebase

#12699 Updated Finnish translation
  po/fi.po
Labels: scope: translation

#12691 improve smooth module scrolling logic
  src/dtgtk/expander.c
Labels: bugfix, priority: high

#12689 Bugfixing and don't prepare opposed for segmentation in sraw images
  src/iop/highlights.c
  src/iop/hlrecovery_v2.c
  src/iop/opposed.c
Labels: bugfix, priority: high

#12698 Noise profiles
  data/noiseprofiles.json
Labels: scope: noise profile

#12690 Bugfix: refresh mask manager after image change
  src/views/darkroom.c
Labels: bugfix, priority: high, scope: codebase, release notes: pending

#10044 JPEG XL output format support
  .ci/Brewfile
  .ci/ci-script.sh
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  DefineOptions.cmake
  README.md
  cmake/modules/FindJXL.cmake
  cmake/windows-macros.cmake
  data/darktableconfig.xml.in
  packaging/macosx/1_install_hb_dependencies.sh
  packaging/macosx/BUILD-ARM64.txt
  packaging/macosx/BUILD.txt
  packaging/windows/README.md
  src/CMakeLists.txt
  src/imageio/format/CMakeLists.txt
  src/imageio/format/jxl.c
  src/imageio/storage/gallery.c
Labels: feature: enhancement, priority: low, difficulty: hard, documentation-pending, release notes: pending

#12696 curl_tools: set proper useragent
  src/common/curl_tools.c
Labels: feature: enhancement, priority: low

#12716 Update min Windows requirements
  README.md
  packaging/windows/README.md
Labels: scope: windows support

#12721 fix for build issue (#12720) with macOS sdk13
  src/osx/osx.mm
Labels: scope: macos support

#12717 slideshow: Properly use the display profile.
  src/views/slideshow.c
Labels: bugfix

#12728 Manifest WebP support in the output of darktable --version
  src/common/darktable.c
Labels: scope: UI

#12731 restore separate "scroll to module" setting for lighttable/libs
  src/develop/imageop.c
  src/dtgtk/expander.c
Labels: bugfix

#12732 Manifest more optional features in the output of darktable --version
  src/common/darktable.c
Labels: feature: enhancement

#12738 select created mask shape and improve hinter visibility
  src/common/collection.c
  src/develop/masks/masks.c
  src/gui/gtk.c
  src/iop/liquify.c
  src/libs/tools/hinter.c
Labels: bugfix, priority: medium, release notes: pending

#12718 clarify meaning of ctrl+scroll widget "resizing"
  src/gui/gtk.c
Labels: feature: enhancement, scope: UI
