Repository darktable-org/darktable, pull requests merged in 2022-01, with the labels that each got.

#10715 Factorize the on/off history item representation.
  src/common/history.c
  src/common/history.h
  src/common/styles.c
Labels: feature: enhancement, priority: medium, difficulty: trivial, scope: UI, documentation-pending

#10756 tags presets: append preset's tags instead of replacing.
  src/libs/tagging.c
Labels: scope: DAM, bug: fixed

#10762 register lib presets before loading shortcuts
  src/libs/lib.c
  src/libs/lib.h
  src/libs/location.c
  src/libs/metadata_view.c
  src/libs/print_settings.c
  src/views/view.c
Labels: bugfix

#10769 masks: reverse up/down behaviour
  src/libs/masks.c
Labels: bugfix, difficulty: trivial, scope: UI

#10599 make perspective helpers shortcuttable actions
  src/control/jobs/control_jobs.c
  src/control/jobs/control_jobs.h
  src/gui/accelerators.c
  src/iop/ashift.c
  src/libs/image.c
Labels: bugfix, feature: enhancement

#10526 variables: add the vairable $(DARKTABLE_VERSION)
  src/common/variables.c
  src/gui/gtkentry.c
Labels: feature: enhancement, scope: DAM, documentation-pending

#10768 reduce space required for filter/sort box in header
  data/themes/darktable.css
  src/libs/tools/filter.c
Labels: bugfix

#10782 print: setup of paper/medium on printer change
  src/libs/print_settings.c
Labels: bugfix

#10805 Update Japanese translation
  po/ja.po
Labels: scope: translation

#10815 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#10816 Update ja.po
  po/ja.po
Labels: scope: translation

#10810 simplify/fix export dimensions widgets visibility
  src/libs/export.c
Labels: bugfix, scope: UI

#10818 update filmic graph in module or QAP
  src/iop/filmicrgb.c
Labels: bugfix

#10831 use rename_new_instance pref when duplicating for preset
  src/develop/imageop.c
  src/develop/imageop.h
  src/gui/presets.c
Labels: bugfix, difficulty: trivial, scope: UI

#10833 [styles.c] remove `/` from style name to avoid crash
  src/common/styles.c
Labels: bugfix, scope: UI

#10826 data/kernels: switch atomics to OpenCL 1.1+
  data/kernels/bilateral.cl
  data/kernels/colorreconstruction.cl
Labels: scope: hardware support, scope: software support, scope: codebase

#10843 Add screenshot on Github page
  README.md
Labels: feature: enhancement

#10841 Fix various demosaicer issues with amd drivers
  data/kernels/demosaic_other.cl
  data/kernels/demosaic_ppg.cl
  data/kernels/demosaic_rcd.cl
  data/kernels/demosaic_vng.cl
  src/iop/demosaic.c
Labels: bugfix, priority: high, scope: image processing

#10859 tagging: in export filename, replaces : by - in timestamp
  src/libs/tagging.c
Labels: bugfix, scope: DAM, scope: windows support

#10867 Update ja.po
  po/ja.po
Labels: scope: translation

#10887 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#10888 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#10877 rework ui for copy history and style creation dialog
  src/common/history.c
  src/common/history.h
  src/common/styles.c
  src/develop/imageop.c
  src/develop/imageop.h
  src/dtgtk/paint.c
  src/dtgtk/paint.h
  src/gui/draw.h
  src/gui/hist_dialog.c
  src/gui/styles_dialog.c
  src/libs/history.c
  src/libs/import.c
Labels: feature: redesign, scope: UI

#10891 Fix typos in source file comments
  src/iop/temperature.c
Labels: scope: codebase

#10812 only send updates to active midi devices
  src/gui/accelerators.c
  src/libs/tools/midi.c
Labels: bugfix

#10897 New noise profiles
  data/noiseprofiles.json
Labels: scope: noise profile

#10901 Update Esperanto translation.
  po/eo.po
Labels: scope: translation

#10851 exif: fix DNG Daylight illuminant parsing
  src/common/exif.cc
Labels: bugfix, scope: camera support, difficulty: average

#10874 tagging: allow to drag over tags without necessarily expand them
  src/libs/tagging.c
Labels: feature: enhancement, scope: UI, scope: DAM, documentation-pending

#10784 tagging: some UI improvements as suggested on dev.
  src/libs/tagging.c
Labels: feature: enhancement, scope: UI, scope: DAM, documentation-pending

#10798 Fix default blend colorspace for contrast equalizer module and dummy IOP
  src/iop/atrous.c
  src/iop/useless.c
Labels: feature: redesign

#10863 tagging: fix regression - Shift+click full expands the tag in treeview.
  src/libs/tagging.c
Labels: bugfix, scope: UI, scope: DAM

#10911 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#10913 Update ja.po
  po/ja.po
Labels: scope: translation

#10907 performance: speed up heal tool's adaptation code
  src/common/heal.c
Labels: scope: image processing, scope: performance

#10918 Update ja.po
  po/ja.po
Labels: scope: translation

#10940 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#10931 po/piwigo lounge
  src/imageio/storage/piwigo.c
Labels: bugfix, priority: medium, feature: redesign

#10961 drawing grid inside the cropped section for rotate and perspective
  src/iop/ashift.c
Labels: bugfix, priority: medium, scope: UI

#10968 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#10959 thumb : refine cross/stars positions
  src/dtgtk/thumbnail.c
Labels: feature: enhancement, difficulty: trivial, scope: UI

#10989 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#10990 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#10991 exif: remove ICC and few more tags
  src/common/exif.cc
Labels: bugfix, priority: medium

#10997 Spanish translation update
  po/es.po
Labels: scope: translation

#10998 Update ja.po
  po/ja.po
Labels: scope: translation

#11000 Update de.po
  po/de.po
Labels: scope: translation

#11004 Spanish translation update
  po/es.po
Labels: scope: translation

#11006 Updated czech language
  po/cs.po
Labels: scope: translation

#10993 avif: add XMP metadata
  src/imageio/format/avif.c
Labels: bugfix

#10937 import: don't expect that filename comes from g_file_get_parse_name()
  src/common/import_session.c
  src/libs/import.c
Labels: bugfix

#11008 avif: omit nul terminator on XMP write
  src/imageio/format/avif.c
Labels: scope: software support

#11011 singular / plural correction
  po/cs.po
Labels: scope: translation

#11015 exif: improve unknown DNG illuminant handling
  src/common/exif.cc
Labels: bugfix, scope: camera support

#11017 set notebook padding at label level not tab, fixing resizing error
  data/themes/darktable.css
  src/gui/gtk.c
Labels: bugfix, difficulty: trivial

#11041 preferences: open in correct tab regardless of language
  src/gui/preferences.c
Labels: bugfix, difficulty: trivial
