Repository darktable-org/darktable, pull requests merged in 2022-02, with the labels that each got.

#11037 imageop: fix enabling iop modules with kbd shortcut
  src/develop/imageop.c
Labels: bugfix, difficulty: trivial, scope: UI

#11047 Update pl.po
  po/pl.po
Labels: scope: translation

#11049 exif: remove spurious error message
  src/common/exif.cc
Labels: bugfix

#11054 metadata: make module reset button work again
  src/libs/metadata.c
Labels: bugfix, scope: UI, scope: DAM

#11020 fix $(RATING_ICONS) variable substitution
  src/common/variables.c
  src/gui/gtkentry.c
Labels: bugfix

#11055 Fix monochrome lens correction
  data/kernels/basic.cl
  src/iop/lens.cc
Labels: bugfix, scope: image processing, scope: color management

#11057 Update it.po
  po/it.po
Labels: scope: translation

#11063 Fix lens.cc building for old compilers
  src/iop/lens.cc
Labels: scope: codebase

#11061 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#10650 Switch CI to Ninja, fetch tag for nightly
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  packaging/windows/BUILD.md
Labels: scope: windows support

#11077 Update nl.po
  po/nl.po
Labels: scope: translation

#11078 enable shortcuts to popover widgets before first open
  src/gui/guides.c
  src/views/darkroom.c
Labels: bugfix, difficulty: trivial

#11079 Respect high_quality setting while exporting (bugfix 11068)
  src/common/imageio.c
Labels: scope: codebase

#11080 Update ja.po
  po/ja.po
Labels: scope: translation

#11084 Update pl.po
  po/pl.po
Labels: scope: translation

#11085 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#11086 fix some minor typo in italian translation
  po/it.po
Labels: scope: translation

#11091 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11095 Update italian translation
  po/it.po
Labels: scope: translation

#10822 Tone equalizer presets shall use scene referred blending mode by default
  src/iop/toneequal.c
Labels: feature: enhancement

#11036 modulegroups: module search should include user-defined name
  src/libs/modulegroups.c
Labels: feature: enhancement, scope: UI, documentation-pending, release notes: pending

#10950 handle simultaneous shortcut presses and improve responsiveness
  src/gui/accelerators.c
Labels: priority: high, feature: redesign

#10967 UI improvements: new icons and more
  data/themes/darktable.css
  po/fr.po
  src/bauhaus/bauhaus.c
  src/dtgtk/paint.c
  src/dtgtk/paint.h
  src/dtgtk/thumbnail.c
  src/libs/tools/filter.c
Labels: feature: new, feature: redesign, difficulty: trivial, scope: UI, documentation-pending, release notes: pending

#10982 fix "export 0 images" issue
  src/control/jobs/control_jobs.c
Labels: scope: translation, priority: low, difficulty: trivial, scope: UI

#10793 camera: use correct libgphoto2 translation domain
  src/CMakeLists.txt
  src/common/camera_control.c
  src/libs/camera.c
Labels: scope: software support, scope: codebase

#10965 metadata: control better the start of edition mode
  src/common/act_on.c
  src/dtgtk/thumbtable.c
  src/dtgtk/thumbtable.h
  src/libs/metadata.c
  src/views/lighttable.c
Labels: bugfix, scope: UI, scope: DAM, documentation-pending, release notes: pending

#10499 clicking on slider "header" focuses or pops up
  src/bauhaus/bauhaus.c
Labels: scope: UI

#10808 pref submenu: activate Enter key to save preferences
  src/libs/collect.c
  src/libs/export_metadata.c
  src/libs/import.c
  src/libs/lib.c
  src/libs/lib.h
  src/libs/metadata.c
  src/libs/metadata_view.c
  src/libs/recentcollect.c
Labels: feature: enhancement, feature: redesign, scope: UI, documentation-pending

#10617 fix notebook tooltips
  src/gui/accelerators.c
  src/gui/accelerators.h
  src/gui/gtk.c
Labels: bugfix, scope: UI, release notes: pending

#10595 improve consistency for mouse action mods in H screen
  src/develop/blend_gui.c
  src/gui/accelerators.c
  src/gui/preferences.c
  src/iop/clipping.c
  src/iop/colorchecker.c
  src/iop/crop.c
  src/iop/filmicrgb.c
  src/libs/history.c
  src/libs/metadata_view.c
  src/lua/preferences.c
  src/views/view.c
  src/views/view.h
Labels: feature: enhancement

#10520 midi keys mapped to module header reflect status
  src/bauhaus/bauhaus.c
  src/develop/imageop.c
  src/gui/accelerators.c
  src/libs/lib.c
Labels: priority: low, scope: UI

#10758 Add support for IPAPGothic font (Update darktable-elegant-darker.css)
  data/themes/darktable-elegant-darker.css
Labels: feature: enhancement, scope: UI, release notes: pending

#10881 import: reduce database overhead
  src/common/film.c
  src/common/film.h
  src/common/image.c
  src/common/image.h
  src/libs/import.c
Labels: feature: enhancement, scope: performance

#10739 Only toggle colorlabel if all images have the label
  src/common/colorlabels.c
Labels: priority: medium, feature: redesign, documentation-pending

#11073 guides: refactor overlay color settings and add contrast
  data/darktableconfig.xml.in
  src/develop/masks/brush.c
  src/develop/masks/circle.c
  src/develop/masks/ellipse.c
  src/develop/masks/gradient.c
  src/develop/masks/path.c
  src/gui/draw.h
  src/gui/gtk.c
  src/gui/gtk.h
  src/gui/guides.c
  src/gui/guides.h
  src/iop/ashift.c
  src/iop/clipping.c
  src/iop/crop.c
  src/iop/graduatednd.c
  src/iop/vignette.c
  src/libs/snapshots.c
  src/views/darkroom.c
  src/views/view.h
Labels: feature: enhancement, scope: UI

#11039 po/collapsible section full gui rework, code sharing
  data/themes/darktable-elegant-grey.css
  data/themes/darktable.css
  src/gui/gtk.c
  src/gui/gtk.h
  src/iop/ashift.c
  src/iop/channelmixerrgb.c
  src/iop/crop.c
  src/iop/temperature.c
  src/libs/import.c
Labels: feature: enhancement, scope: UI, release notes: pending

#11099 po/fix path mask
  src/develop/masks/path.c
  src/iop/retouch.c
Labels: bugfix, priority: high, difficulty: hard, scope: UI

#11089 import: allows comma in file name
  src/libs/import.c
Labels: bugfix, scope: UI

#11105 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11108 Update ja.po
  po/ja.po
Labels: scope: translation

#10791 calculate dropdown natural width for filter and popovers
  data/themes/darktable.css
  src/bauhaus/bauhaus.c
  src/gui/guides.c
  src/libs/tools/filter.c
  src/views/darkroom.c
  src/views/lighttable.c
Labels: feature: enhancement, scope: UI

#11070 Improve monochrome images workflow
  src/common/image.c
  src/common/image.h
  src/iop/cacorrect.c
  src/iop/channelmixerrgb.c
  src/iop/colorin.c
  src/iop/colorreconstruction.c
  src/iop/demosaic.c
  src/iop/highlights.c
  src/iop/hotpixels.c
  src/iop/lens.cc
  src/iop/temperature.c
Labels: priority: medium, feature: redesign, scope: image processing, scope: codebase, documentation-pending, release notes: pending

#11110 Update Esperanto translation.
  po/eo.po
Labels: scope: translation

#11114 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11116 Update ja.po
  po/ja.po
Labels: scope: translation

#11109 Update dt_configure_performance() for dt 4.0
  src/common/darktable.c
  src/common/darktable.h
Labels: feature: enhancement, scope: performance, scope: codebase, release notes: pending

#11044 fix some more memory leaks
  src/cli/main.c
  src/common/database.c
  src/common/imageio_heif.c
  src/common/pwstorage/backend_kwallet.c
  src/common/tags.c
  src/develop/masks/group.c
  src/develop/masks/path.c
  src/dtgtk/culling.c
  src/dtgtk/thumbnail.c
  src/dtgtk/thumbtable.c
  src/gui/accelerators.c
  src/gui/gtk.c
  src/gui/presets.c
  src/imageio/format/avif.c
  src/imageio/format/j2k.c
  src/imageio/format/tiff.c
  src/imageio/storage/gallery.c
  src/imageio/storage/latex.c
  src/iop/gaussian_elimination.h
  src/win/dtwin.c
Labels: scope: codebase

#11031 shortcuts: add prefer_focused preference
  data/darktableconfig.xml.in
  src/develop/imageop.c
Labels: feature: enhancement, difficulty: trivial, scope: UI, documentation-pending, release notes: pending

#10660 cmake: only install gphoto2 on Win when detected
  cmake/windows-macros.cmake
Labels: scope: software support, scope: OS support, scope: windows support

#10321 darktable-bench update
  src/tests/benchmark/README.txt
  src/tests/benchmark/darktable-bench
  src/tests/benchmark/darktable-bench-3.8.xmp
Labels: no-pr-activity

#10401 portable _get_total_memory for linux
  src/common/darktable.c
Labels: scope: codebase

#10771 improve movement in filemanager layout
  src/dtgtk/thumbtable.c
Labels: bugfix, feature: enhancement, documentation-pending, release notes: pending

#11117 Update ja.po
  po/ja.po
Labels: scope: translation

#11118 colorbalancergb: add "saturation" to module alias list
  src/iop/colorbalancergb.c
Labels: difficulty: trivial, scope: UI

#11120 unrated icon : fix line width change
  src/dtgtk/paint.c
Labels: feature: enhancement, scope: UI

#11121 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#11123 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11127 Update de.po
  po/de.po
Labels: scope: translation

#11136 import: use transaction
  src/common/image.c
Labels: scope: DAM, scope: codebase

#11140 Update czech translation...
  po/cs.po
Labels: scope: translation

#11133 history: Ensure that a text array is valid UTF-8.
  src/libs/history.c
Labels: bugfix, priority: high

#11147 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#11151 Update ja.po
  po/ja.po
Labels: scope: translation

#11148 import: add NULL check
  src/libs/import.c
Labels: bugfix, scope: DAM

#11153 Bugfix: RCD OpenCL tiling
  src/iop/demosaic.c
Labels: bugfix, scope: performance, scope: codebase, release notes: pending

#11155 Use savepoints which can be nested.
  src/common/exif.cc
  src/common/image.c
Labels: bugfix, scope: DAM, scope: codebase

#11157 collect: do take in account the entry when retrieve a saved collection
  src/libs/collect.c
Labels: bugfix, scope: UI, release notes: pending

#11162 dt_datetime_exif_to_numbers: add NULL check
  src/common/datetime.c
Labels: bugfix, scope: codebase

#11175 lua preferences: do not add enum default value as additional item
  src/lua/preferences.c
Labels: bugfix, lua

#11030 tagging: attempt to improve the suggestion mode
  data/darktableconfig.dtd
  data/darktableconfig.xml.in
  src/common/database.c
  src/common/tags.c
  src/gui/preferences_dialogs.h
  src/libs/tagging.c
  tools/generate_prefs.xsl
Labels: feature: enhancement, scope: UI, scope: DAM, documentation-pending, release notes: pending

#11194 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11190 export_metadata: make $(variables) completion work.
  src/imageio/storage/disk.c
  src/imageio/storage/gallery.c
  src/imageio/storage/latex.c
  src/libs/export_metadata.c
Labels: bugfix, scope: UI, scope: DAM

#11199 Update ja.po
  po/ja.po
Labels: scope: translation

#11200 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#11203 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11196 po/fix crop handles - fix using handles with fast movements
  src/iop/crop.c
Labels: bugfix, scope: UI, scope: codebase, release notes: pending

#11207 Delete documentation.md
  .github/ISSUE_TEMPLATE/documentation.md
Labels: scope: usermanual

#10807 Windows translation bundling alternative
  cmake/windows-macros.cmake
  packaging/macosx/darktable.bundle
  src/common/l10n.c
Labels: scope: translation, scope: codebase, scope: windows support

#11167 Proposal: Introduce "preference->processingl->darktable resources" instead of several tuning options
  data/darktableconfig.xml.in
  src/common/darktable.c
  src/common/darktable.h
  src/common/guided_filter.c
  src/common/mipmap_cache.c
  src/common/opencl.c
  src/common/opencl.h
  src/develop/pixelpipe_hb.c
  src/develop/tiling.c
  src/dtgtk/culling.c
  src/dtgtk/thumbtable.c
  src/gui/preferences.c
  src/views/darkroom.c
Labels: priority: medium, feature: redesign, scope: performance, documentation-pending, release notes: pending

#11206 diffuse: fix diffusion directionality control
  data/kernels/diffuse.cl
  src/iop/diffuse.c
Labels: bugfix

#11210 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11213 thumbnail : fix 'surface from preview' flag
  src/dtgtk/thumbnail.c
Labels: bugfix, difficulty: trivial, scope: UI

#11215 Expose resources levels in darktablerc and bugfix
  src/common/darktable.c
Labels: scope: performance, scope: codebase

#11217 diffuse: better fix for directionality control
  data/kernels/diffuse.cl
  src/iop/diffuse.c
Labels: bugfix, scope: image processing, scope: codebase

#10694 Add text & color label filters
  data/themes/darktable.css
  src/common/collection.c
  src/common/collection.h
  src/dtgtk/paint.c
  src/dtgtk/paint.h
  src/libs/tools/filter.c
Labels: bugfix, feature: enhancement, scope: UI, scope: DAM, documentation-pending

#11219 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11216 Fix lua register_action and register_selection tooltips
  src/libs/image.c
  src/libs/select.c
Labels: bugfix, lua

#10992 use popup instead of dialog for metadata choices
  src/libs/metadata.c
Labels: scope: UI, scope: DAM, scope: codebase

#11221 Move away from adobe_coeff.c.
  src/common/colorspaces.c
  src/common/colorspaces.h
  src/common/exif.cc
  src/common/illuminants.h
  src/common/image.c
  src/common/image.h
  src/common/imageio.h
  src/common/imageio_dng.h
  src/common/imageio_libraw.c
  src/common/imageio_rawspeed.cc
  src/control/jobs/control_jobs.c
  src/external/adobe_coeff.c
  src/iop/channelmixerrgb.c
  src/iop/colorin.c
  src/iop/demosaic.c
  src/iop/invert.c
  src/iop/temperature.c
  tools/basecurve/README.cmake.md
  tools/check_camera_support
  tools/dngmeta.sh
Labels: scope: camera support

#11226 imageio_dng: more tweaks
  src/common/imageio_dng.h
Labels: scope: codebase

#11232 Update de.po
  po/de.po
Labels: scope: translation

#11198 Tagging dictionary: remove entry completion
  data/darktableconfig.xml.in
  src/libs/tagging.c
Labels: feature: enhancement, scope: UI, scope: DAM

#11016 Import datetime detection for copy & import and from camera
  src/common/camera_control.c
  src/common/camera_control.h
  src/common/metadata.c
  src/common/metadata.h
  src/control/jobs/camera_jobs.c
  src/control/jobs/control_jobs.c
  src/gui/import_metadata.c
  src/libs/import.c
  src/libs/metadata.c
  src/libs/metadata_view.c
  src/views/tethering.c
Labels: bugfix, feature: enhancement, scope: UI, scope: DAM, documentation-pending

#11239 Update czech language
  po/cs.po
Labels: scope: translation

#11240 fix for #11234
  po/de.po
Labels: scope: translation
