Repository darktable-org/darktable, pull requests merged in 2022-07, with the labels that each got.

#12162 Spanish translation update
  po/es.po
Labels: scope: translation

#12078 Fix untranslated tooltips of notebook tabs
  src/gui/gtk.c
Labels: scope: translation

#12123 Fix to avoid a crash when zooming with fingers in an empty thumbtable
  src/dtgtk/thumbtable.c
Labels: bugfix

#12029 light up midi modifier keys when real shift/ctrl/alt pressed
  src/control/control.c
Labels: feature: enhancement, priority: low, difficulty: trivial, scope: UI, scope: hardware support

#12149 BUGFIX: blending memory requirements with detail mask
  src/develop/blend.c
Labels: bugfix

#12048 OpenCL fixes regarding runtime changing of tuning settings
  src/common/darktable.c
  src/common/darktable.h
  src/common/opencl.c
  src/common/opencl.h
  src/develop/pixelpipe_hb.c
  src/develop/tiling.c
Labels: bugfix

#12158 Fix processing of shorter date-time strings with TZ info
  src/common/datetime.c
Labels: bugfix

#12185 Fix interactive crop-size information
  src/iop/clipping.c
  src/iop/crop.c
Labels: bugfix, scope: image processing

#11969 colorspaces: introduce an optimized form of Ych
  data/kernels/colorspace.h
  data/kernels/common.h
  data/kernels/extended.cl
  data/kernels/filmic.cl
  src/common/colorspaces_inline_conversions.h
  src/iop/colorbalancergb.c
  src/iop/filmicrgb.c
Labels: feature: enhancement, scope: performance

#12192 po/fix time offset
  src/control/jobs/control_jobs.c
Labels: bugfix, priority: high, scope: DAM

#12189 Add D780 noise profile
  data/noiseprofiles.json
Labels: scope: noise profile

#12200 noiseprofile for nikon d4s
  data/noiseprofiles.json
Labels: feature: enhancement, scope: noise profile

#12202 updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#12207 Fix unterminated string in pt_BR.po
  po/pt_BR.po
Labels: priority: high, reproduce: confirmed, difficulty: trivial, bug: pending

#12212 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#12213 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#12215 Update ja.po
  po/ja.po
Labels: scope: translation

#12188 Miscellaneous bugfixes
  data/kernels/colorspace.h
  src/common/chromatic_adaptation.h
  src/common/colorspaces_inline_conversions.h
  src/common/gamut_mapping.h
Labels: bugfix

#12194 Disable upscaling when export size is set to 0.
  src/control/jobs/control_jobs.c
Labels: bugfix, priority: high, scope: DAM

#12217 updated sq_AL
  po/sq.po
Labels: scope: translation

#12219 Update ja.po
  po/ja.po
Labels: scope: translation

#12218 Add HEIF media type association
  data/CMakeLists.txt
  data/darktable.desktop.in
Labels: feature: enhancement, scope: codebase

#12220 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#12223 fix time offset calculation when offset ist more than 36 minutes (32b…
  src/control/jobs/control_jobs.c
Labels: bugfix, scope: DAM

#12232 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#12238 histogram: shrink display to not crop primary/secondary nodes
  src/libs/histogram.c
Labels: feature: enhancement, scope: UI

#12231 desktop file mime types redux
  data/CMakeLists.txt
  data/darktable.desktop.in
  data/supported_extensions.cmake
  src/CMakeLists.txt
Labels: feature: enhancement, priority: low, scope: codebase

#12241 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation
