Repository darktable-org/darktable, pull requests merged in 2022-12, with the labels that each got.

#13055 Ukrainian translation update
  po/uk.po
Labels: scope: translation / strings

#13056 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#13060 Update to add White Balance presets for the Fujifilm X-T5
  data/wb_presets.json
Labels: scope: camera support

#13061 Update de.po
  po/de.po
Labels: scope: translation / strings

#13064 Adding Fujifilm X-T5 noise profiles
  data/noiseprofiles.json
Labels: scope: noise profile

#13068 Fix hinter message panel resize
  data/themes/darktable.css
  src/gui/gtk.c
Labels: bugfix, scope: UI

#13076 Fix dt crash on HEIF files with orientation (90º CW/CCW rotation) change
  src/common/imageio_heif.c
Labels: bugfix, priority: high, scope: codebase

#13078 allow 1600% zoom to be written entirely
  src/libs/navigation.c
Labels: bugfix, priority: low, scope: UI

#13085 Update Finnish translation
  po/fi.po
Labels: scope: translation / strings

#13082 fix jumping panels when searching modules for wide languages
  src/libs/modulegroups.c
  src/views/darkroom.c
Labels: bugfix, priority: high, scope: UI

#13072 RFC: Improve rating range filter (and more)
  data/themes/darktable-elegant-dark.css
  data/themes/darktable.css
  src/dtgtk/paint.c
  src/dtgtk/range.c
  src/dtgtk/range.h
  src/gui/gtk.c
  src/gui/gtk.h
  src/libs/filters/rating_range.c
Labels: bugfix, feature: enhancement, scope: UI, documentation-pending, release notes: pending

#13081 RFC: topbar : new filtering menu icon
  src/dtgtk/paint.c
  src/dtgtk/paint.h
  src/libs/tools/filter.c
Labels: bugfix, feature: redesign, scope: UI, documentation-pending

#13091 Update zh_TW translation
  po/zh_TW.po
Labels: scope: translation / strings

#13098 Safer css code for header button
  data/themes/darktable.css
Labels: scope: codebase

#13101 Turkish translation update and fix
  po/tr.po
Labels: scope: translation / strings

#13103 Update de.po
  po/de.po
Labels: scope: translation / strings

#13104 Spanish translation update
  po/es.po
Labels: scope: translation / strings

#13106 Update zh_TW translation
  po/zh_TW.po
Labels: scope: translation / strings

#13108 Spanish translation update
  po/es.po
Labels: scope: translation / strings

#13110 imageio: workaround for disabling metadata export
  src/common/imageio.c
  src/imageio/format/avif.c
  src/imageio/format/exr.cc
  src/imageio/format/jpeg.c
  src/imageio/format/jxl.c
  src/imageio/format/webp.c
Labels: bugfix, priority: high

#13112 piwigo: Ensure that we look for image version (duplicate).
  src/imageio/storage/piwigo.c
Labels: bugfix, priority: high, scope: DAM

#13114 Fixes for Finnish translation
  po/fi.po
Labels: scope: translation / strings

#13115 Update Hungarian translation
  po/hu.po
Labels: scope: translation / strings

#13117 Spanish translation update
  po/es.po
Labels: scope: translation / strings

#13121 sq translation update
  po/sq.po
Labels: scope: translation / strings

#13122 Bugfix: HLR roi_out data safety
  src/iop/opposed.c
Labels: bugfix

#13130 Spanish translation update
  po/es.po
Labels: scope: translation / strings

#13125 remove some shapes from group
  src/libs/masks.c
Labels: bugfix, priority: high

#13126 collect : separate collect and filter in query
  src/common/collection.c
Labels: bugfix, priority: medium, difficulty: trivial, scope: DAM

#13124 Fixing #13120
  src/common/gaussian.c
  src/common/opencl.c
  src/common/opencl.h
  src/develop/blend.c
Labels: bugfix

#13131 Ukrainian translation update
  po/uk.po
Labels: scope: translation / strings

#13133 Update ja.po
  po/ja.po
Labels: scope: translation / strings

#13094 Fix the broken ImageMagick loader
  src/common/imageio_im.c
Labels: bugfix, priority: low

#13139 Update pl.po
  po/pl.po
Labels: scope: translation / strings

#13138 collect : fix query if first filter is empty
  src/common/collection.c
Labels: bugfix, priority: high, difficulty: trivial, scope: DAM

#13142 Spanish translation update
  po/es.po
Labels: scope: translation / strings

#13144 Update zh_TW translation
  po/zh_TW.po
Labels: scope: translation / strings

#13147 Ukrainian translation improvement
  po/uk.po
Labels: scope: translation / strings

#13169 RELEASE_NOTES for 4.2: Gtk 3.24.15 min needed
  README.md
  RELEASE_NOTES.md
Labels: documentation-pending, release notes: pending

#13148 Updated Hebrew translation
  po/he.po
Labels: scope: translation / strings

#13168 po: zh_CN translations
  po/zh_CN.po
Labels: scope: translation / strings

#13179 snapshots: Do not invalidate snapshot each time.
  src/libs/snapshots.c
Labels: bugfix, priority: high, scope: performance, release notes: pending

#13196 Update ja.po
  po/ja.po
Labels: scope: translation / strings

#13197 Add "uk" to LINGUAS file
  po/LINGUAS
Labels: bugfix, scope: translation / strings, priority: high, release notes: pending

#13206 Restore soft ranges in color calibration
  src/iop/channelmixerrgb.c
Labels: priority: high, scope: image processing, bug: pending, documentation-pending

#13218 Relax libavif version requirement
  RELEASE_NOTES.md
  src/common/imageio_avif.c
Labels: priority: medium, priority: low, feature: redesign, scope: software support, scope: codebase

#13219 Nikon Z9 : Add WB presets
  data/wb_presets.json
Labels: feature: enhancement, scope: camera support, priority: medium, release notes: pending

#13214 Culling fixes
  data/themes/darktable.css
  src/dtgtk/culling.c
  src/dtgtk/culling.h
  src/dtgtk/thumbnail.c
  src/dtgtk/thumbnail.h
  src/libs/tools/timeline.c
  src/views/lighttable.c
Labels: bugfix, priority: high, scope: DAM, documentation-pending, release notes: pending

#13222 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#13193 Fixes to provide AppStream conformance
  CMakeLists.txt
  data/CMakeLists.txt
  data/org.darktable.darktable.appdata.xml.in
  data/org.darktable.darktable.desktop.in
  po/POTFILES.in
  src/control/progress.c
  tools/darktable-gnome-nightlight-disabled.sh
Labels: bugfix, scope: codebase

#13155 Fix a copy and paste bug in messages in LUT 3D module
  src/iop/lut3d.c
Labels: bugfix, scope: UI, release notes: pending

#13089 wb_presets: merge and sort makers
  data/wb_presets.json
  data/wb_presets.schema
Labels: scope: camera support, scope: codebase

#13239 de: Fix module layout duplication string
  po/de.po
Labels: scope: translation / strings

#13237 set tooltip on expander in color calibration
  src/iop/channelmixerrgb.c
Labels: bugfix, priority: low, difficulty: trivial, scope: UI, release notes: pending

#13229 gtk: Enforce minimal version 3.24.15.
  src/CMakeLists.txt
Labels: scope: codebase

#13238 add expander to sigmoid
  src/iop/sigmoid.c
Labels: feature: enhancement, priority: medium, scope: UI, release notes: pending

#13244 Ukrainian translation update
  po/uk.po
Labels: scope: translation / strings

#13242 sigmoid: Add documentation link.
  src/common/usermanual_url.c
Labels: bugfix, scope: usermanual, priority: high, difficulty: trivial, scope: UI, release notes: pending
