Repository darktable-org/darktable, pull requests merged in 2022-04, with the labels that each got.

#11439 bauhaus : allow to hide the icon
  src/bauhaus/bauhaus.c
  src/bauhaus/bauhaus.h
Labels: feature: enhancement, scope: UI

#11372 Some bauhaus improvement but not only
  data/themes/darktable-elegant-dark.css
  data/themes/darktable-elegant-grey.css
  data/themes/darktable.css
  src/bauhaus/bauhaus.c
  src/dtgtk/paint.c
  src/iop/filmicrgb.c
  src/iop/toneequal.c
Labels: bugfix, feature: redesign, difficulty: hard, scope: UI, release notes: pending

#10976 Filmic v6
  data/kernels/colorspace.h
  data/kernels/extended.cl
  data/kernels/filmic.cl
  src/common/colorspaces_inline_conversions.h
  src/iop/colorbalancergb.c
  src/iop/filmicrgb.c
  tools/derive_filmic_v6_gamut_mapping.py
Labels: feature: redesign, documentation-pending, release notes: pending

#11445 Remove writing RatingPercent in exif data
  src/common/exif.cc
Labels: bugfix, priority: low, scope: DAM, release notes: pending, scope: windows support

#11451 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#11453 Integrate pinned memory transfer into "tune OpenCL performance"
  data/darktableconfig.xml.in
  src/common/darktable.c
  src/common/darktable.h
  src/common/opencl.c
  src/common/opencl.h
  src/develop/pixelpipe_hb.c
  src/develop/tiling.c
Labels: feature: enhancement, scope: performance

#11446 print view: graphical image coordinates overlay
  data/darktableconfig.xml.in
  src/libs/print_settings.c
Labels: feature: enhancement, priority: medium, scope: UI, documentation-pending, release notes: pending

#11458 bauhaus combox alignment
  src/bauhaus/bauhaus.c
  src/bauhaus/bauhaus.h
Labels: bugfix, feature: enhancement, difficulty: trivial, scope: UI

#11461 Better resources translation on prefs for french translation
  po/fr.po
Labels: scope: translation

#11464 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#11465 Fix WB preset lookup
  src/iop/temperature.c
Labels: bugfix, scope: camera support, priority: high

#11472 Turkish translation update
  po/tr.po
Labels: scope: translation

#11469 Safer extending of OpenCl eventlist
  src/common/darktable.c
  src/common/opencl.c
  src/common/opencl.h
Labels: feature: enhancement, scope: performance

#11475 Use American spelling of gray
  src/iop/rgblevels.c
Labels: scope: translation

#11454 New set to simplify code by better use of class + minor glitches fix
  data/themes/darktable-elegant-dark.css
  data/themes/darktable-elegant-grey.css
  data/themes/darktable.css
  src/develop/blend_gui.c
  src/develop/imageop.c
  src/dtgtk/button.c
  src/dtgtk/culling.c
  src/dtgtk/gradientslider.c
  src/dtgtk/paint.c
  src/dtgtk/thumbnail.c
  src/dtgtk/thumbnail_btn.c
  src/dtgtk/thumbtable.c
  src/dtgtk/togglebutton.c
  src/gui/gtk.c
  src/gui/gtk.h
  src/gui/presets.c
  src/iop/colorbalance.c
  src/iop/filmic.c
  src/iop/filmicrgb.c
  src/iop/splittoning.c
  src/iop/temperature.c
  src/iop/toneequal.c
  src/libs/collect.c
  src/libs/colorpicker.c
  src/libs/duplicate.c
  src/libs/export.c
  src/libs/history.c
  src/libs/lib.c
  src/libs/modulegroups.c
  src/libs/recentcollect.c
  src/libs/tools/filter.c
  src/views/darkroom.c
  src/views/view.c
Labels: feature: enhancement, feature: redesign, difficulty: average, scope: UI, scope: codebase

#11481 Update de.po
  po/de.po
Labels: scope: translation

#11483 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#10711 Highlights reconstruction : introduce new method
  data/kernels/basic.cl
  data/kernels/common.h
  data/kernels/diffuse.cl
  src/common/bspline.h
  src/develop/imageop_math.h
  src/iop/diffuse.c
  src/iop/highlights.c
Labels: feature: enhancement, scope: image processing, documentation-pending

#11480 filmicrgb: fix norm handling in v6
  data/kernels/filmic.cl
  src/iop/filmicrgb.c
Labels: bugfix, priority: high

#11478 make opencl_number_event_handles per device
  data/darktableconfig.xml.in
  src/common/darktable.c
  src/common/darktable.h
  src/common/opencl.c
  src/common/opencl.h
Labels: feature: redesign, release notes: pending

#11485 Fix CL memory requirement in retouch
  src/iop/retouch.c
  src/iop/useless.c
Labels: bugfix, priority: high, release notes: pending

#11486 Fix tiling check in pixelpipe_process_on_CPU
  src/develop/pixelpipe_hb.c
Labels: bugfix, priority: high, scope: performance

#11450 increase heal iteration limit
  src/common/heal.c
Labels: feature: enhancement, priority: medium, scope: image processing

#11484 Fix rating toggle behavior if not all images share the same rating
  src/common/ratings.c
  src/common/ratings.h
Labels: bugfix, priority: low, release notes: pending

#11491 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11482 buttons flags cleanup
  data/themes/darktable.css
  src/develop/blend_gui.c
  src/develop/imageop.c
  src/develop/imageop_gui.c
  src/dtgtk/button.c
  src/dtgtk/button.h
  src/dtgtk/paint.c
  src/dtgtk/paint.h
  src/dtgtk/thumbnail.c
  src/dtgtk/thumbnail_btn.c
  src/dtgtk/togglebutton.c
  src/dtgtk/togglebutton.h
  src/gui/color_picker_proxy.c
  src/gui/draw.h
  src/gui/gtk.c
  src/gui/guides.c
  src/iop/ashift.c
  src/iop/basicadj.c
  src/iop/channelmixerrgb.c
  src/iop/colorbalancergb.c
  src/iop/colorzones.c
  src/iop/demosaic.c
  src/iop/filmic.c
  src/iop/filmicrgb.c
  src/iop/retouch.c
  src/iop/rgbcurve.c
  src/iop/rgblevels.c
  src/iop/temperature.c
  src/iop/toneequal.c
  src/iop/watermark.c
  src/libs/backgroundjobs.c
  src/libs/camera.c
  src/libs/collect.c
  src/libs/colorpicker.c
  src/libs/duplicate.c
  src/libs/export_metadata.c
  src/libs/geotagging.c
  src/libs/history.c
  src/libs/import.c
  src/libs/lib.c
  src/libs/live_view.c
  src/libs/map_locations.c
  src/libs/masks.c
  src/libs/modulegroups.c
  src/libs/print_settings.c
  src/libs/tagging.c
  src/libs/tools/battery_indicator.c
  src/libs/tools/colorlabels.c
  src/libs/tools/filter.c
  src/libs/tools/global_toolbox.c
  src/libs/tools/lighttable.c
  src/views/darkroom.c
  src/views/lighttable.c
  src/views/view.c
Labels: feature: redesign, difficulty: average, scope: UI

#11497 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11499 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#11298 add back labels/actions to quick filter dropdowns
  src/libs/collect.c
  src/libs/tools/filter.c
Labels: bugfix, feature: redesign, scope: codebase

#11493 Make async pixelpipe device specific too
  data/darktableconfig.xml.in
  src/common/darktable.c
  src/common/darktable.h
  src/common/nlmeans_core.c
  src/common/opencl.c
  src/common/opencl.h
  src/develop/pixelpipe_hb.c
  src/develop/tiling.c
  src/iop/atrous.c
  src/iop/denoiseprofile.c
  src/iop/nlmeans.c
Labels: feature: redesign, scope: performance

#11505 Ensure minimal requested tiling_cl
  src/common/opencl.c
  src/develop/tiling.c
Labels: bugfix, scope: performance

#11512 fix outer borders drawing
  src/gui/gtk.c
Labels: bugfix, difficulty: trivial, scope: UI

#11514 don't crash while initialising histogram if no tethering
  src/libs/histogram.c
Labels: bugfix, priority: high, scope: UI

#11507 brush: allows to edit a single node in the brush path.
  src/develop/masks/brush.c
Labels: feature: enhancement, scope: UI, scope: image processing, documentation-pending, release notes: pending

#11518 Fix some modules tiling->factor_cl
  src/iop/basicadj.c
  src/iop/censorize.c
  src/iop/hazeremoval.c
  src/iop/overexposed.c
Labels: bugfix, scope: performance

#11519 further tiling factor fixes
  src/iop/hazeremoval.c
  src/iop/overexposed.c
Labels: bugfix, scope: performance

#11522 Add a Cl device specific option to turn it off
  src/common/darktable.c
  src/common/darktable.h
  src/common/opencl.c
  src/common/opencl.h
Labels: feature: enhancement, documentation-pending, release notes: pending

#11526 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11528 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#11525 Finally prepare OpenCl related stuff for dt 4.0
  data/darktableconfig.xml.in
  src/common/opencl.c
Labels: feature: redesign, scope: performance, documentation-pending, release notes: pending

#11530 Update de.po
  po/de.po
Labels: scope: translation

#11529 wb_presets: add Panasonic DC-S5
  src/external/wb_presets.c
Labels: scope: camera support

#11533 check action isn't null before casting
  src/common/action.h
Labels: bugfix, priority: high

#11532 fix bauhaus popup location when widget hidden
  src/bauhaus/bauhaus.c
Labels: bugfix, scope: UI

#11531 Integrate driver blacklisting into per-device struct
  data/darktableconfig.xml.in
  src/common/opencl.c
  src/common/opencl.h
  src/common/opencl_drivers_blacklist.h
Labels: feature: redesign

#11537 Update Esperanto translation.
  po/eo.po
Labels: scope: translation

#11066 collect filtering widgets
  data/darktableconfig.xml.in
  data/themes/darktable.css
  src/CMakeLists.txt
  src/bauhaus/bauhaus.c
  src/common/collection.c
  src/common/collection.h
  src/common/datetime.c
  src/common/datetime.h
  src/common/history.c
  src/common/image.c
  src/common/styles.c
  src/control/jobs/control_jobs.c
  src/control/signal.c
  src/develop/imageop.c
  src/dtgtk/paint.c
  src/dtgtk/paint.h
  src/dtgtk/range.c
  src/dtgtk/range.h
  src/dtgtk/thumbtable.c
  src/gui/accelerators.c
  src/gui/gtk.c
  src/gui/gtk.h
  src/libs/CMakeLists.txt
  src/libs/collect.c
  src/libs/filtering.c
  src/libs/filters/aperture.c
  src/libs/filters/colors.c
  src/libs/filters/date.c
  src/libs/filters/exposure.c
  src/libs/filters/filename.c
  src/libs/filters/focal.c
  src/libs/filters/iso.c
  src/libs/filters/rating.c
  src/libs/filters/ratio.c
  src/libs/filters/search.c
  src/libs/import.c
  src/libs/lib.c
  src/libs/map_locations.c
  src/libs/metadata_view.c
  src/libs/recentcollect.c
  src/libs/tagging.c
  src/libs/tools/filter.c
  src/views/lighttable.c
  src/views/view.c
  src/views/view.h
Labels: bugfix, feature: enhancement, feature: redesign, difficulty: hard, scope: UI, scope: DAM, documentation-pending

#11541 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11546 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11549 Update de.po
  po/de.po
Labels: scope: translation

#11547 Correct a typo in the UI string
  src/libs/filters/ratio.c
Labels: bugfix

#11551 Update tr.po
  po/tr.po
Labels: scope: translation

#11550 Filename filter speedup
  src/libs/filtering.c
  src/libs/filters/filename.c
Labels: bugfix, difficulty: average, scope: DAM

#11554 Add forgotten source file to POTFILES.in
  po/POTFILES.in
Labels: bugfix, scope: translation

#11556 image_cache: Fix copy/paste issue breaking the export timestamp.
  src/common/image_cache.c
Labels: bugfix, priority: high, scope: DAM

#11557 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#11561 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11563 Update de.po
  po/de.po
Labels: scope: translation

#11540 Visualize clipped photosites in highlights module
  src/develop/develop.h
  src/iop/demosaic.c
  src/iop/highlights.c
Labels: feature: enhancement, scope: UI, scope: image processing, release notes: pending, documentation-complete

#11569 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#11573 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11570 Add Canon EOS Rebel SL3 alias
  src/common/imageio_libraw.c
Labels: feature: enhancement, scope: camera support

#11586 Correct a typo in the UI string
  src/dtgtk/range.c
Labels: scope: translation

#11592 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11574 The color_passthru demosaicer gets an OpenCL implementation
  data/kernels/demosaic_other.cl
  src/iop/demosaic.c
Labels: feature: enhancement, scope: performance

#11594 Windows: switch GraphicsMagick to Q16
  cmake/modules/NSIS.template.in
  cmake/windows-macros.cmake
  src/CMakeLists.txt
Labels: scope: windows support

#11593 OpenCL device initializing reports platform information
  src/common/opencl.c
  src/common/opencl.h
Labels: bugfix, feature: enhancement, scope: performance

#11470 Improve darktable-gen-noiseprofile and subr.sh scripts in tools/noise
  tools/noise/darktable-gen-noiseprofile
  tools/noise/subr.sh
Labels: feature: enhancement, scope: noise profile

#11599 fix brush size shortcuts
  src/views/darkroom.c
Labels: bugfix

#11575 The highlights clipping false color indicator gets OpenCL code
  data/kernels/basic.cl
  src/iop/highlights.c
Labels: feature: enhancement, scope: performance

#11600 Two demosaicer improvements
  src/develop/develop.h
  src/iop/demosaic.c
Labels: feature: enhancement, scope: UI, scope: performance

#11602 Fix OpenCL micro_nap resetting
  src/common/opencl.c
Labels: feature: enhancement, scope: performance

#11604 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11605 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#11613 Turkish translation update
  po/tr.po
Labels: scope: translation

#11610 Update de.po
  po/de.po
Labels: scope: translation

#11622 fix DT_SIGNAL_IMAGES_ORDER_CHANGE definition
  src/control/signal.c
Labels: bugfix, priority: high, difficulty: trivial, scope: DAM

#11617 Relax writing of CL scheduling profile
  src/common/opencl.c
Labels: bugfix, scope: performance

#11620 sort : take account of last sort for special JOIN query
  src/common/collection.c
Labels: bugfix, difficulty: trivial, scope: DAM

#11618 Fix CL performance regression due to fitting tests
  src/common/opencl.c
Labels: feature: redesign, scope: performance

#11627 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11626 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#11629 datetime fix: long int is not gint64 equivalent on windows (WIN32)
  src/common/collection.c
Labels: bugfix, scope: UI

#10524 show selected shortcut action in treeview
  src/gui/accelerators.c
Labels: feature: enhancement, scope: UI, documentation-pending

#11638 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11633 String fixes (grammar and style)
  src/libs/filters/filename.c
Labels: scope: UI, scope: codebase

#11634 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#11641 Update tr.po
  po/tr.po
Labels: scope: translation

#11636 collect: fix range selection and click
  src/libs/collect.c
Labels: bugfix, difficulty: average, scope: DAM

#11559 Continue CSS optimization
  data/themes/darktable-elegant-dark.css
  data/themes/darktable-elegant-darker.css
  data/themes/darktable-elegant-grey.css
  data/themes/darktable.css
  src/bauhaus/bauhaus.c
  src/develop/blend_gui.c
  src/develop/imageop.c
  src/dtgtk/paint.c
  src/dtgtk/range.c
  src/dtgtk/thumbnail.c
  src/dtgtk/thumbnail.h
  src/dtgtk/thumbtable.c
  src/gui/gtk.c
  src/gui/gtk.h
  src/gui/guides.c
  src/gui/import_metadata.c
  src/gui/preferences.c
  src/gui/presets.c
  src/iop/colorbalance.c
  src/iop/filmicrgb.c
  src/iop/splittoning.c
  src/iop/temperature.c
  src/libs/backgroundjobs.c
  src/libs/collect.c
  src/libs/colorpicker.c
  src/libs/duplicate.c
  src/libs/export.c
  src/libs/filtering.c
  src/libs/filters/colors.c
  src/libs/filters/filename.c
  src/libs/filters/search.c
  src/libs/history.c
  src/libs/import.c
  src/libs/lib.c
  src/libs/modulegroups.c
  src/libs/tagging.c
  src/libs/tools/colorlabels.c
  src/libs/tools/darktable.c
  src/libs/tools/global_toolbox.c
  src/libs/tools/lighttable.c
  src/libs/tools/viewswitcher.c
  src/views/darkroom.c
  src/views/map.c
  src/views/view.c
Labels: bugfix, difficulty: average, scope: UI

#11644 Update czech language
  po/cs.po
Labels: scope: translation

#11647 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#11639 Fixing re-enabling of disabled OpenCL devices
  src/common/darktable.c
  src/common/darktable.h
  src/common/opencl.c
Labels: bugfix, scope: performance

#11648 Getting rid of `darktable|problem|history-compress'
  src/common/history.c
  src/common/history.h
  src/develop/develop.c
  src/libs/copy_history.c
Labels: priority: low, feature: redesign, scope: codebase

#11651 Correct code for eyes icons
  src/dtgtk/paint.c
Labels: bugfix, scope: UI

#11653 make color pickers in grey theme visible again
  data/themes/darktable-elegant-grey.css
Labels: bugfix, priority: high, difficulty: trivial, scope: UI

#11659 fix brush hardness/opacity shortcuts
  src/views/darkroom.c
Labels: bugfix, difficulty: trivial, scope: UI

#11658 color calib/exposure: remember expand status
  src/iop/channelmixerrgb.c
  src/iop/exposure.c
Labels: feature: enhancement, scope: UI

#11664 Grammar fix: the noun must be plural
  src/libs/print_settings.c
Labels: scope: UI

#11663 Fix likely copy-paste bug in generate-cache
  src/generate-cache/main.c
Labels: scope: codebase

#11667 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11665 range : allow shift-click to select a range
  src/dtgtk/range.c
Labels: feature: enhancement, difficulty: trivial, scope: UI

#11669 Fix reentrant call of gui_critical_section in exposure
  src/iop/exposure.c
Labels: bugfix, priority: high, scope: codebase

#11645 exr: adapt embedded profile to D65
  src/common/imageio_exr.cc
  src/imageio/format/exr.cc
Labels: feature: enhancement

#11671 Turkish translation update
  po/tr.po
Labels: scope: translation

#11672 Only module expanding causes it to scroll to the top
  data/darktableconfig.xml.in
Labels: bugfix

#11674 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#11673 filemanager : fix scrollbar manual move
  src/dtgtk/thumbtable.c
  src/views/lighttable.c
Labels: bugfix, difficulty: trivial, scope: UI

#11686 crop : fix bug when reload without module focused
  src/iop/crop.c
Labels: bugfix, difficulty: average, scope: image processing

#11681 Text style fix (no ending full stop)
  src/dtgtk/range.c
Labels: scope: UI

#11660 revert altered slider-click behaviour
  src/bauhaus/bauhaus.c
Labels: feature: enhancement, scope: UI

#11694 Update de.po
  po/de.po
Labels: scope: translation

#11697 Bayer is a proper name and therefore should not be forcibly lowercased
  src/iop/cacorrect.c
  src/iop/demosaic.c
Labels: scope: translation

#11693 Remove capitalization of the first letter of the sentence
  src/iop/highlights.c
Labels: scope: translation
