Repository darktable-org/darktable, pull requests merged in 2022-06, with the labels that each got.

#11953 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11954 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#11956 Update de.po
  po/de.po
Labels: scope: translation

#11965 Spanish translation update
  po/es.po
Labels: scope: translation

#11966 fix overlay color cycling
  src/gui/guides.c
  src/views/darkroom.c
Labels: bugfix

#11962 filtering small ui update fix
  src/dtgtk/range.c
  src/libs/filtering.c
Labels: bugfix, difficulty: trivial, scope: UI

#11975 Turkish translation update
  po/tr.po
Labels: scope: translation

#11977 Mark the UI label that was not marked for translation
  src/dtgtk/range.c
Labels: bugfix, scope: translation

#11979 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11978 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#11982 Update de.po
  po/de.po
Labels: scope: translation

#11984 Update ja.po
  po/ja.po
Labels: scope: translation

#11980 some new css fixes
  data/themes/darktable.css
  src/gui/accelerators.c
  src/gui/preferences.c
Labels: bugfix, difficulty: trivial, scope: UI

#11987 masks lib : fix icons size, alignment and colors
  data/themes/darktable.css
  src/dtgtk/paint.c
  src/gui/gtk.c
  src/gui/gtk.h
  src/libs/masks.c
Labels: bugfix, difficulty: trivial, scope: UI

#11992 Update nl.po
  po/nl.po
Labels: scope: translation

#11990 bauhaus : ensure the use of css font
  data/themes/darktable.css
  src/bauhaus/bauhaus.c
Labels: bugfix, difficulty: trivial, scope: UI

#11993 [uk.po] Better and more accurate wording of db maintenance messages
  po/uk.po
Labels: scope: translation

#11999 zh_CN translation for darktable 4.0
  po/zh_CN.po
Labels: scope: translation

#11996 range : fix issue with entry focus out when leaving dt
  src/libs/filtering.c
Labels: bugfix, difficulty: trivial

#11997 Some new css fixes
  data/themes/darktable-elegant-darker.css
  data/themes/darktable.css
  src/libs/metadata.c
Labels: bugfix, difficulty: trivial, scope: UI

#12011 iso_12646: fully fix middle-grey value
  src/views/darkroom.c
Labels: bugfix, difficulty: trivial, scope: UI

#12013 Little bauhaus font improvement and better section label
  data/themes/darktable-elegant-darker.css
  data/themes/darktable.css
  src/bauhaus/bauhaus.c
Labels: feature: enhancement, difficulty: trivial, scope: UI

#11991 [Bugfix] Immediately write device conf after detection
  src/common/opencl.c
  src/control/conf.c
  src/control/conf.h
Labels: documentation-pending

#12015 CSS cleanup and better code for icons theme
  data/themes/darktable-elegant-darker.css
  data/themes/darktable-icons.css
  data/themes/darktable.css
  src/develop/imageop.c
Labels: difficulty: trivial, scope: codebase

#12016 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#12018 Update de.po
  po/de.po
Labels: scope: translation

#12019 Update ja.po
  po/ja.po
Labels: scope: translation

#12026 Update Turkish translation
  po/tr.po
Labels: scope: translation

#12030 Late OpenCL fixes for 4.0
  src/common/opencl.c
  src/common/opencl.h
Labels: bugfix, priority: high, understood: incomplete, scope: performance, documentation-pending

#12032 Spanish translation update
  po/es.po
Labels: scope: translation

#12040 Spanish translation update
  po/es.po
Labels: scope: translation

#12041 Update and correction of the Czech translation (thanks to AsciiWolf)
  po/cs.po
Labels: scope: translation

#12034 collect: when filtering the tree displays the matching records
  src/libs/collect.c
Labels: bugfix, scope: UI, scope: DAM

#12039 More readable OpenCL conf key
  src/common/opencl.c
Labels: documentation-pending

#12049 Update ja.po
  po/ja.po
Labels: scope: translation

#12050 Spanish translation update
  po/es.po
Labels: scope: translation

#12053 range : fix filmstrip update in darkroom
  src/libs/filtering.c
Labels: bugfix, priority: high, difficulty: trivial, scope: UI, scope: DAM

#12055 Spanish translation update
  po/es.po
Labels: scope: translation

#12059 Spanish translation update
  po/es.po
Labels: scope: translation

#12058 DT 4.0 might use fixed headroom instead of _opencl_get_unused_device_mem
  src/common/opencl.c
Labels: bugfix, priority: high, feature: redesign, understood: unclear, difficulty: hard, scope: performance

#12068 Update Hungarian translation
  po/hu.po
Labels: scope: translation

#12069 Esperanto translation.
  po/eo.po
Labels: scope: translation

#12066 Spanish translation completed
  po/es.po
Labels: scope: translation

#12065 [uk.po] Minor translation fixes
  po/uk.po
Labels: scope: translation

#12072 Updated Hebrew translation
  po/he.po
Labels: scope: translation

#12074 Update italian translation
  po/it.po
Labels: scope: translation

#12076 Be more optimistic for too slow OpenCL cards.
  src/common/opencl.c
Labels: bugfix

#12088 full revision of the italian translation
  po/it.po
Labels: scope: translation
