Repository darktable-org/darktable, pull requests merged in 2022-05, with the labels that each got.

#11700 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11698 Fix OpenCL device checksum calculation and setting of scheduling profile
  src/common/opencl.c
Labels: scope: performance

#11685 Fresh new icons for better UI and minor fixes
  data/themes/darktable-elegant-darker.css
  data/themes/darktable.css
  src/dtgtk/paint.c
  src/dtgtk/paint.h
  src/iop/lens.cc
  src/libs/colorpicker.c
  src/libs/duplicate.c
  src/libs/filtering.c
  src/libs/modulegroups.c
Labels: bugfix, wip, feature: redesign, scope: UI

#11682 Add multi-versioning for libheif checking
  src/CMakeLists.txt
Labels: feature: enhancement, scope: codebase

#11689 crop : ensure preview_pipe is finished before getting values
  src/iop/crop.c
Labels: bugfix, difficulty: average, scope: image processing

#11702 Good remove icon proposal
  src/dtgtk/paint.c
  src/dtgtk/paint.h
  src/libs/colorpicker.c
  src/libs/duplicate.c
  src/libs/filtering.c
  src/libs/filters/rating.c
  src/libs/modulegroups.c
Labels: feature: redesign, difficulty: trivial, scope: UI

#11701 collect : restore tag sort after history apply
  src/libs/collect.c
Labels: bugfix, difficulty: trivial, scope: DAM

#11688 add shortcuts for rating and colors filters
  src/dtgtk/range.c
  src/dtgtk/range.h
  src/gui/accelerators.c
  src/libs/filtering.c
  src/libs/filters/colors.c
  src/libs/filters/rating.c
Labels: priority: high, scope: UI, scope: codebase

#11710 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11718 range : fix destroy and pref changed signal
  src/dtgtk/range.c
Labels: bugfix, priority: high, difficulty: trivial

#11654 highlights/guided laplacian : reduce memory footprint
  data/kernels/basic.cl
  data/kernels/blurs.cl
  data/kernels/bspline.cl
  data/kernels/common.h
  data/kernels/diffuse.cl
  data/kernels/filmic.cl
  data/kernels/gaussian.cl
  data/kernels/programs.conf
  src/iop/diffuse.c
  src/iop/filmicrgb.c
  src/iop/highlights.c
Labels: scope: performance

#11715 Add exceptions to noise tool capitalization
  data/noiseprofiles.schema
  tools/noise/subr.sh
Labels: scope: noise profile

#11611 Bauhaus label hide
  src/bauhaus/bauhaus.c
  src/bauhaus/bauhaus.h
  src/common/collection.c
  src/common/collection.h
  src/libs/filtering.c
Labels: feature: enhancement, difficulty: average, scope: DAM

#11726 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11728 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#11730 Mark the tooltip that accidentally was not marked for translation
  src/libs/filtering.c
Labels: scope: translation, scope: UI

#11732 Update de.po
  po/de.po
Labels: scope: translation

#11572 image flags : set image type from the beginning
  src/common/database.c
  src/common/image.c
  src/common/imageio.c
  src/common/imageio.h
Labels: bugfix, feature: enhancement, difficulty: hard, scope: DAM

#11740 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#10432 diffuse-sharpen: adjust labels and tooltips
  src/iop/diffuse.c
Labels: feature: enhancement

#11743 diffuse-sharpen: adjust labels and tooltips (2)
  src/iop/diffuse.c
Labels: feature: enhancement, scope: UI, documentation-pending

#11722 colorbalancergb: introduce darktable UCS 22
  data/kernels/colorspace.h
  data/kernels/extended.cl
  src/common/colorspaces_inline_conversions.h
  src/iop/colorbalancergb.c
Labels: feature: enhancement, documentation-pending, release notes: pending

#11721 filtering : add grouping filter
  src/bauhaus/bauhaus.c
  src/bauhaus/bauhaus.h
  src/common/collection.c
  src/libs/filtering.c
  src/libs/filters/grouping.c
  src/libs/filters/history.c
  src/libs/filters/local_copy.c
  src/libs/filters/module_order.c
Labels: feature: new, difficulty: average, scope: DAM

#11753 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11751 range : fix set bounds min-max value
  src/dtgtk/range.c
Labels: bugfix, difficulty: trivial, scope: UI

#11760 Set same background on sliders in popover
  data/themes/darktable.css
Labels: bugfix, scope: UI

#11763 color picker: apply a 5×5 B-spline blur before stats extraction
  src/common/color_picker.c
Labels: feature: enhancement, scope: image processing

#11773 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11774 Update de.po
  po/de.po
Labels: scope: translation

#11775 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#10289 DNG GainMap support
  data/kernels/basic.cl
  src/CMakeLists.txt
  src/common/dng_opcode.c
  src/common/dng_opcode.h
  src/common/exif.cc
  src/common/exif.h
  src/common/image.c
  src/common/image.h
  src/common/image_cache.c
  src/common/imageio_rawspeed.cc
  src/iop/rawprepare.c
Labels: feature: enhancement, priority: medium, scope: image processing, documentation-pending, release notes: pending

#11786 Turkish translation update
  po/tr.po
Labels: scope: translation

#11792 Added padding to items on history
  data/themes/darktable.css
Labels: feature: enhancement, scope: UI

#11794 wb_presets: add Sony ILCE-7M4
  src/external/wb_presets.c
Labels: feature: enhancement, scope: camera support

#11801 recent history and rating filters "soft" revert
  data/darktableconfig.xml.in
  src/common/collection.c
  src/common/collection.h
  src/libs/CMakeLists.txt
  src/libs/collect.c
  src/libs/filtering.c
  src/libs/filters/colors.c
  src/libs/filters/filename.c
  src/libs/filters/grouping.c
  src/libs/filters/history.c
  src/libs/filters/local_copy.c
  src/libs/filters/module_order.c
  src/libs/filters/rating_legacy.c
  src/libs/filters/search.c
  src/libs/recentcollect.c
  src/views/view.c
  src/views/view.h
Labels: feature: enhancement, difficulty: average, scope: UI, scope: DAM, documentation-pending, release notes: pending

#11802 collect : ensure proper initialisation of history visibility
  src/libs/lib.c
  src/libs/recentcollect.c
Labels: bugfix, difficulty: trivial, scope: UI

#11800 fix a crash when changing a theme setting
  src/dtgtk/range.c
Labels: bugfix, priority: high, difficulty: average, scope: UI

#11804 filter : enhance legacy rating widget
  data/themes/darktable.css
  src/libs/filters/rating_legacy.c
Labels: feature: enhancement, difficulty: trivial, scope: UI

#11807 range : reset bounds correctly when typing in entries
  src/dtgtk/range.c
Labels: bugfix, difficulty: trivial, scope: DAM

#11808 filters : always show the pin icon
  data/themes/darktable.css
  src/libs/filtering.c
Labels: feature: enhancement, scope: UI, scope: DAM

#11809 filters : update rating numbers correctly
  src/libs/filters/rating.c
Labels: bugfix, difficulty: trivial, scope: DAM

#11811 filters : keep off/remove visible but dimmed if pinned
  data/themes/darktable.css
  src/libs/filtering.c
Labels: feature: enhancement, difficulty: trivial, scope: UI

#11813 imageio_j2k: remove redundant bpp field
  src/imageio/format/j2k.c
Labels: bugfix, priority: high, scope: codebase

#11816 Better CSS code for buttons in widget filters
  data/themes/darktable.css
  src/develop/blend_gui.c
Labels: bugfix, feature: enhancement, difficulty: trivial, scope: UI

#11820 Update de.po
  po/de.po
Labels: scope: translation

#11822 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11819 filtering : fix an issue with conf value overwritting
  src/libs/filtering.c
Labels: bugfix, difficulty: trivial, scope: UI, scope: DAM

#11826 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#11829 Spanish translation update
  po/es.po
Labels: scope: translation

#11828 collect: display correctly date taken is the tree list
  src/libs/collect.c
Labels: bugfix, scope: UI

#11834 history markup
  src/libs/collect.c
  src/libs/filtering.c
Labels: bugfix, difficulty: trivial, scope: UI, scope: DAM

#11838 wb_presets: Nikon D4S
  src/external/wb_presets.c
Labels: scope: camera support

#11841 Spanish translation update
  po/es.po
Labels: scope: translation

#11843 collection: remove empty textsearch queries
  src/common/collection.c
Labels: bugfix

#11844 Fix typo in GUI string
  data/darktableconfig.xml.in
Labels: scope: UI

#11845 collect: display right images numbers for date taken is the tree list
  src/libs/collect.c
Labels: bugfix, scope: UI

#11837 collect: make work datetime treeview filtering/selection
  src/common/collection.c
  src/libs/collect.c
Labels: bugfix, scope: UI

#11849 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11850 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#11840 colors filter: restore last state equivalent
  src/common/collection.c
  src/libs/filters/colors.c
Labels: bugfix, difficulty: average, scope: DAM

#11858 Spanish translation update
  po/es.po
Labels: scope: translation

#11855 color filter : double-click to reset
  src/libs/filters/colors.c
Labels: bugfix, difficulty: trivial, scope: UI

#11857 Rename orphan images to ungrouped
  src/libs/filters/grouping.c
Labels: scope: UI

#11866 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#11869 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11870 Update de.po
  po/de.po
Labels: scope: translation

#11863 metadata: avoid to apply on hovered image instead of selection
  src/libs/metadata.c
  src/libs/tagging.c
Labels: bugfix, scope: DAM

#11874 Spanish translation update
  po/es.po
Labels: scope: translation

#11872 Fix missing padding and icons on some overlays with shortest code
  data/themes/darktable-elegant-dark.css
  data/themes/darktable-elegant-grey.css
  data/themes/darktable.css
  src/bauhaus/bauhaus.c
  src/dtgtk/thumbnail.c
Labels: bugfix, difficulty: trivial, scope: UI

#11877 Avoid pipeline reprocessing while gui_unfocus tone equalizer
  src/iop/toneequal.c
Labels: bugfix, scope: UI, scope: performance, scope: codebase

#11876 BUGFIX fire pipeline reprocessing in two modules via gui_focus
  src/iop/demosaic.c
  src/iop/highlights.c
Labels: bugfix, scope: UI, scope: performance, scope: codebase

#11879 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11886 Spanish translation update
  po/es.po
Labels: scope: translation

#11848 filtering: custom rating-tooltip
  src/dtgtk/range.c
  src/dtgtk/range.h
  src/libs/filtering.c
  src/libs/filters/rating.c
Labels: scope: UI

#11880 variables: add missing dt_variables_params_destroy() (memory leak)
  src/common/exif.cc
  src/iop/watermark.c
Labels: bugfix, scope: DAM

#11892 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11895 Update de.po
  po/de.po
Labels: scope: translation

#11897 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#11902 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11908 Spanish translation update
  po/es.po
Labels: scope: translation

#11903 update tr.po
  po/tr.po
Labels: scope: translation

#11906 PDF export: fix crash or blank page
  data/darktableconfig.xml.in
Labels: bugfix, priority: high, scope: codebase

#11909 Update de.po
  po/de.po
Labels: scope: translation

#11910 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#11912 Japanese translation update
  po/ja.po
Labels: scope: translation

#11904 Add a consolidated header file for extra GCC optimization flags
  src/common/extra_optimizations.h
  src/common/fast_guided_filter.h
  src/common/focus_peaking.h
  src/common/luminance_mask.h
  src/dtgtk/thumbnail.c
  src/iop/cacorrectrgb.c
  src/iop/choleski.h
  src/iop/diffuse.c
  src/iop/toneequal.c
  src/views/darkroom.c
  src/views/lighttable.c
  src/views/view.c
Labels: bugfix, scope: image processing, scope: performance

#11917 channelmixerrgb: add missing default clauses
  data/kernels/channelmixer.cl
  src/common/chromatic_adaptation.h
  src/iop/channelmixerrgb.c
Labels: scope: codebase

#11920 darktable-bench: updates for v4.0 release
  src/tests/benchmark/README.txt
  src/tests/benchmark/darktable-bench
Labels: scope: performance, scope: codebase

#11921 retouch: Disable color picker when selecting a shape.
  src/iop/retouch.c
Labels: bugfix, priority: high, scope: DAM

#11925 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11928 Minor css fixes
  data/themes/darktable-elegant-dark.css
  data/themes/darktable-elegant-darker.css
Labels: difficulty: trivial, scope: UI, scope: codebase

#11915 fix slider dragging update speed again
  src/bauhaus/bauhaus.c
Labels: bugfix, priority: high

#11916 fix crash from multi module with tabs undo
  src/libs/history.c
Labels: bugfix, priority: high

#11936 make darktable-elegant-grey the default theme
  data/darktableconfig.xml.in
Labels: scope: UI, scope: image processing

#11938 Spanish translation update
  po/es.po
Labels: scope: translation

#11943 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11947 Add the missing space after the comma
  src/libs/export.c
Labels: scope: UI

#11946 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#11948 Update de.po
  po/de.po
Labels: scope: translation

#11914 fix #11805
  src/common/bspline.h
  src/common/color_picker.c
  src/iop/filmicrgb.c
Labels: bugfix, priority: high, scope: image processing
