Repository darktable-org/darktable, pull requests merged in 2022-03, with the labels that each got.

#11060 pixelpipe: tidy control flow and cache/scope/picker interaction
  src/develop/pixelpipe_hb.c
Labels: scope: codebase

#11238 watermark: remove duplicated code / variables
  src/common/variables.c
  src/gui/gtkentry.c
  src/iop/watermark.c
Labels: scope: UI, scope: codebase, documentation-pending, release notes: pending

#11227 Add a "tune OpenCLperformance" button
  data/darktableconfig.xml.in
  src/common/darktable.c
  src/common/darktable.h
  src/common/opencl.c
  src/common/opencl.h
Labels: feature: enhancement, scope: performance

#11255 Correct available mem calculations for AMD, Bugfix 11253
  src/common/opencl.c
Labels: bugfix, priority: high, scope: performance, scope: codebase

#11249 don't add grouped image from outside the collection
  src/common/grouping.c
Labels: bugfix, difficulty: trivial, scope: DAM

#11250 localcopy : fix icon position in block overlay
  data/themes/darktable.css
  src/dtgtk/paint.c
  src/dtgtk/thumbnail.c
Labels: bugfix, difficulty: trivial, scope: UI

#11256 Update de.po
  po/de.po
Labels: scope: translation

#11262 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11142 po/exposure next - exposure mapping + new collapsible section
  data/themes/darktable.css
  src/gui/gtk.c
  src/iop/exposure.c
Labels: feature: enhancement, priority: medium, scope: image processing, documentation-pending, release notes: pending

#11264 text filter: don't add wildcards on empty entry
  src/libs/tools/filter.c
Labels: bugfix, scope: DAM

#11263 Finish resource level stuff
  data/darktableconfig.xml.in
  src/common/darktable.c
  src/common/darktable.h
  src/common/opencl.c
  src/develop/pixelpipe_hb.c
Labels: scope: performance, scope: codebase, documentation-pending, release notes: pending

#11268 Update de.po
  po/de.po
Labels: scope: translation

#11269 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11271 Update ja.po
  po/ja.po
Labels: scope: translation

#11267 Text filter: fix bug on query
  src/common/collection.c
Labels: bugfix, scope: UI, scope: DAM

#11275 Update ja.po
  po/ja.po
Labels: scope: translation

#11280 change notebook page by scrolling over it
  src/gui/gtk.c
Labels: feature: enhancement, scope: UI, documentation-pending, release notes: pending

#11266 Don't treat atom cores in a special way any more
  src/common/darktable.c
Labels: feature: redesign, scope: performance

#11277 Early fallback to cpu path if cl tiling problems are evident
  src/develop/pixelpipe_hb.c
Labels: bugfix, scope: codebase

#11287 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11286 vignette: add two sections for clarity.
  src/iop/vignette.c
Labels: scope: UI

#11291 remove unnecessary section labels in crop and white balance modules
  src/bauhaus/bauhaus.c
  src/iop/crop.c
  src/iop/temperature.c
Labels: bugfix, feature: redesign, scope: UI, scope: codebase

#11290 variables: make current date work: $(YEAR), $(MONTH), ...
  src/common/variables.c
  src/control/jobs/camera_jobs.c
  src/control/jobs/control_jobs.c
Labels: bugfix, scope: DAM

#11292 Fix Tethering on Windows
  src/common/camera_control.c
Labels: bugfix, priority: high, scope: hardware support, scope: windows support

#11294 watermark: remove top most section.
  src/iop/watermark.c
Labels: scope: UI

#11293 color label filter: inverts icons symbols
  src/dtgtk/paint.c
Labels: scope: UI

#11300 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11301 Spanish translation update
  po/es.po
Labels: scope: translation

#11306 Fix early fallback CL strategy (#11277)
  src/develop/pixelpipe_hb.c
Labels: bugfix, scope: performance

#11304 Connect lib and view accels at startup to match action elements/effect
  src/libs/lib.c
  src/views/view.c
Labels: bugfix

#11309 Turkish translation
  po/tr.po
Labels: scope: translation

#11305 Only show element in tooltip when mapping, with shortcuts or on its own
  src/develop/imageop.c
  src/gui/accelerators.c
Labels: bugfix, scope: UI

#11303 filter (text & colors label): save their state between dt sessions
  data/darktableconfig.xml.in
  src/common/collection.c
  src/libs/tools/filter.c
Labels: bugfix, scope: UI, scope: DAM

#11316 skip loading shortcuts with speed zero
  src/gui/accelerators.c
Labels: bugfix, priority: medium, scope: UI

#11314 Fix blending togglebutton shortcuts
  src/common/action.h
  src/common/usermanual_url.c
  src/control/control.c
  src/develop/blend_gui.c
  src/dtgtk/gradientslider.c
  src/gui/accelerators.c
  src/gui/gtk.c
Labels: bugfix, scope: UI

#11315 make all performance configuring done at runtime
  src/common/darktable.c
  src/common/darktable.h
  src/control/conf.c
  src/control/conf.h
Labels: feature: redesign, scope: performance, scope: codebase

#11321 Update ja.po
  po/ja.po
Labels: scope: translation

#11324 Updates to pr_BR
  po/pt_BR.po
Labels: scope: translation

#11344 Turkish translation update
  po/tr.po
Labels: scope: translation

#11339 Correct wrong iso list (only the last error was output)
  tools/noise/darktable-gen-noiseprofile
Labels: bugfix

#11317 add switch to ignore default shortcuts at startup
  data/darktableconfig.xml.in
  src/common/darktable.c
  src/control/control.c
  src/control/control.h
  src/gui/accelerators.c
  src/libs/tools/global_toolbox.c
Labels: documentation-pending

#11281 UI improvement : new set
  data/themes/darktable-elegant-dark.css
  data/themes/darktable-elegant-grey.css
  data/themes/darktable.css
  src/bauhaus/bauhaus.c
  src/dtgtk/paint.c
  src/gui/gtk.c
  src/iop/filmic.c
  src/libs/collect.c
Labels: bugfix, feature: redesign, difficulty: trivial, scope: UI

#11347 Update de.po
  po/de.po
Labels: scope: translation

#11337 Support speed modifiers and force soft boundaries when dragging sliders
  src/bauhaus/bauhaus.c
  src/gui/accelerators.c
Labels: feature: enhancement, scope: UI, documentation-pending, release notes: pending

#11352 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11353 Add a -d verbose option
  src/common/darktable.c
  src/common/darktable.h
  src/develop/tiling.c
Labels: scope: codebase

#11351 bauhaus: make sure the comboboxes entries are vertically aligned.
  src/bauhaus/bauhaus.c
Labels: bugfix, priority: medium, difficulty: hard, scope: UI

#11354 add noise profile for Canon PowerShot G5 X mark II
  data/noiseprofiles.json
Labels: scope: noise profile

#11270 import_session: for win32 don't lower the path
  src/common/film.c
  src/common/import_session.c
Labels: bugfix, difficulty: hard, scope: DAM, scope: windows support

#11357 Treat extra pen tablet button clicks as key presses
  src/gui/accelerators.c
  src/libs/tools/global_toolbox.c
Labels: feature: redesign, scope: UI, documentation-pending, release notes: pending

#11362 Fix bauhaus issue
  data/themes/darktable-elegant-grey.css
  data/themes/darktable.css
Labels: bugfix, difficulty: trivial, scope: UI

#11365 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11359 bauhaus combobox : ensure full vertical align for real
  data/themes/darktable.css
  src/bauhaus/bauhaus.c
  src/bauhaus/bauhaus.h
  src/iop/channelmixerrgb.c
  src/iop/exposure.c
Labels: feature: enhancement, scope: UI

#11370 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#11371 Use American spelling of gray
  src/libs/tools/filter.c
Labels: scope: UI

#11361 specify midi config params in darktablerc
  data/darktableconfig.xml.in
  src/libs/tools/midi.c
Labels: bugfix, scope: UI, documentation-pending, release notes: pending

#11375 Turkish translation update
  po/tr.po
Labels: scope: translation

#11376 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#11380 bauhaus fixes
  src/bauhaus/bauhaus.c
Labels: bugfix, priority: high, difficulty: trivial, scope: UI

#11368 ashift: properly transform pts for the rotation computation.
  src/iop/ashift.c
Labels: bugfix, priority: high, difficulty: trivial

#11363 support gamepad triggers as buttons
  src/libs/tools/gamepad.c
Labels: feature: enhancement, scope: UI

#11384 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#11378 improve bauhaus combo popup positioning at monitor edges
  data/themes/darktable.css
  src/bauhaus/bauhaus.c
  src/bauhaus/bauhaus.h
Labels: bugfix, scope: UI

#11329 datetime: use numerical values in db
  src/common/camera_control.c
  src/common/collection.c
  src/common/darktable.c
  src/common/darktable.h
  src/common/database.c
  src/common/datetime.c
  src/common/datetime.h
  src/common/exif.cc
  src/common/image.c
  src/common/image.h
  src/common/image_cache.c
  src/common/metadata.c
  src/common/metadata.h
  src/control/jobs/camera_jobs.c
  src/control/jobs/control_jobs.c
  src/libs/collect.c
  src/libs/geotagging.c
  src/libs/import.c
  src/libs/metadata_view.c
  src/libs/tools/timeline.c
  src/lua/image.c
Labels: feature: redesign, scope: codebase

#11402 make maximum tile number depending on resourcelevel
  data/darktableconfig.xml.in
  src/develop/tiling.c
Labels: feature: redesign, scope: codebase

#11409 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#11410 import: if no exif datetime use file datetime instead of current datetime
  src/control/jobs/control_jobs.c
Labels: feature: enhancement, scope: DAM

#11421 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#11431 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#11430 print: rely on cups-filter to autorotate images
  src/common/cups_print.c
Labels: bugfix, priority: high, understood: unclear, release notes: pending

#11433 fix available OpenCL memory check for on-cpu devices
  src/common/opencl.c
Labels: feature: redesign, scope: performance, scope: codebase, release notes: pending

#11436 Introduce seperate values for cl roundups
  src/common/darktable.c
  src/common/darktable.h
  src/common/opencl.c
  src/common/opencl.h
Labels: feature: redesign, release notes: pending

#11437 Ukrainian translation update
  po/uk.po
Labels: scope: translation
