Repository darktable-org/darktable, pull requests merged in 2022-09, with the labels that each got.

#12419 cmake: fix SDL2 linking
  src/libs/CMakeLists.txt
Labels: scope: OS support, scope: windows support

#12203 webp: embed ICC profile
  cmake/modules/FindWebP.cmake
  data/darktableconfig.xml.in
  src/imageio/format/webp.c
Labels: feature: enhancement, scope: color management, documentation-pending, release notes: pending

#12356 curve-tool: cmake: enable/disable OpenMP use, via USE_OPENMP
  tools/basecurve/CMakeLists.txt
Labels: feature: enhancement, priority: low, release notes: pending

#12422 Properly support PortMidi in the build system
  DefineOptions.cmake
  cmake/modules/FindPortMidi.cmake
  src/CMakeLists.txt
  src/libs/CMakeLists.txt
Labels: feature: enhancement, scope: hardware support, documentation-pending, release notes: pending

#12102 imageio: avif, exr profile improvements
  src/imageio/format/avif.c
  src/imageio/format/exr.cc
  src/imageio/format/pdf.c
  src/imageio/format/tiff.c
  src/imageio/format/xcf.c
Labels: feature: enhancement, release notes: pending

#12338 show lua command in action tooltip
  src/develop/imageop.c
  src/gui/accelerators.c
  src/lua/gui.c
Labels: bugfix, feature: enhancement, lua

#12184 Move wb presets into an external JSON file (data/wb_presets.json).
  data/CMakeLists.txt
  data/wb_presets.json
  data/wb_presets.schema
  src/CMakeLists.txt
  src/common/darktable.c
  src/common/darktable.h
  src/common/wb_presets.c
  src/common/wb_presets.h
  src/external/wb_presets.c
  src/iop/temperature.c
Labels: scope: camera support, feature: redesign, scope: codebase, release notes: pending

#12424 Correctly display infinity focus in image information
  src/libs/metadata_view.c
Labels: feature: enhancement

#12431 update esperanto translation
  po/eo.po
Labels: scope: translation

#11883 variables: make $(MAKER) and $(MODEL) available at import time
  src/common/camera_control.c
  src/common/camera_control.h
  src/common/datetime.h
  src/common/exif.cc
  src/common/exif.h
  src/common/image.h
  src/common/import_session.c
  src/common/import_session.h
  src/common/variables.c
  src/common/variables.h
  src/control/jobs/camera_jobs.c
  src/control/jobs/control_jobs.c
  src/views/tethering.c
Labels: feature: enhancement, scope: DAM, documentation-pending, release notes: pending

#12434 culling : force size recompute on init
  src/dtgtk/culling.c
Labels: bugfix, difficulty: trivial, scope: UI

#12367 import&copy: keep the original access and modified timestamps
  src/control/jobs/control_jobs.c
Labels: scope: DAM, release notes: pending

#12437 Turkish translation
  po/tr.po
Labels: scope: translation

#12436 Fix HDR merge zero DNG ColorMatrix
  src/control/jobs/control_jobs.c
Labels: bugfix, release notes: pending

#12439 Next atttempt to fix pixelpipe cache issues
  src/develop/pixelpipe_cache.c
  src/develop/pixelpipe_cache.h
  src/develop/pixelpipe_hb.c
  src/develop/pixelpipe_hb.h
Labels: bugfix, priority: high, scope: codebase

#12308 preset and style shortcut fixes
  src/bauhaus/bauhaus.c
  src/bauhaus/bauhaus.h
  src/common/darktable.h
  src/develop/blend.h
  src/develop/blend_gui.c
  src/develop/imageop_gui.c
  src/gui/accelerators.c
  src/gui/guides.c
  src/gui/presets.c
  src/iop/colorout.c
  src/libs/export.c
  src/libs/filters/grouping.c
  src/libs/history.c
  src/libs/image.c
  src/libs/lib.c
  src/libs/print_settings.c
  src/libs/styles.c
  src/views/darkroom.c
  src/views/lighttable.c
Labels: bugfix, feature: enhancement, priority: medium, difficulty: average, scope: UI, scope: codebase

#12404 fix problems with widget visibility in QAP
  src/gui/accelerators.c
  src/gui/accelerators.h
  src/libs/modulegroups.c
Labels: bugfix, priority: medium, scope: UI

#12450 Update for pixelpipe cache size
  src/common/darktable.c
  src/common/darktable.h
  src/develop/pixelpipe_hb.c
Labels: feature: redesign

#12440 code maintenance for detail mask code
  src/develop/blend.c
  src/develop/masks.h
  src/develop/masks/detail.c
Labels: scope: codebase

#12451 Update de.po
  po/de.po
Labels: scope: translation

#12453 Update de.po context specific translation
  po/de.po
Labels: scope: translation

#12455 Update de.po
  po/de.po
Labels: scope: translation

#11579 Provide instructions and helper scripts to generate dmg of homebrew-based build for macOS
  packaging/macosx/1_install_hb_dependencies.sh
  packaging/macosx/2_build_hb_darktable_custom.sh
  packaging/macosx/2_build_hb_darktable_default.sh
  packaging/macosx/3_make_hb_darktable_package.sh
  packaging/macosx/4_make_hb_darktable_dmg.sh
  packaging/macosx/BUILD_hb.txt
  packaging/macosx/Y_cleanup_hb_darktable.sh
Labels: priority: low, difficulty: hard, scope: OS support, no-pr-activity

#10853 refactor(darktable.c): no longer prefer XWayland over Wayland
  src/common/darktable.c
Labels: priority: high, feature: redesign, understood: clear, scope: UI, no-pr-activity, release notes: pending

#12375 set light patterns for Behringer b-control midi rotors (BCR2000/BCF2000)
  src/libs/tools/midi.c
Labels: feature: enhancement, priority: low, scope: hardware support, release notes: pending

#12449 control_jobs: fix macos build for import time
  src/control/jobs/control_jobs.c
Labels: bugfix, priority: high

#12463 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#12464 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#12466 Properly report pixelpipe cache hits
  src/develop/pixelpipe_cache.c
Labels: scope: codebase

#12465 Bugfix both overexposed indicators
  src/iop/overexposed.c
  src/iop/rawoverexposed.c
Labels: bugfix

#12433 scroll through presets using shortcut
  src/bauhaus/bauhaus.c
  src/develop/imageop.c
  src/gui/accelerators.c
  src/gui/accelerators.h
  src/gui/presets.c
  src/gui/presets.h
Labels: documentation-pending, release notes: pending

#12476 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#12452 Make darktable version string in the UI less transparent
  src/libs/tools/darktable.c
Labels: scope: UI

#12462 Don't restore panels when toggling iso_12646 mode
  src/libs/duplicate.c
  src/views/darkroom.c
Labels: bugfix

#12485 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#12486 Update de.po
  po/de.po
Labels: scope: translation

#12487 updated sq.po
  po/sq.po
Labels: scope: translation

#12484 fix bauhaus popup positioning on wayland
  src/bauhaus/bauhaus.c
Labels: bugfix

#12496 Spanish translation update
  po/es.po
Labels: scope: translation

#12491 update TW translation
  po/zh_TW.po
Labels: scope: translation

#12492 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#12494 Fix demosaicer/temperature related glitches
  src/iop/channelmixerrgb.c
  src/iop/demosaic.c
  src/iop/temperature.c
Labels: bugfix, release notes: pending

#12498 Turkish translation update
  po/tr.po
Labels: scope: translation

#12499 Update Czech translation.
  po/cs.po
Labels: scope: translation

#12506 Update Esperanto translation.
  po/eo.po
Labels: scope: translation

#12503 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#12501 [uk.po] Minor refinement: increase the consistency of translation of one of the terms
  po/uk.po
Labels: scope: translation

#12505 Fixed issues in retouch module toast messages
  src/iop/retouch.c
Labels: bugfix, scope: translation

#12502 Highlights segmentation code maintenance (4)
  src/iop/highlights.c
  src/iop/hlrecovery.c
  src/iop/segmentation.h
Labels: scope: codebase

#12504 Remove the `opencl_synch_cache` conf option
  data/darktableconfig.xml.in
  src/common/opencl.c
  src/common/opencl.h
  src/develop/pixelpipe_hb.c
Labels: scope: performance, scope: codebase

#12475 don't disable widgets in a collapsed section
  src/bauhaus/bauhaus.c
  src/bauhaus/bauhaus.h
  src/common/action.h
  src/common/introspection.h
  src/develop/imageop_gui.c
  src/develop/imageop_gui.h
  src/gui/accelerators.c
  src/gui/gtk.c
  src/iop/channelmixerrgb.c
  src/iop/colorbalancergb.c
  src/iop/splittoning.c
  src/libs/history.c
  src/libs/modulegroups.c
Labels: bugfix, feature: enhancement

#12511 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#12510 Updated and fixed RO translation
  po/ro.po
Labels: scope: translation

#12513 Update de.po
  po/de.po
Labels: scope: translation

#12514 import: When importing keep the folder or filmroll property.
  src/libs/import.c
Labels: feature: enhancement, release notes: pending

#12517 Pixelpipe type testing maintenance
  src/common/opencl.c
  src/develop/blend.c
  src/develop/pixelpipe.h
  src/develop/pixelpipe_cache.c
  src/develop/pixelpipe_hb.c
  src/iop/ashift.c
  src/iop/atrous.c
  src/iop/basicadj.c
  src/iop/bilateral.cc
  src/iop/cacorrect.c
  src/iop/channelmixerrgb.c
  src/iop/clipping.c
  src/iop/colorbalancergb.c
  src/iop/colormapping.c
  src/iop/colorout.c
  src/iop/colorreconstruction.c
  src/iop/colortransfer.c
  src/iop/colorzones.c
  src/iop/denoiseprofile.c
  src/iop/diffuse.c
  src/iop/dither.c
  src/iop/dual_demosaic.c
  src/iop/exposure.c
  src/iop/filmicrgb.c
  src/iop/globaltonemap.c
  src/iop/grain.c
  src/iop/hazeremoval.c
  src/iop/hotpixels.c
  src/iop/lens.cc
  src/iop/levels.c
  src/iop/nlmeans.c
  src/iop/retouch.c
  src/iop/rgbcurve.c
  src/iop/rgblevels.c
  src/iop/tonecurve.c
  src/iop/toneequal.c
  src/iop/zonesystem.c
Labels: scope: codebase

#12520 Fix translations issues
  po/pt_BR.po
  po/ro.po
Labels: bugfix, priority: high

#12526 update TW translation
  po/zh_TW.po
Labels: scope: translation

#12523 [uk.po] Minor refinement
  po/uk.po
Labels: scope: translation

#12237 png: try to get colorspace from cICP chunk as well
  src/common/imageio_avif.c
  src/common/imageio_png.c
  src/common/imageio_png.h
  src/iop/colorin.c
Labels: feature: enhancement, scope: software support, release notes: pending

#12542 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation

#12543 Update de.po
  po/de.po
Labels: scope: translation

#12544 Ukrainian translation update
  po/uk.po
Labels: scope: translation

#12528 tiff: fix Lab conversion on import
  src/common/imageio_tiff.c
Labels: bugfix, scope: color management, release notes: pending

#11905 make delete/edit action on presets avoid rebuilding the whole tree
  src/gui/preferences.c
  src/gui/presets.c
  src/gui/presets.h
Labels: feature: enhancement, release notes: pending

#12533 Support for importing webp images via GraphicsMagick
  src/CMakeLists.txt
  src/common/imageio_gm.c
Labels: feature: enhancement, priority: medium, documentation-pending, release notes: pending

#12548 Turkish translation update
  po/tr.po
Labels: scope: translation

#12545 Introduce balanced OpenCL vs CPU tiling
  src/common/opencl.c
  src/common/opencl.h
  src/develop/pixelpipe_hb.c
  src/develop/tiling.c
  src/develop/tiling.h
Labels: priority: high, feature: redesign, difficulty: hard, scope: performance, scope: codebase, release notes: pending

#12557 BUGFIX: highlights reconstruction visualize indicator
  data/kernels/basic.cl
  src/iop/highlights.c
Labels: bugfix, release notes: pending

#12563 Update ja.po
  po/ja.po
Labels: scope: translation
