Repository darktable-org/darktable, pull requests merged in 2023-01, with the labels that each got.

#13248 make yes/no buttons in dialogs respond to alt+y/n
  src/gui/gtk.c
Labels: bugfix, priority: low, difficulty: trivial, scope: UI, release notes: pending

#13245 Reorder the configuration loading (Fix value sanitization).
  src/common/darktable.c
  src/control/conf.c
  tools/generate_darktablerc_conf.xsl
Labels: bugfix, priority: high, scope: codebase, release notes: pending

#13249 Turkish translation update
  po/tr.po
Labels: scope: translation / strings

#13255 Fix crash in camera tethering
  src/common/camera_control.c
Labels: bugfix, priority: medium, scope: hardware support, release notes: pending

#13268 darktableconfig.xml.in: Add RYB option for vectorscope.
  data/darktableconfig.xml.in
Labels: bugfix, priority: medium, difficulty: trivial, scope: UI, release notes: pending

#13265 Add launchable tag to appdata.xml metainfo
  data/org.darktable.darktable.appdata.xml.in
Labels: scope: codebase

#13270 collect : fix query construction if some field empty
  src/common/collection.c
Labels: bugfix, priority: high, difficulty: trivial, scope: DAM

#13280 [GUI] MIDI is an acronym and should be spelled all caps
  data/darktableconfig.xml.in
Labels: scope: translation / strings, scope: UI

#13281 Fix segfaults (double free & color conversion) in darktable-chart
  src/chart/colorchart.c
  src/chart/main.c
Labels: bugfix, priority: high, release notes: pending

#13261 place wider popup on same display as widget or cursor
  src/bauhaus/bauhaus.c
Labels: bugfix, priority: high, feature: redesign, scope: UI

#13279 Fixing Y0-mask calculations (#13271)
  src/develop/pixelpipe_hb.c
  src/iop/dual_demosaic.c
Labels: bugfix, priority: high, scope: image processing, release notes: pending

#13269 config: use fgets instead of fscanf to avoid broken fscanf implementation on Windows
  src/control/conf.c
Labels: bugfix, priority: high, scope: codebase, release notes: pending

#13292 Ukrainian translation update
  po/uk.po
Labels: scope: translation / strings

#13291 Bump required CMake version
  CMakeLists.txt
  README.md
Labels: scope: codebase

#13313 Update ja.po
  po/ja.po
Labels: scope: translation / strings

#13287 CMake: small libjxl search improvements
  cmake/modules/FindJXL.cmake
Labels: feature: enhancement, scope: codebase

#13300 optimize thumbnail infos retrieval
  src/dtgtk/thumbnail.c
Labels: feature: enhancement, difficulty: trivial, scope: performance

#13322 po/actions loop - fix infinite loop when a module load fails
  src/common/imageio_module.c
  src/common/module_api.h
  src/control/control.c
  src/gui/accelerators.c
Labels: bugfix, priority: high, understood: clear, difficulty: hard, scope: codebase, release notes: pending

#13299 make quick access styles and presets buttons shortcutable
  src/views/darkroom.c
Labels: bugfix, scope: codebase, release notes: pending

#13309 Raise libheif version requirement to at least 1.13.0
  README.md
  src/CMakeLists.txt
Labels: bugfix, priority: low, scope: software support

#13189 [fix #12991]remove trailing spaces
  src/common/import_session.c
Labels: bugfix, priority: medium, scope: codebase, scope: windows support

#13326 Turkish translation update
  po/tr.po
Labels: scope: translation / strings

#13328 Ukrainian translation update
  po/uk.po
Labels: scope: translation / strings

#13327 update czech .po file
  po/cs.po
Labels: scope: translation / strings

#13333 Fix grammar in GUI string
  src/views/darkroom.c
Labels: scope: translation / strings

#13341 Ukrainian translation update
  po/uk.po
Labels: scope: translation / strings

#13331 Add script to build and package darktable into AppImage format
  tools/appimage-build-script.sh
Labels: scope: codebase

#13342 Reflect rename of .desktop file in POTFILES.in
  po/POTFILES.in
Labels: scope: codebase

#13343 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#13210 Use a libheif function that will give us the true bit depth of the original pixels
  src/common/imageio_heif.c
Labels: bugfix, priority: medium, scope: image processing, release notes: pending

#13274 don't recalculate on crop change when focused
  src/common/image.c
  src/develop/develop.c
  src/develop/develop.h
  src/develop/imageop.c
  src/iop/ashift.c
  src/iop/clipping.c
  src/iop/crop.c
  src/iop/liquify.c
  src/iop/retouch.c
  src/iop/spots.c
  src/libs/modulegroups.c
Labels: bugfix, priority: medium, difficulty: average, scope: UI, release notes: pending

#13330 Histogram calculation updates
  src/common/histogram.c
  src/common/histogram.h
  src/develop/imageop.h
  src/develop/pixelpipe.h
  src/develop/pixelpipe_hb.c
  src/iop/exposure.c
  src/iop/rgbcurve.c
  src/libs/histogram.c
Labels: feature: redesign, difficulty: hard, scope: performance, scope: codebase, release notes: pending

#13234 po/rework workflow & module groups
  data/darktableconfig.xml.in
  src/common/database.c
  src/common/exif.cc
  src/common/iop_order.c
  src/common/utility.c
  src/common/utility.h
  src/develop/blend.c
  src/develop/develop.c
  src/gui/presets.c
  src/iop/channelmixerrgb.c
  src/iop/filmicrgb.c
  src/iop/temperature.c
  src/libs/modulegroups.c
Labels: priority: high, feature: redesign, scope: UI, scope: image processing, documentation-pending, release notes: pending

#13212 avoid snapshots invalidation
  src/common/database.c
  src/common/history.c
  src/common/styles.c
  src/develop/develop.c
  src/develop/develop.h
  src/libs/snapshots.c
  src/views/slideshow.c
Labels: priority: high, feature: redesign, scope: image processing, documentation-pending, release notes: pending

#13047 Improved error / debugging output in iop_profile.c
  src/common/iop_profile.c
Labels: scope: codebase

#13053 catch some more qap crashes with multi-instance
  src/libs/modulegroups.c
Labels: bugfix, priority: low

#13316 imageio: read Exif from AVIF/HEIC if no Exiv2 support
  src/common/imageio_avif.c
  src/common/imageio_heif.c
Labels: feature: enhancement, priority: low, scope: codebase, release notes: pending

#13216 colorpicker cleanups/improvements
  src/common/color_picker.c
  src/common/color_picker.h
  src/develop/blend_gui.c
  src/develop/pixelpipe_hb.c
  src/gui/color_picker_proxy.c
  src/gui/color_picker_proxy.h
  src/iop/colorzones.c
  src/iop/filmic.c
  src/iop/filmicrgb.c
  src/iop/retouch.c
  src/iop/rgbcurve.c
  src/iop/tonecurve.c
  src/libs/colorpicker.c
  src/libs/colorpicker.h
  src/libs/lib.c
  src/libs/lib.h
  src/views/darkroom.c
Labels: priority: high, feature: redesign, scope: performance, scope: codebase, documentation-pending, release notes: pending

#13329 Redesign of export & thumbs
  src/common/imageio.c
  src/control/jobs/control_jobs.c
  src/control/jobs/control_jobs.h
  src/iop/finalscale.c
  src/libs/export.c
Labels: bugfix, priority: high, difficulty: hard, scope: codebase, release notes: pending

#12894 Implementation of the QOI image loader
  data/CMakeLists.txt
  data/supported_extensions.cmake
  src/CMakeLists.txt
  src/common/image.h
  src/common/imageio.c
  src/common/imageio_qoi.c
  src/common/imageio_qoi.h
  src/common/qoi.h
Labels: priority: medium, feature: new, scope: image processing, release notes: pending

#13254 HLR updates for 4.4 (incl OpenCL)
  data/kernels/basic.cl
  src/iop/highlights.c
  src/iop/hlrecovery_v2.c
  src/iop/opposed.c
  src/iop/segmentation.h
Labels: bugfix, priority: high, feature: redesign, scope: image processing, release notes: pending

#13149 po/multiple auto presets & iop module label
  src/common/database.c
  src/common/exif.cc
  src/common/history.c
  src/common/history_snapshot.c
  src/common/iop_order.c
  src/common/iop_order.h
  src/common/presets.c
  src/common/presets.h
  src/develop/develop.c
  src/develop/develop.h
  src/develop/imageop.c
  src/develop/imageop.h
  src/gui/presets.c
  src/libs/snapshots.c
  src/views/darkroom.c
Labels: feature: enhancement, priority: high, documentation-pending, release notes: pending

#13348 rgbcurve bugfix: draw histogram properly when compensate middle grey is set
  src/iop/rgbcurve.c
Labels: bugfix, priority: medium, scope: UI, release notes: pending

#13352 borders: Fix rounding issues when computing width/height.
  src/iop/borders.c
Labels: bugfix, priority: medium, scope: image processing, release notes: pending

#13351 collect : fix usage of exclude for first item
  src/common/collection.c
Labels: bugfix, priority: high, difficulty: trivial, scope: DAM, release notes: pending

#13360 fix shortcut toast for % sliders
  src/bauhaus/bauhaus.c
Labels: bugfix, difficulty: trivial, scope: UI

#13361 Pixelpipe debugging mods
  src/common/darktable.c
  src/common/darktable.h
  src/common/dlopencl.c
  src/common/exif.cc
  src/common/mipmap_cache.c
  src/common/opencl.c
  src/develop/pixelpipe_cache.c
  src/develop/pixelpipe_hb.c
  src/develop/pixelpipe_hb.h
  src/develop/tiling.c
  src/gui/accelerators.c
  src/iop/demosaic.c
  src/iop/finalscale.c
Labels: scope: codebase

#13337 CMake fixes from Gentoo for 4.2
  DefineOptions.cmake
  src/libs/CMakeLists.txt
Labels: scope: codebase

#13373 Ukrainian translation update
  po/uk.po
Labels: scope: translation / strings

#13374 update de.po
  po/de.po
Labels: scope: translation / strings

#13382 color harmonies: fix translation
  src/libs/histogram.c
Labels: scope: translation / strings

#13380 Fix some string format type mismatches
  src/common/color_picker.c
  src/common/histogram.c
  src/common/locallaplacian.c
  src/common/metadata.c
  src/common/selection.c
  src/common/tags.c
  src/common/variables.c
  src/develop/imageop.c
  src/dtgtk/range.c
  src/gui/accelerators.c
Labels: scope: codebase

#13366 CI: update path for SSL certs on Windows
  cmake/windows-macros.cmake
Labels: bugfix, scope: codebase

#13359 Fix some gchar allocation leaks
  src/common/collection.c
  src/gui/styles_dialog.c
  src/iop/channelmixerrgb.c
  src/iop/exposure.c
Labels: bugfix, priority: medium, scope: codebase, release notes: pending

#13387 Fix potential macro expansion error
  src/common/film.c
Labels: scope: codebase

#13381 dont leak refs when cleaning up iop
  src/develop/imageop.c
Labels: bugfix, priority: medium, scope: codebase

#13393 Ukrainian translation update
  po/uk.po
Labels: scope: translation / strings

#13392 A very minor fix in the Windows build instructions
  packaging/windows/README.md
Labels: feature: enhancement, scope: codebase

#13388 Fix missing va_end()
  src/common/opencl.c
Labels: scope: codebase

#13385 Bugfix: Opposed chroma correction OpenCL update
  data/kernels/basic.cl
  src/common/opencl.c
  src/common/opencl.h
  src/iop/highlights.c
  src/iop/opposed.c
Labels: bugfix, priority: high, scope: performance, scope: codebase

#13400 Update de.po
  po/de.po
Labels: scope: translation / strings

#13401 Update ja.po
  po/ja.po
Labels: scope: translation / strings

#13406 ashift : invalidate pipe for rotation and reset
  src/iop/ashift.c
Labels: bugfix, priority: high, difficulty: trivial, scope: UI

#13399 Fix dt_print() verbose checks
  src/common/darktable.c
  src/develop/pixelpipe_hb.c
Labels: bugfix, scope: codebase

#13405 Fixing pixelpipe cache hickups
  src/develop/pixelpipe_cache.c
Labels: bugfix, priority: high, scope: codebase, release notes: pending

#13411 ashift : recompute pipe on direct enable via structure button
  src/iop/ashift.c
Labels: bugfix, priority: medium, difficulty: trivial, scope: UI

#13407 Monochrome images should use default presets
  src/develop/develop.c
Labels: bugfix, feature: enhancement, priority: high, scope: image processing, scope: codebase

#13398 Cleanup duplicate lines on icons css file
  data/themes/darktable-icons.css
Labels: scope: UI, scope: codebase

#13396 [GUI] Fix truncated text in the current color harmony label
  src/libs/histogram.c
Labels: scope: translation / strings, scope: UI, scope: codebase

#13413 Fix a bug in date-time sanitization function
  src/common/exif.cc
Labels: bugfix, priority: medium, scope: DAM, release notes: pending

#13416 [GUI] Fix strings (typo, grammar) in LUT 3D module
  src/iop/lut3d.c
Labels: scope: translation / strings

#13347 [image load] Identify JPEG files by magic bytes, not file extension
  src/imageio/imageio_jpeg.c
Labels: bugfix, priority: low, feature: redesign, scope: codebase, release notes: pending

#13402 Respect "force pan & zoom on mouse" in more places
  src/develop/masks/masks.c
  src/iop/liquify.c
  src/iop/toneequal.c
  src/libs/snapshots.c
  src/views/darkroom.c
Labels: bugfix, scope: UI

#13215 fix image zoom logic when scrolling
  src/views/darkroom.c
Labels: bugfix, priority: low, scope: codebase, release notes: pending

#13368 move slider popup if off screen
  src/bauhaus/bauhaus.c
Labels: scope: UI

#13377 in crop module overlay always show crop handle areas
  src/iop/crop.c
Labels: feature: enhancement, priority: low, scope: UI, release notes: pending

#13439 Ukrainian translation improvement
  po/uk.po
Labels: scope: translation / strings

#13438 Introduce DT_PRINT_ALWAYS for dt_print() variants
  src/common/darktable.c
  src/common/darktable.h
  src/develop/imageop.c
  src/develop/pixelpipe_hb.c
Labels: scope: codebase

#13418 allow resizing of widgets by dragging bottom
  data/darktableconfig.xml.in
  src/dtgtk/drawingarea.c
  src/gui/accelerators.c
  src/gui/gtk.c
  src/gui/gtk.h
  src/iop/atrous.c
  src/iop/basecurve.c
  src/iop/colorbalancergb.c
  src/iop/colorchecker.c
  src/iop/colorzones.c
  src/iop/denoiseprofile.c
  src/iop/filmicrgb.c
  src/iop/levels.c
  src/iop/lowlight.c
  src/iop/rawdenoise.c
  src/iop/rgbcurve.c
  src/iop/rgblevels.c
  src/iop/tonecurve.c
  src/iop/toneequal.c
  src/libs/collect.c
  src/libs/colorpicker.c
  src/libs/duplicate.c
  src/libs/geotagging.c
  src/libs/histogram.c
  src/libs/history.c
  src/libs/map_locations.c
  src/libs/masks.c
  src/libs/metadata.c
  src/libs/metadata_view.c
  src/libs/navigation.c
  src/libs/recentcollect.c
  src/libs/snapshots.c
  src/libs/styles.c
  src/libs/tagging.c
Labels: feature: enhancement, priority: medium, scope: UI, scope: codebase, documentation-pending, release notes: pending

#13344 Fix homebrew build failure on Ventura
  packaging/macosx/3_make_hb_darktable_package.sh
Labels: scope: macos support

#13345 Homebrew dependency installer improvements
  packaging/macosx/1_install_hb_dependencies.sh
Labels: scope: macos support

#13384 Ignore build folders for build with homebrew
  packaging/macosx/.gitignore
Labels: scope: macos support

#13445 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#13443 reformatting pixelpipe and cleanup
  src/develop/pixelpipe_cache.c
  src/develop/pixelpipe_hb.c
Labels: scope: codebase

#13203 Windows: install ImageMagick libraries
  cmake/windows-macros.cmake
  src/CMakeLists.txt
  src/imageio/imageio_im.c
Labels: scope: windows support

#13428 imageio: write to eXIf PNG chunk if possible
  src/imageio/format/png.c
Labels: feature: redesign, scope: DAM, release notes: pending

#13425 imageio: support writing metadata to XCF
  src/imageio/format/exr.cc
  src/imageio/format/j2k.c
  src/imageio/format/xcf.c
  src/imageio/imageio.c
Labels: feature: enhancement, priority: low, scope: DAM, release notes: pending

#13441 FR: Lower the ISO 12646 border size
  data/darktableconfig.xml.in
  src/develop/develop.c
  src/gui/gtk.c
  src/gui/gtk.h
  src/views/darkroom.c
  src/views/view.c
Labels: priority: low, feature: redesign, scope: UI, scope: image processing, scope: color management, release notes: pending

#13370 fix ignore Exif rating on import
  src/common/exif.cc
Labels: priority: low, bug: wip, scope: DAM, release notes: pending

#13435 histogram gui: radio buttons on the left for mode switching
  data/themes/darktable.css
  src/libs/histogram.c
Labels: priority: high, feature: redesign, scope: UI, documentation-pending, release notes: pending

#13432 po/auto init presets
  src/common/presets.c
  src/common/presets.h
  src/develop/develop.c
  src/develop/imageop.c
  src/gui/presets.c
  src/gui/presets.h
Labels: priority: high, feature: redesign, scope: codebase, documentation-pending, release notes: pending

#13451 Ukrainian translation update
  po/uk.po
Labels: scope: translation / strings

#13452 sq translation update
  po/sq.po
Labels: scope: translation / strings

#13454 database: add missing column "multi_name_hand_edited" in create table
  src/common/database.c
Labels: bugfix, priority: high, scope: DAM, scope: codebase

#13457 histogram radio buttons: simplify tooltips
  src/libs/histogram.c
Labels: scope: translation / strings, scope: UI

#13455 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#13419 Cherrypick AP laplacian HLR updates
  data/kernels/basic.cl
  src/iop/highlights.c
Labels: priority: high, feature: redesign, scope: image processing, scope: performance, documentation-pending, release notes: pending

#13460 Turkish translation update
  po/tr.po
Labels: scope: translation / strings

#13466 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#13476 fix resize cursor when scrolled to bottom of listview
  src/gui/gtk.c
Labels: bugfix, scope: UI

#10979 Update info line when cropped size changes
  src/common/image.c
  src/libs/history.c
Labels: bugfix, scope: UI, release notes: pending

#12928 Transform XMP regions when doing XMP attach.
  .gitignore
  src/common/exif.cc
  src/common/exif.h
  src/imageio/imageio.c
Labels: feature: enhancement, priority: low, understood: clear, release notes: pending

#13488 Demosaic debug workup
  src/common/darktable.c
  src/common/darktable.h
  src/iop/demosaic.c
  src/iop/dual_demosaic.c
Labels: scope: codebase
