Repository darktable-org/darktable, pull requests merged in 2023-02, with the labels that each got.

#13353 Rotate with right-drag in qap and if focused module not using it
  src/develop/develop.h
  src/develop/masks/masks.c
  src/iop/ashift.c
  src/iop/liquify.c
  src/views/darkroom.c
Labels: bugfix, feature: enhancement, priority: medium, difficulty: average, scope: UI, documentation-pending, release notes: pending

#13501 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#13503 Update czech language
  po/cs.po
Labels: scope: translation / strings

#13450 po/auto-init copy&paste
  src/common/history.c
  src/common/history.h
  src/common/styles.c
  src/gui/hist_dialog.c
  src/gui/styles_dialog.c
Labels: feature: enhancement, priority: medium, scope: DAM, documentation-pending, release notes: pending

#13491 [GUI] Paper size names must begin with a capital letter
  src/common/pdf.h
Labels: scope: translation / strings

#13505 database: fix memleak and null deref
  src/common/database.c
Labels: scope: codebase

#12880 Embedded dng lens corrections
  src/common/dng_opcode.c
  src/common/dng_opcode.h
  src/common/exif.cc
  src/common/image.c
  src/common/image.h
  src/iop/lens.cc
Labels: feature: enhancement, priority: medium, scope: image processing, documentation-pending, release notes: pending

#13497 deprecates levels & contrast brightness saturation
  src/iop/colisa.c
  src/iop/levels.c
  src/libs/modulegroups.c
Labels: priority: high, scope: codebase, documentation-pending, release notes: pending

#13508 fix signed/unsigned printf format mismatches
  src/iop/liquify.c
  src/iop/lut3d.c
  src/iop/retouch.c
  src/iop/segmentation.h
  src/iop/spots.c
  src/libs/collect.c
  src/libs/export.c
  src/libs/filtering.c
  src/libs/filters/filename.c
  src/libs/geotagging.c
  src/libs/snapshots.c
  src/libs/tools/midi.c
  src/views/tethering.c
Labels: scope: codebase

#13507 convert navigation zoom dropdown to bauhaus
  src/bauhaus/bauhaus.c
  src/libs/navigation.c
  src/views/darkroom.c
Labels: priority: medium, feature: redesign, scope: UI, documentation-pending, release notes: pending

#13496 RFC show ctrl+scroll tooltip for all resizable lists
  src/gui/accelerators.c
  src/gui/gtk.c
Labels: question, scope: UI, bug: fixed

#13469 rework color harmony GUI - guides selection
  data/darktableconfig.xml.in
  src/dtgtk/paint.c
  src/dtgtk/paint.h
  src/libs/histogram.c
Labels: priority: high, feature: redesign, difficulty: average, scope: UI, scope: image processing, documentation-pending

#13522 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#13524 Update zh_TW translation
  po/zh_TW.po
Labels: scope: translation / strings

#13520 [imageio] Optimize QOI loader
  src/imageio/imageio_dng.h
  src/imageio/imageio_gm.c
  src/imageio/imageio_heif.c
  src/imageio/imageio_im.c
  src/imageio/imageio_libraw.c
  src/imageio/imageio_png.c
  src/imageio/imageio_qoi.c
  src/imageio/imageio_tiff.c
Labels: feature: enhancement, scope: codebase

#13527 Bugfix OpenCL: avoid bad pinned transfer
  src/common/opencl.c
  src/common/opencl.h
Labels: bugfix, scope: performance

#13519 Introduce dt_dump_pfm() as a developers helper
  src/common/darktable.c
  src/common/darktable.h
  src/common/locallaplacian.c
  src/iop/denoiseprofile.c
  src/iop/diffuse.c
  src/iop/highlights.c
Labels: scope: codebase

#13533 Debug memory checks & pixelpipe buffer check
  src/common/darktable.c
  src/common/darktable.h
  src/develop/pixelpipe_hb.c
Labels: scope: codebase

#13534 Fix corrections done message for embedded lenses
  src/iop/lens.cc
Labels: scope: image processing, scope: codebase

#13530 Ukrainian translation update
  po/uk.po
Labels: scope: translation / strings

#13528 [imageio] Make reading Exif data and thumbnails less complaining
  src/common/exif.cc
Labels: scope: codebase

#13538 interpolation: modernize logging
  src/common/interpolation.c
Labels: scope: performance, scope: codebase

#13490 noise profiles
  data/noiseprofiles.json
  data/noiseprofiles.schema
Labels: scope: noise profile

#13059 Add white balance presets for OM System OM-1 camera
  data/wb_presets.json
  data/wb_presets.schema
Labels: scope: camera support, depends: rawspeed

#13523 use shift+alt+scroll for widget resize instead of ctrl+scroll
  src/develop/develop.c
  src/gui/accelerators.c
  src/gui/gtk.c
  src/iop/levels.c
  src/iop/rgblevels.c
  src/libs/histogram.c
  src/libs/navigation.c
Labels: bugfix, question, priority: medium, feature: redesign, scope: UI, documentation-pending, release notes: pending

#13542 pixelpipe: fixup colorpicker sampling area calcualtion
  src/develop/pixelpipe_hb.c
Labels: bugfix, scope: image processing, scope: codebase, release notes: pending

#13540 [GUI] Better wording: we're referring to the parameter, not its value
  src/common/darktable.c
Labels: scope: translation / strings

#13548 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#13111 [debugging feature] Allow raw loader selection by file extension
  data/darktableconfig.xml.in
  src/imageio/imageio_libraw.c
  src/imageio/imageio_rawspeed.cc
Labels: scope: codebase

#13544 imageop: always display filename/id with trouble messages on console.
  src/develop/imageop.c
Labels: scope: codebase

#13554 Update de.po
  po/de.po
Labels: scope: translation / strings

#13545 debug options plus pipe pfm dumping
  src/common/darktable.c
  src/common/darktable.h
  src/develop/pixelpipe_hb.c
Labels: scope: codebase

#13558 Improve debug output for history
  src/develop/develop.c
Labels: scope: codebase

#13557 Bugfix and maintenance rawprepare
  src/iop/rawprepare.c
Labels: bugfix, scope: codebase

#13561 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#13550 imageio_exr: read metadata from standard attributes
  src/common/exif.cc
  src/common/exif.h
  src/imageio/imageio_exr.cc
Labels: scope: codebase

#13562 history: Fix loop for merging modules.
  src/common/history.c
Labels: bugfix, priority: high, scope: codebase

#13565 Update zh_TW translation
  po/zh_TW.po
Labels: scope: translation / strings

#13549 add Canon EOS Kiss X10/X10i aliases
  data/noiseprofiles.json
  src/imageio/imageio_libraw.c
Labels: scope: camera support, release notes: pending

#13570 Ukrainian translation update
  po/uk.po
Labels: scope: translation / strings

#13571 images: Do not set the crop_width/crop_height in dt_image_update_final_size.
  src/common/histogram.c
  src/common/histogram.h
  src/common/image.c
  src/common/image.h
  src/common/image_cache.c
  src/develop/masks/masks.c
  src/develop/pixelpipe_hb.c
  src/imageio/imageio.c
  src/imageio/imageio_libraw.c
  src/imageio/imageio_rawspeed.cc
  src/iop/exposure.c
  src/iop/lens.cc
  src/iop/rawprepare.c
  src/libs/histogram.c
Labels: bugfix, priority: high, release notes: pending

#13574 Catch a stray line in darktable terminal output help text and put it in the right place
  src/common/darktable.c
Labels: scope: CLI

#13575 Dither code maintenance
  src/iop/dither.c
Labels: scope: codebase, release notes: pending

#13518 block quit on light table preview
  src/gui/gtk.c
Labels: priority: low, feature: redesign, difficulty: trivial, scope: UI, release notes: pending

#13283 Add dt_lua_tag_t.flags and dt_lua_tag_t.synonyms
  src/lua/tags.c
Labels: feature: enhancement, lua, release notes: pending

#13587 wb_presets: match Leica M9 to rawspeed
  data/wb_presets.json
Labels: scope: camera support, depends: rawspeed

#13589 Update de.po
  po/de.po
Labels: scope: translation / strings

#13594 noiseprofile for fuji X-H2s
  data/noiseprofiles.json
Labels: scope: noise profile

#13572 interpolation: fix mirror and wrap border modes
  src/common/interpolation.c
  src/common/interpolation.h
Labels: bugfix, priority: high, difficulty: hard, scope: image processing, scope: codebase, release notes: pending

#13568 RFC: Add a simple way to benchmark a module
  src/common/darktable.c
  src/common/darktable.h
  src/develop/pixelpipe_hb.c
Labels: priority: low, feature: new, scope: codebase, release notes: pending

#13596 Performance tuning for embedded lens correction
  src/iop/lens.cc
Labels: priority: medium, scope: performance, scope: codebase, release notes: pending

#13602 Bugfix SSE benchmarking
  src/develop/pixelpipe_hb.c
Labels: bugfix, priority: high, scope: codebase

#13599 Update ja.po
  po/ja.po
Labels: scope: translation / strings

#13604 Ukrainian translation improvements
  po/uk.po
Labels: scope: translation / strings

#13592 Update de.po for dt 4.2.x
  po/de.po
Labels: scope: translation / strings

#13601 Demosaicer maintenance code
  src/iop/demosaic.c
  src/iop/dual_demosaic.c
  src/iop/lmmse_demosaic.c
  src/iop/rcd_demosaic.c
Labels: scope: codebase

#13605 [imageio] Delete redundant code in dt_imageio_open_exotic
  src/imageio/imageio.c
  src/imageio/imageio_gm.c
  src/imageio/imageio_im.c
Labels: bugfix, scope: codebase

#13619 maintenance: remove unused SSE includes
  src/common/guided_filter.h
  src/common/histogram.c
  src/develop/imageop_gui.c
  src/iop/borders.c
  src/iop/exposure.c
  src/iop/highpass.c
  src/iop/soften.c
Labels: scope: codebase

#13614 gradudatednd: optimize code and remove SSE
  src/common/darktable.h
  src/iop/graduatednd.c
Labels: priority: high, scope: image processing, scope: performance, release notes: pending

#13623 Raw chromatic aberrations become ROI immune
  src/iop/cacorrect.c
Labels: priority: high, feature: redesign, difficulty: hard, scope: image processing, release notes: pending

#13625 [imageio] Make loaders set flags and values themselves
  src/imageio/imageio.c
  src/imageio/imageio_exr.cc
  src/imageio/imageio_pfm.c
  src/imageio/imageio_rgbe.c
Labels: priority: low, scope: codebase

#13621 Improve HLR UI performance
  src/iop/highlights.c
  src/iop/opposed.c
Labels: priority: medium, feature: redesign, scope: image processing, release notes: pending

#13626 [performance] Add OpenMP to the RGBE loader
  src/imageio/imageio_rgbe.c
Labels: feature: enhancement, priority: medium, scope: image processing, scope: performance, release notes: pending

#13624 Don't show tooltips for window behind dialog
  src/gui/accelerators.c
Labels: bugfix, scope: UI

#13615 [fix #13231] sigmoid : add OpenCL support
  data/kernels/programs.conf
  data/kernels/sigmoid.cl
  src/iop/sigmoid.c
Labels: feature: enhancement, priority: high, scope: image processing, scope: performance

#13612 rework homebrew build scripts to use build folder
  packaging/macosx/.gitignore
  packaging/macosx/2_build_hb_darktable_custom.sh
  packaging/macosx/2_build_hb_darktable_default.sh
  packaging/macosx/3_make_hb_darktable_package.sh
  packaging/macosx/4_make_hb_darktable_dmg.sh
  packaging/macosx/BUILD_hb.txt
  packaging/macosx/Y_cleanup_hb_darktable.sh
Labels: scope: macos support

#13588 Better handling of update preset entry in preset menu.
  src/common/presets.c
  src/common/presets.h
  src/develop/imageop.c
  src/gui/presets.c
Labels: feature: enhancement, priority: low, scope: UI, scope: codebase, release notes: pending

#13628 RFC: separate colorbalancergb module descriptions
  src/iop/colorbalance.c
  src/iop/colorbalancergb.c
Labels: scope: translation / strings

#13631 Maintenance of some inline functions
  src/common/math.h
  src/iop/ashift.c
  src/iop/cacorrect.c
  src/iop/demosaic.c
  src/iop/dual_demosaic.c
  src/iop/lmmse_demosaic.c
  src/iop/rcd_demosaic.c
Labels: scope: codebase

#13630 libs/iop: tags section with specific context for better translation.
  po/darktable.pot
  src/iop/ashift.c
  src/iop/cacorrectrgb.c
  src/iop/channelmixerrgb.c
  src/iop/colorbalance.c
  src/iop/colorbalancergb.c
  src/iop/diffuse.c
  src/iop/exposure.c
  src/iop/filmic.c
  src/iop/filmicrgb.c
  src/iop/negadoctor.c
  src/iop/profile_gamma.c
  src/iop/rawprepare.c
  src/iop/retouch.c
  src/iop/splittoning.c
  src/iop/temperature.c
  src/iop/toneequal.c
  src/iop/vignette.c
  src/iop/watermark.c
  src/libs/camera.c
  src/libs/colorpicker.c
  src/libs/export.c
  src/libs/geotagging.c
  src/libs/print_settings.c
Labels: scope: translation / strings, scope: UI

#13643 Ukrainian translation update
  po/uk.po
Labels: scope: translation / strings

#13642 Bugfix: embedded lens roi_in calculation
  src/iop/lens.cc
Labels: bugfix, priority: high, scope: image processing, scope: codebase, release notes: pending

#13648 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#13639 po/remove auto hack - exposure & basecurve
  data/darktableconfig.xml.in
  src/develop/develop.c
  src/develop/imageop.c
  src/iop/basecurve.c
  src/iop/exposure.c
Labels: bugfix, feature: enhancement, priority: high, scope: image processing, scope: codebase, release notes: pending

#13651 Get rid of libsoup2
  .ci/Brewfile
  .ci/Dockerfile
  .github/workflows/ci.yml
  .github/workflows/manualrun.yml
  .github/workflows/nightly.yml
  CMakeLists.txt
  cmake/modules/FindLibSoup2.cmake
  iwyu.imp
  packaging/macosx/1_install_hb_dependencies.sh
  packaging/macosx/BUILD-ARM64.txt
  packaging/macosx/BUILD.txt
  packaging/nix/default.nix
  packaging/windows/README.md
  po/POTFILES.in
  src/CMakeLists.txt
  src/common/http_server.c
  src/common/http_server.h
Labels: scope: codebase

#13629 po/fr upcase
  po/fr.po
Labels: scope: translation / strings

#13653 imageio: add OpenMP to XCF export
  src/imageio/format/tiff.c
  src/imageio/format/xcf.c
Labels: feature: enhancement, scope: image processing, scope: performance, release notes: pending

#13656 homebrew: Explicitly install pkg-config
  packaging/macosx/1_install_hb_dependencies.sh
Labels: scope: macos support

#13662 denoiseprofile: Properly reset the default even when no GUI present.
  src/iop/denoiseprofile.c
Labels: bugfix, priority: high, scope: image processing

#13663 [imageio] Remove unused code for RGBE format
  src/imageio/imageio_rgbe.c
Labels: scope: codebase

#13666 Ukrainian translation update
  po/uk.po
Labels: scope: translation / strings

#13659 po/iop instance name - remove hard coded style and use CSS
  data/themes/darktable.css
  src/develop/develop.c
  src/develop/develop.h
  src/develop/imageop.c
  src/develop/imageop.h
Labels: priority: medium, feature: redesign, scope: UI, scope: codebase, release notes: pending

#13669 Update de.po
  po/de.po
Labels: scope: translation / strings

#13670 crop: remove commit button
  src/iop/crop.c
Labels: bugfix, scope: UI

#13672 colorcontrast: optimize code and remove SSE
  src/iop/colorcontrast.c
Labels: scope: performance, scope: codebase

#13676 fix redraw loop of navigation widget
  src/control/signal.c
  src/libs/histogram.c
  src/libs/navigation.c
  src/lua/call.c
Labels: bugfix, priority: high

#13685 maintenance: mipmap_cache.c code cleanup, remove SSE
  src/common/mipmap_cache.c
Labels: scope: codebase

#13687 css navigation zoom tweak
  data/themes/darktable-elegant-dark.css
  data/themes/darktable-elegant-grey.css
  data/themes/darktable.css
  src/libs/navigation.c
Labels: feature: enhancement, scope: UI

#13690 Update ja.po
  po/ja.po
Labels: scope: translation / strings

#13683 add nontemporal writes to image-buffer copying
  src/common/dwt.c
  src/common/imagebuf.c
  src/common/iop_profile.c
  src/develop/blend.c
  src/iop/denoiseprofile.c
  src/iop/toneequal.c
Labels: scope: performance, scope: codebase

#13681 borders: use copy_pixel_nontemporal
  src/iop/borders.c
Labels: feature: enhancement, priority: high, scope: performance, release notes: pending

#13697 More conservative OpenCL compiler options
  src/common/darktable.c
  src/common/darktable.h
  src/common/opencl.c
  src/common/opencl.h
Labels: scope: hardware support, scope: codebase

#13696 maintenance: fix 'extern "C"' mess
  src/bauhaus/bauhaus.h
  src/common/atomic.h
  src/common/colorlabels.h
  src/common/darktable.h
  src/common/database.h
  src/common/datetime.h
  src/common/dng_opcode.h
  src/common/exif.cc
  src/common/file_location.h
  src/common/history.h
  src/common/image.h
  src/common/image_cache.h
  src/common/imagebuf.h
  src/common/interpolation.h
  src/common/iop_order.h
  src/common/metadata.h
  src/common/mipmap_cache.h
  src/common/opencl.h
  src/common/ratings.h
  src/common/tags.h
  src/common/utility.h
  src/common/variables.h
  src/control/conf.h
  src/control/control.h
  src/control/jobs/control_jobs.h
  src/control/signal.h
  src/develop/blend.h
  src/develop/develop.h
  src/develop/imageop.h
  src/develop/imageop_gui.h
  src/develop/masks.h
  src/dtgtk/paint.h
  src/gui/accelerators.h
  src/gui/gtk.h
  src/imageio/format/exr.cc
  src/imageio/imageio_common.h
  src/imageio/imageio_exr.cc
  src/imageio/imageio_jpeg.h
  src/imageio/imageio_module.h
  src/imageio/imageio_rawspeed.cc
  src/iop/amaze_demosaic_RT.cc
  src/iop/bilateral.cc
  src/iop/iop_api.h
  src/iop/lens.cc
  src/iop/tonemap.cc
Labels: bugfix, scope: codebase, scope: macos support

#13695 Feature lua image orientation
  src/lua/image.c
Labels: feature: enhancement, lua

#13700 CI: Windows dependencies cleanup
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  packaging/windows/README.md
Labels: scope: OS support

#13694 Fix homebrew package build
  packaging/macosx/3_make_hb_darktable_package.sh
Labels: scope: macos support

#13698 CMake: make Windows on ARM64 package name different
  cmake/darktable-packaging.cmake
Labels: scope: windows support

#13706 CI Bugfix Nightly
  .github/workflows/nightly.yml
Labels: scope: windows support, scope: macos support

#13579 define widget type mimicking actions with flexible lua scripts
  src/bauhaus/bauhaus.c
  src/bauhaus/bauhaus.h
  src/common/collection.c
  src/common/collection.h
  src/common/styles.c
  src/develop/blend.h
  src/develop/blend_gui.c
  src/develop/imageop.c
  src/develop/imageop_gui.c
  src/gui/accelerators.c
  src/gui/accelerators.h
  src/gui/gtk.c
  src/gui/gtk.h
  src/gui/presets.c
  src/iop/blurs.c
  src/iop/borders.c
  src/iop/channelmixerrgb.c
  src/iop/choleski.h
  src/iop/colorbalancergb.c
  src/iop/diffuse.c
  src/iop/exposure.c
  src/iop/filmicrgb.c
  src/iop/highlights.c
  src/iop/negadoctor.c
  src/iop/toneequal.c
  src/libs/filtering.c
  src/libs/filters/grouping.c
  src/libs/filters/history.c
  src/libs/filters/local_copy.c
  src/libs/filters/module_order.c
  src/libs/filters/rating.c
  src/libs/history.c
  src/libs/lib.c
  src/libs/modulegroups.c
  src/libs/tools/global_toolbox.c
  src/lua/events.c
  src/lua/gui.c
  src/lua/lua.c
  src/lua/widget/combobox.c
  src/lua/widget/slider.c
  src/views/darkroom.c
Labels: bugfix, feature: new, scope: UI, scope: codebase, lua, documentation-pending, release notes: pending

#13708 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#13705 Various bugfixes for embedded lens correction
  src/iop/lens.cc
Labels: bugfix

#13715 colorin: remove LCMS2 codepath SSE version
  src/iop/colorin.c
Labels: scope: codebase

#13713 maintenance: dedup colorspace conversions (to/from rec709 and srgb)
  src/common/colorspaces_inline_conversions.h
  src/iop/ashift.c
  src/iop/colorize.c
  src/iop/colorreconstruction.c
Labels: scope: codebase

#13716 Modulegroup fixes (sigmoid, hlr)
  src/libs/modulegroups.c
Labels: scope: UI

#13704 Bugfix: highlights opposed & segmentation
  src/iop/hlrecovery_v2.c
  src/iop/segmentation.h
Labels: bugfix

#13721 Fix color harmony font size
  src/libs/histogram.c
Labels: bugfix, scope: UI

#13710 Bugfix #13668
  src/common/imagebuf.c
  src/iop/spots.c
Labels: bugfix, priority: high, scope: image processing

#13720 Fix slideshow not working on HiDPI displays
  src/views/slideshow.c
Labels: bugfix, priority: high, scope: UI

#13725 bilat: add checks for memory allocation failure
  src/common/bilateral.c
  src/common/locallaplacian.c
  src/iop/bilat.c
Labels: bugfix, scope: codebase

#13724 reduce cpu load exposure module in automatic mode
  src/iop/exposure.c
Labels: bugfix, scope: performance

#13719 colorize: optimize pixel loop
  src/iop/colorize.c
Labels: scope: performance

#13661 [imageio][performance] Add OpenMP to the PNG loader
  src/imageio/imageio_png.c
Labels: feature: enhancement, scope: performance

#13707 po/history label name
  src/develop/develop.c
  src/develop/develop.h
  src/develop/imageop.c
  src/libs/history.c
Labels: bugfix, feature: redesign, scope: UI

#13205 Windows package do not use appdata.xml
  data/CMakeLists.txt
Labels: scope: windows support

#13738 Ukrainian translation update
  po/uk.po
Labels: scope: translation / strings

#13741 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#13744 Update de.po
  po/de.po
Labels: scope: translation / strings

#13736 Bugfix: restrict --threads to possible values
  .github/workflows/ci.yml
  src/common/bilateral.c
  src/common/darktable.c
  src/common/darktable.h
  src/common/imagebuf.c
  src/common/nlmeans_core.c
  src/control/control.h
  src/control/jobs.c
  src/develop/masks/circle.c
  src/develop/masks/path.c
  src/imageio/imageio_j2k.c
  src/iop/demosaic.c
  src/iop/rawdenoise.c
Labels: bugfix, scope: codebase

#13759 fix minor french text errors
  po/fr.po
Labels: scope: translation / strings

#13748 colorin: optimize simple colormatrix conversion, remove SSE
  src/chart/main.c
  src/common/colorspaces_inline_conversions.h
  src/iop/colorin.c
  src/iop/colorzones.c
  src/iop/gamma.c
Labels: scope: codebase, release notes: pending

#13756 Remove unused header file
  src/views/lighttable_undo.h
Labels: priority: low, difficulty: trivial, scope: codebase

#13750 Let's require gcc8 for darktable
  cmake/compiler-versions.cmake
  src/common/atomic.c
  src/common/atomic.h
  src/common/box_filters.c
  src/iop/lens.cc
Labels: scope: codebase

#13751 more precise parameter validation check
  src/develop/imageop.c
Labels: scope: codebase

#13760 colorchecker(CLUT): optimize and remove never-completed SSE codepath
  src/iop/colorchecker.c
Labels: scope: performance, scope: codebase

#13734 maintenance: memory allocation checks
  src/common/box_filters.c
  src/common/color_picker.c
  src/common/dwt.c
  src/develop/pixelpipe_hb.c
  src/iop/basecurve.c
  src/iop/blurs.c
  src/iop/cacorrect.c
  src/iop/censorize.c
  src/iop/diffuse.c
  src/iop/filmicrgb.c
  src/iop/highlights.c
  src/iop/liquify.c
  src/iop/retouch.c
  src/iop/rgblevels.c
  src/iop/sharpen.c
Labels: bugfix

#13764 [GUI] Fix spelling of initialisms: EIGF, GF
  src/iop/toneequal.c
Labels: scope: translation / strings

#13773 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#13768 Fix build with LLVM 15
  src/imageio/imageio_rawspeed.cc
Labels: scope: codebase

#13757 OpenCL supports --dump-pipe
  src/common/darktable.c
  src/common/darktable.h
  src/common/locallaplacian.c
  src/common/opencl.c
  src/common/opencl.h
  src/develop/pixelpipe_hb.c
  src/iop/denoiseprofile.c
  src/iop/diffuse.c
  src/iop/highlights.c
Labels: feature: enhancement, scope: codebase

#13758 fix bauhaus non-toggle button toggled by shortcut
  src/bauhaus/bauhaus.c
  src/libs/navigation.c
Labels: bugfix

#13774 surfaceblur: optimize 'naive' codepath for very small radii
  src/iop/bilateral.cc
Labels: scope: performance

#13780 Ukrainian translation update
  po/uk.po
Labels: scope: translation / strings

#13772 imageop: Properly ellipsise the module instance name.
  src/develop/imageop.c
Labels: bugfix, priority: high, scope: UI
