Repository darktable-org/darktable, pull requests merged in 2023-08, with the labels that each got.

#14974 Retouch and liquify usabilty,expand and show crop
  src/develop/develop.h
  src/develop/imageop.h
  src/develop/pixelpipe_hb.c
  src/iop/ashift.c
  src/iop/clipping.c
  src/iop/crop.c
  src/iop/liquify.c
  src/iop/retouch.c
  src/views/darkroom.c
Labels: feature: new, scope: image processing, documentation-pending

#14989 reenable macOS nightly builds
  .github/workflows/nightly.yml
Labels: scope: macos support

#14992 Debug option to write the scharr mask
  src/develop/pixelpipe_hb.c
Labels: scope: image processing, scope: codebase

#14990 Getting rid of OpenCL 1.1 functions
  src/common/dlopencl.c
  src/common/dlopencl.h
  src/common/opencl.c
  src/common/opencl.h
Labels: scope: hardware support, scope: codebase

#14765 make metadata editor save changes before showing data for different image
  data/themes/darktable.css
  src/common/usermanual_url.c
  src/gui/accelerators.c
  src/libs/metadata.c
Labels: bugfix, difficulty: average, scope: UI, documentation-pending

#14994 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#14860 sigmoid: code cleanup
  data/kernels/sigmoid.cl
  src/iop/sigmoid.c
Labels: priority: medium, scope: image processing, scope: color management, scope: codebase

#15002 Bump CL kernel version directory
  src/common/opencl.h
Labels: bugfix, priority: high, scope: hardware support

#14998 macOS: handle @loader_paths in package build
  packaging/macosx/3_make_hb_darktable_package.sh
Labels: scope: macos support

#15007 Collapsible section for lens fine-tuning and hide blend fulcrum
  src/develop/blend_gui.c
  src/iop/lens.cc
Labels: feature: redesign, scope: UI

#15004 po/remove deferred preset
  src/common/history.c
  src/develop/develop.c
  src/develop/develop.h
  src/develop/imageop.c
  src/develop/imageop.h
  src/libs/history.c
  src/libs/modulegroups.c
  src/views/darkroom.c
Labels: bugfix, priority: high, difficulty: hard, scope: UI, scope: DAM, scope: codebase

#15008 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#15001 Autosave history only while in darkroom
  src/develop/develop.c
  src/develop/develop.h
  src/views/darkroom.c
Labels: bugfix, priority: high, scope: codebase

#14991 More finishing touches for the shortcuts system
  src/bauhaus/bauhaus.c
  src/bauhaus/bauhaus.h
  src/dtgtk/paint.c
  src/gui/accelerators.c
  src/gui/gtk.c
  src/iop/borders.c
  src/libs/collect.c
  src/libs/modulegroups.c
  src/libs/tools/global_toolbox.c
  src/views/view.h
Labels: bugfix, feature: enhancement, priority: medium, feature: new, feature: redesign, difficulty: hard, scope: UI, scope: codebase, documentation-pending, release notes: pending

#15011 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#15010 macOS: Fix loader path on package build
  packaging/macosx/3_make_hb_darktable_package.sh
Labels: scope: macos support

#15012 Simplify the fast mask blurring code
  src/develop/blend.c
  src/develop/masks.h
  src/develop/masks/detail.c
  src/iop/demosaicing/dual.c
  src/iop/hlreconstruct/segbased.c
Labels: scope: codebase

#15032 fix de tooltip text
  po/de.po
Labels: scope: translation / strings

#15040 imageop: Also rebuild pixelpipe for operation_tags_filter.
  src/develop/imageop.c
Labels: bugfix, priority: high, scope: UI

#15037 Update de.po
  po/de.po
Labels: scope: translation / strings

#15045 imageio: remove naked j2k codestream output
  src/imageio/format/j2k.c
Labels: scope: software support

#15050 [CI/CD] Install jpeg-turbo in the build environment for macOS
  .ci/Brewfile
Labels: scope: macos support

#15057 geotagging: eliminate Gtk null-pointer warning
  src/libs/geotagging.c
Labels: bugfix, priority: low

#15054 Update de.po
  po/de.po
Labels: scope: translation / strings

#15053 [macOS homebrew] add jpeg-turbo dependency
  packaging/macosx/1_install_hb_dependencies.sh
Labels: scope: macos support

#15062 [CI/CD] Don't fail the nightly release if the macOS build failed
  .github/workflows/nightly.yml
Labels: scope: macos support

#15091 Minor fix in french translation
  po/fr.po
Labels: scope: translation / strings

#15065 Add protection against NULL pointer dereference when loading CMYK profile
  src/common/iop_profile.c
Labels: bugfix, scope: image processing, scope: codebase, release notes: pending

#15082 Fix collection filter modes not working
  src/common/collection.c
Labels: bugfix, scope: UI, scope: DAM, release notes: pending

#15066 Precise UI color space and respect visual assessment rule
  data/themes/darktable.css
Labels: difficulty: trivial, scope: UI

#15056 cacorrect: performance optimization
  src/iop/cacorrect.c
Labels: scope: performance

#15073 Make cropping data available for rawspeed sraws
  src/imageio/imageio_rawspeed.cc
Labels: bugfix, priority: medium, reproduce: confirmed, scope: image processing, release notes: pending

#15071 Add white balance presets for Olympus TG-6
  data/wb_presets.json
Labels: scope: camera support

#15077 wb_presets: add Leica M (Typ 240)
  data/wb_presets.json
Labels: scope: camera support

#15078 CMake: enable deprecated rather than drop C++ level
  src/CMakeLists.txt
Labels: scope: codebase

#15030 exif: fix focus distance parsing for Nikon Z bodies
  src/common/exif.cc
Labels: bugfix, scope: software support

#15060 Don't block UI during opencl initialisation
  src/common/darktable.c
  src/common/opencl.c
  src/common/opencl.h
  src/common/variables.c
  src/develop/imageop.c
  src/iop/iop_api.h
Labels: feature: enhancement, scope: UI, scope: performance, release notes: pending

#15055 Add white balance presets for Olympus PEN E-P7.
  data/wb_presets.json
Labels: scope: camera support

#15093 darktable.css macOS roboto patch
  data/themes/darktable.css
Labels: bugfix, difficulty: trivial, scope: UI

#15084 Pan at full resolution and fix iso12646 white border jumps
  src/develop/develop.c
  src/libs/duplicate.c
  src/libs/snapshots.c
  src/views/darkroom.c
  src/views/view.c
  src/views/view.h
Labels: bugfix, feature: enhancement, priority: medium, difficulty: hard, scope: UI, scope: performance, scope: codebase

#15099 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#15102 Updated czech translate
  po/cs.po
Labels: scope: translation / strings

#15114 Fix incorrect use of dt_print in email export target
  src/imageio/storage/email.c
Labels: scope: codebase

#15108 fix opencl cache files for utf8 Windows user names
  src/common/opencl.c
Labels: bugfix, priority: medium, difficulty: trivial, scope: OS support

#15118 fix retina scaling mismatch while pan/zooming
  src/views/view.c
Labels: bugfix, priority: high, scope: UI

#15124 Make median9f a common function
  src/common/math.h
  src/iop/cacorrect.c
  src/iop/demosaicing/lmmse.c
Labels: scope: codebase

#15122 maintenance: remove the last run-time SSE codepath selection
  data/darktableconfig.xml.in
  src/CMakeLists.txt
  src/common/cpuid.c
  src/common/cpuid.h
  src/common/darktable.c
  src/common/darktable.h
  src/common/interpolation.c
  src/iop/colorbalance.c
  src/iop/colorin.c
Labels: scope: performance, scope: codebase

#15098 [GUI] Minor grammar fix: word order
  src/develop/develop.c
Labels: scope: translation / strings

#15129 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#15130 macOS Quick fix Update cacorrect.c
  src/iop/cacorrect.c
Labels: bugfix, priority: low, scope: macos support

#15127 po/fix copy/paste unused multiple instances
  src/common/history.c
Labels: bugfix, priority: high, understood: clear, difficulty: average, scope: image processing, scope: codebase

#15110 Rework OpenCL code and preferences
  data/darktableconfig.xml.in
  src/common/darktable.c
  src/common/darktable.h
  src/common/nvidia_gpus.h
  src/common/opencl.c
  src/common/opencl.h
  src/develop/tiling.c
Labels: priority: medium, feature: redesign, scope: hardware support, scope: codebase, documentation-pending, release notes: pending

#15128 imageio: adjust for libavif 1.0.0 API change
  src/CMakeLists.txt
  src/imageio/imageio_avif.c
Labels: difficulty: trivial, scope: codebase, depends: external lib

#15135 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#15134 fix dt exit from darkroom with lighttable fullpreview
  src/gui/gtk.c
Labels: bugfix, difficulty: trivial, scope: UI

#15140 Let's keep track of OpenCL unified memory
  src/common/opencl.c
  src/common/opencl.h
Labels: scope: hardware support, scope: codebase

#15147 introduce dt_view_get_current
  src/common/camera_control.c
  src/common/colorlabels.c
  src/common/history.c
  src/common/image.c
  src/common/ratings.c
  src/common/styles.c
  src/develop/develop.c
  src/dtgtk/thumbnail.c
  src/dtgtk/thumbtable.c
  src/gui/accelerators.c
  src/gui/gtk.c
  src/libs/export.c
  src/libs/histogram.c
  src/libs/ioporder.c
  src/libs/metadata_view.c
  src/libs/tagging.c
  src/libs/tools/global_toolbox.c
  src/views/view.c
  src/views/view.h
Labels: priority: low, difficulty: trivial, scope: codebase
