Repository darktable-org/darktable, pull requests merged in 2023-12, with the labels that each got.

#15794 Change the default setting that we forgot to change after option renaming
  data/darktableconfig.xml.in
Labels: bugfix

#15789 fix presets GUI when called from preference dialog.
  src/develop/imageop.c
  src/develop/imageop.h
  src/gui/presets.c
Labels: priority: low, documentation-pending

#15801 update translation zh_TW
  po/zh_TW.po
Labels: scope: translation / strings

#15800 darkroom: increase distance between search icon and entry
  data/themes/darktable.css
Labels: priority: low, scope: UI

#15768 po/piwigo filename ext
  src/common/utility.c
  src/common/utility.h
  src/imageio/storage/piwigo.c
Labels: bugfix

#15810 Ensure valid thumb->zoom_100
  src/dtgtk/thumbnail.c
Labels: bugfix

#15742 Enforce struct aligning in rgbcurve
  src/common/curve_tools.h
  src/gui/draw.h
  src/iop/rgbcurve.c
Labels: bugfix, priority: high

#15820 Apply curve_lut in rgbcurve process*()
  src/iop/rgbcurve.c
Labels: bugfix, priority: high

#15807 style history merge
  src/common/history.c
Labels: bugfix, priority: high, scope: codebase

#15818 [GUI] Better placement and font style for the warning in manage module layout window
  data/themes/darktable.css
Labels: priority: low, scope: UI

#15828 add 'Arial Unicode MS' font for glyphs
  data/themes/darktable-elegant-darker.css
  data/themes/darktable.css
Labels: bugfix, scope: macos support

#15827 collection: Always sort ascending on version number.
  src/common/collection.c
Labels: bugfix, priority: medium, scope: UI

#15830 OpenCL double platforms safety check
  src/common/opencl.c
Labels: bugfix, OpenCL

#15836 Highlighting keyboard shortcut changes in macOS version
  RELEASE_NOTES.md
Labels: scope: macos support

#15834 Fix some OpenCL error conditions
  src/common/interpolation.c
  src/iop/ashift.c
  src/iop/basecurve.c
  src/iop/censorize.c
  src/iop/colorbalancergb.c
  src/iop/colormapping.c
  src/iop/globaltonemap.c
  src/iop/lowpass.c
  src/iop/rawoverexposed.c
  src/iop/shadhi.c
Labels: bugfix, priority: high, OpenCL

#15844 CMake: do not tweak find library suffixes for Windows
  CMakeLists.txt
Labels: scope: windows support

#15848 Bugfix: some demosaicer OpenCL error conditions
  src/common/opencl.c
  src/iop/demosaicing/basics.c
  src/iop/demosaicing/vng.c
  src/iop/demosaicing/xtrans.c
Labels: bugfix, OpenCL

#15850 Enforce tone-equalizer pipe-cache data
  src/iop/toneequal.c
Labels: bugfix

#15858 Keep folder when doing copy&import.
  src/control/jobs/control_jobs.c
Labels: bugfix, priority: low, reproduce: confirmed

#15845 macOS: Fix wrong DPI value detected by gtk/gdk
  src/gui/gtk.c
  src/gui/gtk.h
  src/osx/osx.h
  src/osx/osx.mm
  src/views/darkroom.c
Labels: scope: macos support

#15864 Update es.po
  po/es.po
Labels: scope: translation / strings

#15866 Update ja.po
  po/ja.po
Labels: scope: translation / strings

#15871 Ukrainian translation update: shorten the translated name of the module
  po/uk.po
Labels: scope: translation / strings

#15868 Only test raw files as group representative while importing
  src/common/image.c
Labels: bugfix, priority: medium

#15874 Fix avoid colorshift for raw CA correction
  src/iop/cacorrect.c
Labels: bugfix, priority: medium, scope: image processing

#15875 Spanish translation update
  po/es.po
Labels: scope: translation / strings

#15877 Reviewed italian translations
  po/it.po
Labels: scope: translation / strings

#15878 Fix change of group leader during additional import
  src/common/image.c
Labels: bugfix, priority: high

#15870 conf: check also for symlink as a possible path.
  src/control/conf.c
  src/imageio/imageio.c
  src/libs/import.c
Labels: bugfix, priority: high

#15855 Update pl.po
  po/pl.po
Labels: scope: translation / strings

#15885 Avoid roi_in over-expanding
  src/iop/demosaic.c
  src/iop/finalscale.c
Labels: bugfix, priority: medium, scope: image processing

#15924 Spanish translation update: some fixes
  po/es.po
Labels: scope: translation / strings

#15925 Fix memory leaks in imageio_qui
  src/imageio/imageio_qoi.c
Labels: bugfix, priority: low

#15918 Deduplicate hashing code
  src/common/darktable.h
  src/develop/develop.c
  src/develop/develop.h
  src/develop/imageop.c
  src/develop/masks.h
  src/develop/pixelpipe_cache.c
  src/develop/pixelpipe_cache.h
  src/develop/pixelpipe_hb.c
  src/develop/pixelpipe_hb.h
  src/iop/ashift.c
  src/iop/clipping.c
  src/iop/colorreconstruction.c
  src/iop/crop.c
  src/iop/globaltonemap.c
  src/iop/hazeremoval.c
  src/iop/highlights.c
  src/iop/hlreconstruct/opposed.c
  src/iop/lens.cc
  src/iop/levels.c
  src/iop/toneequal.c
  src/views/view.c
  src/views/view.h
Labels: scope: codebase

#15913 Update generate-translation.sh
  tools/release/generate-translation.sh
Labels: scope: translation / strings

#15696 tagging: sort tags case insensitive and unicode
  src/libs/collect.c
  src/libs/tagging.c
Labels: feature: enhancement, priority: medium, scope: DAM, release notes: pending

#15816 Remove unused mipmap functions
  src/common/mipmap_cache.c
  src/common/mipmap_cache.h
Labels: priority: low, scope: codebase

#15912 Remove thumbnail background animation for last active image
  data/themes/darktable.css
Labels: scope: UI

#15930 macOS: Add libraw package for homebrew build
  packaging/macosx/1_install_hb_dependencies.sh
Labels: scope: macos support

#15910 [V2] Optional full image processing in darkroom
  src/develop/develop.h
  src/develop/pixelpipe_hb.c
  src/iop/finalscale.c
  src/libs/duplicate.c
  src/libs/snapshots.c
  src/views/darkroom.c
  src/views/view.c
  src/views/view.h
Labels: feature: enhancement, priority: medium, scope: image processing, documentation-pending, release notes: pending

#15847 Subtle lens fixes
  src/iop/lens.cc
Labels: scope: codebase

#15944 Fix OpenMP for rgbe imageio loader
  src/imageio/imageio_rgbe.c
Labels: bugfix, priority: high, scope: image processing, scope: performance

#15887 [maintenance] Remove unused code in grain.c
  src/iop/grain.c
Labels: scope: codebase

#15900 Stabilize lighttable scrollbar
  src/dtgtk/thumbtable.c
Labels: bugfix, priority: medium

#15946 Some pixelpipe cleanup
  src/develop/develop.c
  src/develop/develop.h
  src/develop/pixelpipe_hb.c
  src/iop/ashift.c
  src/iop/borders.c
  src/iop/clipping.c
  src/iop/crop.c
  src/iop/demosaic.c
  src/iop/flip.c
  src/iop/iop_api.h
  src/iop/liquify.c
  src/iop/rotatepixels.c
Labels: scope: codebase

#15962 Update es.po
  po/es.po
Labels: scope: translation / strings

#15958 Simplify interpolation api
  src/common/interpolation.c
  src/common/interpolation.h
  src/common/mipmap_cache.c
  src/develop/imageop_math.c
  src/develop/imageop_math.h
  src/develop/pixelpipe_hb.c
  src/iop/demosaic.c
  src/iop/finalscale.c
Labels: bugfix, scope: image processing, scope: codebase

#15964 styles: Fix wrong SQL index for multi_name.
  src/common/styles.c
Labels: bugfix, priority: low, difficulty: trivial, scope: UI, release notes: pending

#15726 deduplicate processed_maximum usage
  src/develop/imageop_math.h
  src/iop/cacorrect.c
  src/iop/demosaicing/amaze.cc
  src/iop/demosaicing/lmmse.c
  src/iop/demosaicing/rcd.c
  src/iop/highlights.c
  src/iop/hlreconstruct/opposed.c
Labels: scope: codebase

#15977 Turkish translation update
  po/tr.po
Labels: scope: translation / strings

#15978 Various OpenCL related fixes
  src/common/opencl.c
  src/develop/blend.c
  src/develop/pixelpipe_hb.c
  src/develop/pixelpipe_hb.h
  src/iop/demosaicing/basics.c
  src/iop/demosaicing/rcd.c
  src/iop/demosaicing/vng.c
  src/iop/demosaicing/xtrans.c
  src/iop/rawprepare.c
Labels: bugfix, priority: high, OpenCL

#15986 de.po: fix illegal character
  po/de.po
Labels: bugfix

#15987 Possibly fixing lut3d issues
  src/iop/lut3d.c
Labels: bugfix, OpenCL

#15983 tagging: implement natural sort
  src/libs/collect.c
  src/libs/tagging.c
Labels: bugfix, priority: low, feature: redesign, scope: UI

#15990 Bugfix: guides exposing
  src/iop/ashift.c
  src/views/darkroom.c
Labels: bugfix, priority: low, scope: UI

#15992 maintenance: improved alignment to cache lines
  src/common/cache.c
  src/common/camera_control.c
  src/common/darktable.c
  src/common/darktable.h
  src/common/distance_transform.c
  src/common/dttypes.h
  src/common/focus_peaking.h
  src/common/heal.c
  src/common/histogram.c
  src/common/interpolation.c
  src/common/iop_profile.c
  src/common/mipmap_cache.c
  src/common/nlmeans_core.c
  src/common/opencl.c
  src/common/tea.h
  src/develop/develop.c
  src/develop/imageop.h
  src/develop/masks/path.c
  src/develop/pixelpipe_cache.c
  src/develop/pixelpipe_hb.c
  src/develop/tiling.c
  src/imageio/format/exr.cc
  src/imageio/format/jpeg.c
  src/imageio/format/pdf.c
  src/imageio/format/png.c
  src/imageio/imageio.c
  src/imageio/imageio_jpeg.c
  src/imageio/imageio_png.c
  src/iop/basicadj.c
  src/iop/blurs.c
  src/iop/channelmixerrgb.c
  src/iop/colorbalance.c
  src/iop/colorbalancergb.c
  src/iop/colorchecker.c
  src/iop/colorin.c
  src/iop/colorout.c
  src/iop/colorreconstruction.c
  src/iop/demosaicing/vng.c
  src/iop/diffuse.c
  src/iop/filmicrgb.c
  src/iop/gaussian_elimination.h
  src/iop/hazeremoval.c
  src/iop/hlreconstruct/opposed.c
  src/iop/hlreconstruct/segmentation.c
  src/iop/lens.cc
  src/iop/liquify.c
  src/iop/lut3d.c
  src/iop/rawoverexposed.c
  src/iop/rgbcurve.c
  src/iop/toneequal.c
  src/libs/histogram.c
  src/tests/cache.c
  src/views/tethering.c
Labels: scope: codebase
