Repository darktable-org/darktable, pull requests merged in 2023-10, with the labels that each got.

#15354 Ensure ui_last/import_last_directory is sanitized.
  data/darktableconfig.xml.in
  src/control/conf.c
  src/control/conf.h
  src/libs/import.c
  tools/generate_darktablerc_conf.xsl
Labels: bugfix, priority: high, scope: DAM, scope: codebase

#15357 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#15360 macOS: Set ninja as build generator for homebrew builds
  packaging/macosx/2_build_hb_darktable_default.sh
Labels: scope: macos support

#15362 RFC: possibly a crawler bug
  src/control/crawler.c
Labels: bugfix, priority: high, scope: DAM

#15364 refactor zoom and position handling and 2nd preview
  src/common/colorspaces.c
  src/common/focus.h
  src/common/image.c
  src/control/control.c
  src/control/control.h
  src/control/jobs/develop_jobs.c
  src/control/settings.h
  src/develop/blend.c
  src/develop/blend_gui.c
  src/develop/develop.c
  src/develop/develop.h
  src/develop/imageop.c
  src/develop/imageop.h
  src/develop/masks.h
  src/develop/masks/brush.c
  src/develop/masks/circle.c
  src/develop/masks/ellipse.c
  src/develop/masks/gradient.c
  src/develop/masks/group.c
  src/develop/masks/masks.c
  src/develop/masks/path.c
  src/develop/pixelpipe_hb.c
  src/dtgtk/gradientslider.c
  src/gui/gtk.c
  src/iop/ashift.c
  src/iop/basicadj.c
  src/iop/channelmixerrgb.c
  src/iop/clipping.c
  src/iop/colorbalancergb.c
  src/iop/colorreconstruction.c
  src/iop/colorzones.c
  src/iop/crop.c
  src/iop/exposure.c
  src/iop/graduatednd.c
  src/iop/iop_api.h
  src/iop/liquify.c
  src/iop/primaries.c
  src/iop/rawoverexposed.c
  src/iop/retouch.c
  src/iop/rgblevels.c
  src/iop/spots.c
  src/iop/toneequal.c
  src/iop/vignette.c
  src/libs/navigation.c
  src/libs/snapshots.c
  src/views/darkroom.c
  src/views/slideshow.c
  src/views/view.c
Labels: priority: high, difficulty: hard, scope: UI, scope: codebase

#15342 Fix flicker effect while module gets focus
  src/develop/imageop.c
  src/views/darkroom.c
Labels: bugfix, priority: medium, scope: UI

#15300 Rewrite help section to comply with GNU CLI standards
  src/cli/main.c
  src/common/darktable.c
  src/config.cmake.h
Labels: difficulty: trivial, scope: CLI

#15372 fix crash when selecting a non supported icc profile
  src/libs/histogram.c
Labels: bugfix, priority: high, scope: color management, release notes: pending

#15369 Add noise profile for Sony ILCE 6700
  data/noiseprofiles.json
Labels: scope: noise profile

#15379 dt_tag_count_attached: New routine to get only the count of tag.
  src/common/tags.c
  src/common/tags.h
Labels: scope: DAM, scope: codebase

#15380 [CI/CD] Bring back the temporarily removed libopenexr-dev for the AppImage build
  .github/workflows/nightly.yml
Labels: scope: codebase

#15389 Some fixes of '--version' code and output
  src/common/darktable.c
Labels: scope: CLI

#15373 RFC: Extend preference "create sidecar files: after edit"
  data/darktableconfig.xml.in
  src/common/image.c
Labels: priority: low, feature: redesign, scope: DAM, documentation-pending, release notes: pending

#15395 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#15399 [CI] Remove the macOS 11 build from CI
  .github/workflows/ci.yml
Labels: scope: macos support

#15392 po/collect sorting - full rework of the collect display/sorting/order
  data/darktableconfig.xml.in
  po/darktable.pot
  po/fr.po
  src/common/collection.c
  src/libs/collect.c
  src/libs/filters/camera.c
  src/libs/filters/lens.c
Labels: bugfix, priority: medium, feature: redesign, scope: DAM, release notes: pending

#15400 macOS: Fix several shift-scrollwheel issues
  src/gui/gtk.c
  src/libs/geotagging.c
  src/libs/histogram.c
Labels: bugfix, release notes: pending, scope: macos support

#15371 imageio: OpenMP accelerate TIFF and JP2 export
  src/imageio/format/j2k.c
  src/imageio/format/tiff.c
Labels: scope: performance

#15401 [GUI] The rating range filter tooltip optimization (removing MasterYoda-ism)
  src/libs/filters/rating_range.c
Labels: scope: translation / strings, scope: UI

#15104 sigmoid: introduce custom primaries ("AgX-like" processing)
  data/kernels/sigmoid.cl
  src/iop/sigmoid.c
Labels: priority: medium, feature: new, difficulty: average, scope: image processing, scope: color management, documentation-pending, release notes: pending

#15347 macOS: Request classic linker for Xcode15
  CMakeLists.txt
Labels: bugfix, scope: macos support

#15403 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#15408 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#15406 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#15407 [UI] Dont show equiv focal length when crop factor is unknown
  src/libs/metadata_view.c
Labels: scope: UI

#15377 [imageio] Implementation of export to email in Windows
  src/imageio/storage/email.c
Labels: scope: DAM, scope: windows support

#15410 [imageio] implement export to email on macOS
  src/imageio/storage/email.c
Labels: scope: macos support

#15294 Backthread calculating mipmaps while in lighttable without user activity
  data/darktableconfig.xml.in
  src/common/darktable.c
  src/common/darktable.h
  src/common/database.c
  src/common/history.c
  src/common/image.c
  src/common/import_session.c
  src/common/undo.c
  src/control/control.h
  src/control/crawler.c
  src/control/crawler.h
  src/dtgtk/thumbtable.c
  src/imageio/imageio.c
  src/libs/import.c
  src/views/view.c
Labels: priority: low, feature: new, difficulty: hard, scope: DAM, documentation-pending, release notes: pending

#15413 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#15414 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#15418 Update de.po
  po/de.po
Labels: scope: translation / strings

#15432 update zh_TW translation
  po/zh_TW.po
Labels: scope: translation / strings

#15433 Spanish translation update
  po/es.po
Labels: scope: translation / strings

#15417 Some more legacy_presets removal.
  src/common/database.c
  src/common/metadata.c
Labels: difficulty: trivial, scope: DAM, scope: codebase

#15423 Fixing a log error in interpolation
  src/common/interpolation.c
Labels: priority: medium, scope: codebase

#15434 [GUI] Correct a typo in the settings tooltip
  data/darktableconfig.xml.in
Labels: scope: translation / strings

#15415 [GUI] Make strings with the correct dir separator under Windows
  src/common/database.c
Labels: scope: UI

#15431 [GUI] Fix spelling of B&W and 4K (should use uppercase letters)
  data/darktableconfig.xml.in
  src/common/mipmap_cache.c
  src/imageio/format/tiff.c
Labels: scope: translation / strings

#15438 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#15440 Update fi.po
  po/fi.po
Labels: scope: translation / strings

#15437 fix scripts_installer handling user names with spaces on windows
  RELEASE_NOTES.md
  data/luarc
Labels: bugfix, lua, scope: windows support

#15442 [CI/CD] Switch the macOS nightly build to macOS 12
  .github/workflows/nightly.yml
Labels: scope: macos support

#15426 Bufix: Safe duplicate version
  src/common/image.c
Labels: bugfix, priority: medium

#15449 macOS: avoid linker warning
  CMakeLists.txt
Labels: scope: macos support

#15451 Fix backthumbs crawler
  src/dtgtk/thumbtable.c
  src/views/darkroom.c
Labels: bugfix, priority: high

#15443 BUGFIX: Extended GPS coordinate import to support just decimal value in .xmp fixes #15444 …
  src/common/utility.c
  src/develop/lightroom.c
Labels: bugfix, priority: high, scope: DAM, scope: codebase

#15428 lighttable : speedup scrolling
  src/dtgtk/thumbnail.c
  src/dtgtk/thumbnail.h
  src/dtgtk/thumbtable.c
  src/dtgtk/thumbtable.h
Labels: feature: enhancement, priority: high, difficulty: hard, scope: UI, scope: performance

#15452 Fixes to darktable help text
  src/common/darktable.c
Labels: scope: CLI

#15455 Updates to pt_BR
  po/pt_BR.po
Labels: scope: image processing

#15454 thumbtable: Remove two g_list_length calls in loop.
  src/dtgtk/thumbtable.c
Labels: priority: medium, scope: DAM, scope: performance

#15468 [imageio] [DAM] Calculate the sensor crop factor for Canon cameras
  src/common/exif.cc
Labels: scope: DAM

#15462 Thumbtable glist improve
  src/dtgtk/culling.c
  src/dtgtk/thumbnail.c
  src/dtgtk/thumbnail.h
  src/dtgtk/thumbtable.c
  src/libs/duplicate.c
Labels: bugfix, feature: enhancement, difficulty: hard, scope: UI, scope: performance

#15474 g_timeout_add... fct return a guint not a int
  src/develop/blend.h
  src/dtgtk/thumbnail.h
  src/dtgtk/thumbtable.h
  src/libs/import.c
  src/libs/snapshots.c
  src/libs/tagging.c
  src/views/map.c
Labels: bugfix, priority: high, scope: codebase

#15472 rgb primaries: enhancements
  src/iop/primaries.c
Labels: feature: enhancement, scope: image processing

#15479 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#15453 Allow choosing basis for border width calculation
  src/iop/borders.c
Labels: feature: enhancement, priority: low, scope: image processing

#15484 Update de.po
  po/de.po
Labels: scope: translation / strings

#15483 Fix crash when trying to calculate crop factor from sensor pixel dimensions and resolution
  src/common/exif.cc
Labels: bugfix, priority: high, scope: DAM

#15487 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#15492 Update de.po
  po/de.po
Labels: scope: translation / strings

#15496 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#15500 fix crash when entering Chinese in bauhaus popup
  src/bauhaus/bauhaus.c
Labels: bugfix, scope: translation / strings, priority: high, difficulty: trivial, scope: windows support

#15497 Rework temperature and channelmixerrgb
  src/develop/develop.c
  src/develop/develop.h
  src/develop/imageop.c
  src/iop/channelmixerrgb.c
  src/iop/temperature.c
  src/libs/history.c
  src/views/darkroom.c
Labels: scope: color management, scope: codebase

#15498 Update darktable.bundle for gtk-keys.css
  packaging/macosx/darktable.bundle
Labels: scope: macos support

#15459 Add substitution variables for crop factor and 35 mm equivalent focal length
  src/common/variables.c
  src/gui/gtkentry.c
Labels: priority: low, difficulty: trivial, scope: DAM, documentation-pending, release notes: pending

#15495 Fix the text of one of the choices in initial dialog for "copy & import"
  src/libs/import.c
Labels: scope: translation / strings, priority: low, scope: UI

#15503 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#15504 Update de.po
  po/de.po
Labels: scope: translation / strings

#15509 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#15506 Restrict effect of operation_tags_filter() & operation_tags()
  src/develop/develop.c
  src/develop/pixelpipe.h
  src/develop/pixelpipe_cache.c
  src/develop/pixelpipe_hb.c
  src/iop/ashift.c
  src/iop/crop.c
  src/iop/retouch.c
Labels: bugfix, priority: high, scope: UI

#15507 Simplify importance_hint
  src/develop/develop.c
  src/develop/develop.h
  src/develop/imageop.c
  src/develop/imageop.h
  src/develop/pixelpipe_hb.c
Labels: scope: codebase

#15515 Add timing info to dt_dev_pixelpipe_synch_all
  src/develop/pixelpipe_hb.c
Labels: scope: codebase

#15514 de: fix unfinished sentence in sigmoid tooltip
  po/de.po
Labels: scope: translation / strings

#15510 [GUI] Fix misspelling of the word 'illuminant'
  src/iop/channelmixerrgb.c
Labels: scope: translation / strings

#15513 Disable highlights reconstruction for non-supported monochromes
  src/iop/highlights.c
Labels: bugfix, priority: high, scope: image processing

#15517 fix infinite "working..." on colorpicker
  src/develop/develop.c
Labels: bugfix, priority: high, difficulty: trivial

#15534 Update de.po
  po/de.po
Labels: scope: translation / strings

#15535 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#15532 duplicate : copy also camera_id in the database
  src/common/image.c
Labels: bugfix, difficulty: trivial, scope: DAM

#15529 filtering : ensure filter initialization with 0
  src/libs/filtering.c
Labels: bugfix, difficulty: trivial

#15526 fix darkroom center view scrollbar update loop
  src/gui/gtk.c
  src/views/view.c
Labels: bugfix

#15525 lighttable : fix crash in zoomable
  src/dtgtk/thumbtable.c
  src/dtgtk/thumbtable.h
Labels: bugfix, difficulty: average, scope: UI

#15531 clear snapshot buffer pointer after releasing
  src/libs/snapshots.c
Labels: bugfix, priority: high, scope: UI

#15539 Update fi.po
  po/fi.po
Labels: scope: translation / strings
