Repository darktable-org/darktable, pull requests merged in 2023-11, with the labels that each got.

#15523 exif: no need to extra sanitize IPTC date and time
  src/common/datetime.c
  src/common/exif.cc
Labels: bugfix, priority: medium, scope: DAM

#15536 Fix bug in variable expansion due to incorrect match order
  src/common/variables.c
  src/gui/gtkentry.c
Labels: bugfix, priority: high, scope: DAM, scope: codebase

#15527 imageio: tweak support for CICP mistagged sRGB files (AVIF/HEIF/PNG)
  src/common/colorspaces.c
  src/imageio/format/avif.c
  src/imageio/imageio_avif.c
  src/imageio/imageio_heif.c
Labels: bugfix, priority: low

#15518 [imageio] [DAM] Fix getting sensor pixel dimensions for DNG files
  src/common/exif.cc
Labels: bugfix, priority: medium, scope: image processing

#15548 Fix framing basis regression #15545
  src/iop/borders.c
Labels: bugfix, priority: high, difficulty: trivial, scope: image processing, scope: codebase

#15544 po/fix borders - fix border alignments
  src/CMakeLists.txt
  src/develop/borders_helper.c
  src/develop/borders_helper.h
  src/iop/borders.c
  src/iop/useless.c
Labels: bugfix, priority: medium, scope: image processing

#15516 Another round of OpenCL stability fixes
  src/common/darktable.c
  src/common/darktable.h
  src/common/opencl.c
  src/common/opencl.h
Labels: bugfix, priority: high, scope: performance

#15550 Bugfix: cacorrect avoid colorshift
  src/iop/cacorrect.c
Labels: bugfix, priority: high, scope: image processing, release notes: pending

#15553 [imageio] Avoid crash with jxl files without Exif
  src/imageio/imageio_jpegxl.c
Labels: bugfix, priority: high, scope: DAM

#15555 fix crash in slideshow
  src/develop/develop.c
Labels: bugfix, scope: codebase

#15558 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#15559 [imageio] Add extensions to "get type from extension" lists
  src/imageio/imageio.c
Labels: feature: enhancement, priority: low

#15560 [GUI] The most common spelling of "bit depth" is without a hyphen
  src/iop/dither.c
  src/iop/lut3d.c
Labels: scope: translation / strings

#15557 use dt_print macros to avoid calling when inactive
  src/common/darktable.c
  src/common/darktable.h
  src/develop/pixelpipe_hb.c
  src/develop/pixelpipe_hb.h
  src/iop/cacorrect.c
  src/views/view.c
Labels: priority: low, scope: codebase

#15563 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#15564 Update de.po
  po/de.po
Labels: scope: translation / strings

#15570 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#15476 exif: detect correct orientation for Sinar backs
  src/common/exif.cc
Labels: depends: rawspeed

#15567 snapshots: Remove snapshots for removed images.
  src/common/image.c
  src/control/signal.c
  src/control/signal.h
  src/libs/snapshots.c
Labels: bugfix, priority: high, release notes: pending

#15582 Fix dt_view_get_view_context()
  src/views/view.c
Labels: bugfix

#15584 Fix median9f aligning
  src/iop/cacorrect.c
  src/iop/demosaicing/lmmse.c
Labels: bugfix, priority: medium, scope: image processing, scope: performance

#15581 refactor iop module skipping code
  src/develop/develop.c
  src/develop/imageop.c
  src/develop/imageop.h
  src/develop/pixelpipe_cache.c
  src/develop/pixelpipe_hb.c
  src/iop/ashift.c
Labels: scope: codebase

#15586 make distort functions return a gboolean
  src/develop/develop.c
  src/develop/develop.h
  src/develop/imageop.c
  src/iop/ashift.c
  src/iop/borders.c
  src/iop/clipping.c
  src/iop/crop.c
  src/iop/flip.c
  src/iop/iop_api.h
  src/iop/lens.cc
  src/iop/liquify.c
  src/iop/rawprepare.c
  src/iop/rotatepixels.c
  src/iop/scalepixels.c
  src/iop/useless.c
Labels: scope: codebase

#15588 Text corrections
  src/common/database.c
  src/common/math.h
  src/dtgtk/culling.c
  src/imageio/imageio.c
  src/iop/profile_gamma.c
  src/iop/rawprepare.c
  src/iop/useless.c
  src/libs/snapshots.c
Labels: scope: codebase

#15594 Fix the list of debug print options in the help text to reflect the ones that are actually supported
  src/common/darktable.c
Labels: scope: CLI

#15546 smoothly switch crop on/off part II
  src/develop/develop.c
  src/develop/develop.h
  src/gui/color_picker_proxy.c
  src/gui/gtk.c
  src/gui/gtk.h
  src/iop/crop.c
  src/libs/duplicate.c
  src/libs/lib.h
  src/libs/snapshots.c
  src/views/darkroom.c
  src/views/slideshow.c
  src/views/view.c
  src/views/view.h
Labels: bugfix, feature: enhancement, priority: high, difficulty: hard

#15597 fix segfault on tiny RoI
  src/iop/colorbalance.c
  src/iop/colorin.c
  src/iop/colorout.c
Labels: bugfix, priority: high, scope: image processing

#15591 Update noiseprofiles.json for Nikon Zf
  data/noiseprofiles.json
Labels: scope: noise profile

#15576 wb_presets: add Sony ILCE-7CM2
  data/wb_presets.json
Labels: scope: camera support

#15603 Fix --verion output when Lua is disabled
  src/common/darktable.c
Labels: difficulty: trivial, scope: CLI

#15604 fix modulegroups preset use after free
  src/libs/modulegroups.c
Labels: bugfix, difficulty: trivial

#15599 Visualize mask in developer mode
  data/darktableconfig.xml.in
  src/iop/gamma.c
Labels: priority: medium, feature: new, scope: image processing

#15605 Some debug log improvements
  src/develop/blend.c
  src/iop/hlreconstruct/opposed.c
Labels: scope: codebase

#15593 add missing history lock when switching images
  src/develop/develop.c
  src/iop/liquify.c
  src/views/darkroom.c
Labels: bugfix, priority: high

#15610 Add a gettext context to the Export action button
  src/libs/export.c
Labels: scope: translation / strings

#15612 Bugfix: blend feathering
  src/common/box_filters.c
  src/common/guided_filter.c
  src/develop/blend.c
Labels: priority: high, difficulty: hard, scope: image processing, bug: pending

#15618 fix color assessment borders on macos
  src/views/view.c
Labels: bugfix, priority: high, scope: UI

#15617 switch vignetting module off when crop focused
  src/iop/vignette.c
Labels: bugfix, scope: UI

#15619 Introduce dt_get_debug_wtime()
  src/common/cache.c
  src/common/darktable.h
  src/common/opencl.c
  src/develop/masks/brush.c
  src/develop/masks/circle.c
  src/develop/masks/ellipse.c
  src/develop/masks/gradient.c
  src/develop/masks/group.c
  src/develop/masks/path.c
  src/develop/pixelpipe_hb.c
  src/dtgtk/culling.c
  src/dtgtk/thumbtable.c
  src/views/lighttable.c
  src/views/view.c
Labels: scope: performance, scope: codebase

#15609 sigmoid custom primaries: enhancements and release note entry
  RELEASE_NOTES.md
  data/kernels/sigmoid.cl
  src/iop/sigmoid.c
Labels: feature: enhancement, scope: image processing, scope: color management

#15629 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#15628 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#15623 Update de.po
  po/de.po
Labels: scope: translation / strings

#15631 fix openstreetmap location search string
  data/darktableconfig.xml.in
  src/libs/location.c
Labels: bugfix, priority: medium, difficulty: trivial, scope: UI

#15633 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#15606 don't place tooltip window if not moved
  src/gui/accelerators.c
  src/libs/tools/global_toolbox.c
  src/views/darkroom.c
Labels: bugfix, priority: low, scope: UI

#15639 Update fi.po
  po/fi.po
Labels: scope: translation / strings

#15635 Correct tiling requirements for blending
  src/develop/blend.c
Labels: bugfix, scope: image processing

#15634 Guided filter OpenCL fixes
  data/kernels/blendop.cl
  data/kernels/guided_filter.cl
  src/common/guided_filter.c
Labels: bugfix, priority: high, scope: image processing, scope: hardware support

#15638 Bugfix: OpenCL issues with details mask & dual demosaic
  data/kernels/demosaic_rcd.cl
  src/develop/blend.c
  src/develop/blend.h
  src/develop/pixelpipe_hb.c
  src/iop/demosaicing/dual.c
Labels: bugfix, priority: high, scope: image processing, scope: hardware support

#15620 po/record harmony guide xmp
  po/POTFILES.in
  src/CMakeLists.txt
  src/common/color_harmony.c
  src/common/color_harmony.h
  src/common/database.c
  src/common/exif.cc
  src/common/image.c
  src/common/image.h
  src/common/image_cache.c
  src/libs/histogram.c
Labels: feature: enhancement, priority: medium, scope: DAM, release notes: pending

#15641 Update de.po
  po/de.po
Labels: scope: translation / strings

#15640 [imageio] Allow fallback method to obtain the crop factor if tag for EFL contains zero
  src/common/exif.cc
Labels: feature: enhancement, scope: DAM

#15642 don't show inactive picker under snapshot overlay
  src/develop/develop.h
  src/develop/imageop.c
  src/develop/imageop.h
  src/develop/masks/masks.c
  src/gui/color_picker_proxy.c
  src/iop/ashift.c
  src/iop/channelmixerrgb.c
  src/iop/crop.c
  src/iop/graduatednd.c
  src/iop/liquify.c
  src/iop/retouch.c
  src/iop/toneequal.c
  src/iop/vignette.c
  src/views/darkroom.c
Labels: bugfix

#15651 avoid recalc when scrollbar updated with current position
  src/gui/gtk.c
  src/gui/gtk.h
  src/views/view.c
Labels: bugfix, priority: high

#14503 [imageio] Implementation of optional rejection of all non-raw files instead of JPEG files
  data/darktableconfig.xml.in
  src/common/image.c
  src/common/image.h
  src/imageio/imageio.c
  src/imageio/imageio_common.h
  src/libs/import.c
Labels: bugfix, priority: medium, scope: DAM, release notes: pending

#15654 exif: prettify Tamron lenses
  src/common/exif.cc
Labels: scope: camera support

#15652 OpenCL guided filter (III)
  data/kernels/guided_filter.cl
  src/common/guided_filter.c
  src/develop/blend.c
Labels: bugfix, priority: high, scope: image processing, scope: hardware support, release notes: pending

#15657 [Nightly builds]: require C++17 for curve tool on macOS
  tools/basecurve/CMakeLists.txt
Labels: scope: macos support

#15658 [macOS]: enable curve and noise tools for homebrew
  packaging/macosx/2_build_hb_darktable_default.sh
Labels: scope: macos support

#12760 Olympus embedded metadata lens correction
  src/common/exif.cc
  src/common/image.c
  src/common/image.h
  src/iop/lens.cc
Labels: scope: camera support, release notes: pending

#15644 po/toneeq & distort modules
  src/common/luminance_mask.h
  src/control/signal.c
  src/control/signal.h
  src/develop/develop.c
  src/develop/develop.h
  src/develop/imageop.c
  src/iop/crop.c
  src/iop/toneequal.c
Labels: bugfix, priority: high, scope: UI, scope: image processing, release notes: pending

#15653 imageio: reshuffle EFL fallback retrieval methods
  src/common/exif.cc
Labels: bugfix, priority: low

#15661 Fix usage of raw chromatic aberrations for RGBY bayer sensors
  src/common/image.c
  src/common/image.h
  src/iop/cacorrect.c
Labels: bugfix, priority: medium, scope: image processing

#15627 [imageio] Exposing chroma subsampling control in JPEG export
  src/imageio/format/jpeg.c
Labels: feature: enhancement, priority: low, scope: image processing, release notes: pending

#15675 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#15676 Update de.po
  po/de.po
Labels: scope: image processing

#15677 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#15664 Fix cacorrect multithreading
  src/iop/cacorrect.c
Labels: bugfix, priority: high, scope: image processing

#15678 Show an error message window when we can't run due to too new database version
  src/common/database.c
Labels: bugfix, scope: codebase

#15683 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#15682 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#15681 Code maintenance for colorbalancergb LUT lookup
  data/kernels/extended.cl
  src/iop/colorbalancergb.c
Labels: bugfix, scope: codebase

#15684 Add path suffix for opencl-c.h
  CMakeLists.txt
Labels: bugfix, scope: codebase

#15693 [imageio] [DAM] Hardcode the crop factor for the handful of cameras for which we can't calculate it correctly
  src/common/exif.cc
  src/common/exif.h
Labels: bugfix, scope: camera support

#15691 Bugfix: blending OpenCL requirements
  src/develop/blend.c
  src/develop/pixelpipe_hb.c
Labels: bugfix

#15698 Fix the text in the compile options section of the --version output
  src/common/darktable.c
Labels: bugfix, scope: CLI

#15705 fix collection filter title label truncating
  src/libs/filtering.c
Labels: bugfix, priority: low, scope: UI

#15706 [GUI] Fixes to Piwigo export tooltips
  src/imageio/storage/piwigo.c
Labels: bugfix, scope: translation / strings, scope: UI

#15712 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#15713 Fix NULL pointer dereference when dragging on background in zoomable lighttable
  src/dtgtk/thumbtable.c
Labels: bugfix, reproduce: confirmed, scope: DAM, scope: codebase

#15714 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#15710 Fix feathering Part V - use modified feather weight and eps
  src/common/math.h
  src/develop/blend.c
  src/develop/blend.h
  src/develop/blend_gui.c
Labels: bugfix, scope: image processing, scope: codebase

#15719 Fix demosaicing mode for tiny roi_out sizes
  src/iop/demosaic.c
Labels: bugfix

#15721 Safe improvement of rcd demosaic cpu performance
  src/iop/demosaicing/rcd.c
Labels: bugfix, scope: image processing, scope: performance

#15717 [GUI] Fix text in framing module for better accuracy
  src/iop/borders.c
Labels: scope: translation / strings, scope: UI

#15718 Fix various highlights issues
  src/iop/highlights.c
Labels: bugfix

#15725 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#15728 [GUI] Fix a couple more tooltips for better wording
  src/iop/filmic.c
  src/iop/filmicrgb.c
Labels: scope: translation / strings

#15729 preferences: use consistent wording for thumbnails
  data/darktableconfig.xml.in
Labels: scope: translation / strings

#15734 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#15731 reword auto-save preference
  data/darktableconfig.xml.in
Labels: scope: translation / strings

#15732 preferences: make xmp descriptions consistent
  data/darktableconfig.xml.in
Labels: scope: translation / strings

#15733 [macOS]: fix libgphoto2 paths for homebrew build
  packaging/macosx/3_make_hb_darktable_package.sh
Labels: bugfix, scope: macos support

#15736 daterange : fix wrong date casting in windows
  src/dtgtk/range.c
  src/libs/filters/date.c
Labels: bugfix, priority: high, difficulty: trivial, scope: DAM

#15740 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#15738 fix dt_print perf and verbose checks
  src/common/darktable.h
Labels: bugfix, priority: medium

#15745 [GUI] Reword failed tiling message to make it more clear what the user should expect
  src/develop/tiling.c
Labels: scope: translation / strings

#15739 don't trigger unnecessary workings on zoom bounds
  src/develop/develop.c
  src/views/darkroom.c
Labels: bugfix, priority: low

#15751 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#15750 Fix ashift crashes while removing lines
  src/iop/ashift.c
Labels: bugfix

#15758 Update de.po
  po/de.po
Labels: scope: translation / strings

#15759 Fix matching DNG file extension (this will ensure that it is not ignored as non-raw)
  src/common/image.c
Labels: bugfix, priority: high, understood: clear

#15760 Update translation zh_TW.po
  po/zh_TW.po
Labels: scope: translation / strings

#15765 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#15770 [GUI] Tooltip text improvements in AVIF export
  src/imageio/format/avif.c
Labels: scope: translation / strings

#15769 noiseprofile for Canon IXY 220F and Pentax ist D5
  data/noiseprofiles.json
Labels: scope: noise profile

#15767 darktable.css: Adjust overlay UI.
  data/themes/darktable.css
Labels: feature: enhancement, scope: UI

#15301 imageio_libraw: double check Canon CR3 model support
  src/imageio/imageio_libraw.c
Labels: scope: camera support, scope: software support, depends: libraw

#15776 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#15778 imageio_jxl: future proof for upcoming libjxl API
  src/imageio/format/jxl.c
Labels: scope: software support

#15777 basecurve: tweak cmake check for exiv2 version
  tools/basecurve/CMakeLists.txt
Labels: scope: codebase

#15779 imageio_jxl: workaround for missing v0.7 version macros
  src/imageio/format/jxl.c
Labels: bugfix, priority: high, scope: software support

#15781 [GUI] Rename spot mapping to area mapping as a spot is always small area by definition
  src/iop/channelmixerrgb.c
  src/iop/exposure.c
Labels: scope: translation / strings

#15783 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#15784 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#15791 Update de.po
  po/de.po
Labels: scope: translation / strings
