Repository darktable-org/darktable, pull requests merged in 2023-05, with the labels that each got.

#14382 sq translation update
  po/sq.po
Labels: scope: translation / strings

#14383 colorbalancergb: improve vectorization and other optimizations
  src/common/colorspaces_inline_conversions.h
  src/common/dttypes.h
  src/common/math.h
  src/iop/colorbalancergb.c
Labels: scope: performance

#14384 liquify: add missing guard condition to avoid crash
  src/iop/liquify.c
Labels: bugfix, priority: high

#14380 Mostly fixes retouch opacity slider jumpy dragging
  src/bauhaus/bauhaus.c
  src/iop/retouch.c
Labels: bugfix, priority: medium, reproduce: peculiar

#14390 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#14391 [GUI] Fix text issues spotted by Besmir Godolja
  src/develop/blend_gui.c
  src/develop/lightroom.c
  src/gui/gtk.c
  src/imageio/storage/piwigo.c
  src/iop/lens.cc
  src/iop/sigmoid.c
  src/views/darkroom.c
Labels: scope: translation / strings

#14386 Some mask manager maintenance
  src/libs/masks.c
Labels: scope: codebase

#14396 Update de.po
  po/de.po
Labels: scope: translation / strings

#14395 nlmeans_core: fix crash due to unaligned memory access
  src/common/nlmeans_core.c
Labels: bugfix

#14399 Remove the implementation code of the function missing from ancient OS releases
  src/common/system_signal_handling.c
Labels: scope: codebase

#14401 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#14378 Add support for format in lib preset.
  src/develop/develop.c
  src/libs/filtering.c
  src/libs/ioporder.c
  src/libs/lib.c
  src/libs/lib.h
  src/libs/metadata.c
  src/libs/modulegroups.c
Labels: bugfix, priority: medium, scope: image processing, release notes: pending

#14400 Stop zoom and geo entries swallowing shortcuts
  src/libs/geotagging.c
  src/libs/tools/lighttable.c
Labels: priority: low, difficulty: trivial

#14397 colorcal: transpose color-adaptation matrices for vectorization
  src/common/chromatic_adaptation.h
  src/common/colorspaces_inline_conversions.h
  src/iop/channelmixerrgb.c
Labels: scope: performance, scope: codebase

#14407 Improved dt_print_pipe() interface
  src/common/interpolation.c
  src/common/mipmap_cache.c
  src/develop/blend.c
  src/develop/imageop.c
  src/develop/pixelpipe_cache.c
  src/develop/pixelpipe_hb.c
  src/develop/pixelpipe_hb.h
  src/iop/colorin.c
  src/iop/demosaic.c
  src/iop/demosaicing/basics.c
  src/iop/demosaicing/rcd.c
  src/iop/demosaicing/vng.c
  src/iop/demosaicing/xtrans.c
  src/iop/finalscale.c
Labels: feature: enhancement, scope: codebase

#14402 Rework the default modules for different workflows.
  src/develop/develop.c
  src/develop/imageop.c
  src/develop/imageop.h
  src/gui/presets.h
  src/iop/basecurve.c
  src/iop/channelmixerrgb.c
  src/iop/exposure.c
  src/iop/filmicrgb.c
  src/iop/sigmoid.c
Labels: priority: low, feature: redesign, scope: codebase

#14419 develop: Fix workflow auto presets when user's ones are defined.
  src/develop/develop.c
Labels: bugfix, priority: high, scope: codebase

#14413 FilmicRGB optimization
  src/common/gamut_mapping.h
  src/iop/filmicrgb.c
  src/tests/unittests/iop/test_filmicrgb.c
Labels: scope: performance

#14416 po/rework lib header label
  src/common/image.c
  src/libs/ioporder.c
  src/libs/lib.c
  src/libs/lib.h
Labels: bugfix, priority: high, difficulty: average, scope: UI

#14404 new mostly-vectorized dt_XYZ_2_JzAzBz and dt_JzAzBz_2_XYZ
  src/common/colorspaces_inline_conversions.h
Labels: bugfix

#14421 Make several color pickers shortcutable
  src/develop/blend_gui.c
  src/iop/borders.c
  src/iop/colorzones.c
  src/iop/negadoctor.c
  src/iop/retouch.c
  src/iop/rgbcurve.c
  src/iop/rgblevels.c
  src/iop/tonecurve.c
  src/iop/watermark.c
Labels: bugfix, difficulty: trivial, scope: UI, release notes: pending

#14420 [RFC] Explain in slider tooltip how to ignore soft limits
  src/gui/accelerators.c
Labels: feature: enhancement, priority: low, scope: UI, release notes: pending

#14426 denoise(profiled) optimizations: matrix mult, nontemporal writes, vectorization
  src/common/eaw.c
  src/iop/denoiseprofile.c
Labels: scope: performance

#14411 Pixelpipe cache maintenance again
  src/develop/pixelpipe_cache.c
  src/develop/pixelpipe_cache.h
  src/develop/pixelpipe_hb.c
  src/develop/pixelpipe_hb.h
Labels: scope: codebase

#14431 Update de.po
  po/de.po
Labels: scope: translation / strings

#14430 Fix "RGB parade" spelling in config to avoid histogram mode resetting
  data/darktableconfig.xml.in
Labels: bugfix, priority: medium, scope: codebase

#14432 Details mask refactoring and fixes
  src/develop/blend.c
  src/develop/masks.h
  src/develop/masks/detail.c
  src/develop/pixelpipe_cache.c
  src/develop/pixelpipe_hb.c
  src/develop/pixelpipe_hb.h
  src/iop/demosaic.c
  src/iop/demosaicing/dual.c
  src/iop/demosaicing/vng.c
Labels: bugfix, priority: medium, reproduce: random, scope: codebase

#14427 work around GPhoto2 crashing dt by disabling device scans during imports
  src/common/camera_control.c
  src/libs/import.c
Labels: bugfix

#14435 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#14434 filmicrgb: further optimize highlight reconsruction
  src/common/bspline.h
  src/iop/filmicrgb.c
Labels: scope: performance

#14437 po/conf enum no case
  src/control/conf.c
Labels: bugfix, priority: low

#14440 grain.c: optimize
  src/iop/grain.c
Labels: scope: performance

#14436 don't mark multi-level action path as translatable
  src/develop/blend_gui.c
Labels: bugfix, priority: medium, difficulty: trivial, scope: codebase

#14452 [GUI] Remove a capital letter that does not fit the style
  data/darktableconfig.xml.in
Labels: scope: translation / strings

#14456 [GUI] Don't show useless info on the legacy image flag
  src/libs/metadata_view.c
Labels: priority: low, feature: redesign, scope: DAM

#14442 Some details mask related fixes
  src/develop/blend.c
  src/develop/blend.h
  src/develop/masks/detail.c
  src/develop/pixelpipe_hb.c
  src/iop/demosaic.c
  src/iop/demosaicing/dual.c
  src/iop/demosaicing/vng.c
Labels: bugfix, priority: high, reproduce: confirmed, scope: hardware support, scope: codebase

#14459 presets: Properly use double for iso/exposure/aperture.
  src/common/presets.c
Labels: bugfix, priority: high, reproduce: confirmed, scope: DAM, release notes: pending

#14458 Update hidden module button sensitivity on shortcut
  src/gui/accelerators.c
  src/libs/lib.c
  src/libs/lib.h
Labels: bugfix, priority: high

#14463 box filters: tune optimization flags, tweak OpenMP directives
  src/common/box_filters.c
Labels: scope: performance

#14465 lib: Add missing support for mouse-leave event.
  src/libs/lib.c
Labels: feature: enhancement, priority: high, scope: UI, scope: DAM

#14461 borders.c: Allow w:h entry in bauhaus popup, direct user there for custom aspect ratios
  src/bauhaus/bauhaus.c
  src/common/calculator.c
  src/iop/borders.c
Labels: bugfix, feature: enhancement, priority: low, release notes: pending

#14451 Improve dialog options of deletion error second attempt
  src/control/jobs/control_jobs.c
Labels: bugfix, priority: medium, difficulty: average, scope: DAM, documentation-pending, release notes: pending

#14464 Redesign pixelpipe cache importance
  src/develop/develop.c
  src/develop/imageop.c
  src/develop/imageop.h
  src/develop/pixelpipe_hb.c
  src/develop/pixelpipe_hb.h
  src/iop/colorbalancergb.c
  src/iop/colorin.c
  src/iop/diffuse.c
  src/iop/highlights.c
Labels: feature: redesign, scope: UI, scope: image processing, scope: performance

#14469 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#14479 Inpaint Opposed: optimize code
  src/iop/hlreconstruct/opposed.c
Labels: scope: performance

#14480 Fix rating popup not shown when using shortcut
  src/common/ratings.c
Labels: bugfix, scope: UI, scope: DAM, release notes: pending

#14482 Early CPU fallback in dt_interpolation_resample_cl()
  src/common/interpolation.c
  src/develop/imageop_math.c
  src/iop/demosaic.c
  src/iop/demosaicing/dual.c
Labels: scope: image processing, scope: performance

#14143 [RFC] eliminate NAN as marker value (part 1)
  src/common/colorspaces.c
  src/common/dttypes.h
  src/common/exif.cc
  src/common/illuminants.h
  src/common/image.c
  src/common/image_cache.c
  src/common/iop_profile.c
  src/common/math.h
  src/control/jobs/control_jobs.c
  src/imageio/imageio_dng.h
  src/iop/channelmixerrgb.c
  src/iop/colorbalancergb.c
  src/iop/colorin.c
  src/iop/colorout.c
  src/libs/histogram.c
Labels: scope: codebase

#14475 Add 5th masks combine mode "sum"
  src/develop/blend_gui.c
  src/develop/masks.h
  src/develop/masks/group.c
  src/develop/masks/masks.c
  src/dtgtk/paint.c
  src/dtgtk/paint.h
  src/libs/masks.c
Labels: feature: enhancement, scope: codebase

#14485 Fix _raster_value_changed_callback()
  src/develop/blend_gui.c
Labels: bugfix, priority: high

#14468 lens: new embedded metadata algorithm
  src/iop/lens.cc
Labels: feature: redesign, difficulty: hard, scope: image processing

#14486 masks: Fix mask visibility when removing a shape.
  src/libs/masks.c
Labels: bugfix, priority: medium

#14490 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#14494 Turkish translation update
  po/tr.po
Labels: scope: translation / strings

#14477 Add Nikon Z6 II noise profile
  data/noiseprofiles.json
Labels: scope: noise profile

#14489 Avoid some channelmixer rgb trouble messages
  src/iop/channelmixerrgb.c
Labels: feature: enhancement, scope: UI, release notes: pending

#14497 filters : fix pin icon when adding/removing filters
  src/libs/filtering.c
Labels: bugfix, priority: medium, difficulty: trivial, scope: UI

#14297 Handle fuji X-Trans I/II/III embedded lens metadata
  src/common/exif.cc
  src/common/image.h
Labels: scope: camera support, priority: low, feature: new, release notes: pending

#14493 move pen pressure and brush smoothing to mask manager
  data/darktableconfig.xml.in
  src/gui/gtk.c
  src/gui/gtk.h
  src/libs/masks.c
Labels: priority: medium, feature: redesign, scope: UI, documentation-pending, release notes: pending

#14495 develop: Fix single instance module & auto-presets.
  src/develop/develop.c
Labels: bugfix, priority: high, understood: clear, difficulty: trivial, scope: codebase

#14499 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#14502 Update de.po
  po/de.po
Labels: scope: translation / strings

#14505 Update zh_TW translation
  po/zh_TW.po
Labels: scope: translation / strings

#14487 [GUI] [imageio] Add metadata display of current image's embedded ICC profile
  src/common/dttypes.h
  src/iop/colorin.c
Labels: feature: enhancement, priority: low, documentation-pending, release notes: pending

#14509 [imageio] .ORI is the raw file extension
  src/imageio/imageio.c
Labels: bugfix, scope: DAM

#14511 [GUI] Uncapitalize method names in 'dither or posterize'
  src/iop/dither.c
Labels: scope: translation / strings

#14515 correct inverted validity test
  src/common/colorspaces.c
Labels: bugfix, priority: high

#14514 Use safe value for INVALID_CACHEHASH
  src/develop/pixelpipe_cache.c
Labels: bugfix

#14512 ensure filemanager is not scrolled too far
  src/dtgtk/thumbtable.c
Labels: bugfix, difficulty: trivial, scope: UI

#14519 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#14517 lens: don't consider vignetting in modify_roi_in_md
  src/iop/lens.cc
Labels: bugfix, priority: high, scope: image processing

#14523 Modifications of pixelpipe debugging
  src/develop/pixelpipe_hb.c
Labels: scope: codebase

#14522 3 Raster mask fixes
  src/develop/blend.c
  src/develop/blend.h
  src/develop/blend_gui.c
  src/develop/blends/blendif_rgb_hsl.c
  src/develop/blends/blendif_rgb_jzczhz.c
Labels: bugfix, priority: medium, scope: codebase

#14524 Change the Ukrainian translation of the color profile modules names
  po/uk.po
Labels: scope: translation / strings

#14520 fix crash when sampling only half the candidate patches in fast mode
  src/common/nlmeans_core.c
Labels: bugfix, priority: high

#14521 po/UI lang - fix part of ui being translated
  src/common/darktable.c
  src/common/l10n.c
  src/common/l10n.h
  src/control/conf.c
  src/control/conf.h
Labels: bugfix, priority: high, scope: UI

#14531 Update de.po
  po/de.po
Labels: scope: translation / strings

#14532 Update zh_TW translation
  po/zh_TW.po
Labels: scope: translation / strings

#13174 Add geometry of Spyder Checkr Photo.
  src/common/colorchecker.h
  src/iop/channelmixerrgb.c
  tools/spyder-checkr-photo-coords.py
Labels: bugfix, feature: enhancement, wip, priority: low, scope: color management, documentation-pending, release notes: pending

#14535 zh_CN: update for 4.4
  po/zh_CN.po
Labels: scope: translation / strings

#14537 maintenance: remove bogus pointer alignment directives
  src/common/bspline.h
  src/iop/cacorrectrgb.c
  src/iop/diffuse.c
  src/iop/hlreconstruct/laplacian.c
Labels: scope: codebase

#14545 Update de.po
  po/de.po
Labels: scope: translation / strings

#14541 capitalize first letter of the name
  src/iop/denoiseprofile.c
Labels: scope: translation / strings

#14540 CIELAB terminology in colorzone
  src/iop/colorzones.c
Labels: bugfix, priority: low

#14547 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#14548 [GUI] Reformat the message to achieve a better distribution of line lengths
  src/develop/pixelpipe_hb.c
Labels: scope: translation / strings

#14533 Fix raster mask source handling
  src/common/iop_profile.c
  src/develop/blend.c
  src/develop/blend.h
  src/develop/blend_gui.c
  src/develop/imageop.c
  src/develop/imageop.h
  src/develop/pixelpipe_hb.c
  src/develop/tiling.c
Labels: bugfix, priority: high, scope: image processing, scope: performance

#14543 [GUI] Reword color profile tooltips for greater clarity
  src/iop/colorin.c
  src/iop/colorout.c
  src/libs/export.c
  src/libs/print_settings.c
  src/views/darkroom.c
  src/views/lighttable.c
Labels: priority: low

#14544 borders.c: add search aliases
  src/iop/borders.c
Labels: scope: UI

#14553 fix segfault on small image/region
  src/common/eaw.c
Labels: bugfix

#14550 Ignore empty GPX points
  src/common/gpx.c
Labels: bugfix, release notes: pending

#14555 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#14552 fix collect history position saving
  src/common/collection.c
  src/common/collection.h
  src/dtgtk/thumbtable.c
  src/libs/collect.c
  src/libs/recentcollect.c
Labels: bugfix, priority: low, difficulty: average, scope: UI

#14551 [GUI] Reword the trashing/deletion error dialog
  src/control/jobs/control_jobs.c
Labels: scope: translation / strings, scope: UI

#14561 Update de.po
  po/de.po
Labels: scope: translation / strings

#14562 Update zh_TW translation
  po/zh_TW.po
Labels: scope: translation / strings

#14559 Properly apply Sigmoid or FilmicRGB to matrix based pictures.
  src/iop/filmicrgb.c
  src/iop/sigmoid.c
  src/libs/ioporder.c
Labels: bugfix, priority: high, scope: image processing

#14567 [GUI] Assorted string fixes
  src/develop/masks/path.c
  src/iop/denoiseprofile.c
  src/iop/lens.cc
Labels: scope: translation / strings

#14565 [GUI] More correct text about ICC files in color profile widget tooltips
  src/common/iop_profile.c
  src/common/iop_profile.h
  src/iop/colorin.c
  src/iop/colorout.c
  src/libs/export.c
  src/libs/print_settings.c
  src/views/darkroom.c
  src/views/lighttable.c
Labels: bugfix, scope: translation / strings, priority: high

#14566 Add colorspace handling to debugging log
  src/develop/pixelpipe_cache.c
  src/develop/pixelpipe_hb.c
Labels: scope: codebase

#14564 support Exiv2 0.28 API changes
  CMakeLists.txt
  README.md
  src/CMakeLists.txt
  src/common/exif.cc
Labels: bugfix, scope: DAM, depends: external lib

#14571 [GUI] Fix UI language on first launch
  src/common/l10n.c
Labels: bugfix, priority: high

#14572 print_settings: bugfix -- image flipping
  src/libs/print_settings.c
Labels: bugfix, priority: high, scope: UI, release notes: pending

#14570 ioporder: Do not apply JPEG module order for RAW/mono images.
  src/libs/ioporder.c
Labels: bugfix, priority: medium

#14578 More debugging output for colorspace and raster masks
  src/develop/blend.c
  src/develop/imageop.c
Labels: priority: high, scope: codebase

#14577 exif: DNG detection improvements
  src/common/exif.cc
Labels: bugfix, priority: high

#14580 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#14582 Update de.po
  po/de.po
Labels: scope: translation / strings

#14584 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#14586 Update hu.po
  po/hu.po
Labels: scope: translation / strings

#14588 Update sq.po
  po/sq.po
Labels: scope: translation / strings

#14589 [GUI] Replace the questionable word with the most commonly used one
  src/iop/profile_gamma.c
Labels: scope: translation / strings

#14592 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#14594 Update de.po
  po/de.po
Labels: scope: translation / strings

#14595 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#14603 Update zh_TW.po
  po/zh_TW.po
Labels: scope: translation / strings

#14600 Fixes for pixelpipe cache 4.4
  src/develop/pixelpipe_cache.c
  src/develop/pixelpipe_cache.h
  src/develop/pixelpipe_hb.c
Labels: bugfix, priority: high

#14605 Bump blendop to v13 and migrate to new version.
  src/develop/blend.c
  src/develop/blend.h
Labels: bugfix, priority: high, scope: UI

#14606 [GUI] Reword the middle mouse button configuration tooltip
  data/darktableconfig.xml.in
Labels: scope: translation / strings

#14614 Bugfix #14496
  src/common/collection.c
  src/common/collection.h
  src/dtgtk/thumbtable.c
Labels: bugfix, scope: UI

#13034 [GUI] Fix incorrect naming of the slider in the vignetting module
  src/iop/vignette.c
Labels: scope: translation / strings, scope: UI, documentation-pending

#14616 Update de.po
  po/de.po
Labels: scope: translation / strings
