Repository darktable-org/darktable, pull requests merged in 2023-09, with the labels that each got.

#15155 colorspaces: add Display P3 built-in support
  src/cli/main.c
  src/common/colorspaces.c
  src/common/colorspaces.h
  src/imageio/format/avif.c
  src/imageio/format/jxl.c
Labels: feature: enhancement, priority: low, scope: color management, release notes: pending

#15148 improve bauhaus popup behaviour
  src/bauhaus/bauhaus.c
  src/bauhaus/bauhaus.h
  src/gui/gtk.c
  src/libs/filtering.c
  src/libs/filters/grouping.c
  src/libs/filters/history.c
  src/libs/filters/local_copy.c
  src/libs/filters/module_order.c
  src/libs/filters/rating.c
  src/libs/navigation.c
Labels: bugfix, priority: medium, difficulty: hard, scope: UI, documentation-pending

#15158 disable rotate&perspective structure modes on focus loss
  src/iop/ashift.c
  src/iop/colorzones.c
  src/libs/modulegroups.c
Labels: bugfix, priority: high

#15161 Bugfix: Use intel OpenCL platform aliases
  data/darktableconfig.xml.in
  src/common/opencl.c
Labels: bugfix, scope: hardware support

#15167 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#15163 macOS: Provide an application menu
  src/CMakeLists.txt
  src/common/usermanual_url.c
  src/gui/about.c
  src/gui/about.h
  src/gui/gtk.c
  src/gui/gtk.h
  src/libs/CMakeLists.txt
  src/libs/tools/darktable.c
Labels: scope: macos support

#15166 Introduce `unified_fraction` per OpenCL device
  src/common/darktable.c
  src/common/darktable.h
  src/common/opencl.c
  src/common/opencl.h
Labels: feature: enhancement, priority: medium, scope: hardware support, documentation-pending

#15164 Update fr.po
  po/fr.po
Labels: scope: translation / strings

#15171 Update de.po
  po/de.po
Labels: scope: translation / strings

#15113 New module: primaries
  data/kernels/extended.cl
  src/CMakeLists.txt
  src/common/colorspaces.c
  src/common/colorspaces.h
  src/common/custom_primaries.c
  src/common/custom_primaries.h
  src/common/iop_order.c
  src/common/iop_profile.c
  src/common/iop_profile.h
  src/iop/CMakeLists.txt
  src/iop/primaries.c
Labels: priority: medium, feature: new, scope: image processing, scope: color management, documentation-pending, release notes: pending

#15177 Add missing gettext macro
  src/gui/gtk.c
Labels: scope: translation / strings

#15176 [GUI] A few spelling fixes
  data/darktableconfig.xml.in
Labels: scope: translation / strings

#15173 Revamp OpenCL process_cl() usage, part 2
  src/develop/pixelpipe_hb.c
  src/iop/demosaic.c
  src/iop/demosaicing/basics.c
  src/iop/demosaicing/dual.c
  src/iop/demosaicing/rcd.c
  src/iop/demosaicing/vng.c
  src/iop/demosaicing/xtrans.c
  src/iop/highlights.c
  src/iop/hlreconstruct/laplacian.c
  src/iop/hlreconstruct/opposed.c
  src/iop/rawprepare.c
Labels: scope: codebase

#15168 Fix highlights colorspace conversion, enable for non-monochromes
  src/iop/highlights.c
Labels: bugfix, scope: codebase

#15042 Relnotes: remove some suspended Samsung models
  RELEASE_NOTES.md
Labels: scope: camera support, depends: rawspeed

#15180 Add 'about.c' to POTFILES.in
  po/POTFILES.in
Labels: scope: translation / strings

#15181 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#15184 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#15183 ctrl scroll filmstrip to zoom and shift to move fast
  src/dtgtk/thumbtable.c
  src/gui/gtk.c
Labels: scope: UI, documentation-pending, release notes: pending

#15186 OpenCL process_cl() maintenance part 3
  src/common/bilateralcl.c
  src/common/dwt.c
  src/common/gaussian.c
  src/common/heal.c
  src/iop/bilat.c
  src/iop/denoiseprofile.c
Labels: scope: codebase

#15199 [CMake] fix dependency for generate_authors_h
  src/CMakeLists.txt
  src/libs/CMakeLists.txt
Labels: bugfix

#15209 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#15210 [maintenance] Code maintenance for win/dtwin.c
  src/win/dtwin.c
Labels: scope: codebase, scope: windows support

#15200 avif: don't embed ICC profile if CICP coding works
  src/imageio/format/avif.c
Labels: feature: redesign, scope: software support, scope: color management

#15206 png: store color encoding as cICP chunk as well
  src/imageio/format/png.c
Labels: feature: enhancement, scope: software support, scope: color management

#15207 Fix escapedkerneldir for OpenCL kernels on Linux/ARM64
  src/common/opencl.c
Labels: bugfix

#15195 Replace cl_device_v5 with cldevice_v5 in all hint messages
  po/cs.po
  po/darktable.pot
  po/de.po
  po/en@truecase.po
  po/es.po
  po/fi.po
  po/fr.po
  po/he.po
  po/hu.po
  po/it.po
  po/ja.po
  po/pl.po
  po/pt_BR.po
  po/ru.po
  po/sl.po
  po/sq.po
  po/tr.po
  po/uk.po
  po/zh_CN.po
  po/zh_TW.po
  src/common/darktable.c
Labels: scope: translation / strings

#15212 More aliases for intel opencl
  data/darktableconfig.xml.in
  src/common/opencl.c
Labels: scope: hardware support

#15214 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#15215 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#15217 Update de.po
  po/de.po
Labels: scope: translation / strings

#15219 interpolation aligning fix and maintenance
  src/common/interpolation.c
  src/develop/imageop_math.c
Labels: bugfix, scope: codebase

#15145 rename to create XMP
  README.md
  data/darktableconfig.xml.in
Labels: scope: translation / strings

#15222 avoid double image when unfocusing crop
  src/develop/imageop.c
  src/views/darkroom.c
Labels: bugfix, priority: high, scope: UI

#15223 Fix filmicrgb highlights cpu code
  src/common/bspline.h
  src/common/color_picker.c
  src/iop/filmicrgb.c
Labels: bugfix, priority: high, scope: codebase

#15228 [CI/CD] Unbreak macOS nightly build environment
  .github/workflows/nightly.yml
Labels: scope: macos support

#15229 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#15170 Enable further exposing if there is a color picker enabled
  src/develop/masks/masks.c
  src/iop/ashift.c
  src/iop/channelmixerrgb.c
  src/iop/crop.c
  src/iop/graduatednd.c
  src/iop/liquify.c
  src/iop/vignette.c
  src/views/darkroom.c
Labels: feature: enhancement, priority: low, scope: image processing

#15213 Display color-picker samples even if global picker not selected.
  src/libs/colorpicker.c
Labels: scope: UI, release notes: pending

#15197 further improvements to thumbnail placement in culling
  src/dtgtk/culling.c
Labels: bugfix, difficulty: hard, scope: UI

#15227 Add Olympus E-P7 noise profiles
  data/noiseprofiles.json
Labels: scope: noise profile

#15233 Make dt version available in logs
  src/common/darktable.c
Labels: scope: codebase

#15230 [GUI] Remove exposure duplicates from preset auto-apply dialog
  src/gui/presets.c
Labels: scope: codebase

#15249 Spanish translation update
  po/es.po
Labels: scope: translation / strings

#15236 po/db camera - DB table refactoring for better DB structure
  src/common/cache.c
  src/common/cache.h
  src/common/collection.c
  src/common/darktable.c
  src/common/database.c
  src/common/database.h
  src/common/image.c
  src/common/image.h
  src/common/image_cache.c
  src/libs/collect.c
  src/libs/filters/rating_range.c
  src/libs/metadata_view.c
  src/win/win.h
Labels: priority: high, difficulty: hard, scope: DAM, scope: codebase

#15245 reset bauhaus to auto preset with ctrl+dblclick and add quad tooltip
  src/bauhaus/bauhaus.c
  src/bauhaus/bauhaus.h
  src/develop/imageop.c
  src/gui/accelerators.c
  src/gui/color_picker_proxy.c
  src/gui/presets.c
  src/gui/presets.h
  src/imageio/format/avif.c
  src/imageio/format/j2k.c
  src/imageio/format/jpeg.c
  src/imageio/format/webp.c
  src/iop/exposure.c
Labels: feature: enhancement, priority: low, scope: UI, documentation-pending, release notes: pending

#15241 Lens module work
  data/kernels/basic.cl
  src/iop/lens.cc
Labels: feature: new, scope: image processing, scope: hardware support, scope: performance

#15254 More precise button tooltips for highlights
  src/iop/highlights.c
Labels: feature: enhancement, scope: translation / strings, scope: UI

#15251 [GUI] Optimize aperture matching in presets auto-apply dialog
  src/gui/presets.c
Labels: scope: codebase

#15257 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#15256 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#15232 fix several minor issues with dialog boxes
  data/themes/darktable-elegant-grey.css
  data/themes/darktable.css
  src/common/darktable.c
  src/common/database.c
  src/gui/gtk.c
  src/gui/presets.c
  src/gui/styles_dialog.c
  src/libs/collect.c
  src/libs/export_metadata.c
  src/libs/geotagging.c
  src/libs/import.c
  src/libs/metadata.c
  src/libs/metadata_view.c
  src/libs/modulegroups.c
  src/libs/recentcollect.c
  src/libs/styles.c
  src/libs/tagging.c
Labels: bugfix, priority: medium, scope: UI

#15259 [GUI] Use American spelling of favor
  src/iop/highlights.c
Labels: scope: translation / strings, scope: UI

#15258 macOS: Fix packaging for ARM architecture
  packaging/macosx/3_make_hb_darktable_package.sh
Labels: scope: macos support

#15263 po/cameras db - separate maker / model column
  src/common/database.c
  src/common/image.c
Labels: scope: codebase

#15266 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#15260 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#15202 disable global colorpicker on any focus change request
  src/develop/imageop.c
  src/views/darkroom.c
Labels: feature: redesign, scope: UI

#15267 rgb primaries: minor fix to CL code, add release notes entry
  RELEASE_NOTES.md
  data/kernels/extended.cl
Labels: bugfix, priority: high

#15270 [GUI] Correcting the spelling of loader names
  src/common/image.h
Labels: scope: translation / strings, scope: UI

#15141 imageio: extract more image info if using latest OpenEXR
  src/imageio/imageio_exr.cc
Labels: feature: enhancement, priority: low, scope: software support, release notes: pending

#15272 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#15273 macOS: Update homebrew build instructions
  packaging/macosx/BUILD_hb.txt
Labels: scope: macos support

#15274 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#15275 legacy_presets: remove legacy presets DB and corresponding support.
  src/common/database.c
  src/develop/develop.c
  src/gui/legacy_presets.h
Labels: scope: codebase

#15276 Filters reset
  src/libs/filtering.c
  src/libs/filters/camera.c
  src/libs/filters/filename.c
  src/libs/filters/lens.c
Labels: feature: enhancement, difficulty: trivial, scope: UI, scope: DAM

#15277 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#15271 imageio: synchronize wording for grayscale output, AVIF updates
  data/darktableconfig.xml.in
  src/control/conf.c
  src/imageio/format/avif.c
  src/imageio/format/j2k.c
  src/imageio/format/jpeg.c
  src/imageio/format/tiff.c
  src/imageio/format/webp.c
Labels: scope: translation / strings, scope: UI

#15281 Add null string check to dt_conf_get_bool tests
  src/control/conf.c
Labels: bugfix

#15191 Windows: bump libgphoto2 links
  cmake/modules/FindGphoto2.cmake
  cmake/modules/NSIS.template.in
  packaging/windows/README.md
  src/CMakeLists.txt
Labels: scope: windows support

#15253 Improved OpenCL platform error reports
  src/common/opencl.c
  src/common/opencl.h
  src/develop/pixelpipe_hb.c
Labels: feature: enhancement, scope: hardware support

#15282 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#15283 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#15284 Fix translatable strings
  src/common/opencl.c
  src/control/jobs/camera_jobs.c
  src/develop/blend_gui.c
  src/gui/accelerators.c
  src/iop/highlights.c
  src/iop/lens.cc
  src/libs/export.c
Labels: scope: translation / strings

#15289 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#15293 collection query cleanup and fix
  src/common/collection.c
  src/common/collection.h
Labels: bugfix, difficulty: trivial, scope: DAM

#15296 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#15298 collection: Fix large slow-down on tag collection.
  src/common/collection.c
Labels: bugfix, priority: high, scope: DAM

#15309 Add column fullthumb_hash into main.history_hash.
  src/common/database.c
Labels: feature: enhancement, scope: DAM, scope: codebase

#15311 po/db clean up
  src/common/database.c
  src/common/image.c
Labels: priority: low, difficulty: trivial, scope: codebase

#15315 Update de.po
  po/de.po
Labels: scope: translation / strings

#15306 Avoid dt_dev_pixelpipe_rebuild() if not necessary in focus in&out
  src/develop/imageop.c
Labels: bugfix, difficulty: hard, scope: image processing

#15312 collection query cleanup (part 2)
  src/common/collection.c
  src/libs/filters/grouping.c
  src/libs/filters/rating_range.c
Labels: bugfix, difficulty: average, scope: DAM

#15285 build prefs layout from xml and use bauhaus combo
  data/darktableconfig.dtd
  data/darktableconfig.xml.in
  data/themes/darktable.css
  src/gui/accelerators.c
  src/gui/preferences.c
  src/gui/preferences.h
  src/libs/collect.c
  src/libs/filtering.c
  src/libs/map_settings.c
  src/libs/masks.c
  src/views/view.c
  tools/generate_darktablerc_conf.xsl
  tools/generate_prefs.xsl
Labels: bugfix, scope: translation / strings, priority: medium, difficulty: hard, scope: UI, scope: codebase, release notes: pending

#15304 Update change timestamp when doing image flip from lighttable.
  src/common/image.c
Labels: bugfix, priority: medium, scope: DAM

#15318 fix crash switching to lighttable while editing module instance name
  src/control/control.c
Labels: bugfix, priority: high, understood: clear, difficulty: trivial, scope: UI

#15320 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#15068 map.c: optimize dbscan code
  src/views/map.c
Labels: priority: low, scope: performance

#15319 [GUI] Remove the empty trailing line in the tooltip
  src/iop/lens.cc
Labels: scope: translation / strings, scope: UI

#15321 fix bauhaus combos in preferences on Windows
  src/bauhaus/bauhaus.c
Labels: bugfix, priority: high, scope: UI

#15325 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#15326 Fix truncation of '--version' output on Windows
  src/common/darktable.c
Labels: bugfix, priority: low, scope: CLI

#15305 [GUI] Typo fix and some rewording
  src/develop/pixelpipe_hb.c
Labels: scope: translation / strings, scope: UI

#15328 masks: Do not read past the history end.
  src/develop/masks/masks.c
Labels: priority: medium, scope: codebase

#15323 Don't change global color picker focus if restrict scope to selection is set
  src/develop/imageop.c
Labels: bugfix, reproduce: confirmed, scope: image processing

#15338 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#15341 [GUI] Remove unnecessary text in tooltip
  src/imageio/format/avif.c
Labels: scope: translation / strings

#15344 macOS: minor build script improvements
  build.sh
  packaging/macosx/2_build_hb_darktable_default.sh
Labels: scope: macos support

#15351 Fix precision problems for 'int' in conf / calculator
  src/common/calculator.c
  src/common/calculator.h
  src/control/conf.c
  src/control/conf.h
Labels: bugfix, scope: codebase

#15349 Update README.md
  README.md
Labels: scope: translation / strings

#15348 control & jobs maintenance
  src/control/control.c
  src/control/control.h
  src/control/jobs.c
  src/control/jobs.h
  src/develop/develop.c
Labels: scope: codebase
