Repository darktable-org/darktable, pull requests merged in 2023-04, with the labels that each got.

#14080 Update de.po
  po/de.po
Labels: scope: translation / strings

#14081 OpenCL and dynlib maintenance & fixes
  src/common/darktable.c
  src/common/dlopencl.c
  src/common/dlopencl.h
  src/common/dynload.c
  src/common/dynload.h
  src/common/opencl.c
  src/common/opencl.h
  src/develop/pixelpipe_hb.c
Labels: bugfix, scope: codebase

#14083 Import metadata from commonly used keys
  src/common/exif.cc
Labels: feature: enhancement, scope: DAM

#14085 fix tiny circle shapes
  src/develop/masks/circle.c
Labels: scope: UI

#14093 [GUI] Remove leading space from tooltip lines
  src/iop/exposure.c
Labels: scope: translation / strings

#14086 performance: optimize chromatic adaptation in Color Calibration
  src/common/chromatic_adaptation.h
  src/iop/channelmixerrgb.c
Labels: scope: performance

#14096 Turkish translation update
  po/tr.po
Labels: scope: image processing

#14099 Ukrainian translation update
  po/uk.po
Labels: scope: translation / strings

#14097 maintenance: remove unused colormatrix functions, move mat3inv
  src/common/colorspaces.c
  src/common/colorspaces.h
  src/common/matrices.c
  src/common/matrices.h
  src/imageio/imageio_rgbe.c
  src/iop/ashift.c
Labels: scope: codebase

#14090 Large Overhaul of pixelpipe code
  src/common/color_picker.c
  src/common/darktable.h
  src/common/histogram.c
  src/common/interpolation.c
  src/common/iop_order.c
  src/common/iop_profile.c
  src/common/styles.c
  src/develop/develop.c
  src/develop/develop.h
  src/develop/format.h
  src/develop/imageop.c
  src/develop/imageop.h
  src/develop/pixelpipe_hb.c
  src/develop/pixelpipe_hb.h
  src/develop/tiling.c
  src/gui/color_picker_proxy.c
  src/gui/presets.c
  src/imageio/imageio.c
  src/iop/ashift.c
  src/iop/bilat.c
  src/iop/cacorrect.c
  src/iop/channelmixerrgb.c
  src/iop/clahe.c
  src/iop/colorchecker.c
  src/iop/colorin.c
  src/iop/colorout.c
  src/iop/colorzones.c
  src/iop/demosaic.c
  src/iop/equalizer.c
  src/iop/filmic.c
  src/iop/finalscale.c
  src/iop/flip.c
  src/iop/gamma.c
  src/iop/globaltonemap.c
  src/iop/highlights.c
  src/iop/hotpixels.c
  src/iop/invert.c
  src/iop/lens.cc
  src/iop/overexposed.c
  src/iop/rawdenoise.c
  src/iop/rawoverexposed.c
  src/iop/rawprepare.c
  src/iop/retouch.c
  src/iop/rotatepixels.c
  src/iop/scalepixels.c
  src/iop/spots.c
  src/iop/temperature.c
  src/iop/tonecurve.c
  src/iop/toneequal.c
  src/iop/useless.c
  src/libs/histogram.c
  src/views/darkroom.c
Labels: scope: codebase

#14102 correctly handle NANs with new optimization flags
  src/common/illuminants.h
Labels: bugfix, priority: high, scope: image processing

#14092 po/masks arrows - better drawing
  src/develop/masks.h
  src/develop/masks/brush.c
  src/develop/masks/circle.c
  src/develop/masks/ellipse.c
  src/develop/masks/masks.c
  src/develop/masks/path.c
Labels: bugfix, priority: medium, scope: UI, release notes: pending

#14089 more free german translation for automatic module name
  po/de.po
Labels: scope: translation / strings

#14101 fix crash when checking a gui.action in other view from lua
  src/gui/accelerators.c
Labels: bugfix

#14105 fix another module scroll jump and simplify
  src/dtgtk/expander.c
Labels: bugfix, scope: UI

#14107 Some updates on darkroom view related stuff
  src/develop/blend.h
  src/develop/develop.c
  src/develop/develop.h
  src/libs/masks.c
  src/views/darkroom.c
  src/views/map.c
  src/views/print.c
  src/views/slideshow.c
  src/views/tethering.c
  src/views/view.c
  src/views/view.h
  src/views/view_api.h
Labels: scope: codebase

#14088 [GUI] Use ngettext to ensure correct translation of text in the plural form
  src/common/image.c
Labels: bugfix

#14111 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#14112 relight: optimize code
  src/iop/relight.c
Labels: scope: performance

#14117 Check for valid pointer while dynlib loading
  src/common/dynload.c
Labels: bugfix, scope: hardware support, scope: software support

#14064 Fix #14046 middle button zoom level
  data/darktableconfig.xml.in
  src/views/darkroom.c
Labels: wip, priority: low, scope: UI, release notes: pending

#14123 Ukrainian translation update
  po/uk.po
Labels: scope: translation / strings

#14122 Ricoh GR-IIIx noise profile
  data/noiseprofiles.json
Labels: scope: noise profile

#14124 circle/ellipse: Fix continuous creation in spot/retouch module.
  src/develop/masks/circle.c
  src/develop/masks/ellipse.c
Labels: bugfix, priority: high, reproduce: confirmed

#14129 translation: update for zh_CN
  po/zh_CN.po
Labels: scope: translation / strings

#14133 Turkish translation update
  po/tr.po
Labels: scope: translation / strings

#14132 po/masks cleanup - code refactoring masks drawing in single routine - consistent display
  src/develop/masks.h
  src/develop/masks/brush.c
  src/develop/masks/circle.c
  src/develop/masks/ellipse.c
  src/develop/masks/gradient.c
  src/develop/masks/masks.c
  src/develop/masks/path.c
  src/gui/draw.h
Labels: scope: UI, scope: codebase

#14119 macOS: Bundle graphicsmagick without modules
  .github/workflows/nightly.yml
Labels: scope: macos support

#14137 maintenance: remove INFINITY or replace by FLT_MAX
  src/common/opencl.c
  src/develop/blend.c
  src/develop/blend_gui.c
  src/develop/pixelpipe_hb.c
  src/iop/ashift.c
  src/iop/basicadj.c
  src/iop/cacorrectrgb.c
  src/iop/censorize.c
  src/iop/clipping.c
  src/iop/colorcontrast.c
  src/iop/lens.cc
  src/iop/lowpass.c
  src/iop/retouch.c
  src/iop/rgblevels.c
  src/iop/rotatepixels.c
  src/iop/shadhi.c
  src/views/map.c
Labels: scope: codebase

#14128 osx: allow GTK+ to be installed with X11 support
  src/osx/osx.mm
Labels: scope: macos support

#14140 Maintenance of imgid
  src/common/database.c
  src/common/history.c
  src/common/history.h
  src/common/image_cache.c
  src/common/selection.c
  src/common/selection.h
  src/common/variables.c
  src/common/variables.h
  src/iop/rawprepare.c
  src/libs/geotagging.c
  src/libs/image.c
  src/libs/import.c
  src/libs/snapshots.c
  src/libs/tools/image_infos.c
Labels: scope: codebase

#14142 imageio: use only valid data window for EXRs
  src/imageio/imageio_exr.cc
Labels: bugfix, release notes: pending

#14146 Update de.po
  po/de.po
Labels: scope: translation / strings

#14138 Update homebrew build descriptions
  packaging/macosx/BUILD_hb.txt
Labels: scope: macos support

#14135 fix wide panels jumping due to varying metadata
  src/libs/metadata.c
Labels: bugfix, priority: medium, difficulty: trivial, scope: UI

#14151 have lib views() return an enum instead of strings again
  src/common/darktable.h
  src/gui/accelerators.c
  src/libs/backgroundjobs.c
  src/libs/camera.c
  src/libs/collect.c
  src/libs/colorpicker.c
  src/libs/copy_history.c
  src/libs/duplicate.c
  src/libs/export.c
  src/libs/filtering.c
  src/libs/geotagging.c
  src/libs/histogram.c
  src/libs/history.c
  src/libs/image.c
  src/libs/import.c
  src/libs/ioporder.c
  src/libs/lib.c
  src/libs/lib_api.h
  src/libs/live_view.c
  src/libs/location.c
  src/libs/map_locations.c
  src/libs/map_settings.c
  src/libs/masks.c
  src/libs/metadata.c
  src/libs/metadata_view.c
  src/libs/modulegroups.c
  src/libs/navigation.c
  src/libs/print_settings.c
  src/libs/recentcollect.c
  src/libs/select.c
  src/libs/session.c
  src/libs/snapshots.c
  src/libs/styles.c
  src/libs/tagging.c
  src/libs/tools/battery_indicator.c
  src/libs/tools/colorlabels.c
  src/libs/tools/darktable.c
  src/libs/tools/filmstrip.c
  src/libs/tools/filter.c
  src/libs/tools/gamepad.c
  src/libs/tools/global_toolbox.c
  src/libs/tools/hinter.c
  src/libs/tools/image_infos.c
  src/libs/tools/lighttable.c
  src/libs/tools/midi.c
  src/libs/tools/module_toolbox.c
  src/libs/tools/ratings.c
  src/libs/tools/timeline.c
  src/libs/tools/view_toolbox.c
  src/libs/tools/viewswitcher.c
  src/lua/lualib.c
  src/views/view.h
Labels: priority: low, scope: codebase

#14152 Capitalizing Ukrainian translation
  po/uk.po
Labels: scope: translation / strings

#14153 Some more masks clean-up
  src/develop/masks.h
  src/develop/masks/brush.c
  src/develop/masks/masks.c
  src/develop/masks/path.c
Labels: scope: UI, scope: codebase

#14130 Pixelpipe caching finally fixed (very hopefully)
  src/develop/develop.h
  src/develop/imageop.c
  src/develop/pixelpipe_cache.c
  src/develop/pixelpipe_cache.h
  src/develop/pixelpipe_hb.c
  src/develop/pixelpipe_hb.h
Labels: bugfix, priority: high, difficulty: hard

#14156 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#14160 More pixelpipe stuff
  src/common/act_on.h
  src/common/exif.cc
  src/common/image.c
  src/common/image.h
  src/common/image_cache.c
  src/common/iop_order.c
  src/common/iop_order.h
  src/common/iop_profile.c
  src/common/iop_profile.h
  src/common/presets.c
  src/common/presets.h
  src/dtgtk/thumbtable.c
  src/libs/copy_history.c
  src/libs/image.c
Labels: scope: codebase

#14161 [GUI] Fix spelling of acronyms CSS and UI (should be all caps)
  data/darktableconfig.xml.in
Labels: scope: translation / strings

#14163 Update zh_TW translation
  po/zh_TW.po
Labels: scope: translation / strings

#12243 Add the sentence case version of Darktable UI that can be selected as another UI language
  po/LINGUAS
  po/en@truecase.po
Labels: scope: translation / strings, scope: UI

#14166 Pixelpipe cache respects internal histograms
  src/develop/pixelpipe.h
  src/develop/pixelpipe_cache.c
  src/develop/pixelpipe_hb.c
  src/develop/pixelpipe_hb.h
  src/iop/colorzones.c
  src/iop/levels.c
  src/iop/rgbcurve.c
  src/iop/rgblevels.c
  src/iop/tonecurve.c
Labels: bugfix, difficulty: hard, scope: UI, scope: codebase

#14171 Dump pipe pfm fixes
  src/common/darktable.c
  src/develop/pixelpipe_hb.c
Labels: scope: codebase

#14170 Add WB Presets for Pentax K-1 Mark II
  data/wb_presets.json
Labels: scope: camera support

#14179 [GUI] Collection sort names were shown untranslated
  src/libs/filtering.c
Labels: bugfix, scope: translation / strings, scope: UI

#14181 Update de.po
  po/de.po
Labels: scope: translation / strings

#14165 HLR segmentation maintenance
  src/iop/hlreconstruct/segbased.c
  src/iop/hlreconstruct/segmentation.c
Labels: bugfix, priority: high, scope: image processing, scope: codebase

#14187 Postpone update of libs until visible and drawn
  src/common/darktable.h
  src/develop/imageop.c
  src/gui/gtk.c
  src/gui/gtk.h
  src/libs/collect.c
  src/libs/copy_history.c
  src/libs/export.c
  src/libs/history.c
  src/libs/image.c
  src/libs/lib.c
  src/libs/lib.h
  src/libs/lib_api.h
  src/libs/masks.c
  src/libs/metadata.c
  src/libs/metadata_view.c
  src/libs/select.c
  src/libs/styles.c
  src/libs/tagging.c
  src/libs/tools/timeline.c
Labels: priority: medium, scope: UI, scope: codebase

#13999 don't show undescribed enum in combo
  src/bauhaus/bauhaus.c
  src/bauhaus/bauhaus.h
  src/control/control.c
  src/control/control.h
  src/gui/accelerators.c
  src/iop/channelmixerrgb.c
  src/iop/colorzones.c
  src/iop/demosaic.c
  src/iop/denoiseprofile.c
  src/iop/filmicrgb.c
  src/iop/highlights.c
  src/iop/lens.cc
  src/iop/toneequal.c
Labels: bugfix

#14191 en@truecase update and fixes
  po/en@truecase.po
Labels: scope: translation / strings

#14190 CMake: prevent unsuitable libheif from showing in package summary
  src/CMakeLists.txt
Labels: scope: codebase

#14174 exif: remove Xmp.dc.format key
  src/common/exif.cc
Labels: scope: DAM

#14189 masks: makes the mask editing sensitivity consistent.
  src/develop/masks.h
  src/develop/masks/brush.c
  src/develop/masks/circle.c
  src/develop/masks/ellipse.c
  src/develop/masks/gradient.c
  src/develop/masks/group.c
  src/develop/masks/path.c
Labels: feature: enhancement, scope: UI, scope: image processing, release notes: pending

#14193 Bugfix #12913 (HLR segmentation masks)
  src/iop/hlreconstruct/segbased.c
  src/iop/hlreconstruct/segmentation.c
Labels: bugfix, priority: high, scope: image processing

#14199 po/masks edit - another (and probably last for 4.4) usability enhacement for the masks
  src/develop/masks/brush.c
  src/develop/masks/circle.c
  src/develop/masks/ellipse.c
  src/develop/masks/masks.c
  src/develop/masks/path.c
Labels: bugfix, feature: enhancement, priority: high, scope: UI

#14202 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#14208 masks: Refine the masks drawing (line width & alpha).
  src/develop/masks/masks.c
Labels: scope: UI

#14206 Show the full-frame equivalent focal length in the image information module
  src/libs/metadata_view.c
Labels: feature: enhancement, scope: UI, release notes: pending

#14212 Update de.po
  po/de.po
Labels: scope: translation / strings

#14211 Fix Bayer4 demosaicing
  src/iop/demosaic.c
Labels: bugfix, scope: camera support, priority: low, scope: UI

#14177 make dragging sliders smoother by creating only one undo record
  src/bauhaus/bauhaus.c
  src/control/signal.c
  src/develop/develop.c
  src/develop/imageop.c
  src/libs/history.c
Labels: bugfix, priority: medium, difficulty: average, scope: performance

#14224 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#14217 More cleanup of struct dt_iop_module_t
  src/develop/blend_gui.c
  src/develop/develop.h
  src/develop/imageop.c
  src/develop/imageop.h
  src/develop/pixelpipe.h
Labels: scope: codebase

#14218 Translations update and fixes: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#14222 accelerators.c: reformat function headers
  src/gui/accelerators.c
Labels: scope: codebase

#10846 lib modules: defer widget updates while collapsed
  src/common/collection.c
  src/dtgtk/thumbtable.c
  src/libs/collect.c
  src/libs/copy_history.c
  src/libs/metadata.c
  src/libs/select.c
  src/libs/tools/timeline.c
  src/views/lighttable.c
Labels: feature: redesign, scope: UI, scope: performance, release notes: pending

#14229 [GUI] Proper names should be capitalized
  src/iop/colorchecker.c
Labels: scope: translation / strings

#14228 [GUI] Do not truncate EXIF_FOCAL_LENGTH
  src/common/variables.c
Labels: bugfix, priority: low, release notes: pending

#14225 RFC: Exposure default settings
  src/iop/exposure.c
Labels: feature: enhancement, scope: image processing, release notes: pending

#14216 Don't crash when applying style from Lua in darkroom mode
  src/lua/styles.c
Labels: bugfix, lua

#13978 Watermark with scale-to-height option
  RELEASE_NOTES.md
  data/watermarks/text-fixedsize.svg
  src/iop/watermark.c
Labels: feature: enhancement, priority: medium, scope: image processing, release notes: pending

#14234 import: fix already imported check
  src/libs/import.c
Labels: bugfix, priority: high, scope: DAM

#14065 [GUI] Redesign ISO matching widget for presets
  src/gui/presets.c
Labels: feature: redesign, scope: UI, release notes: pending

#14240 fix apply style in darkroom mode
  src/lua/styles.c
Labels: bugfix, lua

#14223 determine visibility of multiinstance menu when showing
  src/common/styles.c
  src/develop/develop.c
  src/develop/develop.h
  src/develop/imageop.c
  src/develop/imageop.h
  src/libs/modulegroups.c
  src/views/darkroom.c
Labels: scope: codebase

#14239 Modify masking code to use `typedef dt_mask_id_t`
  src/common/darktable.h
  src/common/history.c
  src/develop/blend.c
  src/develop/blend.h
  src/develop/develop.c
  src/develop/develop.h
  src/develop/imageop.c
  src/develop/lightroom.c
  src/develop/masks.h
  src/develop/masks/brush.c
  src/develop/masks/circle.c
  src/develop/masks/ellipse.c
  src/develop/masks/gradient.c
  src/develop/masks/masks.c
  src/develop/masks/path.c
  src/develop/pixelpipe_hb.c
  src/develop/pixelpipe_hb.h
  src/iop/retouch.c
  src/libs/masks.c
  src/views/darkroom.c
Labels: scope: codebase

#14249 Update de.po
  po/de.po
Labels: scope: translation / strings

#14251 Fix crash in history tooltip for already deleted item
  src/libs/history.c
Labels: bugfix, priority: high, difficulty: trivial

#14255 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#14250 Add support for Behringer X-Touch Compact
  src/bauhaus/bauhaus.c
  src/libs/tools/gamepad.c
  src/libs/tools/midi.c
Labels: bugfix, priority: medium, feature: new, difficulty: average, scope: UI, scope: hardware support, scope: codebase, documentation-pending, release notes: pending

#14260 maintenance: optimization-safe isnan / isinf / isfinite
  src/common/math.h
Labels: scope: performance, scope: codebase

#14258 Fix blending for feathering input
  src/common/imagebuf.c
  src/develop/blend.c
  src/develop/pixelpipe_hb.c
Labels: bugfix, priority: high, reproduce: confirmed, scope: codebase, release notes: pending

#14232 po/invert masks - remove invert masks from drawn mask UI
  src/develop/blend.c
  src/develop/blend.h
  src/develop/blend_gui.c
Labels: priority: high, feature: redesign, scope: UI, scope: image processing, documentation-pending, release notes: pending

#14253 ashift: check for pathological parameters to avoid crash.
  src/iop/ashift.c
Labels: bugfix, priority: medium, reproduce: confirmed, scope: image processing, release notes: pending

#14266 Fixing details mask #14257
  src/develop/blend.c
  src/develop/blend.h
  src/develop/blend_gui.c
  src/develop/pixelpipe_hb.c
  src/develop/pixelpipe_hb.h
  src/iop/lens.cc
  src/iop/toneequal.c
  src/views/darkroom.c
Labels: bugfix, priority: high, scope: codebase

#14262 maintenance: isfinite -> dt_isfinite
  src/bauhaus/bauhaus.c
  src/libs/history.c
Labels: scope: codebase

#14263 maintenance: isinf -> dt_isinf
  src/develop/pixelpipe_hb.c
Labels: scope: codebase

#14210 maintenance: eliminate NaN as marker value (part 2)
  src/bauhaus/bauhaus.c
  src/common/image.c
  src/common/image.h
  src/common/image_cache.c
  src/common/variables.c
  src/control/conf.c
  src/develop/masks.h
  src/develop/masks/brush.c
  src/develop/masks/masks.c
  src/develop/masks/path.c
  src/iop/exposure.c
  src/iop/globaltonemap.c
  src/iop/levels.c
  src/iop/temperature.c
  src/iop/toneequal.c
  src/libs/metadata_view.c
Labels: scope: codebase

#14270 masks: Some more use of dt_mask_id_t & NO_MASKID.
  src/develop/masks/masks.c
Labels: scope: codebase

#14269 fix selection start with shift-click
  src/common/selection.c
Labels: bugfix, priority: medium, scope: DAM

#14272 fix first image of collection as selection start
  src/common/selection.c
Labels: scope: DAM

#14274 [maintenance] JPEG XL loader maintenance
  src/imageio/imageio_jpegxl.c
Labels: scope: codebase

#14273 maintenance: isnan -> dt_isnan in IOPs (NAN removal, part 5)
  src/iop/basicadj.c
  src/iop/denoiseprofile.c
  src/iop/dither.c
  src/iop/lut3d.c
  src/iop/scalepixels.c
  src/iop/sigmoid.c
  src/iop/toneequal.c
Labels: scope: codebase

#14256 Remove use of nan as signal in shortcuts/actions
  src/bauhaus/bauhaus.c
  src/common/action.h
  src/common/colorlabels.c
  src/common/ratings.c
  src/control/control.c
  src/develop/imageop.c
  src/gui/accelerators.c
  src/gui/accelerators.h
  src/gui/gtk.c
  src/iop/atrous.c
  src/iop/colorzones.c
  src/iop/rgblevels.c
  src/libs/filters/colors.c
  src/libs/filters/rating_range.c
  src/libs/lib.c
  src/libs/tools/lighttable.c
  src/libs/tools/midi.c
  src/lua/gui.c
  src/views/darkroom.c
  src/views/lighttable.c
Labels: scope: codebase

#14276 update homebrew build instructions
  packaging/macosx/BUILD_hb.txt
Labels: scope: macos support

#14277 tagging: Ensure categeory & private are initialized (4.2.x)
  src/libs/tagging.c
Labels: scope: codebase

#14275 maintenance: isnan -> dt_isnan in misc files (NAN removal, part 6)
  src/control/conf.c
  src/develop/blend.c
  src/develop/imageop.c
  src/develop/openmp_maths.h
  src/develop/pixelpipe_hb.c
  src/dtgtk/gradientslider.c
  src/imageio/imageio_libraw.c
  src/libs/masks.c
  src/libs/metadata_view.c
Labels: scope: codebase

#14279 maintenance: isnormal -> dt_isnormal
  src/common/illuminants.h
  src/common/math.h
  src/common/pdf.c
  src/develop/masks/circle.c
  src/develop/masks/ellipse.c
  src/develop/masks/gradient.c
  src/iop/temperature.c
  src/lua/types.c
Labels: scope: codebase

#14173 wb_presets: add Sony ILME-FX30
  data/wb_presets.json
Labels: scope: camera support, depends: rawspeed

#14283 [GUI] Remove excessive leading space in the line of multi-line tooltip
  src/iop/exposure.c
Labels: scope: translation / strings

#14290 maintenance: isnan -> dt_isnan (NAN removal, part 8)
  src/bauhaus/bauhaus.c
  src/common/variables.c
  src/iop/hazeremoval.c
Labels: scope: codebase

#14292 Some cleanup of colorin module
  src/iop/colorin.c
Labels: scope: codebase

#14282 Various fixes related to details mask
  src/develop/blend.c
  src/develop/imageop.c
  src/develop/pixelpipe_cache.c
  src/develop/pixelpipe_hb.c
  src/iop/demosaic.c
Labels: bugfix, priority: medium, release notes: pending

#14284 Don't silently swallow image change request while pipe active
  src/develop/develop.c
  src/develop/develop.h
  src/views/darkroom.c
Labels: priority: medium, difficulty: average, scope: UI, release notes: pending

#14298 Again work on pixelpipe cache ( #14291)
  src/develop/develop.c
  src/develop/imageop.c
  src/develop/pixelpipe_cache.c
  src/develop/pixelpipe_cache.h
  src/develop/pixelpipe_hb.c
  src/develop/pixelpipe_hb.h
  src/iop/ashift.c
  src/iop/channelmixerrgb.c
Labels: bugfix, priority: medium, scope: image processing

#14299 Ukrainian translation fixes
  po/uk.po
Labels: scope: translation / strings

#14281 style: fix export/import overwrite message.
  src/libs/styles.c
Labels: scope: translation / strings, scope: UI

#14302 maint: dedup single-channel pixel interpolation
  src/common/interpolation.c
  src/common/interpolation.h
  src/iop/ashift.c
Labels: scope: codebase

#14267 opencl: use also platform name to distinguish devices
  src/common/darktable.c
  src/common/darktable.h
  src/common/opencl.c
  src/common/opencl.h
Labels: bugfix, feature: redesign, scope: hardware support

#14287 Stop the collect module flickering during import
  src/libs/collect.c
Labels: bugfix

#14248 rawprepare: enable per-color black control for non-CFA images
  data/kernels/basic.cl
  src/imageio/imageio_rawspeed.cc
  src/iop/rawprepare.c
Labels: scope: image processing

#14305 More mask_id and imgid fixes
  src/develop/blend_gui.c
  src/develop/imageop.c
  src/iop/useless.c
  src/libs/history.c
Labels: scope: codebase

#14310 Fixes some recently introduced mask_id problems
  src/common/darktable.h
  src/develop/masks/masks.c
  src/libs/history.c
  src/libs/masks.c
Labels: priority: high, scope: codebase

#14308 maint: eliminate temporary buffer for auto WB
  src/iop/channelmixerrgb.c
Labels: scope: codebase

#14307 allow double-middle-press to cycle through fit-100-200 zoom
  src/views/darkroom.c
Labels: priority: low, difficulty: trivial, scope: UI

#14313 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#14293 masks: Ensure the gui_module is set when editing masks.
  src/develop/blend_gui.c
Labels: bugfix, priority: high, scope: UI, release notes: pending

#14324 colorchecker: fix -Werror=stringop-overflow=
  src/iop/colorchecker.c
Labels: scope: codebase

#14306 Remove the date-time sanitizer
  src/common/exif.cc
  src/imageio/imageio_exr.cc
Labels: bugfix, priority: high, scope: DAM, scope: codebase

#14326 colorchecker: fix -Werror=stringop-overflow=
  src/iop/colorchecker.c
Labels: scope: codebase

#14315 Fix raster masks access from above the pixelpipe
  src/develop/blend.c
  src/develop/pixelpipe_hb.c
  src/develop/pixelpipe_hb.h
  src/imageio/format/exr.cc
  src/imageio/format/tiff.c
  src/imageio/format/xcf.c
Labels: bugfix, priority: medium, scope: image processing

#14330 Update zh_TW translation
  po/zh_TW.po
Labels: scope: translation / strings

#14329 dither: add posterization options (quantization w/o error diffusion)
  src/iop/dither.c
Labels: feature: enhancement, feature: new, scope: image processing, documentation-pending, release notes: pending

#14321 po/filmicv7 - port Filmic V7 to darktable.
  data/kernels/filmic.cl
  src/iop/filmicrgb.c
Labels: feature: enhancement, scope: image processing, documentation-pending, release notes: pending

#14337 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#14336 Add help buttons to a few dialogs and preferences tabs
  src/common/usermanual_url.c
  src/common/usermanual_url.h
  src/develop/blend_gui.c
  src/develop/imageop.c
  src/dtgtk/culling.c
  src/dtgtk/thumbtable.c
  src/gui/accelerators.c
  src/gui/gtk.c
  src/gui/gtk.h
  src/gui/preferences.c
  src/libs/copy_history.c
  src/libs/export_metadata.c
  src/libs/filtering.c
  src/libs/image.c
  src/libs/import.c
  src/libs/modulegroups.c
  src/libs/print_settings.c
  src/libs/tools/global_toolbox.c
  src/libs/tools/lighttable.c
  src/views/darkroom.c
  src/views/view.c
Labels: feature: enhancement, priority: low, scope: UI, documentation-pending, release notes: pending

#14340 squash some more GCC 13 warnings
  data/kernels/CMakeLists.txt
  src/iop/Permutohedral.h
Labels: scope: codebase

#14339 liquify: optimize and clean up code
  src/iop/liquify.c
Labels: scope: performance

#14343 noiseprofile tools: fix unused result warnings
  tools/noise/noiseprofile.c
Labels: scope: codebase

#14344 add help buttons to prefs, style, presets and copy paste
  src/common/usermanual_url.c
  src/gui/gtk.c
  src/gui/gtk.h
  src/gui/hist_dialog.c
  src/gui/preferences.c
  src/gui/presets.c
  src/gui/styles_dialog.c
  src/libs/export_metadata.c
  src/libs/import.c
  tools/generate_prefs.xsl
Labels: feature: enhancement, scope: usermanual, priority: low, scope: UI

#14351 maintenance: remove unused/unnecessary SSE-related code
  src/common/darktable.c
  src/common/darktable.h
  src/common/eigf.h
  src/common/fast_guided_filter.h
  src/common/interpolation.h
  src/common/points.h
  src/develop/masks.h
  src/iop/toneequal.c
Labels: scope: codebase

#14350 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#14346 Update de.po
  po/de.po
Labels: scope: translation / strings

#14349 Bugfix: pixelpipe cache versus raster mask
  src/develop/blend.c
  src/develop/pixelpipe_cache.c
  src/develop/pixelpipe_hb.c
  src/develop/pixelpipe_hb.h
  src/iop/demosaic.c
  src/iop/demosaicing/basics.c
  src/iop/demosaicing/rcd.c
  src/iop/demosaicing/vng.c
  src/iop/demosaicing/xtrans.c
  src/iop/rawprepare.c
Labels: bugfix, priority: high, feature: redesign, difficulty: hard, scope: image processing, scope: codebase

#14353 Center click in culling mode grabs focus
  src/dtgtk/culling.c
Labels: bugfix

#14347 show toast with name of last midi device opened
  src/gui/accelerators.c
  src/libs/lib.c
  src/libs/tools/gamepad.c
  src/libs/tools/midi.c
Labels: priority: low, difficulty: trivial

#14352 In shortcuts dialog tailor tooltip to item under cursor
  src/gui/accelerators.c
Labels: priority: low, scope: UI

#14355 [GUI] POTFILES.in: Add missing wb_presets.c
  po/POTFILES.in
Labels: scope: translation / strings

#14358 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#14357 Force a resize immediately after a delayed list update
  src/gui/gtk.c
Labels: priority: medium, scope: UI

#14361 colormapping.c: optimize kmeans for acquiring clusters
  src/iop/colormapping.c
Labels: scope: performance

#14362 maintenance: remove SSE PRNG implementation
  src/common/points.h
Labels: scope: codebase

#14363 Rename "help" buttons to "?" and reorder
  src/gui/accelerators.c
  src/gui/gtk.c
  src/gui/preferences.c
  src/iop/colorbalance.c
  src/libs/modulegroups.c
  tools/generate_prefs.xsl
Labels: feature: redesign, scope: UI

#14365 highpass.c: optimize code
  src/iop/highpass.c
Labels: scope: performance

#14366 add auto-vectorized log2 and exp2 functions
  src/common/math.h
  src/common/sse.h
  src/iop/colorbalance.c
Labels: scope: codebase

#14371 fix for_four_channels typos
  src/common/math.h
Labels: bugfix, priority: high

#14368 maintenance: use sqr()/sqrt() instead of pow() where possible
  src/common/rgb_norms.h
  src/iop/hlreconstruct/segbased.c
  src/iop/rgbcurve.c
  src/iop/tonecurve.c
Labels: scope: performance
