Repository darktable-org/darktable, pull requests merged in 2023-03, with the labels that each got.

#13784 gradient: only run as many threads as requested
  src/develop/masks/gradient.c
Labels: bugfix

#13785 Update zh_TW translation
  po/zh_TW.po
Labels: scope: translation / strings

#13787 Update de.po
  po/de.po
Labels: scope: translation / strings

#13771 po/fix workflow none
  src/develop/develop.c
  src/develop/imageop.c
  src/iop/channelmixerrgb.c
  src/iop/temperature.c
Labels: bugfix, priority: high, scope: image processing, scope: codebase

#13794 Fix build problem because of wrong po.de
  po/de.po
Labels: bugfix, scope: translation / strings

#13778 Maintenance gboolean dt_opencl_build_program()
  src/common/opencl.c
Labels: scope: codebase

#13781 [imageio][performance] Add OpenMP to the JPEG2000 loader
  src/imageio/imageio_j2k.c
Labels: feature: enhancement, scope: performance, release notes: pending

#13793 Fix distort_mask in finalscale
  src/iop/finalscale.c
Labels: bugfix, priority: high, scope: image processing, release notes: pending

#13796 Turkish translation update
  po/tr.po
Labels: scope: translation / strings

#13770 colorchecker/CLUT: allow adding color patch on 7x7 grid
  src/iop/colorchecker.c
Labels: bugfix, scope: codebase, release notes: pending

#13606 merge sticky and hold preview in lighttable
  src/common/action.h
  src/gui/accelerators.c
  src/gui/gtk.c
  src/libs/tools/lighttable.c
  src/views/lighttable.c
  src/views/view.c
  src/views/view.h
Labels: bugfix, feature: redesign, scope: codebase, release notes: pending

#13800 maintenance: remove unnecessary alpha-channel copying
  src/iop/atrous.c
  src/iop/bilat.c
  src/iop/bilateral.cc
  src/iop/bloom.c
  src/iop/censorize.c
  src/iop/channelmixer.c
  src/iop/colorbalance.c
  src/iop/colorchecker.c
  src/iop/colorin.c
  src/iop/colorout.c
  src/iop/defringe.c
  src/iop/denoiseprofile.c
  src/iop/dither.c
  src/iop/exposure.c
  src/iop/filmic.c
  src/iop/filmicrgb.c
  src/iop/globaltonemap.c
  src/iop/hazeremoval.c
  src/iop/highlights.c
  src/iop/invert.c
  src/iop/levels.c
  src/iop/negadoctor.c
  src/iop/nlmeans.c
  src/iop/sharpen.c
  src/iop/temperature.c
  src/iop/velvia.c
Labels: scope: codebase

#13802 update cs.po
  po/cs.po
Labels: scope: translation / strings

#13792 po/fix masks manager
  src/common/colorspaces.c
  src/common/history.c
  src/common/image.c
  src/common/iop_order.c
  src/common/iop_profile.c
  src/common/styles.c
  src/develop/develop.c
  src/develop/imageop.c
  src/develop/imageop.h
  src/develop/masks.h
  src/develop/masks/brush.c
  src/develop/masks/circle.c
  src/develop/masks/detail.c
  src/develop/masks/ellipse.c
  src/develop/masks/gradient.c
  src/develop/masks/masks.c
  src/develop/masks/path.c
  src/develop/pixelpipe_hb.c
  src/gui/presets.c
  src/imageio/imageio.c
  src/libs/masks.c
  src/views/darkroom.c
Labels: bugfix, priority: high, scope: UI, scope: codebase

#13766 [CI] Win64: Link with the packaged libraw
  .github/workflows/ci.yml
Labels: scope: windows support

#13797 [GUI] Change mention of "ROI" to a clearer explanation
  src/develop/blend.c
Labels: scope: UI, scope: codebase

#13805 po/fix masks manager - no collapsing
  src/libs/masks.c
Labels: bugfix, scope: UI

#13795 Fix PPG & VNG/VNG4 demosaicer CPU code
  data/kernels/demosaic_vng.cl
  src/iop/demosaic.c
Labels: bugfix, priority: high, scope: image processing, release notes: pending

#13798 AMaZE demosaicer code maintenance
  src/iop/amaze_demosaic_RT.cc
Labels: scope: performance, scope: codebase

#13808 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#13810 [GUI] Add line breaks to long tooltips
  src/libs/export.c
Labels: scope: translation / strings

#13814 surface blur: crash fix and speed optimization
  src/iop/Permutohedral.h
  src/iop/bilateral.cc
Labels: bugfix, scope: performance

#13819 restore tooltips for styles and presets
  src/gui/accelerators.c
Labels: bugfix, priority: high, scope: UI

#13821 Bugfix: -d pipe info about clip&zoom
  src/develop/pixelpipe_hb.c
Labels: bugfix, scope: codebase

#13822 pl.po update and correction
  po/pl.po
Labels: scope: translation / strings

#13820 fix for crash in _opencl_bench_cpu when restricting number of threads
  src/common/opencl.c
Labels: bugfix, scope: codebase

#13817 Fix missing map module on macOS homebrew builds
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  packaging/macosx/1_install_hb_dependencies.sh
Labels: scope: macos support

#13809 Suppress hidden files in import dialog
  src/libs/import.c
Labels: scope: DAM

#13816 Remove unused function `normalize_laplacian()`
  src/common/bspline.h
Labels: scope: codebase

#13825 Ukrainian translation update
  po/uk.po
Labels: scope: translation / strings

#13824 retouch: fix clone/heal brush
  src/develop/masks/brush.c
Labels: bugfix, scope: UI, scope: image processing

#13827 Update de.po
  po/de.po
Labels: scope: translation / strings

#13830 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#13834 retouch: remove remnants of SSE
  src/iop/retouch.c
Labels: scope: codebase

#13835 denoiseprofile: remove unused SSE wavelet codepath
  src/common/eaw.c
  src/common/eaw.h
Labels: scope: codebase

#13836 Invert: optimize code, remove SSE
  src/iop/invert.c
Labels: scope: performance

#13828 local laplacians: optimize and remove SSE code
  src/common/locallaplacian.c
  src/common/locallaplacian.h
  src/iop/bilat.c
Labels: scope: performance, scope: codebase

#13832 colorout: optimization and remove SSE
  src/common/colorspaces_inline_conversions.h
  src/iop/colorout.c
  src/iop/exposure.c
Labels: scope: performance, scope: codebase

#13563 imageio: export masks for EXRs as extra channels
  src/develop/imageop.h
  src/develop/pixelpipe.h
  src/develop/pixelpipe_hb.h
  src/imageio/format/exr.cc
  src/imageio/imageio_exr.h
  src/imageio/imageio_exr.hh
Labels: feature: enhancement, priority: medium, scope: image processing, scope: software support, scope: codebase, documentation-pending, release notes: pending

#13843 po/fast expf - closer output between OpenCL & CPU
  data/kernels/basecurve.cl
  data/kernels/basic.cl
  data/kernels/common.h
  data/kernels/locallaplacian.cl
  src/common/locallaplacian.c
Labels: feature: enhancement, priority: high, scope: image processing, release notes: pending

#13844 [CI] macOS: Link with the packaged libraw
  .ci/Brewfile
  .github/workflows/ci.yml
Labels: scope: macos support

#13846 Simplify css code for treeview entries
  data/themes/darktable.css
Labels: scope: UI, scope: codebase

#13848 maintenance: remove unused/dead code
  src/common/darktable.c
  src/common/dwt.c
  src/common/guided_filter.c
  src/common/math.h
  src/develop/imageop.c
  src/iop/atrous.c
  src/iop/equalizer.c
  src/iop/overexposed.c
Labels: scope: codebase

#13847 maintenance: remove some last remnants of SSE code from dwt.c
  src/common/dwt.c
  src/common/dwt.h
  src/iop/retouch.c
Labels: scope: codebase

#13831 [GUI] A more accurate tooltip for highlights reconstruction module
  src/iop/highlights.c
Labels: scope: UI

#13853 lowpass: optimize code
  src/iop/lowpass.c
Labels: scope: performance

#13859 maintenance: remove more unused code
  src/common/history.c
  src/common/points.h
  src/develop/masks/brush.c
  src/develop/tiling.c
  src/imageio/format/png.c
  src/imageio/format/tiff.c
  src/iop/ashift_lsd.c
  src/iop/basecurve.c
  src/iop/colormapping.c
  src/iop/colortransfer.c
Labels: scope: codebase

#13693 Canon PowerShot SX160 IS rename
  data/noiseprofiles.json
  data/wb_presets.json
Labels: feature: enhancement, wip, priority: medium, depends: rawspeed

#13865 Replace fprintf to stderr by unconditional debug print (iop modules)
  src/iop/ashift_lsd.c
  src/iop/atrous.c
  src/iop/basicadj.c
  src/iop/clipping.c
  src/iop/colorbalance.c
  src/iop/colorbalancergb.c
  src/iop/colorin.c
  src/iop/colormapping.c
  src/iop/colorout.c
  src/iop/colorreconstruction.c
  src/iop/colorzones.c
  src/iop/crop.c
  src/iop/defringe.c
  src/iop/denoiseprofile.c
  src/iop/filmic.c
  src/iop/gaussian_elimination.h
  src/iop/highlights.c
  src/iop/invert.c
  src/iop/lut3d.c
  src/iop/negadoctor.c
  src/iop/overexposed.c
  src/iop/profile_gamma.c
  src/iop/rgbcurve.c
  src/iop/rgblevels.c
  src/iop/rotatepixels.c
  src/iop/scalepixels.c
  src/iop/segmentation.h
  src/iop/svd.h
  src/iop/temperature.c
  src/iop/watermark.c
Labels: scope: codebase

#13861 exposure: Properly reset the spot mode to correct when changing image.
  src/iop/exposure.c
Labels: bugfix, priority: low, scope: image processing, release notes: pending

#13858 hazeremoval: optimize and bugfix
  src/iop/hazeremoval.c
Labels: bugfix, scope: performance

#13863 imageio: ignore Canon CR3 crop
  src/imageio/imageio_libraw.c
Labels: scope: image processing

#13867 Revert to XWayland
  src/common/darktable.c
Labels: scope: UI, scope: codebase, release notes: pending

#13869 Lua API bump to 9.1.0
  src/lua/configuration.h
Labels: lua

#13874 retouch.c: reformat function headers
  src/iop/retouch.c
Labels: scope: codebase

#13873 rgblevels: add nontemporal writes and optimize OpenMP loop
  src/iop/rgblevels.c
Labels: scope: performance

#13875 RFC: remove OPENMP_SIMD codepath config
  src/common/darktable.c
  src/common/darktable.h
  src/common/interpolation.c
  src/develop/imageop.c
Labels: scope: codebase

#13877 refactor: functions to set SSE denormals-flushing mode
  src/common/darktable.c
  src/develop/blends/blendif_lab.c
  src/develop/blends/blendif_rgb_hsl.c
  src/develop/blends/blendif_rgb_jzczhz.c
  src/develop/imageop.h
  src/iop/filmicrgb.c
  src/iop/overexposed.c
Labels: scope: codebase

#13866 eaw.c: optimize function eaw_synthesize, drop SSE version
  src/common/eaw.c
  src/common/eaw.h
  src/iop/atrous.c
Labels: scope: performance, scope: codebase

#13878 dedup dt_alloc_sse_ps
  src/common/darktable.h
  src/common/eigf.h
  src/common/fast_guided_filter.h
  src/iop/channelmixerrgb.c
  src/iop/choleski.h
  src/iop/filmicrgb.c
  src/iop/toneequal.c
Labels: scope: codebase

#13879 resampling: optimize and remove SSE path
  src/common/interpolation.c
Labels: scope: codebase

#13884 atrous: remove process_sse2
  src/common/eaw.c
  src/iop/atrous.c
Labels: scope: codebase

#13883 wb_presets: add Canon R7
  data/wb_presets.json
Labels: scope: camera support

#13882 wb_presets: add Sony RX100M6 and RX100M7
  data/wb_presets.json
Labels: scope: camera support

#13804 RFC: Use camera, maker and lens fields in text search
  src/common/collection.c
  src/libs/filters/search.c
Labels: feature: enhancement, priority: medium, scope: DAM, release notes: pending

#13885 update compile-time warning about lack of SSE
  src/is_supported_platform.h
Labels: scope: codebase

#13886 colorbalance: refactor and optimize
  src/common/colorspaces_inline_conversions.h
  src/common/math.h
  src/develop/openmp_maths.h
  src/iop/colorbalance.c
Labels: scope: performance

#13890 dt_mm_enable_flush_zero needs to produce value in non-SSE builds
  src/develop/imageop.h
Labels: scope: codebase

#13891 [maintenance] Enhance error messaging by using dt_print instead of fprintf
  src/control/crawler.c
  src/imageio/format/j2k.c
  src/libs/export.c
  src/libs/histogram.c
  src/libs/history.c
  src/libs/lib.c
  src/libs/live_view.c
  src/libs/location.c
  src/libs/print_settings.c
  src/libs/tools/darktable.c
  src/libs/tools/gamepad.c
  src/libs/tools/midi.c
  src/win/getrusage.c
Labels: scope: codebase

#13894 colorbalance: refactor SSE, remove SSE version of legacy mode
  src/common/colorspaces_inline_conversions.h
  src/iop/colorbalance.c
Labels: scope: codebase

#13897 remove OpenMP directive for powf
  src/develop/openmp_maths.h
Labels: bugfix

#13896 [maint] centralize definitions of prefetch macros into header
  src/common/box_filters.c
  src/common/guided_filter.c
  src/common/nlmeans_core.c
  src/develop/imageop.h
Labels: scope: codebase

#13900 colorin: optimize plain codepath, refactor
  src/common/colorspaces_inline_conversions.h
  src/common/math.h
  src/iop/colorin.c
Labels: scope: codebase, release notes: pending

#13899 lowlight: optimize OpenMP, add nontemporal write
  src/iop/lowlight.c
Labels: scope: performance

#13898 levels(legacy): optimize OpenMP
  src/iop/levels.c
Labels: scope: performance

#13901 optimize dt_bilateral_slice
  src/common/bilateral.c
Labels: scope: performance

#13903 velvia: optimize and use nontemporal writes
  src/iop/velvia.c
Labels: scope: performance

#13902 splittoning: optimize
  src/common/colorspaces.c
  src/common/colorspaces.h
  src/iop/splittoning.c
Labels: scope: performance

#13905 maintenance: use dt_print instead of fprintf(stderr, ...)
  src/bauhaus/bauhaus.c
  src/common/file_location.c
  src/common/system_signal_handling.c
  src/control/jobs/control_jobs.c
  src/control/progress.c
  src/control/signal.c
  src/develop/blend.c
  src/develop/masks.h
  src/develop/masks/masks.c
  src/develop/tiling.c
Labels: scope: codebase

#13907 maintenance: use dt_printf instead of fprintf(stderr,...)
  src/gui/accelerators.c
  src/gui/gtk.c
  src/gui/preferences.c
  src/imageio/imageio.c
  src/imageio/imageio_libraw.c
  src/libs/history.c
  src/views/darkroom.c
  src/views/lighttable.c
Labels: scope: codebase

#13904 [maintenance] Replace fprintf to stderr by unconditional debug print in exif.cc
  src/common/exif.cc
Labels: scope: codebase

#13906 maintenance: remove process_sse2 remnants
  src/develop/imageop.c
  src/develop/pixelpipe_hb.c
  src/iop/iop_api.h
Labels: scope: codebase

#13857 [GUI] Fix hiding enable button in highlights reconstruction
  src/iop/highlights.c
Labels: scope: codebase

#13887 wb_presets: lint and add Sony ILCE-7C
  data/wb_presets.json
Labels: scope: camera support

#13837 RFC: Keep sort order on collection change
  src/common/tags.c
  src/common/tags.h
  src/libs/collect.c
Labels: feature: redesign, scope: DAM

#13910 wb_presets: add Fujifilm X-H2S and X-T200
  data/wb_presets.json
Labels: scope: camera support

#13915 [maintenance] Remove the old compatibility definition that is no longer needed
  cmake/compiler-warnings.cmake
Labels: scope: codebase

#13916 wb_presets: remove duplicate entries for Canon MILCs
  data/wb_presets.json
Labels: scope: camera support

#13922 [maintenance] Enhance error messaging in lua subsystem
  src/lua/image.c
  src/lua/luastorage.c
Labels: scope: codebase

#13921 wb_presets: add Canon EOS R10
  RELEASE_NOTES.md
  data/wb_presets.json
Labels: scope: camera support

#13920 po/fix fast img reload
  src/develop/imageop.c
Labels: bugfix, priority: high, scope: DAM, scope: codebase

#13927 Ukrainian translation update
  po/uk.po
Labels: scope: translation / strings

#13925 nlmeans: fix performance degradation
  src/common/nlmeans_core.c
Labels: scope: performance

#13928 sq translation update
  po/sq.po
Labels: scope: translation / strings

#13931 Turkish translation update
  po/tr.po
Labels: scope: translation / strings

#13932 Update zh_TW translation
  po/zh_TW.po
Labels: scope: translation / strings

#13933 [CI] update compiler matrix for macOS
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
Labels: scope: macos support

#13938 Fix shifting text on top hinter in new french translation and minor things
  po/fr.po
Labels: bugfix, scope: translation / strings, difficulty: trivial, scope: UI

#13940 Update de.po
  po/de.po
Labels: scope: translation / strings

#13935 imageio: try loading BigTIFF images via libtiff first
  src/imageio/imageio.c
Labels: scope: image processing

#13929 more responsive style previews
  src/common/styles.c
  src/gui/styles_dialog.c
Labels: bugfix, feature: enhancement, scope: UI

#13937 [CI] macOS: Speed up build by removing the limiting number of parallel jobs
  .ci/ci-script.sh
Labels: scope: macos support

#13945 exif: tentative fix for MacOS build issue.
  src/common/exif.cc
Labels: bugfix, priority: high, scope: codebase

#13947 More dt_print() variants used instead of fprintf()
  src/common/cups_print.c
  src/common/dlopencl.c
  src/common/exif.cc
  src/common/locallaplaciancl.c
  src/common/module_api.h
  src/common/noiseprofiles.c
  src/common/printprof.c
  src/common/profiling.c
  src/common/pwstorage/backend_libsecret.c
  src/common/pwstorage/pwstorage.c
Labels: scope: codebase

#13942 darktable.css: Use a more transparent brush trace.
  data/themes/darktable.css
Labels: scope: UI, release notes: pending

#13948 Improve and fix new shifting text in french translation
  po/fr.po
Labels: bugfix, scope: translation / strings, scope: UI

#13854 move lua event pixelpipe-processing-complete to end of preview pixelpipe
  src/develop/develop.c
Labels: bugfix, lua, release notes: pending

#13950 Bugfix: Opposed HLR Inpaint border issues
  data/kernels/basic.cl
  src/iop/hlrecovery_v2.c
  src/iop/opposed.c
Labels: bugfix, priority: high, release notes: pending

#13955 liquify: Rework tooltip text.
  src/iop/liquify.c
Labels: feature: enhancement, scope: UI, release notes: pending

#13960 Ukrainian translation update
  po/uk.po
Labels: scope: translation / strings

#13963 reposition module tooltips if off to right
  src/gui/accelerators.c
Labels: bugfix, scope: UI

#13958 Bugfix and refactor xmp writing tests
  src/common/history.c
  src/common/history.h
  src/common/image.c
  src/common/image.h
  src/control/crawler.c
  src/views/darkroom.c
Labels: bugfix, scope: codebase

#13966 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#13974 Update de.po
  po/de.po
Labels: scope: translation / strings

#13964 optimize pixel interpolation
  src/common/interpolation.c
  src/common/interpolation.h
  src/common/math.h
Labels: scope: performance

#13980 [maintenance] Enhance error messaging by using dt_print instead of printf
  src/common/database.c
  src/common/dwt.c
  src/common/image_cache.c
  src/common/mipmap_cache.c
Labels: scope: codebase

#13977 performance: RGB-display blending
  src/develop/blends/blendif_rgb_hsl.c
Labels: scope: performance

#13979 performance: RGB-scene blending
  src/develop/blends/blendif_rgb_jzczhz.c
Labels: scope: performance

#13981 performance: Lab blending
  src/develop/blends/blendif_lab.c
Labels: scope: performance

#13969 Add Sony Alpha 7 IV (ILCE-7M4) noise profiles
  data/noiseprofiles.json
Labels: scope: noise profile

#13984 Bugfix #13975
  src/cli/main.c
  src/common/exif.cc
  src/common/exif.h
  src/common/image.c
Labels: bugfix, scope: DAM, scope: codebase

#13986 wb_presets: add Ricoh GR IIIx
  data/wb_presets.json
Labels: scope: camera support

#13990 optimize tone equalizer's luminance mask calculation
  src/common/luminance_mask.h
  src/iop/toneequal.c
Labels: scope: performance

#13996 [maintenance] Enhance error messaging by using dt_print instead of printf
  src/imageio/storage/gallery.c
  src/imageio/storage/latex.c
Labels: scope: codebase

#13994 performance: vectorize negadoctor code
  src/common/math.h
  src/iop/negadoctor.c
Labels: scope: performance

#13997 Bugfix: laplacian highlights reconstruction artefacts
  data/kernels/basic.cl
  src/iop/highlights.c
Labels: bugfix, priority: high, reproduce: confirmed, scope: hardware support

#13988 RFC: Always write database timestamp in dt_image_write_sidecar_file()
  src/common/image.c
Labels: bugfix, priority: high, scope: DAM, release notes: pending

#13993 Makes module & label display consistent in all cases.
  src/common/history.c
  src/common/history.h
  src/common/styles.c
  src/common/styles.h
  src/develop/lightroom.c
  src/gui/hist_dialog.c
  src/gui/styles_dialog.c
  src/imageio/imageio.c
  src/libs/history.c
  src/lua/styles.c
Labels: feature: enhancement, scope: UI

#14001 Turkish translation update
  po/tr.po
Labels: scope: translation / strings

#14000 Grammatically correct word capitalization in the Ukrainian translation
  po/uk.po
Labels: scope: translation / strings

#14007 Cleaning up the demosaicer source code
  src/iop/CMakeLists.txt
  src/iop/demosaic.c
  src/iop/demosaicing/amaze.cc
  src/iop/demosaicing/basics.c
  src/iop/demosaicing/dual.c
  src/iop/demosaicing/lmmse.c
  src/iop/demosaicing/passthrough.c
  src/iop/demosaicing/ppg.c
  src/iop/demosaicing/rcd.c
  src/iop/demosaicing/vng.c
  src/iop/demosaicing/xtrans.c
Labels: scope: codebase

#13991 fix mouse moves over bauhaus causing histogram redraws
  src/bauhaus/bauhaus.c
  src/bauhaus/bauhaus.h
  src/libs/histogram.c
Labels: bugfix, scope: UI, scope: performance, release notes: pending

#14010 [GUI] Split a long line in the preferences tooltip
  data/darktableconfig.xml.in
Labels: scope: translation / strings

#14011 Ukrainian translation update
  po/uk.po
Labels: scope: translation / strings

#14016 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#14018 Update de.po
  po/de.po
Labels: scope: translation / strings

#14013 [maintenance] Enhance error messaging in l10n.c
  src/common/l10n.c
Labels: scope: codebase

#14014 eaw,c: optimize, remove SSE code
  src/common/eaw.c
  src/common/eaw.h
  src/common/math.h
Labels: scope: performance, scope: codebase

#14017 performance: optimize colorin, remove more SSE code
  src/common/colorspaces_inline_conversions.h
  src/common/math.h
  src/iop/colorin.c
Labels: scope: performance, scope: codebase

#14021 Highlights reconstruction bugfix and code cleanup
  data/kernels/basic.cl
  src/CMakeLists.txt
  src/common/distance_transform.c
  src/common/distance_transform.h
  src/iop/highlights.c
  src/iop/hlreconstruct/inpaint.c
  src/iop/hlreconstruct/laplacian.c
  src/iop/hlreconstruct/lch.c
  src/iop/hlreconstruct/opposed.c
  src/iop/hlreconstruct/segbased.c
  src/iop/hlreconstruct/segmentation.c
Labels: bugfix, scope: codebase

#14024 Simplify demosaicer code
  data/darktableconfig.xml.in
  src/common/darktable.c
  src/iop/demosaic.c
Labels: feature: redesign, scope: UI, scope: image processing, scope: codebase

#14019 po/mask manager mode - ensure state stays meaningful
  src/develop/masks.h
  src/develop/masks/masks.c
  src/libs/masks.c
Labels: bugfix, feature: redesign, scope: UI, scope: image processing, scope: codebase, release notes: pending

#13998 Use preset's multi_name as module label.
  data/darktableconfig.xml.in
  src/common/history.c
  src/common/presets.c
  src/common/presets.h
  src/develop/develop.c
  src/develop/imageop.c
  src/gui/presets.c
  src/iop/colorzones.c
  src/iop/flip.c
Labels: feature: enhancement, priority: high, scope: UI

#14006 maintenance: remove unused functions and extraneous #includes
  src/common/colorspaces_inline_conversions.h
  src/common/eaw.c
  src/common/math.h
  src/common/sse.h
  src/develop/imageop_math.c
  src/develop/imageop_math.h
  src/iop/diffuse.c
Labels: scope: codebase

#14031 Ukrainian translation update
  po/uk.po
Labels: scope: translation / strings

#13967 center iop module tooltip across side panel
  src/develop/imageop.c
Labels: scope: UI

#14036 Bugfix: HLR clip mode
  data/kernels/basic.cl
  src/iop/highlights.c
Labels: bugfix

#14037 develop: Fix module label update in none auto-mode.
  src/develop/develop.c
Labels: bugfix, priority: high, reproduce: confirmed, scope: UI

#13965 Make dt_lua_image_t millisecond aware
  src/lua/image.c
Labels: lua, release notes: pending

#14032 add width and height fields to dt_lua_image_t
  src/lua/image.c
Labels: lua, release notes: pending
