Repository darktable-org/darktable, pull requests merged in 2023-06, with the labels that each got.

#14618 Update de.po
  po/de.po
Labels: scope: translation / strings

#14476 Add Sony A7rV noise profile
  data/noiseprofiles.json
Labels: scope: noise profile

#14627 [maintenance] Remove duplicate commented out code from jpeg export implementation
  src/imageio/format/jpeg.c
Labels: scope: codebase

#14625 Update sq.po
  po/sq.po
Labels: scope: translation / strings

#14628 Update zh_TW.po
  po/zh_TW.po
Labels: scope: translation / strings

#14626 focus (and reposition) lib with mouse
  src/libs/lib.c
  src/libs/metadata.c
Labels: bugfix, priority: high

#14629 [CI] Add AppImage nightly build
  .github/workflows/nightly.yml
Labels: scope: codebase

#14635 update translations for zh_CN
  po/zh_CN.po
Labels: scope: translation / strings

#14638 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#14640 Properly escape text in profile tooltips
  src/common/iop_profile.c
Labels: bugfix, priority: low, difficulty: trivial

#14634 fix padding for modules with top level event box
  src/libs/metadata.c
  src/libs/metadata_view.c
  src/libs/recentcollect.c
Labels: bugfix, priority: high, difficulty: trivial

#14615 Gitpod integration
  .gitpod.Dockerfile
  .gitpod.yml
Labels: scope: codebase

#14649 correction of filmic translation in zh_TW
  po/zh_TW.po
Labels: scope: translation / strings

#14653 Update ja.po
  po/ja.po
Labels: scope: translation / strings

#14646 fix shift+drag edge to shrink crop with constant aspect
  src/iop/crop.c
Labels: bugfix, feature: enhancement

#14657 Bugfix retouch #14648
  src/iop/retouch.c
Labels: bugfix

#14643 Clean up Windows dependencies
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  packaging/windows/README.md
Labels: scope: windows support

#14666 Update ja.po
  po/ja.po
Labels: scope: translation / strings

#14661 CIELAB terminology in colorzone drop-down menu
  src/iop/colorzones.c
Labels: scope: translation / strings

#14663 Bugfix cacheline re-use for 4.4
  src/develop/pixelpipe_cache.c
Labels: bugfix, priority: high, difficulty: hard, scope: codebase

#14665 Ignore 'nightly' tag in the version detection script
  tools/get_git_version_string.sh
Labels: scope: codebase

#14674 Update ja.po
  po/ja.po
Labels: scope: translation / strings

#14673 Polish translation update
  po/pl.po
Labels: scope: translation / strings

#14675 Fix lmmse crashing on improper dsc.processed_maximum data
  src/iop/demosaicing/lmmse.c
Labels: bugfix

#14651 basecurve tool: support Exiv2 0.28 API changes
  src/CMakeLists.txt
  src/common/exif.cc
  tools/basecurve/exif-wrapper.cpp
Labels: bugfix, priority: medium, depends: external lib

#14681 Update ja.po
  po/ja.po
Labels: scope: translation / strings

#14676 Fix un-initialized user modified temperature
  src/common/illuminants.h
  src/iop/temperature.c
Labels: bugfix

#14684 Fix issue after rework of the default modules for different workflows.
  src/develop/imageop.c
Labels: bugfix, priority: high, understood: clear, difficulty: trivial, scope: image processing, scope: codebase

#14680 fix macOS homebrew links
  packaging/macosx/1_install_hb_dependencies.sh
Labels: scope: macos support

#14705 RELEASE CRITICAL: lens: Rework lens auto-detection on first run.
  src/iop/lens.cc
Labels: bugfix, priority: high, understood: clear, reproduce: confirmed, difficulty: average

#14708 Undo reading MaxApertureValue as the actual aperture value
  src/common/exif.cc
Labels: bugfix, priority: high, understood: clear, scope: DAM

#14710 Updated Hebrew translation
  po/he.po
Labels: scope: translation / strings

#14712 Spanish translation update
  po/es.po
Labels: scope: translation / strings

#14713 Spanish translation update
  po/es.po
Labels: scope: translation / strings

#14722 Update de.po
  po/de.po
Labels: scope: translation / strings

#14727 Bugfix dt_ioppr_transform_image_colorspace_cl()
  src/common/iop_profile.c
Labels: bugfix, difficulty: trivial

#14724 Add distort_mask() to highlights
  src/iop/highlights.c
Labels: bugfix, priority: low, difficulty: trivial

#14726 CI: fix macOS architecture string
  .github/workflows/nightly.yml
  packaging/macosx/1_install_hb_dependencies.sh
  packaging/macosx/4_make_hb_darktable_dmg.sh
Labels: scope: macos support

#14737 italian translation
  po/it.po
Labels: scope: translation / strings

#14734 Fixing 2 obscure `distort_mask()` missings
  src/iop/cacorrect.c
  src/iop/scalepixels.c
Labels: bugfix, priority: low

#14719 fully hide metadata fields without leaving margin
  src/libs/metadata.c
Labels: bugfix, priority: low, difficulty: trivial, release notes: pending

#14736 Ensure supported OpenCL device version
  src/common/opencl.c
Labels: bugfix, scope: hardware support, release notes: pending

#14730 allow preview via shortcut when no image hovered
  src/libs/tools/lighttable.c
Labels: bugfix, release notes: pending

#14761 liquify: fix corruption in grow/shrink modes
  src/iop/liquify.c
Labels: bugfix, priority: high, scope: image processing, release notes: pending

#14762 Fix snapshot name if label has a & for example.
  src/common/history.c
Labels: bugfix, priority: high, scope: UI, release notes: pending

#14786 po/fix instance name
  src/develop/imageop.c
Labels: priority: high, release notes: pending

#14753 colorbalancergb: fix alignment to avoid crash when activating shadow/mid/highlight masks
  src/iop/colorbalancergb.c
Labels: bugfix, priority: high, release notes: pending

#14790 Fix liquify grow/shrink direction.
  src/iop/liquify.c
Labels: bugfix, priority: high, reproduce: confirmed, scope: image processing, release notes: pending

#14781 Fix to ensure build with libxml2 2.11 where xmlParseEntity is deprecated
  src/develop/lightroom.c
Labels: scope: codebase

#14798 align module and instance name to same baseline
  src/develop/imageop.c
Labels: bugfix, priority: low, difficulty: trivial, scope: UI, release notes: pending

#14801 filmicrgb: don't desat/resat in v7 gamut mapping
  src/iop/filmicrgb.c
Labels: bugfix, priority: high, scope: image processing, release notes: pending

#14802 negadoctor: fix placement of parenthesis
  src/iop/negadoctor.c
Labels: bugfix, scope: image processing

#14804 Fix workflow default auto-presets.
  src/develop/develop.c
Labels: bugfix, priority: high, scope: image processing, release notes: pending
