Repository darktable-org/darktable, pull requests merged in 2023-07, with the labels that each got.

#14835 Turkish translation update
  po/tr.po
Labels: scope: translation / strings

#14847 graduatednd: fix density computation for negative EVs
  src/iop/graduatednd.c
Labels: bugfix, scope: image processing, release notes: pending

#14852 de.po: fix markup error
  po/de.po
Labels: scope: translation / strings

#14846 Fix blending for raw_space modules
  src/develop/blend.c
Labels: bugfix, priority: medium, scope: image processing, scope: hardware support, release notes: pending

#14863 print: fix snap to grid for cm/inch units
  src/libs/print_settings.c
Labels: bugfix, priority: low, scope: UI, release notes: pending

#14866 highlights: Makes DT_IOP_HIGHLIGHTS_OPPOSED the default method.
  src/iop/highlights.c
Labels: bugfix, priority: low, scope: image processing, release notes: pending

#14870 highlights: Makes DT_IOP_HIGHLIGHTS_OPPOSED the default method.
  src/common/exif.cc
  src/iop/highlights.c
Labels: bugfix, priority: medium, difficulty: hard, scope: image processing, release notes: pending

#14881 Module highlights must only be activated for RAW.
  src/common/exif.cc
Labels: bugfix, priority: high, understood: clear, scope: image processing

#14878 Fix dump pfm pipe for OpenCL modules
  src/develop/pixelpipe_hb.c
Labels: bugfix

#14886 Fix last pixels in colorin cpu code
  src/iop/colorin.c
Labels: bugfix, scope: image processing

#14887 fix chunksize computation
  src/iop/colorbalance.c
  src/iop/colorout.c
Labels: bugfix, scope: image processing

#14869 Fix temperature bayer copy loop
  src/iop/temperature.c
Labels: bugfix, priority: medium

#14889 Fix two demosaicer cpu paths
  src/iop/demosaicing/lmmse.c
  src/iop/demosaicing/rcd.c
Labels: bugfix, priority: medium

#14865 CMake: install only the libdarktable.dll runtime
  src/CMakeLists.txt
Labels: bugfix, scope: windows support

#14895 po/retouch - fix synch of blend params - avoid missing retouch spot
  src/iop/retouch.c
  src/iop/spots.c
Labels: bugfix, priority: high, understood: clear, difficulty: hard, scope: image processing, scope: codebase, release notes: pending

#14896 Fix demosaicer snapping
  src/iop/demosaic.c
Labels: bugfix, priority: medium

#14907 CMake: update options descriptions
  DefineOptions.cmake
Labels: scope: codebase

#14903 [CI] Bump GCC in the Linux job to GCC 13
  .github/workflows/ci.yml
Labels: scope: codebase

#14779 Fix various typos
  RELEASE_NOTES.md
  data/darktableconfig.xml.in
  src/control/conf.h
  src/develop/develop.c
  src/develop/imageop.h
  src/develop/masks.h
  src/develop/masks/masks.c
  src/develop/pixelpipe_cache.c
  src/develop/pixelpipe_hb.c
  src/dtgtk/range.c
  src/imageio/imageio_heif.c
  src/iop/filmicrgb.c
  src/iop/hlreconstruct/segmentation.c
  src/iop/lens.cc
  src/iop/sigmoid.c
  src/libs/snapshots.c
  src/views/map.c
  src/views/view.c
  tools/diff_lua_api.lua
Labels: scope: codebase

#14756 [maintenance] Get rid of USE_LENSFUN option
  .ci/ci-script.sh
  DefineOptions.cmake
Labels: scope: codebase

#14883 Add --dumpdir option in command line
  src/common/darktable.c
Labels: feature: enhancement, priority: low, scope: CLI

#14879 remove obsolete and never-completed regression test code
  tools/regression_tests/README
  tools/regression_tests/src/all.rb
  tools/regression_tests/src/lib/build.rb
  tools/regression_tests/src/lib/common.rb
  tools/regression_tests/src/lib/runner.rb
  tools/regression_tests/src/progs/imgcmp.c
  tools/regression_tests/src/web/assets/bootstrap/css/bootstrap-theme.css
  tools/regression_tests/src/web/assets/bootstrap/css/bootstrap-theme.css.map
  tools/regression_tests/src/web/assets/bootstrap/css/bootstrap-theme.min.css
  tools/regression_tests/src/web/assets/bootstrap/css/bootstrap.css
  tools/regression_tests/src/web/assets/bootstrap/css/bootstrap.css.map
  tools/regression_tests/src/web/assets/bootstrap/css/bootstrap.min.css
  tools/regression_tests/src/web/assets/bootstrap/fonts/glyphicons-halflings-regular.eot
  tools/regression_tests/src/web/assets/bootstrap/fonts/glyphicons-halflings-regular.svg
  tools/regression_tests/src/web/assets/bootstrap/fonts/glyphicons-halflings-regular.ttf
  tools/regression_tests/src/web/assets/bootstrap/fonts/glyphicons-halflings-regular.woff
  tools/regression_tests/src/web/assets/bootstrap/fonts/glyphicons-halflings-regular.woff2
  tools/regression_tests/src/web/assets/bootstrap/js/bootstrap.js
  tools/regression_tests/src/web/assets/bootstrap/js/bootstrap.min.js
  tools/regression_tests/src/web/assets/bootstrap/js/npm.js
  tools/regression_tests/src/web/assets/jquery.js
  tools/regression_tests/src/web/assets/theme.css
  tools/regression_tests/src/web/builder.rb
  tools/regression_tests/src/web/helpers.rb
  tools/regression_tests/src/web/templates/index.erb
  tools/regression_tests/src/web/templates/main.erb
  tools/regression_tests/src/web/templates/testdiff.erb
Labels: scope: codebase

#14658 watermark: clarify tooltips
  src/iop/watermark.c
Labels: feature: enhancement, scope: translation / strings

#14611 _check_deleted_instances return a gboolean
  src/libs/history.c
Labels: scope: codebase

#14693 Manifest G'MIC support in "darktable --version" output
  src/common/darktable.c
Labels: feature: enhancement

#14909 Italian translation
  po/it.po
Labels: scope: translation / strings

#14894 CMake: normalize GraphicsMagick detection
  cmake/modules/FindGraphicsMagick.cmake
  cmake/windows-macros.cmake
Labels: scope: codebase

#14862 [imageio] Update qoi.h to the latest upstream version
  src/imageio/qoi.h
Labels: feature: enhancement, priority: low, scope: software support

#14698 show active shape combine mode in menu
  src/libs/masks.c
Labels: feature: enhancement, priority: low, difficulty: trivial, scope: UI, documentation-pending, release notes: pending

#14904 Split focal length field into three
  src/libs/metadata_view.c
Labels: priority: low, feature: redesign, scope: UI

#14632 Introduce copymode for HLR inpaint opposed
  data/kernels/basic.cl
  src/iop/highlights.c
  src/iop/hlreconstruct/opposed.c
Labels: scope: image processing, scope: performance

#14899 Try to correctly check for OpenCL platforms
  src/common/opencl.c
Labels: bugfix, priority: high, priority: medium, scope: hardware support, release notes: pending

#14783 Access image change_timestamp from lua
  src/lua/configuration.h
  src/lua/image.c
Labels: lua

#14910 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#14916 constify default_params
  src/iop/atrous.c
  src/iop/basecurve.c
  src/iop/borders.c
  src/iop/channelmixer.c
  src/iop/colorbalance.c
  src/iop/colorchecker.c
  src/iop/colorcorrection.c
  src/iop/colorzones.c
  src/iop/denoiseprofile.c
  src/iop/diffuse.c
  src/iop/equalizer.c
  src/iop/exposure.c
  src/iop/filmic.c
  src/iop/filmicrgb.c
  src/iop/levels.c
  src/iop/lowlight.c
  src/iop/mask_manager.c
  src/iop/monochrome.c
  src/iop/negadoctor.c
  src/iop/profile_gamma.c
  src/iop/rawdenoise.c
  src/iop/retouch.c
  src/iop/rgbcurve.c
  src/iop/rgblevels.c
  src/iop/spots.c
  src/iop/tonecurve.c
  src/iop/toneequal.c
  src/iop/watermark.c
Labels: scope: codebase

#14619 Monochrome image support for hotpixels
  src/iop/hotpixels.c
Labels: feature: enhancement, scope: image processing, documentation-pending, release notes: pending

#14908 Only remove trailing carriage return/linefeed from preferences on loading
  src/control/conf.c
Labels: bugfix, scope: codebase

#14921 [uk.po] The translation of one of the terms was changed to be more accurate
  po/uk.po
Labels: scope: translation / strings

#14919 recentcollections: add null-pointer check
  src/libs/recentcollect.c
Labels: priority: high, scope: UI

#14923 Retouch module should not have the internal guide widget
  src/iop/retouch.c
Labels: priority: low, feature: redesign

#14885 [imageio] Avoid overflow when counting the number of pixels in the QOI loader
  src/imageio/imageio_qoi.c
Labels: feature: enhancement, scope: codebase

#14914 allow import to be canceled by user
  src/control/jobs/control_jobs.c
Labels: feature: enhancement, scope: UI, documentation-pending

#14624 imageio: support auto orientation for AVIF/HEIF import
  README.md
  src/CMakeLists.txt
  src/common/image.h
  src/imageio/imageio_avif.c
  src/imageio/imageio_heif.c
Labels: feature: enhancement, priority: low, release notes: pending

#14807 negadoctor: ensure alpha channel in params properly initialized
  src/iop/negadoctor.c
Labels: bugfix, priority: low

#14936 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#14839 Ask user where to store images on the first run (13390)
  src/libs/import.c
Labels: feature: enhancement, scope: DAM

#14940 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#14828 Manual lens vignette correction
  data/kernels/basic.cl
  src/iop/lens.cc
Labels: feature: new, scope: image processing

#14949 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#14948 temporarily disable macOS nightly builds
  .github/workflows/nightly.yml
Labels: scope: macos support

#14941 lut3d: fix crash on unsupported LUTs
  src/iop/lut3d.c
Labels: bugfix, scope: image processing

#14950 database: Allow nested transaction.
  data/darktableconfig.xml.in
  src/common/database.c
  src/develop/develop.c
Labels: priority: medium, feature: redesign, scope: codebase

#14942 lut3d: add linear Prophoto RGB as LUT colorspace
  src/iop/lut3d.c
Labels: scope: UI, scope: image processing, documentation-pending, release notes: pending

#14953 Add -d expose debugging option
  src/common/darktable.c
  src/common/darktable.h
  src/views/darkroom.c
Labels: feature: new, scope: UI, scope: codebase, documentation-pending

#14961 [uk.po] Capitalization of some strings that should have been capitalized
  po/uk.po
Labels: scope: translation / strings

#14964 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#14960 Fix the calculation of resizable widgets based on linesize of contents
  src/gui/gtk.c
  src/gui/gtk.h
  src/iop/atrous.c
  src/iop/colorbalancergb.c
  src/iop/colorzones.c
  src/iop/denoiseprofile.c
  src/iop/filmicrgb.c
  src/iop/levels.c
  src/iop/lowlight.c
  src/iop/rawdenoise.c
  src/iop/rgblevels.c
  src/libs/histogram.c
  src/libs/navigation.c
  src/libs/snapshots.c
Labels: bugfix, scope: UI, scope: codebase

#14622 Visualize rastermasks & blend mask header
  src/develop/blend.c
  src/develop/blend_gui.c
  src/develop/imageop.c
Labels: feature: enhancement, feature: new, scope: UI, scope: image processing

#14970 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#14978 Update zh_TW translation
  po/zh_TW.po
Labels: scope: translation / strings

#14966 Fix culling thumb placement
  src/dtgtk/culling.c
Labels: bugfix, priority: high, difficulty: average, scope: UI, scope: DAM, release notes: pending

#14981 Fix french translation on diffuse & sharpen module
  po/fr.po
Labels: bugfix, scope: translation / strings
