Repository darktable-org/darktable, pull requests merged in 2024-01, with the labels that each got.

#16003 Fix details mask on low opencl memory
  src/develop/blend.c
  src/develop/pixelpipe_hb.c
  src/iop/demosaic.c
Labels: bugfix, priority: high, scope: image processing, OpenCL

#16011 Culling : ensure to keep zoom value between images
  src/dtgtk/culling.c
  src/dtgtk/thumbnail.c
Labels: bugfix, difficulty: average, scope: DAM

#16014 Update es.po
  po/es.po
Labels: scope: translation / strings

#16017 zoomable : ensure thumbs stay on screen when zooming using slider
  src/dtgtk/thumbtable.c
Labels: bugfix, difficulty: average, scope: UI

#16024 Update boxing filters for 4.8
  src/common/box_filters.c
  src/common/box_filters.h
Labels: feature: new, scope: image processing, scope: performance

#16021 Strictly avoid NaNs in lens module output
  data/kernels/basic.cl
  src/common/interpolation.c
Labels: bugfix, priority: high, scope: image processing, OpenCL

#16015 iop_validate_params improvements
  src/develop/imageop.c
Labels: scope: codebase

#15998 [macOS] handle rpath dependencies in package build
  packaging/macosx/3_make_hb_darktable_package.sh
Labels: bugfix, scope: macos support

#16019 Masks distort should use warp interpolator in demosaic
  src/iop/demosaic.c
Labels: scope: image processing, scope: codebase

#16008 Pixelpipe work III
  src/common/darktable.h
  src/common/interpolation.c
  src/common/mipmap_cache.c
  src/develop/blend.c
  src/develop/imageop.c
  src/develop/imageop_math.c
  src/develop/pixelpipe_cache.c
  src/develop/pixelpipe_hb.c
  src/develop/pixelpipe_hb.h
  src/iop/channelmixerrgb.c
  src/iop/colorin.c
  src/iop/demosaic.c
  src/iop/demosaicing/basics.c
  src/iop/demosaicing/rcd.c
  src/iop/demosaicing/vng.c
  src/iop/demosaicing/xtrans.c
  src/iop/finalscale.c
  src/iop/hlreconstruct/opposed.c
  src/views/darkroom.c
  src/views/view.c
Labels: scope: codebase

#16035 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#16041 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#16043 snapshots: Properly initialize the snapshot id before clearing entry.
  src/libs/snapshots.c
Labels: bugfix, priority: medium, scope: image processing, release notes: pending

#16030 po/remember styles selection after edit
  src/gui/styles.h
  src/gui/styles_dialog.c
  src/libs/styles.c
Labels: bugfix, priority: low, difficulty: average, release notes: pending

#15465 New IOPs to do some composing in darktable
  po/POTFILES.in
  src/CMakeLists.txt
  src/common/database.c
  src/common/history.c
  src/common/image.c
  src/common/image.h
  src/common/iop_order.c
  src/common/overlay.c
  src/common/overlay.h
  src/control/jobs/control_jobs.c
  src/develop/develop.c
  src/develop/develop.h
  src/develop/pixelpipe_hb.c
  src/develop/pixelpipe_hb.h
  src/dtgtk/thumbtable.c
  src/iop/CMakeLists.txt
  src/iop/enlargecanvas.c
  src/iop/overlay.c
  src/libs/duplicate.c
  src/libs/modulegroups.c
  src/libs/snapshots.c
  src/libs/tagging.c
  src/views/map.c
  src/views/slideshow.c
Labels: feature: enhancement, priority: low, difficulty: hard, scope: image processing, documentation-pending, release notes: pending

#16039 snapshot: Add support for rolling back history to a given snapshot.
  src/libs/snapshots.c
Labels: priority: low, feature: new, difficulty: average, scope: image processing, documentation-pending, release notes: pending

#16049 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#16044 Fix locale for aperture filter
  src/common/utility.c
  src/common/utility.h
  src/libs/filters/aperture.c
  src/libs/filters/exposure.c
  src/libs/filters/iso.c
  src/libs/filters/ratio.c
Labels: bugfix, priority: medium, difficulty: trivial, release notes: pending

#16045 Raw CA correction buffersize fixes
  src/iop/cacorrect.c
Labels: bugfix

#16052 support channels in _blur_horizontal_Nch_Kahan()
  src/common/box_filters.c
Labels: bugfix

#16060 Avoid multiple guides drawing
  src/views/darkroom.c
Labels: bugfix, scope: UI

#16066 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#16070 Avoid crash when starting with a locked database on Windows
  src/common/database.c
Labels: bugfix

#16054 Remove unused code that might trigger compiler warning
  src/control/jobs/control_jobs.c
Labels: scope: codebase

#16071 Fix XYZ_to_xyY and dt_xyY_to_XYZ conversions
  data/kernels/colorspace.h
  src/common/colorspaces_inline_conversions.h
Labels: bugfix, priority: high, scope: codebase, OpenCL

#16074 import: move folder id retrieval out of the loop
  src/libs/import.c
Labels: scope: performance, scope: codebase

#16072 po/collect header sort
  data/darktableconfig.xml.in
  src/common/module.c
  src/common/module.h
  src/libs/collect.c
  src/libs/lib.c
  src/libs/lib_api.h
  src/views/view.c
Labels: priority: medium, feature: redesign, scope: UI, scope: DAM, scope: codebase, documentation-pending, release notes: pending

#16076 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#16078 iop_order: Move overlay before liquify & retouch.
  src/common/iop_order.c
Labels: bugfix, priority: high

#16079 lens: Properly set scale_md_v1 to 1 (the default) in legacy params.
  src/iop/lens.cc
Labels: bugfix, priority: high, scope: image processing, release notes: pending

#16082 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#16085 Use D65_xy as fallback in dt_XYZ_to_xyY
  data/kernels/colorspace.h
  src/common/colorspaces.c
  src/common/colorspaces.h
  src/common/colorspaces_inline_conversions.h
Labels: feature: enhancement, scope: color management

#16086 [map]: fix double click on map osd circle
  src/views/map.c
Labels: bugfix, priority: medium, scope: UI, release notes: pending

#16084 Ensure safe RGB data while processing colorbalancergb
  data/kernels/extended.cl
  src/iop/colorbalancergb.c
Labels: bugfix, priority: medium, scope: image processing, release notes: pending, OpenCL

#16089 New IOP Color Equalizer (III)
  data/darktableconfig.xml.in
  po/POTFILES.in
  src/common/colorspaces_inline_conversions.h
  src/common/darktable_ucs_22_helpers.h
  src/common/iop_order.c
  src/iop/CMakeLists.txt
  src/iop/colorequal.c
  src/libs/modulegroups.c
Labels: priority: medium, feature: new, difficulty: hard, documentation-pending, release notes: pending

#16093 Fixes for gamut_lut in colorbalance rgb
  data/kernels/colorspace.h
  src/common/colorspaces_inline_conversions.h
  src/iop/colorbalancergb.c
Labels: bugfix, scope: image processing, scope: codebase

#16102 Possibly avoid bilinear interpolation in color equalizer
  src/iop/colorequal.c
Labels: scope: image processing, scope: codebase

#16110 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#16108 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#16111 Update de.po
  po/de.po
Labels: scope: translation / strings

#16107 Colorequal 3
  src/common/colorspaces.c
  src/common/colorspaces.h
  src/common/darktable_ucs_22_helpers.h
  src/iop/colorequal.c
Labels: bugfix, priority: high, scope: image processing, scope: codebase

#16113 po/fix print draganddrop
  src/control/control.h
  src/dtgtk/thumbtable.c
  src/views/print.c
Labels: bugfix, priority: high, scope: UI, scope: codebase

#16114 Make use of public illuminant whitepoints
  data/kernels/colorspace.h
  src/common/colorspaces.h
  src/common/illuminants.h
  src/iop/channelmixerrgb.c
  src/iop/temperature.c
Labels: scope: color management, scope: codebase

#16123 Avoid div-by-zero in xyY_to_dt_UCS_UV
  data/kernels/colorspace.h
  src/common/colorspaces_inline_conversions.h
Labels: bugfix

#16127 darktable_ucs_22_helpers.h: Fix crash due to missing alignment.
  src/common/darktable_ucs_22_helpers.h
Labels: bugfix

#16128 overlay: Avoid cross references between image and overlay.
  src/common/overlay.c
  src/common/overlay.h
  src/iop/overlay.c
Labels: bugfix, priority: high

#16124 Lua widget enhancements
  src/lua/configuration.h
  src/lua/types.c
  src/lua/types.h
  src/lua/widget/box.c
  src/lua/widget/button.c
  src/lua/widget/label.c
Labels: lua

#16144 Some minor fixes in color equalizer
  src/iop/colorequal.c
Labels: scope: codebase

#16147 colorequal: saturation and brightness are gains.
  src/iop/colorequal.c
Labels: bugfix

#16141 Canon PowerShot SX70 HS support
  src/imageio/imageio_libraw.c
Labels: scope: camera support

#16138 [Issue #16131] add shift for sequence number
  src/common/variables.c
  src/gui/gtkentry.c
Labels: feature: enhancement, priority: low, feature: redesign, documentation-pending, release notes: pending

#16151 darkroom.c: Ensure the rotate perspective line is drawn.
  src/views/darkroom.c
Labels: bugfix, priority: high

#16146 Some color maths improving
  data/kernels/colorspace.h
  data/kernels/extended.cl
  src/common/colorspaces.c
  src/common/colorspaces_inline_conversions.h
  src/common/darktable_ucs_22_helpers.h
  src/iop/channelmixerrgb.c
  src/iop/colorbalancergb.c
  src/iop/colorequal.c
  src/libs/histogram.c
Labels: bugfix, scope: color management, scope: codebase

#16154 Color equalizer weighed brightness correction
  src/iop/colorequal.c
Labels: feature: enhancement, priority: medium, scope: image processing

#16155 Some OpenCL initializing fixes
  src/common/opencl.c
Labels: bugfix, priority: medium, scope: performance, OpenCL

#16156 Some OpenCL initializing fixes
  src/common/opencl.c
Labels: bugfix, priority: medium, scope: performance, OpenCL

#16163 Remove easter egg game completely
  DefineOptions.cmake
  po/POTFILES.in
  src/CMakeLists.txt
  src/common/darktable.c
  src/control/control.c
  src/views/CMakeLists.txt
  src/views/knight.c
  src/views/knight_font.h
Labels: scope: codebase

#16168 Updates to pt_BR
  po/pt_BR.po
Labels: scope: translation / strings

#16171 [CI/CD] Remove cmocka from all build environments
  .ci/Brewfile
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
Labels: scope: codebase

#16172 Remove cmocka from homebrew deps
  packaging/macosx/1_install_hb_dependencies.sh
Labels: scope: codebase

#16170 clarify 'restricted mode' in blendop tooltip
  src/develop/blend_gui.c
Labels: scope: UI

#16173 Color equalizer improvements
  src/iop/colorequal.c
Labels: feature: enhancement, priority: medium, scope: image processing

#16159 iop-order: Move color equal before color balance rgb.
  src/common/iop_order.c
Labels: priority: high, feature: redesign, scope: image processing

#16174 Translations update: en@truecase and Ukrainian
  po/en@truecase.po
  po/uk.po
Labels: scope: translation / strings

#16178 [GUI] Fix a typo in the color equalizer module
  src/iop/colorequal.c
Labels: scope: translation / strings

#16183 [maintenance] Remove no longer needed leftovers
  .ci/ci-script.sh
  build.sh
  data/darktableconfig.xml.in
Labels: scope: codebase

#16187 Turkish translation update
  po/tr.po
Labels: scope: translation / strings

#16166 Use gp_camera_get_single_config where possible
  src/common/camera_control.c
  src/common/camera_control.h
Labels: bugfix, feature: redesign, scope: hardware support, scope: performance
